using HRMS.Application.Abstractions;
using HRMS.Application.Services;
using HRMS.Domain.Entities;
using HRMS.Domain.Enums;
using HRMS.Tests.TestSupport;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;

namespace HRMS.Tests;

public sealed class CompOffAcceptanceTests
{
    [Fact] public async Task Effective_dated_weekoff_policy_creates_one_traceable_credit() { await using var f = await CompOffFixture.CreateAsync(RosterDayType.WeeklyOff, 480); var old = await f.Service.CreatePolicyAsync(f.Policy("V1", new(2026, 1, 1), new(2026, 9, 14), ratio: 1)); var current = await f.Service.CreatePolicyAsync(f.Policy("V2", new(2026, 9, 15), null, ratio: .5m)); Assert.True(old.Succeeded); Assert.True(current.Succeeded); var result = await f.Service.EarnAsync(new(f.EmployeeId, f.WorkDate, CompOffSourceType.WeekOff, f.AttendanceDayId, 7)); Assert.True(result.Succeeded, result.Message); Assert.Equal(current.Value!.Id, result.Value!.PolicyId); Assert.Equal(240, result.Value.CreditedMinutes); Assert.Equal(7, result.Value.SourceAttendanceVersion); }
    [Fact] public async Task Ineligible_and_below_threshold_sources_do_not_credit() { await using var f = await CompOffFixture.CreateAsync(RosterDayType.WeeklyOff, 239); Assert.True((await f.Service.CreatePolicyAsync(f.Policy("NONE", new(2026, 1, 1), null, ratio: 1, minimum: 240, eligibility: "None"))).Succeeded); var no = await f.Service.EarnAsync(new(f.EmployeeId, f.WorkDate, CompOffSourceType.WeekOff, f.AttendanceDayId, 1)); Assert.False(no.Succeeded); await using var g = await CompOffFixture.CreateAsync(RosterDayType.WeeklyOff, 239); Assert.True((await g.Service.CreatePolicyAsync(g.Policy("THRESHOLD", new(2026, 1, 1), null, ratio: 1, minimum: 240))).Succeeded); Assert.False((await g.Service.EarnAsync(new(g.EmployeeId, g.WorkDate, CompOffSourceType.WeekOff, g.AttendanceDayId, 1))).Succeeded); }
    [Fact] public async Task Holiday_ratio_rounding_and_expiry_are_policy_owned() { await using var f = await CompOffFixture.CreateAsync(RosterDayType.Holiday, 500); Assert.True((await f.Service.CreatePolicyAsync(f.Policy("HOL", new(2026, 1, 1), null, ratio: .5m, rounding: 30, roundingMode: CompOffRoundingMode.Floor, expiryDays: 10))).Succeeded); var credit = await f.Service.EarnAsync(new(f.EmployeeId, f.WorkDate, CompOffSourceType.Holiday, f.AttendanceDayId, 1)); Assert.True(credit.Succeeded, credit.Message); Assert.Equal(240, credit.Value!.CreditedMinutes); Assert.Equal(f.WorkDate.AddDays(10), credit.Value.ExpiresOn); }
    [Fact] public async Task Credit_approval_is_required_when_policy_requires_it() { await using var f = await CompOffFixture.CreateAsync(RosterDayType.WeeklyOff, 480); Assert.True((await f.Service.CreatePolicyAsync(f.Policy("APP", new(2026, 1, 1), null, ratio: 1, requireApproval: true))).Succeeded); var pending = await f.Service.EarnAsync(new(f.EmployeeId, f.WorkDate, CompOffSourceType.WeekOff, f.AttendanceDayId, 1)); Assert.True(pending.Succeeded); Assert.Equal(CompOffEarningStatus.PendingApproval, pending.Value!.Status); Assert.Equal(0, (await f.Service.GetBalanceAsync(f.EmployeeId)).Value!.AvailableMinutes); Assert.True((await f.Service.ApproveAsync(pending.Value.Id)).Succeeded); Assert.Equal(480, (await f.Service.GetBalanceAsync(f.EmployeeId)).Value!.AvailableMinutes); }
    [Fact] public async Task Ledger_reservation_consumption_release_and_restore_are_idempotent() { await using var f = await CompOffFixture.CreateAsync(RosterDayType.WeeklyOff, 480); Assert.True((await f.Service.CreatePolicyAsync(f.Policy("LED", new(2026, 1, 1), null, ratio: 1))).Succeeded); var earning = await f.Service.EarnAsync(new(f.EmployeeId, f.WorkDate, CompOffSourceType.WeekOff, f.AttendanceDayId, 1)); Assert.True(earning.Succeeded); var leave = Guid.NewGuid(); Assert.True((await f.Service.ReserveAsync(leave, f.EmployeeId, 240)).Succeeded); Assert.True((await f.Service.ReserveAsync(leave, f.EmployeeId, 240)).Succeeded); Assert.Equal(240, (await f.Service.GetBalanceAsync(f.EmployeeId)).Value!.ReservedMinutes); Assert.True((await f.Service.ConsumeAsync(leave)).Succeeded); Assert.Equal(240, (await f.Service.GetBalanceAsync(f.EmployeeId)).Value!.ConsumedMinutes); Assert.True((await f.Service.RestoreAsync(leave)).Succeeded); Assert.Equal(0, (await f.Service.GetBalanceAsync(f.EmployeeId)).Value!.ConsumedMinutes); }
    [Fact] public async Task Earliest_expiry_is_allocated_first_and_insufficient_balance_is_rejected() { await using var f = await CompOffFixture.CreateAsync(RosterDayType.WeeklyOff, 480); Assert.True((await f.Service.CreatePolicyAsync(f.Policy("EARLY", new(2026, 1, 1), null, ratio: 1, expiryDays: 5))).Succeeded); var first = await f.Service.EarnAsync(new(f.EmployeeId, f.WorkDate, CompOffSourceType.WeekOff, f.AttendanceDayId, 1)); Assert.True(first.Succeeded); var secondDay = new DateOnly(2026, 9, 16); var second = await f.AddDayAsync(secondDay, 480); var secondCredit = await f.Service.EarnAsync(new(f.EmployeeId, secondDay, CompOffSourceType.WeekOff, second, 1)); Assert.True(secondCredit.Succeeded); var leave = Guid.NewGuid(); Assert.True((await f.Service.ReserveAsync(leave, f.EmployeeId, 600)).Succeeded); Assert.False((await f.Service.ReserveAsync(Guid.NewGuid(), f.EmployeeId, 400)).Succeeded); var allocations = await f.Db.CompOffLeaveAllocations.Where(x => x.LeaveRequestId == leave).Include(x => x.Earning).OrderBy(x => x.Earning!.ExpiresOn).ToListAsync(); Assert.Equal(first.Value!.Id, allocations[0].EarningId); }
    [Fact] public async Task Expiry_keeps_history_and_removes_available_balance() { await using var f = await CompOffFixture.CreateAsync(RosterDayType.WeeklyOff, 480); Assert.True((await f.Service.CreatePolicyAsync(f.Policy("EXP", new(2026, 1, 1), null, ratio: 1, expiryDays: 1))).Succeeded); var credit = await f.Service.EarnAsync(new(f.EmployeeId, f.WorkDate, CompOffSourceType.WeekOff, f.AttendanceDayId, 1)); Assert.True(credit.Succeeded); Assert.Equal(1, (await f.Service.ExpireAsync(f.WorkDate.AddDays(1))).Value); Assert.Equal(0, (await f.Service.GetBalanceAsync(f.EmployeeId)).Value!.AvailableMinutes); Assert.Contains((await f.Service.GetLedgerAsync(f.EmployeeId)).Value!, x => x.EntryType == CompOffLedgerEntryType.Expire); }
    [Fact] public async Task Source_correction_preserves_v1_and_creates_a_replacement() { await using var f = await CompOffFixture.CreateAsync(RosterDayType.WeeklyOff, 480); Assert.True((await f.Service.CreatePolicyAsync(f.Policy("COR", new(2026, 1, 1), null, ratio: 1))).Succeeded); var v1 = await f.Service.EarnAsync(new(f.EmployeeId, f.WorkDate, CompOffSourceType.WeekOff, f.AttendanceDayId, 1)); Assert.True(v1.Succeeded); var v2 = await f.Service.CorrectSourceAsync(v1.Value!.Id, 240, "Attendance V2 correction"); Assert.True(v2.Succeeded, v2.Message); Assert.Equal(CompOffEarningStatus.Superseded, await f.Db.CompOffEarnings.Where(x => x.Id == v1.Value.Id).Select(x => x.Status).SingleAsync()); Assert.Equal(240, v2.Value!.CreditedMinutes); Assert.Equal(2, await f.Db.CompOffEarnings.CountAsync()); }
    [Fact] public async Task Overtime_source_is_rejected_when_benefit_mode_is_not_dual() { await using var f = await CompOffFixture.CreateAsync(RosterDayType.WeeklyOff, 480); Assert.True((await f.Service.CreatePolicyAsync(f.Policy("EX", new(2026, 1, 1), null, ratio: 1, benefit: CompOffBenefitMode.CompOffOnly))).Succeeded); var result = await f.Service.EarnAsync(new(f.EmployeeId, f.WorkDate, CompOffSourceType.Overtime, f.AttendanceDayId, 1, 480, Guid.NewGuid(), Guid.NewGuid())); Assert.False(result.Succeeded); Assert.Contains("DoubleBenefitDenied", result.Message); }
    [Fact] public async Task Daily_and_monthly_caps_preserve_raw_source_but_cap_credit() { await using var f = await CompOffFixture.CreateAsync(RosterDayType.WeeklyOff, 600); Assert.True((await f.Service.CreatePolicyAsync(f.Policy("CAP", new(2026, 1, 1), null, ratio: 1, dailyCap: 300, monthlyCap: 600))).Succeeded); var first = await f.Service.EarnAsync(new(f.EmployeeId, f.WorkDate, CompOffSourceType.WeekOff, f.AttendanceDayId, 1)); Assert.True(first.Succeeded); Assert.Equal(600, first.Value!.EligibleMinutes); Assert.Equal(300, first.Value.CreditedMinutes); var secondDay = new DateOnly(2026, 9, 16); var second = await f.AddDayAsync(secondDay, 600); var secondCredit = await f.Service.EarnAsync(new(f.EmployeeId, secondDay, CompOffSourceType.WeekOff, second, 1)); Assert.True(secondCredit.Succeeded); Assert.Equal(300, secondCredit.Value!.CreditedMinutes); var thirdDay = new DateOnly(2026, 9, 17); var third = await f.AddDayAsync(thirdDay, 600); Assert.False((await f.Service.EarnAsync(new(f.EmployeeId, thirdDay, CompOffSourceType.WeekOff, third, 1))).Succeeded); }
    [Fact] public async Task Source_increase_creates_only_incremental_entitlement() { await using var f = await CompOffFixture.CreateAsync(RosterDayType.WeeklyOff, 240); Assert.True((await f.Service.CreatePolicyAsync(f.Policy("INC", new(2026, 1, 1), null, ratio: 1))).Succeeded); var v1 = await f.Service.EarnAsync(new(f.EmployeeId, f.WorkDate, CompOffSourceType.WeekOff, f.AttendanceDayId, 1)); Assert.True(v1.Succeeded); var v2 = await f.Service.CorrectSourceAsync(v1.Value!.Id, 480, "Attendance V2 increase"); Assert.True(v2.Succeeded, v2.Message); Assert.Equal(480, v2.Value!.CreditedMinutes); Assert.Equal(CompOffEarningStatus.Superseded, await f.Db.CompOffEarnings.Where(x => x.Id == v1.Value.Id).Select(x => x.Status).SingleAsync()); Assert.Equal(480, (await f.Service.GetBalanceAsync(f.EmployeeId)).Value!.AvailableMinutes); }
    [Fact] public async Task Consumed_credit_reduction_requires_controlled_adjustment() { await using var f = await CompOffFixture.CreateAsync(RosterDayType.WeeklyOff, 480); Assert.True((await f.Service.CreatePolicyAsync(f.Policy("USED", new(2026, 1, 1), null, ratio: 1))).Succeeded); var v1 = await f.Service.EarnAsync(new(f.EmployeeId, f.WorkDate, CompOffSourceType.WeekOff, f.AttendanceDayId, 1)); Assert.True(v1.Succeeded); var leave = Guid.NewGuid(); Assert.True((await f.Service.ReserveAsync(leave, f.EmployeeId, 240)).Succeeded); Assert.True((await f.Service.ConsumeAsync(leave)).Succeeded); var correction = await f.Service.CorrectSourceAsync(v1.Value!.Id, 120, "Attendance V2 reduction"); Assert.False(correction.Succeeded); Assert.Contains("CorrectionRequiresAdjustment", correction.Message); Assert.Equal(240, (await f.Service.GetBalanceAsync(f.EmployeeId)).Value!.ConsumedMinutes); }
    [Fact] public async Task Repeated_transitions_never_create_negative_or_duplicate_entitlement() { await using var f = await CompOffFixture.CreateAsync(RosterDayType.WeeklyOff, 480); Assert.True((await f.Service.CreatePolicyAsync(f.Policy("INV", new(2026, 1, 1), null, ratio: 1, expiryDays: 1))).Succeeded); var credit = await f.Service.EarnAsync(new(f.EmployeeId, f.WorkDate, CompOffSourceType.WeekOff, f.AttendanceDayId, 1)); Assert.True(credit.Succeeded); var leave = Guid.NewGuid(); Assert.True((await f.Service.ReserveAsync(leave, f.EmployeeId, 240)).Succeeded); Assert.True((await f.Service.ConsumeAsync(leave)).Succeeded); Assert.True((await f.Service.ConsumeAsync(leave)).Succeeded); Assert.True((await f.Service.RestoreAsync(leave)).Succeeded); Assert.True((await f.Service.RestoreAsync(leave)).Succeeded); Assert.True((await f.Service.ExpireAsync(f.WorkDate.AddDays(1))).Succeeded); Assert.True((await f.Service.ExpireAsync(f.WorkDate.AddDays(1))).Succeeded); var balance = (await f.Service.GetBalanceAsync(f.EmployeeId)).Value!; Assert.True(balance.AvailableMinutes >= 0); Assert.True(balance.ReservedMinutes >= 0); Assert.True(balance.ConsumedMinutes >= 0); Assert.True(balance.ExpiredMinutes >= 0); }
    [Fact] public async Task Restoration_after_expiry_remains_non_spendable() { await using var f = await CompOffFixture.CreateAsync(RosterDayType.WeeklyOff, 480); Assert.True((await f.Service.CreatePolicyAsync(f.Policy("RESTEXP", new(2026, 1, 1), null, ratio: 1, expiryDays: 1))).Succeeded); var credit = await f.Service.EarnAsync(new(f.EmployeeId, f.WorkDate, CompOffSourceType.WeekOff, f.AttendanceDayId, 1)); Assert.True(credit.Succeeded); var leave = Guid.NewGuid(); Assert.True((await f.Service.ReserveAsync(leave, f.EmployeeId, 240)).Succeeded); Assert.True((await f.Service.ConsumeAsync(leave)).Succeeded); Assert.Equal(1, (await f.Service.ExpireAsync(f.WorkDate.AddDays(1))).Value); Assert.True((await f.Service.RestoreAsync(leave)).Succeeded); var balance = (await f.Service.GetBalanceAsync(f.EmployeeId)).Value!; Assert.Equal(0, balance.AvailableMinutes); Assert.Equal(480, balance.ExpiredMinutes); }

    public sealed class CompOffFixture : IAsyncDisposable
    {
        private readonly SqliteInMemoryDatabase _database; public HRMS.Infrastructure.Persistence.HrmsDbContext Db { get; } public ICompOffService Service { get; } public Guid TenantId { get; } public Guid EmployeeId { get; } public Guid AttendanceDayId { get; private set; } public DateOnly WorkDate { get; } = new(2026, 9, 15);
        private CompOffFixture(SqliteInMemoryDatabase database, HRMS.Infrastructure.Persistence.HrmsDbContext db, Guid tenantId, Guid employeeId) { _database = database; Db = db; TenantId = tenantId; EmployeeId = employeeId; Service = new CompOffService(db, new TestTenantContext(tenantId), TimeProvider.System); }
        public static async Task<CompOffFixture> CreateAsync(RosterDayType dayType, int workedMinutes)
        {
            var database = new SqliteInMemoryDatabase(); var tenant = Guid.NewGuid(); var employee = Guid.NewGuid();
            await using (var catalog = database.CreateCatalogContext())
            {
                catalog.Tenants.Add(new Tenant { Id = tenant, TenantCode = $"CO{tenant:N}"[..12], TenantName = "Comp Off", Host = $"{tenant:N}.test", ShardKey = tenant.ToString("N") });
                await catalog.SaveChangesAsync();
            }
            await using (var seed = database.CreateContext(new TestTenantContext(tenant)))
            {
                seed.Tenants.Add(new Tenant { Id = tenant, TenantCode = $"CO{tenant:N}"[..12], TenantName = "Comp Off", Host = $"{tenant:N}.test", ShardKey = tenant.ToString("N") });
                seed.Employees.Add(new Employee { Id = employee, TenantId = tenant, EmployeeCode = "CO-001", FirstName = "Comp", LastName = "Off", Email = $"{employee:N}@test.local", DateOfJoining = new(2026, 1, 1), Status = EmployeeStatus.Active });
                seed.EmployeeEmploymentHistory.Add(new EmployeeEmploymentHistory { Id = Guid.NewGuid(), TenantId = tenant, EmployeeId = employee, EffectiveFrom = new(2026, 1, 1), EmploymentStatus = EmployeeStatus.Active });
                var day = new EmployeeAttendanceDay { Id = Guid.NewGuid(), TenantId = tenant, EmployeeId = employee, BusinessDate = new(2026, 9, 15), RosterDayType = dayType, Status = dayType == RosterDayType.Holiday ? EmployeeAttendanceDayStatus.Holiday : EmployeeAttendanceDayStatus.WeeklyOff, ExpectedWorkMinutes = 480, WorkedMinutes = workedMinutes, ProcessedAtUtc = DateTime.UtcNow };
                seed.EmployeeAttendanceDays.Add(day); await seed.SaveChangesAsync();
                var db = database.CreateContext(new TestTenantContext(tenant)); return new CompOffFixture(database, db, tenant, employee) { AttendanceDayId = day.Id };
            }
        }
        public async Task<Guid> AddDayAsync(DateOnly date, int worked) { var day = new EmployeeAttendanceDay { Id = Guid.NewGuid(), TenantId = TenantId, EmployeeId = EmployeeId, BusinessDate = date, RosterDayType = RosterDayType.WeeklyOff, Status = EmployeeAttendanceDayStatus.WeeklyOff, ExpectedWorkMinutes = 480, WorkedMinutes = worked, ProcessedAtUtc = DateTime.UtcNow }; Db.EmployeeAttendanceDays.Add(day); await Db.SaveChangesAsync(); return day.Id; }
        public (HRMS.Infrastructure.Persistence.HrmsDbContext Db, ICompOffService Service) CreateIndependentService(params IInterceptor[] interceptors) { var scope = new TestTenantContext(TenantId); var db = _database.CreateIsolatedContext(scope, interceptors); return (db, new CompOffService(db, scope, TimeProvider.System)); }
        public CompOffPolicyRequest Policy(string code, DateOnly from, DateOnly? to, decimal ratio, int minimum = 0, int rounding = 0, CompOffRoundingMode roundingMode = CompOffRoundingMode.None, int? expiryDays = null, bool requireApproval = false, CompOffBenefitMode benefit = CompOffBenefitMode.CompOffOnly, string eligibility = "All", int? dailyCap = null, int? monthlyCap = null) => new(code, code, from, to, true, true, true, minimum, ratio, roundingMode, rounding, dailyCap, monthlyCap, expiryDays, null, requireApproval, true, 1, benefit, eligibility);
        public ValueTask DisposeAsync() { Db.Dispose(); _database.Dispose(); return ValueTask.CompletedTask; }
    }
}
