using System.Text;
using HRMS.Application.DTOs.Payroll;
using HRMS.Application.Services;
using HRMS.Domain.Entities;
using HRMS.Domain.Enums;
using HRMS.Infrastructure.Persistence;
using HRMS.Tests.TestSupport;
using Microsoft.EntityFrameworkCore;

namespace HRMS.Tests;

internal static class PayrollStatutoryComplianceProviderAcceptance
{
    public static async Task RunAsync(HrmsDbContext db, TestTenantContext tenant)
    {
        var tenantId = Guid.NewGuid(); var employeeId = Guid.NewGuid(); var periodId = Guid.NewGuid(); var runId = Guid.NewGuid(); var runEmployeeId = Guid.NewGuid(); var resultId = Guid.NewGuid(); var assignmentId = Guid.NewGuid(); var structureId = Guid.NewGuid(); var structureVersionId = Guid.NewGuid(); var componentId = Guid.NewGuid();
        db.Tenants.Add(new Tenant { Id = tenantId, TenantCode = $"7K{tenantId:N}"[..12], TenantName = "Compliance provider tenant", Host = $"{tenantId:N}.compliance.test", ShardKey = tenantId.ToString("N") }); await db.SaveChangesAsync(); tenant.TenantId = tenantId;
        var payrollPeriod = new PayrollPeriod { Id = periodId, TenantId = tenantId, Code = $"7K-{periodId:N}"[..12], Name = "September 2026", PeriodType = PayrollPeriodType.Monthly, StartDate = new DateOnly(2026, 9, 1), EndDate = new DateOnly(2026, 9, 30), PayDate = new DateOnly(2026, 10, 5), FiscalYear = 2026, PeriodNumber = 9, Status = PayrollPeriodStatus.Locked };
        var employee = new Employee { Id = employeeId, TenantId = tenantId, EmployeeCode = $"EMP-{employeeId:N}"[..12], FirstName = "Compliance", LastName = "Employee", Email = $"{employeeId:N}@compliance.test", DateOfJoining = new DateOnly(2025, 1, 1), Status = EmployeeStatus.Active, UanNumber = $"UAN{employeeId:N}"[..12], EsicNumber = $"ESI{employeeId:N}"[..12], PanNumber = $"PAN{employeeId:N}"[..10] };
        var structure = new SalaryStructure { Id = structureId, TenantId = tenantId, Code = $"STRUCT-{structureId:N}"[..16], Name = "Compliance structure", IsActive = true };
        var structureVersion = new SalaryStructureVersion { Id = structureVersionId, TenantId = tenantId, SalaryStructureId = structureId, EffectiveFrom = payrollPeriod.StartDate, IsActive = true };
        var component = new SalaryComponent { Id = componentId, TenantId = tenantId, Code = $"BASIC{componentId:N}"[..10], Name = "Basic", ComponentType = SalaryComponentType.Earning, CalculationType = SalaryCalculationType.FixedAmount, EffectiveFrom = payrollPeriod.StartDate, IsActive = true, AffectsGross = true, AffectsNetPay = true };
        var assignment = new EmployeeSalaryAssignment { Id = assignmentId, TenantId = tenantId, EmployeeId = employeeId, SalaryStructureId = structureId, SalaryStructureVersionId = structureVersionId, EffectiveFrom = payrollPeriod.StartDate, MonthlyCtc = 10000, CurrencyCode = "INR", Status = EmployeeSalaryAssignmentStatus.Active };
        var runEmployee = new PayrollRunEmployee { Id = runEmployeeId, TenantId = tenantId, PayrollRunId = runId, EmployeeId = employeeId, EmployeeSalaryAssignmentId = assignmentId, SalaryStructureId = structureId, SalaryStructureVersionId = structureVersionId, EmploymentSnapshotDate = payrollPeriod.EndDate, IsEligible = true, Status = PayrollRunEmployeeStatus.Eligible };
        var run = new PayrollRun { Id = runId, TenantId = tenantId, PayrollPeriodId = periodId, RunNumber = $"RUN-{runId:N}"[..12], Status = PayrollRunStatus.Finalized, EmployeeCount = 1 };
        var result = new PayrollResult { Id = resultId, TenantId = tenantId, PayrollRunId = runId, PayrollRunEmployeeId = runEmployeeId, EmployeeId = employeeId, EmployeeSalaryAssignmentId = assignmentId, SalaryStructureId = structureId, SalaryStructureVersionId = structureVersionId, CalculationAttemptId = Guid.NewGuid(), PeriodStartDate = payrollPeriod.StartDate, PeriodEndDate = payrollPeriod.EndDate, EmploymentSnapshotDate = payrollPeriod.EndDate, CalendarDays = 30, EligibleDays = 30, ProrationFactor = 1, CurrencyCode = "INR", GrossEarnings = 10000, TotalDeductions = 1700, NetPay = 8300, Status = PayrollResultStatus.Calculated, IsCurrent = true, Components = [new PayrollResultComponent { Id = Guid.NewGuid(), TenantId = tenantId, SalaryComponentId = componentId, ComponentCode = component.Code, ComponentName = component.Name, ComponentType = SalaryComponentType.Earning, CalculatedAmount = 10000, UnproratedAmount = 10000, IsEarning = true, CalculationSource = "Structure", CalculationSequence = 1 }] };
        db.Employees.Add(employee); db.PayrollPeriods.Add(payrollPeriod); db.SalaryStructures.Add(structure); db.SalaryStructureVersions.Add(structureVersion); db.SalaryComponents.Add(component); db.EmployeeSalaryAssignments.Add(assignment); db.PayrollRuns.Add(run); db.PayrollRunEmployees.Add(runEmployee); db.PayrollResults.Add(result);
        var definitions = new[] { (PayrollComplianceType.ProvidentFund, StatutoryType.ProvidentFund, "PF", 10000m, 500m, 1200m), (PayrollComplianceType.Esi, StatutoryType.Esi, "ESI", 10000m, 300m, 400m), (PayrollComplianceType.ProfessionalTax, StatutoryType.ProfessionalTax, "PT", 10000m, 200m, 0m), (PayrollComplianceType.IncomeTaxTds, StatutoryType.IncomeTax, "TDS", 10000m, 700m, 0m) };
        var statutoryResults = new List<PayrollStatutoryResult>();
        foreach (var definition in definitions) { var configurationId = Guid.NewGuid(); var versionId = Guid.NewGuid(); db.StatutoryConfigurations.Add(new StatutoryConfiguration { Id = configurationId, TenantId = tenantId, Code = $"{definition.Item3}-{configurationId:N}"[..12], Name = $"Provider {definition.Item3}", StatutoryType = definition.Item2, IsActive = true }); db.StatutoryConfigurationVersions.Add(new StatutoryConfigurationVersion { Id = versionId, TenantId = tenantId, StatutoryConfigurationId = configurationId, EffectiveFrom = payrollPeriod.StartDate, Status = StatutoryConfigurationStatus.Active, ConfigurationJson = "{}" }); statutoryResults.Add(new PayrollStatutoryResult { Id = Guid.NewGuid(), TenantId = tenantId, PayrollResultId = resultId, PayrollRunId = runId, EmployeeId = employeeId, StatutoryType = definition.Item2, JurisdictionCode = "IN", StatutoryConfigurationId = configurationId, StatutoryConfigurationVersionId = versionId, CalculationBasis = definition.Item4, EmployeeAmount = definition.Item5, EmployerAmount = definition.Item6, TotalAmount = definition.Item5 + definition.Item6, CreatedAtUtc = DateTime.UtcNow }); }
        db.PayrollStatutoryResults.AddRange(statutoryResults); await db.SaveChangesAsync();
        var service = new PayrollStatutoryComplianceService(db, tenant, TimeProvider.System);
        foreach (var definition in definitions)
        {
            var period = await service.CreatePeriodAsync(new PayrollCompliancePeriodRequest { JurisdictionCode = "IN", ComplianceType = definition.Item1, PeriodStart = payrollPeriod.StartDate, PeriodEnd = payrollPeriod.EndDate }); Assert.True(period.Succeeded, period.Message); var generated = await service.GenerateAsync(period.Value!.Id); Assert.True(generated.Succeeded, $"{definition.Item3}: {generated.Message}"); Assert.Equal(definition.Item1, generated.Value!.ComplianceType); Assert.Equal(1, generated.Value.EmployeeCount); Assert.Equal(definition.Item4, generated.Value.GrossRelevantWages); Assert.Equal(definition.Item5, generated.Value.EmployeeContribution); Assert.Equal(definition.Item6, generated.Value.EmployerContribution); Assert.Single(generated.Value.Employees); Assert.Single(await db.PayrollStatutoryReturnSources.Where(x => x.PayrollStatutoryReturnBatchId == generated.Value.Id).ToListAsync()); var row = generated.Value.Employees[0]; if (definition.Item1 == PayrollComplianceType.ProvidentFund) Assert.Equal(employee.UanNumber, row.Uan); if (definition.Item1 == PayrollComplianceType.Esi) Assert.Equal(employee.EsicNumber, row.EsicNumber); if (definition.Item1 == PayrollComplianceType.IncomeTaxTds) Assert.Equal(employee.PanNumber, row.Pan); Assert.True((await service.ValidateAsync(generated.Value.Id)).Succeeded); Assert.True((await service.ApproveAsync(generated.Value.Id)).Succeeded); var export = await service.ExportAsync(generated.Value.Id); Assert.True(export.Succeeded, export.Message); Assert.Contains("EmployeeCode,EmployeeName,Identifier", Encoding.UTF8.GetString(export.Value!.Content)); var filed = await service.MarkFiledAsync(generated.Value.Id, "MANUAL-7K"); Assert.True(filed.Succeeded, filed.Message); Assert.Equal(PayrollStatutoryReturnStatus.Filed, filed.Value!.Status); Assert.False((await new PayrollStatutoryComplianceService(db, new TestTenantContext(Guid.NewGuid()), TimeProvider.System).GetAsync(generated.Value.Id)).Succeeded);
        }
    }
}
