using HRMS.Application.Services;
using HRMS.Application.DTOs.Separation;
using HRMS.Domain.Entities;
using HRMS.Domain.Enums;
using HRMS.Infrastructure.Persistence;
using HRMS.Tests.TestSupport;
using Microsoft.EntityFrameworkCore;

namespace HRMS.Tests;

public sealed class SeparationSettlementConcurrencyTests
{
    [Fact] public async Task Initiate_vs_initiate() { var setup = await ReadyAsync(); var results = await Task.WhenAll(InvokeSuccess(setup, s => s.InitiateAsync(setup.Fixture.SeparationId, new())), InvokeSuccess(setup, s => s.InitiateAsync(setup.Fixture.SeparationId, new()))); await AssertOneSettlementAsync(setup); Assert.Contains(results, x => x); }
    [Fact] public async Task Initiate_vs_clearance_reopen() { var setup = await ReadyAsync(); var results = await Task.WhenAll(InvokeSuccess(setup, s => s.InitiateAsync(setup.Fixture.SeparationId, new())), ReopenClearanceAsync(setup)); Assert.Contains(results, x => x); await AssertOneSettlementAsync(setup); }
    [Fact] public async Task Initiate_vs_lwd_revision() { var setup = await ReadyAsync(); var results = await Task.WhenAll(InvokeSuccess(setup, s => s.InitiateAsync(setup.Fixture.SeparationId, new())), ReviseLwdAsync(setup)); Assert.Contains(results, x => x); await AssertOneSettlementAsync(setup); }
    [Fact] public async Task Retry_vs_retry() { var setup = await ReadyAsync(); await SeedFailedAsync(setup); var results = await Task.WhenAll(InvokeSuccess(setup, s => s.RetryAsync(setup.Fixture.SeparationId, new SettlementRetryRequest { Reason = "retry" })), InvokeSuccess(setup, s => s.RetryAsync(setup.Fixture.SeparationId, new SettlementRetryRequest { Reason = "retry" }))); await AssertOneSettlementAsync(setup); Assert.Contains(results, x => x); }
    [Fact] public async Task Settlement_complete_vs_clearance_reopen() { var setup = await ReadyAsync(); await SeedFinalizedAsync(setup); var results = await Task.WhenAll(InvokeSuccess(setup, s => s.GetStatusAsync(setup.Fixture.SeparationId)), ReopenClearanceAsync(setup)); Assert.Contains(results, x => x); }
    [Fact] public async Task Settlement_complete_vs_lwd_revision() { var setup = await ReadyAsync(); await SeedFinalizedAsync(setup); var results = await Task.WhenAll(InvokeSuccess(setup, s => s.GetStatusAsync(setup.Fixture.SeparationId)), ReviseLwdAsync(setup)); Assert.Contains(results, x => x); Assert.False(await ReviseLwdAsync(setup)); }

    private static async Task<(SqliteInMemoryDatabase Database, NoticeFixture Fixture)> ReadyAsync() { var database = new SqliteInMemoryDatabase(); var fixture = await NoticeTestData.CreateApprovedAsync(database, new(2026, 10, 2)); await SettlementTestData.SeedReadyState(database, fixture); return (database, fixture); }
    private static async Task<bool> InvokeSuccess<T>((SqliteInMemoryDatabase Database, NoticeFixture Fixture) setup, Func<SeparationSettlementOrchestrationService, Task<HRMS.Application.Common.Result<T>>> call) { try { await using var db = setup.Database.CreateContext(new TestTenantContext(setup.Fixture.TenantId, setup.Fixture.HrUserId)); return (await call(SettlementTestData.Service(db, setup.Fixture))).Succeeded; } catch (DbUpdateException) { return false; } }
    private static async Task<bool> ReopenClearanceAsync((SqliteInMemoryDatabase Database, NoticeFixture Fixture) setup) { await using var db = setup.Database.CreateContext(new TestTenantContext(setup.Fixture.TenantId, setup.Fixture.HrUserId)); var clearance = await db.SeparationClearances.SingleAsync(); return (await new ClearanceService(db, new TestTenantContext(setup.Fixture.TenantId, setup.Fixture.HrUserId), new EmployeeIdentityResolver(db, new TestTenantContext(setup.Fixture.TenantId, setup.Fixture.HrUserId)), new EmployeeManagerResolver(db, new TestTenantContext(setup.Fixture.TenantId, setup.Fixture.HrUserId)), TimeProvider.System).ReopenAsync(clearance.Id, "concurrent reopen")).Succeeded; }
    private static async Task<bool> ReviseLwdAsync((SqliteInMemoryDatabase Database, NoticeFixture Fixture) setup) { await using var db = setup.Database.CreateContext(new TestTenantContext(setup.Fixture.TenantId, setup.Fixture.HrUserId)); return (await NoticeTestData.CreateService(db, setup.Fixture.TenantId, setup.Fixture.HrUserId).ReviseApprovedLwdAsync(setup.Fixture.SeparationId, new(new(2026, 10, 3), "concurrent LWD revision"))).Succeeded; }
    private static async Task SeedFailedAsync((SqliteInMemoryDatabase Database, NoticeFixture Fixture) setup) { await using var db = setup.Database.CreateContext(new TestTenantContext(setup.Fixture.TenantId, setup.Fixture.HrUserId)); db.SeparationSettlementOrchestrations.Add(new() { Id = Guid.NewGuid(), TenantId = setup.Fixture.TenantId, EmployeeSeparationId = setup.Fixture.SeparationId, EmployeeId = setup.Fixture.EmployeeId, Status = SeparationSettlementOrchestrationStatus.Failed }); await db.SaveChangesAsync(); }
    private static async Task SeedFinalizedAsync((SqliteInMemoryDatabase Database, NoticeFixture Fixture) setup) { await using var db = setup.Database.CreateContext(new TestTenantContext(setup.Fixture.TenantId, setup.Fixture.HrUserId)); var settlement = new FinalSettlementCase { Id = Guid.NewGuid(), TenantId = setup.Fixture.TenantId, EmployeeId = setup.Fixture.EmployeeId, SeparationDate = new(2026, 10, 2), LastWorkingDate = new(2026, 10, 2), SettlementDate = new(2026, 10, 2), Status = FinalSettlementStatus.Finalized }; db.FinalSettlementCases.Add(settlement); db.SeparationSettlementOrchestrations.Add(new() { Id = Guid.NewGuid(), TenantId = setup.Fixture.TenantId, EmployeeSeparationId = setup.Fixture.SeparationId, EmployeeId = setup.Fixture.EmployeeId, PayrollFinalSettlementId = settlement.Id, Status = SeparationSettlementOrchestrationStatus.Initiated }); await db.SaveChangesAsync(); }
    private static async Task AssertOneSettlementAsync((SqliteInMemoryDatabase Database, NoticeFixture Fixture) setup) { await using var db = setup.Database.CreateContext(new TestTenantContext(setup.Fixture.TenantId, setup.Fixture.HrUserId)); Assert.Equal(1, await db.SeparationSettlementOrchestrations.CountAsync()); Assert.Equal(1, await db.FinalSettlementCases.CountAsync(x => x.EmployeeId == setup.Fixture.EmployeeId)); }
}
