using HRMS.Application.Abstractions;
using HRMS.Application.Services;
using HRMS.Domain.Entities;
using HRMS.Domain.Entities.Separation;
using HRMS.Domain.Enums;
using HRMS.Infrastructure.Persistence;
using HRMS.Tests.TestSupport;
using Microsoft.EntityFrameworkCore;

namespace HRMS.Tests;

public sealed class SeparationSettlementFailureInjectionTests
{
    [Fact] public async Task Settlement_initiation_failure_rolls_back_or_reconciles() { using var database = new SqliteInMemoryDatabase(); var fixture = await NoticeTestData.CreateApprovedAsync(database, new(2026, 10, 2)); await SettlementTestData.SeedReadyState(database, fixture); await using var failing = database.CreateContext(new TestTenantContext(fixture.TenantId, fixture.HrUserId)); var result = await SettlementTestData.Service(failing, fixture, new OneShotInjector { Initiation = true }).InitiateAsync(fixture.SeparationId, new()); Assert.False(result.Succeeded); await using var retry = database.CreateContext(new TestTenantContext(fixture.TenantId, fixture.HrUserId)); Assert.True((await SettlementTestData.Service(retry, fixture).InitiateAsync(fixture.SeparationId, new())).Succeeded); }
    [Fact] public async Task Payroll_link_persistence_failure_is_recoverable() { using var database = new SqliteInMemoryDatabase(); var fixture = await NoticeTestData.CreateApprovedAsync(database, new(2026, 10, 2)); await SettlementTestData.SeedReadyState(database, fixture); await using var failing = database.CreateContext(new TestTenantContext(fixture.TenantId, fixture.HrUserId)); var result = await SettlementTestData.Service(failing, fixture, new OneShotInjector { Link = true }).InitiateAsync(fixture.SeparationId, new()); Assert.False(result.Succeeded); await using var retry = database.CreateContext(new TestTenantContext(fixture.TenantId, fixture.HrUserId)); Assert.True((await SettlementTestData.Service(retry, fixture).InitiateAsync(fixture.SeparationId, new())).Succeeded); Assert.Equal(1, await retry.FinalSettlementCases.CountAsync()); }
    [Fact] public async Task Completion_sync_failure_is_replay_safe() { using var database = new SqliteInMemoryDatabase(); var fixture = await NoticeTestData.CreateApprovedAsync(database, new(2026, 10, 2)); await SettlementTestData.SeedReadyState(database, fixture); await SettlementTestData.SeedFinalizedAsync(database, fixture); await using var failing = database.CreateContext(new TestTenantContext(fixture.TenantId, fixture.HrUserId)); var result = await SettlementTestData.Service(failing, fixture, new OneShotInjector { Completion = true }).GetStatusAsync(fixture.SeparationId); Assert.False(result.Succeeded); await using var retry = database.CreateContext(new TestTenantContext(fixture.TenantId, fixture.HrUserId)); var replay = await SettlementTestData.Service(retry, fixture).GetStatusAsync(fixture.SeparationId); Assert.True(replay.Succeeded); Assert.True(replay.Value!.ReadyForFinalExitClosure); }
    private sealed class OneShotInjector : ISeparationSettlementFailureInjector { public bool Initiation { get; init; } public bool Link { get; init; } public bool Completion { get; init; } public void BeforeInitiationCommit() { if (Initiation) throw new InvalidOperationException("Injected initiation failure."); } public void BeforePayrollLinkCommit() { if (Link) throw new InvalidOperationException("Injected link failure."); } public void BeforeCompletionSyncCommit() { if (Completion) throw new InvalidOperationException("Injected completion failure."); } }
}

internal static class SettlementTestData
{
    public static SeparationSettlementOrchestrationService Service(HrmsDbContext db, NoticeFixture fixture, ISeparationSettlementFailureInjector? injector = null) => new(db, new TestTenantContext(fixture.TenantId, fixture.HrUserId), new PayrollRetroSettlementService(db, new TestTenantContext(fixture.TenantId, fixture.HrUserId), TimeProvider.System), TimeProvider.System, injector);
    public static async Task SeedReadyState(SqliteInMemoryDatabase database, NoticeFixture fixture) { await using var db = database.CreateContext(new TestTenantContext(fixture.TenantId, fixture.HrUserId)); db.SeparationClearances.Add(new SeparationClearance { Id = Guid.NewGuid(), TenantId = fixture.TenantId, EmployeeSeparationId = fixture.SeparationId, EmployeeId = fixture.EmployeeId, TemplateId = Guid.NewGuid(), Status = SeparationClearanceStatus.Completed, CompletedAtUtc = DateTime.UtcNow }); db.SeparationExitInterviews.Add(new SeparationExitInterview { Id = Guid.NewGuid(), TenantId = fixture.TenantId, EmployeeSeparationId = fixture.SeparationId, EmployeeId = fixture.EmployeeId, TemplateVersionId = Guid.NewGuid(), Status = SeparationExitInterviewStatus.Completed, AssignedAtUtc = DateTime.UtcNow, HrCompletedAtUtc = DateTime.UtcNow, FinalizedAtUtc = DateTime.UtcNow }); await db.SaveChangesAsync(); }
    public static async Task SeedFinalizedAsync(SqliteInMemoryDatabase database, NoticeFixture fixture) { await using var db = database.CreateContext(new TestTenantContext(fixture.TenantId, fixture.HrUserId)); var settlement = new FinalSettlementCase { Id = Guid.NewGuid(), TenantId = fixture.TenantId, EmployeeId = fixture.EmployeeId, SeparationDate = new(2026, 10, 2), LastWorkingDate = new(2026, 10, 2), SettlementDate = new(2026, 10, 2), Status = FinalSettlementStatus.Finalized }; db.FinalSettlementCases.Add(settlement); db.SeparationSettlementOrchestrations.Add(new() { Id = Guid.NewGuid(), TenantId = fixture.TenantId, EmployeeSeparationId = fixture.SeparationId, EmployeeId = fixture.EmployeeId, PayrollFinalSettlementId = settlement.Id, Status = SeparationSettlementOrchestrationStatus.Initiated }); await db.SaveChangesAsync(); }
}
