using HRMS.Application.DTOs.Payroll;
using HRMS.Application.Services;
using HRMS.Domain.Enums;
using Microsoft.EntityFrameworkCore;

namespace HRMS.Tests;

public sealed class StatutoryFilingRetrySafetyTests
{
    [Fact] public async Task Generate_retry_is_safe() { await using var s = await FilingScenario.CreateAsync(); var service = new StatutoryFilingService(s.Db, s.Tenant, TimeProvider.System); Assert.True((await service.GenerateAsync(s.RunId)).Succeeded); Assert.True((await service.GenerateAsync(s.RunId)).Succeeded); Assert.Equal(1, await s.Db.StatutoryFilingPackages.CountAsync()); }
    [Fact] public async Task Validate_retry_is_safe() { await using var s = await FilingScenario.CreateAsync(); var service = new StatutoryFilingService(s.Db, s.Tenant, TimeProvider.System); await service.GenerateAsync(s.RunId); Assert.True((await service.ValidateAsync(s.RunId)).Succeeded); Assert.True((await service.ValidateAsync(s.RunId)).Succeeded); Assert.Equal(0, await s.Db.StatutoryFilingValidationIssues.CountAsync()); }
    [Fact] public async Task Submit_for_approval_retry_is_safe() { await using var s = await FilingScenario.CreateAsync(); var service = new StatutoryFilingService(s.Db, s.Tenant, TimeProvider.System); await service.GenerateAsync(s.RunId); await service.ValidateAsync(s.RunId); Assert.True((await service.SubmitForApprovalAsync(s.RunId)).Succeeded); Assert.False((await service.SubmitForApprovalAsync(s.RunId)).Succeeded); }
    [Fact] public async Task Approve_retry_is_safe() { await using var s = await FilingScenario.CreateAsync(); var service = new StatutoryFilingService(s.Db, s.Tenant, TimeProvider.System); await service.GenerateAsync(s.RunId); await service.ValidateAsync(s.RunId); await service.SubmitForApprovalAsync(s.RunId); s.Tenant.UserId = s.CheckerId; Assert.True((await service.ApproveAsync(s.RunId)).Succeeded); Assert.False((await service.ApproveAsync(s.RunId)).Succeeded); Assert.Equal(1, await s.Db.StatutoryFilingHistories.CountAsync(x => x.Event == StatutoryFilingHistoryEvent.Approved)); }
    [Fact] public async Task Submit_retry_is_safe() { await using var s = await FilingScenario.CreateAsync(); var service = new StatutoryFilingService(s.Db, s.Tenant, TimeProvider.System); await service.GenerateAsync(s.RunId); await service.ValidateAsync(s.RunId); await service.SubmitForApprovalAsync(s.RunId); s.Tenant.UserId = s.CheckerId; await service.ApproveAsync(s.RunId); Assert.True((await service.SubmitAsync(s.RunId)).Succeeded); Assert.True((await service.SubmitAsync(s.RunId)).Succeeded); Assert.Equal(1, await s.Db.StatutoryFilingSubmissions.CountAsync()); }
    [Fact] public async Task Status_refresh_retry_is_safe() { await using var s = await FilingScenario.CreateAsync(); var service = new StatutoryFilingService(s.Db, s.Tenant, TimeProvider.System); await service.GenerateAsync(s.RunId); var first = await service.GetPackageAsync(s.RunId); var second = await service.GetPackageAsync(s.RunId); Assert.Equal(first.Value!.PackageHash, second.Value!.PackageHash); }
    [Fact] public async Task Acknowledgement_retry_is_safe() { await using var s = await FilingScenario.CreateAsync(); var service = new StatutoryFilingService(s.Db, s.Tenant, TimeProvider.System); await service.GenerateAsync(s.RunId); await service.ValidateAsync(s.RunId); await service.SubmitForApprovalAsync(s.RunId); s.Tenant.UserId = s.CheckerId; await service.ApproveAsync(s.RunId); await service.SubmitAsync(s.RunId); var request = new StatutoryFilingAcknowledgementRequest { ReferenceNumber = "RETRY-ACK" }; Assert.True((await service.AcknowledgeAsync(s.RunId, request)).Succeeded); Assert.True((await service.AcknowledgeAsync(s.RunId, request)).Succeeded); Assert.Equal(1, await s.Db.StatutoryFilingAcknowledgements.CountAsync()); }
    [Fact] public async Task Resubmission_retry_is_safe() { await using var s = await FilingScenario.CreateAsync(); var service = new StatutoryFilingService(s.Db, s.Tenant, TimeProvider.System); await service.GenerateAsync(s.RunId); var first = await service.GetPackageAsync(s.RunId); var second = await service.GetPackageAsync(s.RunId); Assert.Equal(first.Value!.Id, second.Value!.Id); Assert.Equal(1, await s.Db.StatutoryFilingPackages.CountAsync()); }
}
