import { useEffect, useState, type ReactNode } from 'react'
import { toApiError } from '../api/errors.ts'
import { fetchTenantRecoverySettings, saveTenantRecoverySettings, type TenantRecoverySettings } from '../api/tenantRecoverySettings.ts'

const defaults: TenantRecoverySettings = { passwordRecoveryEnabled: true, allowEmailOtp: true, allowSmsOtp: true, otpExpiryMinutes: 5, otpMaxAttempts: 5, otpResendCooldownSeconds: 60, otpMaxResends: 5 }
type NumericField = 'otpExpiryMinutes' | 'otpResendCooldownSeconds' | 'otpMaxAttempts' | 'otpMaxResends'
type FormErrors = Partial<Record<NumericField, string>>

function SecurityIcon({ className = 'recovery-settings-icon' }: { className?: string }) { return <svg aria-hidden="true" viewBox="0 0 24 24" className={className}><path d="M12 3 19 6v5c0 4.6-2.9 8.2-7 10-4.1-1.8-7-5.4-7-10V6z" /><path d="m9 12 2 2 4-4" /></svg> }
function MailIcon() { return <svg aria-hidden="true" viewBox="0 0 24 24" className="recovery-settings-option-icon"><rect x="3" y="5" width="18" height="14" rx="2" /><path d="m4 7 8 6 8-6" /></svg> }
function PhoneIcon() { return <svg aria-hidden="true" viewBox="0 0 24 24" className="recovery-settings-option-icon"><rect x="7" y="3" width="10" height="18" rx="2" /><path d="M10 6h4M11 18h2" /></svg> }
function ClockIcon() { return <svg aria-hidden="true" viewBox="0 0 24 24" className="recovery-settings-field-icon"><circle cx="12" cy="12" r="8" /><path d="M12 7v5l3 2" /></svg> }
function RefreshIcon() { return <svg aria-hidden="true" viewBox="0 0 24 24" className="recovery-settings-field-icon"><path d="M4 7v5h5M5 12a7 7 0 1 0 2-5" /><path d="M12 8v4l2 2" /></svg> }
function SendIcon() { return <svg aria-hidden="true" viewBox="0 0 24 24" className="recovery-settings-field-icon"><path d="m4 4 16 8-16 8 3-8z" /><path d="M7 12h13" /></svg> }

function ToggleSwitch({ id, checked, onChange }: { id: string; checked: boolean; onChange: (value: boolean) => void }) { return <span className="recovery-toggle"><input id={id} type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /><span aria-hidden="true" /></span> }
function RecoveryOptionCard({ id, title, description, checked, icon, onChange }: { id: string; title: string; description: string; checked: boolean; icon: ReactNode; onChange: (value: boolean) => void }) { return <div className={`recovery-option-card${checked ? '' : ' is-disabled'}`}><span className="recovery-option-icon-box">{icon}</span><div className="recovery-option-copy"><label htmlFor={id}>{title}</label><p>{description}</p></div><ToggleSwitch id={id} checked={checked} onChange={onChange} /></div> }
function OtpSettingField({ id, label, value, helper, icon, min, max, error, onChange }: { id: NumericField; label: string; value: number; helper: string; icon: ReactNode; min: number; max: number; error?: string; onChange: (value: number) => void }) { return <label className={`recovery-setting-field${error ? ' has-error' : ''}`} htmlFor={id}><span className="recovery-setting-label">{label}</span><span className="recovery-number-input"><span>{icon}</span><input id={id} type="number" inputMode="numeric" min={min} max={max} value={value} aria-invalid={Boolean(error)} aria-describedby={`${id}-help`} onChange={(event) => onChange(Number(event.target.value))} /></span><small id={`${id}-help`}>{error ?? helper}</small></label> }

export function TenantPasswordRecoverySettingsPage() {
  const [settings, setSettings] = useState(defaults)
  const [initialSettings, setInitialSettings] = useState(defaults)
  const [message, setMessage] = useState('')
  const [busy, setBusy] = useState(false)
  const [errors, setErrors] = useState<FormErrors>({})

  useEffect(() => { void fetchTenantRecoverySettings().then((value) => { setSettings(value); setInitialSettings(value) }).catch((e) => setMessage(toApiError(e).message)) }, [])
  function validate() { const next: FormErrors = {}; if (settings.otpExpiryMinutes < 1 || settings.otpExpiryMinutes > 60) next.otpExpiryMinutes = 'OTP expiry must be between 1 and 60 minutes.'; if (settings.otpResendCooldownSeconds < 10 || settings.otpResendCooldownSeconds > 3600) next.otpResendCooldownSeconds = 'OTP resend cooldown must be between 10 and 3600 seconds.'; if (settings.otpMaxAttempts < 1 || settings.otpMaxAttempts > 10) next.otpMaxAttempts = 'Maximum attempts must be between 1 and 10.'; if (settings.otpMaxResends < 1 || settings.otpMaxResends > 10) next.otpMaxResends = 'Maximum resends must be between 1 and 10.'; setErrors(next); return Object.keys(next).length === 0 }
  async function save() { if (busy || !validate()) return; setBusy(true); setMessage(''); try { const saved = await saveTenantRecoverySettings(settings); setSettings(saved); setInitialSettings(saved); setMessage('Password recovery settings saved.') } catch (e) { setMessage(toApiError(e).message) } finally { setBusy(false) } }
  function reset() { setSettings(initialSettings); setErrors({}); setMessage('') }
  function update(field: NumericField, value: number) { setSettings({ ...settings, [field]: value }); if (errors[field]) setErrors({ ...errors, [field]: undefined }) }

  return <main className="recovery-settings-page">
    <section className="recovery-settings-hero"><div className="recovery-settings-hero-copy"><span className="recovery-settings-hero-icon"><SecurityIcon /></span><div><h1>Password Recovery Settings</h1><p>Choose how users can recover access to this tenant.</p></div></div><div className="recovery-settings-security-note"><span className="recovery-settings-security-icon"><SecurityIcon /></span><div><strong>Secure Access</strong><span>Help your users get back to work safely.</span></div></div></section>
    <section className="recovery-settings-card" aria-labelledby="recovery-options-heading">
      <div className="recovery-settings-section recovery-options-section"><div className="recovery-settings-section-heading"><div><h2 id="recovery-options-heading">Recovery Options</h2><p>Enable the recovery methods available to users.</p></div></div><div className="recovery-options-grid"><RecoveryOptionCard id="passwordRecoveryEnabled" title="Enable Forgot Password" description="Allow users to reset their password using the Forgot Password link." checked={settings.passwordRecoveryEnabled} icon={<SecurityIcon className="recovery-settings-option-icon" />} onChange={(value) => setSettings({ ...settings, passwordRecoveryEnabled: value })} /><RecoveryOptionCard id="allowEmailOtp" title="Allow Email OTP" description="Send a one-time password via email for verification." checked={settings.allowEmailOtp} icon={<MailIcon />} onChange={(value) => setSettings({ ...settings, allowEmailOtp: value })} /><RecoveryOptionCard id="allowSmsOtp" title="Allow Mobile OTP" description="Send a one-time password via mobile/SMS for verification." checked={settings.allowSmsOtp} icon={<PhoneIcon />} onChange={(value) => setSettings({ ...settings, allowSmsOtp: value })} /></div></div>
      <div className="recovery-settings-section"><div className="recovery-settings-section-heading"><div><h2>OTP Configuration</h2><p>Configure OTP related timing and security settings.</p></div></div><div className="recovery-otp-panel"><OtpSettingField id="otpExpiryMinutes" label="OTP expiry (minutes)" value={settings.otpExpiryMinutes} min={1} max={60} helper="Time before the OTP expires." icon={<ClockIcon />} error={errors.otpExpiryMinutes} onChange={(value) => update('otpExpiryMinutes', value)} /><OtpSettingField id="otpResendCooldownSeconds" label="OTP resend cooldown (seconds)" value={settings.otpResendCooldownSeconds} min={10} max={3600} helper="Minimum time between OTP resend requests." icon={<RefreshIcon />} error={errors.otpResendCooldownSeconds} onChange={(value) => update('otpResendCooldownSeconds', value)} /><OtpSettingField id="otpMaxAttempts" label="OTP maximum attempts" value={settings.otpMaxAttempts} min={1} max={10} helper="Maximum invalid OTP attempts allowed." icon={<SecurityIcon className="recovery-settings-field-icon" />} error={errors.otpMaxAttempts} onChange={(value) => update('otpMaxAttempts', value)} /><OtpSettingField id="otpMaxResends" label="OTP maximum resends" value={settings.otpMaxResends} min={1} max={10} helper="Maximum number of OTP resend requests." icon={<SendIcon />} error={errors.otpMaxResends} onChange={(value) => update('otpMaxResends', value)} /></div></div>
      <div className="recovery-settings-info"><span className="recovery-settings-info-icon">i</span><div><strong>Important</strong><p>These settings apply to all users in this tenant. Configure secure values to help prevent misuse.</p></div></div>
      {message && <p className={`recovery-settings-message${message === 'Password recovery settings saved.' ? ' is-success' : ' is-error'}`} role="status">{message}</p>}
      <footer className="recovery-settings-actions"><button className="button button-secondary" type="button" onClick={reset} disabled={busy}><RefreshIcon />Reset</button><button className="button button-primary" type="button" onClick={() => void save()} disabled={busy}><SendIcon />{busy ? 'Saving…' : 'Save Settings'}</button></footer>
    </section>
  </main>
}
