import { useEffect, useState } from 'react'
import { fetchTenantRecoverySettings, saveTenantRecoverySettings, type TenantRecoverySettings } from '../api/tenantRecoverySettings.ts'
import { toApiError } from '../api/errors.ts'

const defaults: TenantRecoverySettings = { passwordRecoveryEnabled: true, allowEmailOtp: true, allowSmsOtp: true, otpExpiryMinutes: 5, otpMaxAttempts: 5, otpResendCooldownSeconds: 60, otpMaxResends: 5 }
export function TenantPasswordRecoverySettingsPage() {
  const [settings, setSettings] = useState(defaults); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => { void fetchTenantRecoverySettings().then(setSettings).catch((e) => setMessage(toApiError(e).message)) }, [])
  async function save() { setBusy(true); setMessage(''); try { setSettings(await saveTenantRecoverySettings(settings)); setMessage('Password recovery settings saved.') } catch (e) { setMessage(toApiError(e).message) } finally { setBusy(false) } }
  return <main className="card"><h1>Password Recovery Settings</h1><p>Choose how users can recover access to this tenant.</p><label><input type="checkbox" checked={settings.passwordRecoveryEnabled} onChange={(e) => setSettings({ ...settings, passwordRecoveryEnabled: e.target.checked })} /> Enable Forgot Password</label><label><input type="checkbox" checked={settings.allowEmailOtp} onChange={(e) => setSettings({ ...settings, allowEmailOtp: e.target.checked })} /> Allow Email OTP</label><label><input type="checkbox" checked={settings.allowSmsOtp} onChange={(e) => setSettings({ ...settings, allowSmsOtp: e.target.checked })} /> Allow Mobile OTP</label><label>OTP expiry (minutes)<input type="number" min="1" max="60" value={settings.otpExpiryMinutes} onChange={(e) => setSettings({ ...settings, otpExpiryMinutes: Number(e.target.value) })} /></label><label>OTP resend cooldown (seconds)<input type="number" min="10" max="3600" value={settings.otpResendCooldownSeconds} onChange={(e) => setSettings({ ...settings, otpResendCooldownSeconds: Number(e.target.value) })} /></label><label>OTP maximum attempts<input type="number" min="1" max="10" value={settings.otpMaxAttempts} onChange={(e) => setSettings({ ...settings, otpMaxAttempts: Number(e.target.value) })} /></label><label>OTP maximum resends<input type="number" min="1" max="10" value={settings.otpMaxResends} onChange={(e) => setSettings({ ...settings, otpMaxResends: Number(e.target.value) })} /></label>{message && <p role="status">{message}</p>}<button type="button" onClick={() => void save()} disabled={busy}>Save Settings</button></main>
}
