import { useEffect, useState } from 'react'
import { approveBankAdvice, exportBankAdvice, getBankAdvice, listBankAdvice, prepareBankAdvice, type BankAdviceBatch, type BankAdvicePayment, validateBankAdvice } from '../../api/payroll.ts'

export function BankAdvicePage() {
  const [batches, setBatches] = useState<BankAdviceBatch[]>([])
  const [selected, setSelected] = useState<BankAdviceBatch | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [busy, setBusy] = useState(false)
  const load = async () => { try { setError(null); const page = await listBankAdvice({ page: 1, pageSize: 25 }); setBatches(page.items) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load bank advice.') } }
  useEffect(() => { void load() }, [])
  const select = async (id: string) => { try { setError(null); setSelected(await getBankAdvice(id)) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load the batch.') } }
  const action = async (fn: (id: string) => Promise<BankAdviceBatch>) => { if (!selected) return; try { setBusy(true); setSelected(await fn(selected.id)); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Bank advice action failed.') } finally { setBusy(false) } }
  const download = async () => { if (!selected) return; try { const blob = await exportBankAdvice(selected.id); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `${selected.batchNumber.replaceAll('/', '-')}.csv`; anchor.click(); URL.revokeObjectURL(url); await select(selected.id) } catch (e) { setError(e instanceof Error ? e.message : 'Export failed.') } }
  return <section className="page-shell"><div className="page-heading"><div><p className="eyebrow">Payroll</p><h1>Bank Advice</h1><p>Prepare controlled payment instructions from approved payroll results.</p></div></div>{error && <p role="alert">{error}</p>}<div className="split-layout"><div className="card"><h2>Batches</h2>{batches.length === 0 ? <p>No bank advice batches found.</p> : <ul>{batches.map(batch => <li key={batch.id}><button type="button" onClick={() => void select(batch.id)}>{batch.batchNumber} — {batch.status} — {batch.totalAmount.toFixed(2)} {batch.currencyCode}</button></li>)}</ul>}</div>{selected && <div className="card"><h2>{selected.batchNumber}</h2><p>Pay date {selected.payDate} · {selected.totalEmployees} employees · {selected.totalAmount.toFixed(2)} {selected.currencyCode}</p><div className="button-row">{selected.status === 'Draft' && <><button disabled={busy} onClick={() => void action(validateBankAdvice)}>Validate</button><button disabled={busy} onClick={() => void action(prepareBankAdvice)}>Prepare</button></>}{selected.status === 'Prepared' && <button disabled={busy} onClick={() => void action(approveBankAdvice)}>Approve</button>}{(selected.status === 'Approved' || selected.status === 'Exported') && <button disabled={busy} onClick={() => void download()}>Export CSV</button>}</div><table><thead><tr><th>Employee</th><th>Account</th><th>Amount</th><th>Validation</th></tr></thead><tbody>{selected.payments.map((payment: BankAdvicePayment) => <tr key={payment.id}><td>{payment.employeeCode} — {payment.employeeName}</td><td>{payment.bankName} {payment.maskedAccountNumber}</td><td>{payment.netPay.toFixed(2)}</td><td>{payment.validationStatus}{payment.validationMessage && `: ${payment.validationMessage}`}</td></tr>)}</tbody></table></div>}</div></section>
}
