import { useState } from 'react'
import { Card } from '../../components/Card.tsx'
import { PageHeader } from '../../components/PageHeader.tsx'
import { useApiQuery } from '../../hooks/useApiQuery.ts'
import { useAuth } from '../../auth/useAuth.ts'
import { Permissions } from '../../auth/permissions.ts'
import { approvePayrollInputBatch, createPayrollInputBatch, getPayrollInputIssues, listPayrollInputTemplates, listPayrollInputBatches, payrollInputExportUrl, postPayrollInputBatch, previewPayrollInputBatch, submitPayrollInputBatch, uploadPayrollInputCsv, validatePayrollInputBatch } from '../../api/payrollInputs.ts'

type Tab = 'batches' | 'import' | 'manual' | 'templates'

export function PayrollInputsPage() {
  const { can } = useAuth()
  const [tab, setTab] = useState<Tab>('batches')
  const [refresh, setRefresh] = useState(0)
  const [batchId, setBatchId] = useState('')
  const [file, setFile] = useState<File | null>(null)
  const [filter, setFilter] = useState('All')
  const rows = useApiQuery(signal => listPayrollInputBatches({ page: 1, pageSize: 50, status: filter === 'All' ? undefined : filter }, signal), [refresh, filter])
  const templates = useApiQuery(signal => listPayrollInputTemplates(signal), [refresh])
  const issues = useApiQuery(signal => batchId ? getPayrollInputIssues(batchId, { page: 1, pageSize: 25 }, signal) : Promise.resolve(undefined), [batchId, refresh])
  const preview = useApiQuery(signal => batchId ? previewPayrollInputBatch(batchId, signal) : Promise.resolve(undefined), [batchId, refresh])
  const reload = () => setRefresh(value => value + 1)
  const create = async () => { if (!can(Permissions.payroll.inputCreate)) return; const result = await createPayrollInputBatch({ name: 'Payroll input import', effectiveDate: new Date().toISOString().slice(0, 10), sourceType: 'Csv', lines: [] }); if (result) { setBatchId(result.id); setTab('import') }; reload() }
  const upload = async () => { if (batchId && file && can(Permissions.payroll.inputImport)) { await uploadPayrollInputCsv(batchId, file); if (can(Permissions.payroll.inputValidate)) await validatePayrollInputBatch(batchId); reload() } }
  const transition = async (id: string, action: (value: string) => Promise<unknown>) => { await action(id); reload() }
  return <section className="page-shell"><PageHeader title="Payroll Inputs & Imports" subtitle="Stage, validate, approve and post payroll inputs without changing finalized payroll." />
    <nav aria-label="Payroll input sections" className="tabs"><button type="button" aria-current={tab === 'batches'} onClick={() => setTab('batches')}>Batches</button><button type="button" aria-current={tab === 'import'} onClick={() => setTab('import')}>New Import</button><button type="button" aria-current={tab === 'manual'} onClick={() => setTab('manual')}>Manual Input</button><button type="button" aria-current={tab === 'templates'} onClick={() => setTab('templates')}>Templates</button></nav>
    {tab === 'import' && <Card title="Import wizard"><p>Step 1: choose a template and period. Step 2: upload CSV. Step 3: validate and preview. Submission, approval and posting are separate actions.</p><div className="form-grid"><button type="button" onClick={create} disabled={!can(Permissions.payroll.inputCreate)}>Create draft batch</button><input aria-label="Batch ID" value={batchId} onChange={event => setBatchId(event.target.value)} placeholder="Batch ID" /><input aria-label="CSV file" type="file" accept=".csv,text/csv" onChange={event => setFile(event.target.files?.[0] ?? null)} /><button type="button" onClick={upload} disabled={!batchId || !file || !can(Permissions.payroll.inputImport)}>Upload + validate</button></div>{batchId && <p>Current batch: <code>{batchId}</code></p>}</Card>}
    {tab === 'manual' && <Card title="Manual input"><p>Manual rows use the same batch validation and maker-checker pipeline as CSV imports. Create a draft batch above, then use the row API or the validation grid to add and correct staged rows.</p></Card>}
    {tab === 'templates' && <Card title="Import templates"><p>Active templates and their immutable versions:</p><ul>{templates.data?.items?.map(template => <li key={template.id}>{template.code} — {template.name} v{template.version} ({template.active ? 'Active' : 'Inactive'})</li>)}</ul>{can(Permissions.payroll.inputConfigureTemplate) && <p>Template changes are permission-gated and preserve the version used by historical batches.</p>}</Card>}
    {(tab === 'batches' || tab === 'import') && <><Card title="Preview summary"><div className="form-grid"><span>Total rows: {preview.data?.batch.totalRows ?? '—'}</span><span>Valid: {preview.data?.batch.validRows ?? '—'}</span><span>Errors: {preview.data?.batch.invalidRows ?? '—'}</span><span>Warnings: {preview.data?.batch.warningRows ?? '—'}</span><span>Employees: {preview.data?.employeeCount ?? '—'}</span><span>Earnings: {preview.data?.earnings?.toFixed(2) ?? '—'}</span><span>Deductions: {preview.data?.deductions?.toFixed(2) ?? '—'}</span><span>Net input impact (arithmetic only): {preview.data?.netInputImpact?.toFixed(2) ?? '—'}</span></div>{batchId && <><a href={payrollInputExportUrl(batchId, 'issues')}>Download validation issues</a>{preview.data?.batch.status === 'Posted' && <a href={payrollInputExportUrl(batchId, 'result')}>Download posted result</a>}</>}</Card><Card title="Batches"><div className="form-grid"><label>Status <select value={filter} onChange={event => setFilter(event.target.value)}><option>All</option><option>Draft</option><option>ValidationFailed</option><option>Validated</option><option>Submitted</option><option>Approved</option><option>Posted</option></select></label></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Batch</th><th>Period/date</th><th>Rows</th><th>Valid</th><th>Errors</th><th>Warnings</th><th>Total</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.data?.items.map(row => <tr key={row.id}><td>{row.batchNumber}<br />{row.name}</td><td>{row.payrollPeriodId ?? '—'}<br />{row.effectiveDate}</td><td>{row.totalRows}</td><td>{row.validRows}</td><td>{row.invalidRows}</td><td>{row.warningRows}</td><td>{row.totalAmount.toFixed(2)}</td><td>{row.status}</td><td><button type="button" onClick={() => setBatchId(row.id)}>Inspect</button>{row.status === 'Validated' && can(Permissions.payroll.inputSubmit) && <button type="button" onClick={() => void transition(row.id, submitPayrollInputBatch)}>Submit</button>}{row.status === 'Submitted' && can(Permissions.payroll.inputApprove) && <button type="button" onClick={() => void transition(row.id, approvePayrollInputBatch)}>Approve</button>}{row.status === 'Approved' && can(Permissions.payroll.inputPost) && <button type="button" onClick={() => void transition(row.id, postPayrollInputBatch)}>Post</button>}</td></tr>)}</tbody></table></div><p>Validation issues: {issues.data?.totalCount ?? '—'}</p></Card></>}
  </section>
}
