import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { createPayrollAccountingConfiguration, createPayrollGLAccount, listPayrollAccountingConfigurations, listPayrollGLAccounts, type PayrollAccountingConfiguration, type PayrollGLAccount, type PayrollGLAccountType } from '../../api/payroll.ts'

export function PayrollAccountingConfigurationPage() {
  const [accounts, setAccounts] = useState<PayrollGLAccount[]>([]); const [configurations, setConfigurations] = useState<PayrollAccountingConfiguration[]>([]); const [error, setError] = useState<string | null>(null); const [account, setAccount] = useState({ code: '', name: '', accountType: 'Expense' as PayrollGLAccountType }); const [configuration, setConfiguration] = useState({ code: '', name: '' })
  const load = async () => { try { setError(null); const [a, c] = await Promise.all([listPayrollGLAccounts({ page: 1, pageSize: 100 }), listPayrollAccountingConfigurations({ page: 1, pageSize: 100 })]); setAccounts(a.items); setConfigurations(c.items) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load accounting configuration.') } }
  useEffect(() => { void load() }, [])
  const addAccount = async (event: FormEvent) => { event.preventDefault(); try { await createPayrollGLAccount({ ...account, isActive: true }); setAccount({ code: '', name: '', accountType: 'Expense' }); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Unable to create GL account.') } }
  const addConfiguration = async (event: FormEvent) => { event.preventDefault(); try { await createPayrollAccountingConfiguration({ ...configuration, isActive: true }); setConfiguration({ code: '', name: '' }); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Unable to create configuration.') } }
  return <section className="page-shell"><div className="page-heading"><div><p className="eyebrow">Payroll</p><h1>Accounting Configuration</h1><p>Manage tenant GL accounts and effective-dated payroll accounting configurations.</p></div></div>{error && <p role="alert">{error}</p>}<div className="split-layout"><div className="card"><h2>GL Accounts</h2><form onSubmit={addAccount}><input aria-label="Account code" value={account.code} onChange={e => setAccount({ ...account, code: e.target.value })} placeholder="Code" required /><input aria-label="Account name" value={account.name} onChange={e => setAccount({ ...account, name: e.target.value })} placeholder="Name" required /><select aria-label="Account type" value={account.accountType} onChange={e => setAccount({ ...account, accountType: e.target.value as PayrollGLAccountType })}><option>Expense</option><option>Liability</option><option>Asset</option><option>Clearing</option></select><button type="submit">Add account</button></form><ul>{accounts.map(item => <li key={item.id}>{item.code} — {item.name} ({item.accountType})</li>)}</ul></div><div className="card"><h2>Configurations</h2><form onSubmit={addConfiguration}><input aria-label="Configuration code" value={configuration.code} onChange={e => setConfiguration({ ...configuration, code: e.target.value })} placeholder="Code" required /><input aria-label="Configuration name" value={configuration.name} onChange={e => setConfiguration({ ...configuration, name: e.target.value })} placeholder="Name" required /><button type="submit">Add configuration</button></form><ul>{configurations.map(item => <li key={item.id}>{item.code} — {item.name} · {item.versions.length} version(s)</li>)}</ul></div></div></section>
}
