import { useEffect, useState } from 'react'
import { approvePayrollAccounting, exportPayrollAccounting, getPayrollAccounting, listPayrollAccounting, postPayrollAccounting, type PayrollJournal, validatePayrollAccounting } from '../../api/payroll.ts'

export function PayrollAccountingPage() {
  const [journals, setJournals] = useState<PayrollJournal[]>([])
  const [selected, setSelected] = useState<PayrollJournal | null>(null)
  const [error, setError] = useState<string | null>(null)
  const load = async () => { try { setJournals((await listPayrollAccounting({ page: 1, pageSize: 25 })).items) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load payroll journals.') } }
  useEffect(() => { void load() }, [])
  const action = async (fn: (id: string) => Promise<PayrollJournal>) => { if (!selected) return; try { setSelected(await fn(selected.id)); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Accounting action failed.') } }
  const exportJournal = async () => { if (!selected) return; const blob = await exportPayrollAccounting(selected.id); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `${selected.journalNumber.replaceAll('/', '-')}.csv`; anchor.click(); URL.revokeObjectURL(url) }
  return <section className="page-shell"><div className="page-heading"><div><p className="eyebrow">Payroll</p><h1>Payroll Accounting</h1><p>Review balanced internal payroll journals generated from finalized payroll results.</p></div></div>{error && <p role="alert">{error}</p>}<div className="split-layout"><div className="card"><h2>Journal batches</h2>{journals.length === 0 ? <p>No payroll journals found.</p> : <ul>{journals.map(journal => <li key={journal.id}><button type="button" onClick={() => void getPayrollAccounting(journal.id).then(setSelected)}>{journal.journalNumber} — {journal.status} — {journal.totalDebit.toFixed(2)} {journal.currencyCode}</button></li>)}</ul>}</div>{selected && <div className="card"><h2>{selected.journalNumber}</h2><p>{selected.status} · Debit {selected.totalDebit.toFixed(2)} · Credit {selected.totalCredit.toFixed(2)}</p><div className="button-row">{selected.status === 'Generated' && <button onClick={() => void action(validatePayrollAccounting)}>Validate</button>}{selected.status === 'Validated' && <button onClick={() => void action(approvePayrollAccounting)}>Approve</button>}{selected.status === 'Approved' && <button onClick={() => void action(postPayrollAccounting)}>Post</button>}{['Approved', 'Posted', 'Exported'].includes(selected.status) && <button onClick={() => void exportJournal()}>Export CSV</button>}</div><table><thead><tr><th>Account</th><th>Description</th><th>Debit</th><th>Credit</th></tr></thead><tbody>{selected.lines.map(line => <tr key={line.id}><td>{line.accountCode} — {line.accountName}</td><td>{line.description}</td><td>{line.debit.toFixed(2)}</td><td>{line.credit.toFixed(2)}</td></tr>)}</tbody></table></div>}</div></section>
}
