import { useState } from 'react'
import type { FormEvent } from 'react'
import { Card } from '../../components/Card.tsx'
import { PageHeader } from '../../components/PageHeader.tsx'
import { useApiQuery } from '../../hooks/useApiQuery.ts'
import { approvePayrollAdjustment, createPayrollAdjustment, listPayrollAdjustments, submitPayrollAdjustment } from '../../api/payrollAdjustments.ts'

export function PayrollAdjustmentsPage() {
  const [refresh, setRefresh] = useState(0)
  const [form, setForm] = useState({ employeeId: '', effectiveDate: '', amount: '', description: '', direction: 'Earning', componentCode: 'PAYROLL-ADJUSTMENT' })
  const rows = useApiQuery(signal => listPayrollAdjustments({ page: 1, pageSize: 50 }, signal), [refresh])
  const transition = async (id: string, action: (value: string) => Promise<unknown>) => { await action(id); setRefresh(value => value + 1) }
  const save = async (event: FormEvent) => { event.preventDefault(); await createPayrollAdjustment({ ...form, amount: Number(form.amount), adjustmentType: form.direction === 'Earning' ? 'AdditionalEarning' : 'AdditionalDeduction', sourceType: 'ManualPayrollCorrection', currencyCode: 'INR', taxTreatment: 'Taxable', statutoryTreatment: 'RecalculateConfiguredStatutory', settlementMethod: 'Payroll' }); setForm({ employeeId: '', effectiveDate: '', amount: '', description: '', direction: 'Earning', componentCode: 'PAYROLL-ADJUSTMENT' }); setRefresh(value => value + 1) }
  return <section className="page-shell"><PageHeader title="Payroll Adjustments" subtitle="Create controlled, auditable earnings and deduction corrections without rewriting historical payroll." /><Card title="New adjustment"><form className="form-grid" onSubmit={save}><input aria-label="Employee ID" required value={form.employeeId} onChange={e => setForm({ ...form, employeeId: e.target.value })} placeholder="Employee ID" /><input aria-label="Effective date" required type="date" value={form.effectiveDate} onChange={e => setForm({ ...form, effectiveDate: e.target.value })} /><input aria-label="Amount" required type="number" min="0.01" step="0.01" value={form.amount} onChange={e => setForm({ ...form, amount: e.target.value })} placeholder="Amount" /><input aria-label="Description" required value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} placeholder="Reason / description" /><select aria-label="Direction" value={form.direction} onChange={e => setForm({ ...form, direction: e.target.value })}><option>Earning</option><option>Deduction</option></select><button type="submit">Create draft</button></form></Card><Card title="Adjustment register"><div className="table-wrap"><table className="data-table"><thead><tr><th>Number</th><th>Employee</th><th>Type</th><th>Amount</th><th>Applied</th><th>Outstanding</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.data?.items.map(row => <tr key={row.id}><td>{row.adjustmentNumber}</td><td>{row.employeeCode}</td><td>{row.direction}</td><td>{row.amount.toFixed(2)}</td><td>{row.appliedAmount.toFixed(2)}</td><td>{row.outstandingAmount.toFixed(2)}</td><td>{row.status}</td><td>{row.status === 'Draft' ? <button type="button" onClick={() => transition(row.id, submitPayrollAdjustment)}>Submit</button> : null}{row.status === 'Submitted' ? <button type="button" onClick={() => transition(row.id, approvePayrollAdjustment)}>Approve</button> : null}</td></tr>)}</tbody></table></div></Card></section>
}
