import { useState } from 'react'
import { Card } from '../../components/Card.tsx'
import { PageHeader } from '../../components/PageHeader.tsx'
import { useApiQuery } from '../../hooks/useApiQuery.ts'
import { approveReimbursement, cancelReimbursement, createReimbursementCategory, createReimbursementPolicyVersion, getReimbursement, listReimbursementCategories, listReimbursementRegister, rejectReimbursement, settleReimbursementManually, updateReimbursementCategory, type ReimbursementApprovalRequest, type ReimbursementCategoryRequest, type ReimbursementClaim, type ReimbursementPolicyVersionRequest } from '../../api/reimbursements.ts'

const blank: ReimbursementCategoryRequest = { code: '', name: '', categoryType: 'Other', isActive: true, currencyCode: 'INR', requiresReceipt: true, allowsMultipleLines: true, taxTreatment: 'NonTaxable', defaultSettlementMethod: 'Payroll', requiresApproval: true, settlementPriority: 0 }
const money = (value: number) => value.toFixed(2)

export function ReimbursementsPage() {
  const [filters, setFilters] = useState({ employeeId: '', categoryId: '', status: '', settlementMethod: '', from: '', to: '' }); const [page, setPage] = useState(1)
  const categories = useApiQuery(signal => listReimbursementCategories(signal), [])
  const register = useApiQuery(signal => listReimbursementRegister({ page, pageSize: 50, ...filters }, signal), [page, filters.employeeId, filters.categoryId, filters.status, filters.settlementMethod, filters.from, filters.to])
  const [form, setForm] = useState(blank); const [editingCategoryId, setEditingCategoryId] = useState<string | null>(null); const [selected, setSelected] = useState<ReimbursementClaim | null>(null); const [error, setError] = useState<string | null>(null)
  async function refresh() { register.refetch(); categories.refetch() }
  async function save() { try { setError(null); if (editingCategoryId) await updateReimbursementCategory(editingCategoryId, form); else await createReimbursementCategory(form); setForm(blank); setEditingCategoryId(null); await refresh() } catch (e) { setError(e instanceof Error ? e.message : 'Unable to save reimbursement category.') } }
  async function action(work: () => Promise<unknown>) { try { setError(null); await work(); setSelected(null); await refresh() } catch (e) { setError(e instanceof Error ? e.message : 'Reimbursement action failed.') } }
  async function openClaim(id: string) { try { setSelected(await getReimbursement(id)) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load claim.') } }
  const approval = (claim: ReimbursementClaim): ReimbursementApprovalRequest => ({ lines: claim.lines.map(line => ({ claimLineId: line.id, approvedAmount: line.eligibleAmount, taxableAmount: line.taxableAmount })) })
  const policy: ReimbursementPolicyVersionRequest = { effectiveFrom: new Date().toISOString().slice(0, 10), requiresReceipt: true, taxTreatment: form.taxTreatment, settlementMethod: form.defaultSettlementMethod, status: 'Active' }
  return <section className="page-shell"><PageHeader title="Reimbursements & Claims" subtitle="Configure policy-driven claims, review approvals, and track settlement status." />{error || categories.error || register.error ? <p role="alert">{error ?? categories.error?.message ?? register.error?.message}</p> : null}
    <Card title="Category and policy master"><div className="form-grid"><label>Code<input value={form.code} onChange={e => setForm({ ...form, code: e.target.value })} /></label><label>Name<input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>Type<select value={form.categoryType} onChange={e => setForm({ ...form, categoryType: e.target.value as ReimbursementCategoryRequest['categoryType'] })}><option>Other</option><option>Travel</option><option>Meal</option><option>Medical</option><option>Mobile</option><option>Internet</option></select></label><label>Tax treatment<select value={form.taxTreatment} onChange={e => setForm({ ...form, taxTreatment: e.target.value as ReimbursementCategoryRequest['taxTreatment'] })}><option>NonTaxable</option><option>Taxable</option><option>PartiallyTaxable</option><option>InformationalOnly</option></select></label></div><button type="button" disabled={!form.code || !form.name} onClick={() => void save()}>{editingCategoryId ? 'Update category' : 'Create category'}</button><div className="table-wrap"><table className="data-table"><thead><tr><th>Code</th><th>Name</th><th>Receipt</th><th>Tax</th><th>Settlement</th><th>Versions</th><th>Actions</th></tr></thead><tbody>{categories.data?.map(item => <tr key={item.id}><td>{item.code}</td><td>{item.name}</td><td>{item.requiresReceipt ? 'Required' : 'Optional'}</td><td>{item.taxTreatment}</td><td>{item.defaultSettlementMethod}</td><td><button type="button" onClick={() => void action(() => createReimbursementPolicyVersion(item.id, policy))}>Add policy version</button> {item.versions.length}</td><td><button type="button" onClick={() => { setEditingCategoryId(item.id); setForm({ ...form, code: item.code, name: item.name, categoryType: item.categoryType, isActive: item.isActive, currencyCode: item.currencyCode, requiresReceipt: item.requiresReceipt, allowsMultipleLines: item.allowsMultipleLines, taxTreatment: item.taxTreatment, defaultSettlementMethod: item.defaultSettlementMethod }) }}>Edit</button></td></tr>)}</tbody></table></div></Card>
    <Card title="Claim register"><div className="form-grid"><label>Employee filter<input aria-label="Employee filter" value={filters.employeeId} onChange={e => { setPage(1); setFilters({ ...filters, employeeId: e.target.value }) }} /></label><label>Category filter<select aria-label="Category filter" value={filters.categoryId} onChange={e => { setPage(1); setFilters({ ...filters, categoryId: e.target.value }) }}><option value="">All categories</option>{categories.data?.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Status filter<select aria-label="Status filter" value={filters.status} onChange={e => { setPage(1); setFilters({ ...filters, status: e.target.value }) }}><option value="">All statuses</option><option>Submitted</option><option>Approved</option><option>PartiallyApproved</option><option>Settled</option><option>Cancelled</option></select></label><label>Settlement filter<select aria-label="Settlement method filter" value={filters.settlementMethod} onChange={e => { setPage(1); setFilters({ ...filters, settlementMethod: e.target.value }) }}><option value="">All methods</option><option>Payroll</option><option>Manual</option><option>FinalSettlement</option></select></label><label>From date<input aria-label="From date" type="date" value={filters.from} onChange={e => { setPage(1); setFilters({ ...filters, from: e.target.value }) }} /></label><label>To date<input aria-label="To date" type="date" value={filters.to} onChange={e => { setPage(1); setFilters({ ...filters, to: e.target.value }) }} /></label></div><a href="/api/payroll/reimbursements/register/export.csv">Export CSV</a><div className="table-wrap"><table className="data-table"><thead><tr><th>Claim</th><th>Employee</th><th>Claimed</th><th>Eligible</th><th>Approved</th><th>Taxable</th><th>Non-taxable</th><th>Settled</th><th>Outstanding</th><th>Status</th><th>Method</th></tr></thead><tbody>{register.data?.items.map(item => <tr key={item.id}><td><button type="button" onClick={() => void openClaim(item.id)}>{item.claimNumber}</button></td><td>{item.employeeName || item.employeeCode}</td><td>{money(item.claimedAmount)}</td><td>{money(item.eligibleAmount)}</td><td>{money(item.approvedAmount)}</td><td>{money(item.taxableAmount)}</td><td>{money(item.nonTaxableAmount)}</td><td>{money(item.settledAmount)}</td><td>{money(item.outstandingAmount)}</td><td>{item.status}</td><td>{item.settlementMethod}</td></tr>)}</tbody></table></div><div className="button-row"><button type="button" disabled={page <= 1} onClick={() => setPage(page - 1)}>Previous page</button><span>Page {page} of {Math.max(1, Math.ceil((register.data?.totalCount ?? 0) / 50))}</span><button type="button" disabled={!register.data || page * 50 >= register.data.totalCount} onClick={() => setPage(page + 1)}>Next page</button></div></Card>
    {selected ? <Card title={`Claim ${selected.claimNumber}`}><p>Status: {selected.status} · Settlement: {selected.settlementMethod}</p><p>Claimed {money(selected.totalClaimedAmount)} · Eligible {money(selected.totalEligibleAmount)} · Approved {money(selected.totalApprovedAmount)} · Taxable {money(selected.taxableAmount)} · Non-taxable {money(selected.nonTaxableAmount)} · Settled {money(selected.settledAmount)}</p><h3>Lines</h3><ul>{selected.lines.map(line => <li key={line.id}>{line.categoryCode}: {line.description} — claimed {money(line.claimedAmount)}, approved {money(line.approvedAmount)}, {line.taxableAmount.toFixed(2)} taxable, {line.status}</li>)}</ul><h3>Attachments and settlements</h3><ul>{selected.attachments?.map(item => <li key={item.id}>{item.fileName} ({item.contentType})</li>)}{selected.settlements?.map(item => <li key={item.id}>{item.settlementType}: {money(item.amount)} on {item.settlementDate}</li>)}</ul><h3>History</h3><ul>{selected.history?.map(item => <li key={item.id}>{item.eventType} — {item.occurredAtUtc}</li>)}</ul><div className="button-row">{selected.status === 'Submitted' || selected.status === 'UnderReview' ? <><button type="button" onClick={() => void action(() => approveReimbursement(selected.id, approval(selected)))}>Approve</button><button type="button" onClick={() => void action(() => approveReimbursement(selected.id, { ...approval(selected), lines: approval(selected).lines.map(line => ({ ...line, approvedAmount: line.approvedAmount / 2, comment: 'Partial approval' })) }))}>Partial approve</button><button type="button" onClick={() => void action(() => rejectReimbursement(selected.id, 'Rejected during review'))}>Reject</button></> : null}{selected.status === 'Approved' || selected.status === 'PartiallyApproved' || selected.status === 'ReadyForSettlement' ? <button type="button" onClick={() => void action(() => settleReimbursementManually(selected.id, { amount: selected.totalApprovedAmount - selected.settledAmount, reference: `MANUAL-${selected.claimNumber}` }))}>Manual settlement</button> : null}{selected.status !== 'Settled' && selected.status !== 'Cancelled' ? <button type="button" onClick={() => void action(() => cancelReimbursement(selected.id, 'Cancelled by administrator'))}>Cancel</button> : null}</div></Card> : null}
  </section>
}
