using HRMS.Domain.Enums;

namespace HRMS.Application.DTOs.Payroll;

public sealed record PayrollAnalyticsOverviewDto(Guid PayrollRunId, string RunNumber, PayrollRunStatus Status, int EmployeeCount, decimal GrossTotal, decimal DeductionTotal, decimal NetPayTotal, decimal EmployerContributionTotal, decimal TaxTotal, decimal BankAdviceTotal, decimal AccountingDebitTotal, decimal AccountingCreditTotal, int OpenFindings, int CriticalFindings, int AnomalyCount);
public sealed record PayrollVarianceRowDto(Guid EmployeeId, string EmployeeCode, string EmployeeName, decimal? BaseGross, decimal CurrentGross, decimal GrossDelta, decimal? GrossVariancePercent, decimal? BaseDeduction, decimal CurrentDeduction, decimal DeductionDelta, decimal? DeductionVariancePercent, decimal? BaseNet, decimal CurrentNet, decimal NetDelta, decimal? NetVariancePercent, string Classification, IReadOnlyList<string> Flags);
public sealed record PayrollComponentVarianceDto(string SourceType, string ComponentCode, string ComponentName, decimal BaseAmount, decimal CurrentAmount, decimal Delta, decimal? VariancePercent);
public sealed record PayrollReconciliationDto(Guid Id, Guid PayrollRunId, PayrollReconciliationType Type, int Version, PayrollReconciliationStatus Status, int TotalChecks, int PassedChecks, int WarningChecks, int FailedChecks, int CriticalChecks, DateTime GeneratedAtUtc, IReadOnlyList<PayrollFindingDto> Findings);
public sealed record PayrollFindingDto(Guid Id, string ControlCode, PayrollControlScope Scope, PayrollFindingSeverity Severity, PayrollControlAction Action, PayrollControlMetric Metric, Guid? EmployeeId, decimal? ExpectedValue, decimal? ActualValue, decimal? Difference, decimal? VariancePercent, string Message, PayrollFindingStatus Status, DateTime GeneratedAtUtc, string? ResolutionNote, string? ResolutionReference);
public sealed record PayrollAnalyticsControlDto(Guid Id, string Code, string Name, PayrollControlScope Scope, PayrollControlMetric Metric, decimal? AbsoluteThreshold, decimal? PercentageThreshold, PayrollFindingSeverity Severity, PayrollControlAction Action, PayrollRunType? AppliesToRunType, bool IsActive, DateOnly EffectiveFrom, DateOnly? EffectiveTo, int ConcurrencyVersion);
public sealed class PayrollAnalyticsControlRequest { public string Code { get; set; } = string.Empty; public string Name { get; set; } = string.Empty; public PayrollControlScope Scope { get; set; } public PayrollControlMetric Metric { get; set; } public decimal? AbsoluteThreshold { get; set; } public decimal? PercentageThreshold { get; set; } public PayrollFindingSeverity Severity { get; set; } = PayrollFindingSeverity.Warning; public PayrollControlAction Action { get; set; } = PayrollControlAction.Informational; public PayrollRunType? AppliesToRunType { get; set; } public bool IsActive { get; set; } = true; public DateOnly EffectiveFrom { get; set; } = DateOnly.FromDateTime(DateTime.UtcNow); public DateOnly? EffectiveTo { get; set; } }
public sealed record PayrollFindingActionRequest(string? Note, string? Reference);
public sealed record PayrollControlTotalsDto(int EmployeeCount, int ResultCount, decimal EarningsTotal, decimal DeductionTotal, decimal GrossTotal, decimal NetPayTotal, decimal EmployerContributionTotal, decimal TaxTotal, decimal ReimbursementTotal, decimal LoanRecoveryTotal, decimal VariablePayTotal, decimal AdjustmentTotal);
public sealed record PayrollRunSummaryDto(Guid PayrollRunId, Guid PayrollPeriodId, PayrollRunType RunType, PayrollRunStatus Status, PayrollControlTotalsDto Totals, decimal? BankAdviceTotal, decimal? AccountingDebitTotal, decimal? AccountingCreditTotal);
public sealed record PayrollExceptionDto(Guid Id, Guid PayrollRunId, Guid? EmployeeId, string? EmployeeCode, PayrollAnomalyType AnomalyType, PayrollFindingSeverity Severity, PayrollControlMetric Metric, decimal? CurrentValue, decimal? ComparisonValue, decimal? Difference, decimal? VariancePercent, PayrollFindingStatus Status, string Message, DateTime CreatedAtUtc, DateTime? AcknowledgedAtUtc, Guid? AcknowledgedByUserId, string? ResolutionNote);
public sealed record PayrollDimensionSummaryDto(Guid? DimensionId, string Code, string Name, int EmployeeCount, int PayrollResultCount, decimal EarningsTotal, decimal GrossTotal, decimal DeductionTotal, decimal NetPayTotal, decimal EmployerContributionTotal);
