using HRMS.Application.Common;
using HRMS.Domain.Enums;

namespace HRMS.Application.DTOs.Payroll;

public sealed record TaxDeclarationCycleDto(Guid Id, string Code, string Name, int FinancialYear, DateOnly DeclarationOpenDate, DateOnly DeclarationCloseDate, DateOnly ProofSubmissionOpenDate, DateOnly ProofSubmissionCloseDate, TaxDeclarationCycleStatus Status);
public sealed record TaxDeclarationCategoryDto(Guid Id, string Code, string Name, TaxDeclarationCategoryType CategoryType, bool RequiresProof, bool AllowsMultipleEntries, bool Active, int DisplayOrder);
public sealed record TaxDeclarationItemDto(Guid Id, Guid CategoryId, string Code, string Name, bool RequiresProof, bool AllowsAmount, bool AllowsReferenceNumber, bool AllowsDate, bool Active, string? PayrollTaxInputCode);
public sealed record TaxDeclarationProofDto(Guid Id, string FileName, string ContentType, long FileSize, string DocumentType, TaxDeclarationProofStatus Status, DateTime UploadedAtUtc, string? ReviewerComment);
public sealed record TaxDeclarationLineDto(Guid Id, Guid CategoryId, string CategoryCode, Guid ItemId, string ItemCode, decimal DeclaredAmount, decimal? ApprovedAmount, string? ReferenceNumber, DateOnly? DeclarationDate, string? Notes, EmployeeTaxDeclarationLineStatus Status, string? ReviewerComment, IReadOnlyList<TaxDeclarationProofDto> Proofs);
public sealed record EmployeeTaxDeclarationDto(Guid Id, Guid EmployeeId, Guid CycleId, string CycleCode, int FinancialYear, EmployeeTaxDeclarationStatus Status, int Version, DateTime? SubmittedAtUtc, DateTime? ReviewedAtUtc, IReadOnlyList<TaxDeclarationLineDto> Lines);
public sealed record TaxDeclarationAuditDto(Guid Id, Guid? LineId, TaxDeclarationAuditAction Action, Guid? ActorUserId, DateTime OccurredAtUtc, string? OldValue, string? NewValue, string? Comment);
public sealed record ApprovedTaxDeclarationInput(Guid DeclarationId, Guid LineId, Guid ItemId, string ItemCode, decimal ApprovedAmount, string? ReferenceNumber, int DeclarationVersion, DateTime? ApprovedAtUtc);
public sealed class TaxDeclarationCycleRequest { public string Code { get; set; } = string.Empty; public string Name { get; set; } = string.Empty; public int FinancialYear { get; set; } public DateOnly DeclarationOpenDate { get; set; } public DateOnly DeclarationCloseDate { get; set; } public DateOnly ProofSubmissionOpenDate { get; set; } public DateOnly ProofSubmissionCloseDate { get; set; } public DateOnly EffectiveFrom { get; set; } public DateOnly? EffectiveTo { get; set; } public TaxDeclarationCycleStatus Status { get; set; } = TaxDeclarationCycleStatus.Draft; }
public sealed class TaxDeclarationCategoryRequest { public string Code { get; set; } = string.Empty; public string Name { get; set; } = string.Empty; public string? Description { get; set; } public TaxDeclarationCategoryType CategoryType { get; set; } public bool RequiresProof { get; set; } public bool AllowsMultipleEntries { get; set; } = true; public int DisplayOrder { get; set; } }
public sealed class TaxDeclarationItemRequest { public Guid CategoryId { get; set; } public string Code { get; set; } = string.Empty; public string Name { get; set; } = string.Empty; public string? Description { get; set; } public bool RequiresProof { get; set; } public string? PayrollTaxInputCode { get; set; } }
public sealed class TaxDeclarationLineRequest { public Guid CategoryId { get; set; } public Guid ItemId { get; set; } public decimal DeclaredAmount { get; set; } public string? ReferenceNumber { get; set; } public DateOnly? DeclarationDate { get; set; } public string? Notes { get; set; } }
public sealed class TaxDeclarationLineUpdateRequest { public decimal DeclaredAmount { get; set; } public string? ReferenceNumber { get; set; } public DateOnly? DeclarationDate { get; set; } public string? Notes { get; set; } }
public sealed class TaxDeclarationReviewRequest { public Guid LineId { get; set; } public decimal? ApprovedAmount { get; set; } public EmployeeTaxDeclarationLineStatus Decision { get; set; } public string? Comment { get; set; } }
public sealed class TaxDeclarationProofRequest { public Guid LineId { get; set; } public string FileName { get; set; } = string.Empty; public string ContentType { get; set; } = string.Empty; public long FileSize { get; set; } public string StorageReference { get; set; } = string.Empty; public string? DocumentType { get; set; } public string? Hash { get; set; } }
public sealed class TaxDeclarationProofReviewRequest { public TaxDeclarationProofStatus Decision { get; set; } public string? Comment { get; set; } }
public sealed class TaxDeclarationReviewQuery : PagedQuery { public Guid? CycleId { get; set; } public EmployeeTaxDeclarationStatus? Status { get; set; } public Guid? EmployeeId { get; set; } }
