using HRMS.Domain.Enums;
using HRMS.Application.Common;

namespace HRMS.Application.DTOs.Separation;

public sealed record SeparationDocumentTemplateDto(Guid Id, string Code, string Name, SeparationDocumentType DocumentType, string? Description, bool IsActive, DateOnly EffectiveFrom, DateOnly? EffectiveTo, bool RequiresApproval, int ConcurrencyVersion, IReadOnlyList<SeparationDocumentTemplateVersionDto> Versions);
public sealed record SeparationDocumentTemplateVersionDto(Guid Id, int VersionNumber, SeparationDocumentTemplateVersionStatus Status, DateOnly EffectiveFrom, DateOnly? EffectiveTo, string? Subject, string BodyTemplate, string? HeaderTemplate, string? FooterTemplate, DateTime? PublishedAtUtc);
public sealed record SeparationDocumentPreviewDto(string FileName, string ContentType, string ContentHash, string ContentBase64, bool IsOfficial);
public sealed record SeparationDocumentReadinessDto(bool IsEligible, IReadOnlyList<string> Blockers, Guid SeparationId, Guid EmployeeId, DateOnly? ApprovedLastWorkingDate, FinalSettlementStatus? SettlementStatus, bool ClearanceComplete, bool ReadyForFinalExitClosure);
public sealed record SeparationGeneratedDocumentDto(Guid Id, Guid SeparationId, Guid EmployeeId, string EmployeeName, string? EmployeeCode, SeparationDocumentType DocumentType, string? CustomDocumentCode, string DocumentNumber, SeparationGeneratedDocumentStatus Status, DateOnly IssueDate, DateTime GeneratedAtUtc, DateTime? ApprovedAtUtc, string FileName, string ContentHash, Guid TemplateId, Guid TemplateVersionId, Guid? SupersedesDocumentId, Guid? SupersededByDocumentId, string? LastReason);
public sealed record SeparationDocumentEventDto(Guid Id, SeparationDocumentEventType EventType, DateTime OccurredAtUtc, Guid? ActorUserId, string? Reason);
public sealed record SeparationDocumentDashboardItemDto(Guid Id, Guid SeparationId, Guid EmployeeId, string EmployeeName, string? EmployeeCode, DateOnly? ApprovedLastWorkingDate, SeparationDocumentType DocumentType, string DocumentNumber, SeparationGeneratedDocumentStatus Status, DateTime GeneratedAtUtc, DateTime? ApprovedAtUtc, DateOnly IssueDate, bool IsCurrent, string? SupersededStatus);
public sealed class SeparationDocumentTemplateRequest { public string Code { get; set; } = string.Empty; public string Name { get; set; } = string.Empty; public SeparationDocumentType DocumentType { get; set; } public string? Description { get; set; } public bool IsActive { get; set; } = true; public DateOnly EffectiveFrom { get; set; } = DateOnly.FromDateTime(DateTime.UtcNow); public DateOnly? EffectiveTo { get; set; } public bool RequiresApproval { get; set; } }
public sealed class SeparationDocumentTemplateVersionRequest { public DateOnly EffectiveFrom { get; set; } = DateOnly.FromDateTime(DateTime.UtcNow); public DateOnly? EffectiveTo { get; set; } public string? Subject { get; set; } public string BodyTemplate { get; set; } = string.Empty; public string? HeaderTemplate { get; set; } public string? FooterTemplate { get; set; } public string? PageSettingsJson { get; set; } }
public sealed class SeparationDocumentPreviewRequest { public Guid? SeparationId { get; set; } }
public sealed class SeparationDocumentGenerateRequest { public SeparationDocumentType DocumentType { get; set; } public string? CustomDocumentCode { get; set; } public Guid? TemplateVersionId { get; set; } public DateOnly? IssueDate { get; set; } public int ExpectedConcurrencyVersion { get; set; } public Guid? SupersedesDocumentId { get; set; } }
public sealed class SeparationDocumentApproveRequest { public int ExpectedConcurrencyVersion { get; set; } }
public sealed class SeparationDocumentSupersedeRequest { public Guid? TemplateVersionId { get; set; } public DateOnly? IssueDate { get; set; } public string Reason { get; set; } = string.Empty; public int ExpectedConcurrencyVersion { get; set; } }
public sealed class SeparationDocumentCancelRequest { public string Reason { get; set; } = string.Empty; public int ExpectedConcurrencyVersion { get; set; } }
public sealed class SeparationDocumentDashboardQuery : PagedQuery { public string? EmployeeSearch { get; set; } public SeparationDocumentType? DocumentType { get; set; } public SeparationGeneratedDocumentStatus? Status { get; set; } public DateOnly? LwdFrom { get; set; } public DateOnly? LwdTo { get; set; } public DateOnly? IssueFrom { get; set; } public DateOnly? IssueTo { get; set; } }
