import { api, cleanParams, request } from './client.ts'
import type { ApiResponse, PagedResult } from './types.ts'

export type Shift = { id: string; shiftCode: string; shiftName: string; description?: string | null; shiftType: string; isDefault: boolean; startTime: string; endTime: string; plannedDurationMinutes: number; breakDurationMinutes: number; minimumWorkMinutes: number; fullDayWorkMinutes: number; halfDayWorkMinutes?: number | null; mandatoryStartTime?: string | null; mandatoryEndTime?: string | null; stretchedStartTime?: string | null; stretchedEndTime?: string | null; graceInMinutes: number; graceOutMinutes: number; lateThresholdMinutes: number; earlyOutThresholdMinutes: number; isNightShift: boolean; crossesMidnight: boolean; captureMode: string; allowedAttendanceSources: number; primaryAttendanceSource?: number | null; useDefaultAttendanceMethodology: boolean; allowEarlyMarkIn: boolean; maximumEarlyMarkInMinutes: number; postShiftMarkOutMode: string; maximumPostShiftMinutes: number; isMarkOutMandatory: boolean; allowPresentOnSinglePunch: boolean; requireExpectedWorkMinutes: boolean; showLateInIndicator: boolean; showEarlyOutIndicator: boolean; isActive: boolean; effectiveFrom: string; effectiveTo?: string | null; concurrencyToken: string; breaks: { id: string; name: string; startTime: string; endTime: string; description?: string | null; sequence: number; isPaid: boolean }[] }
export type Pattern = { id: string; code: string; name: string; cycleLengthDays: number; isActive: boolean; effectiveFrom: string; effectiveTo?: string | null; days: { sequenceDay: number; shiftId?: string | null; dayType: string }[] }
export type ShiftRequest = Omit<Shift, 'id' | 'concurrencyToken'> & { concurrencyToken?: string }
export type PatternRequest = Omit<Pattern, 'id' | 'days'> & { days: Pattern['days'] }
export type RosterBatch = { id: string; fileName: string; status: string; totalRows: number; validRows: number; invalidRows: number; committedRows: number; rows: { rowNumber: number; employeeCode: string; rosterDate: string; shiftCode?: string | null; dayType: string; isValid: boolean; action: 'New' | 'Update' | 'Unchanged' | 'Error'; currentShiftCode?: string | null; currentDayType?: string | null; errorMessage?: string | null; underlyingCalendarDayType?: string; isCurrentCalendarOverride?: boolean; willOverrideCalendar?: boolean }[] }
export type ApplicabilityCondition = { dimension: string; valueId: string; valueLabel: string }
export type ApplicabilityRequest = { ruleName?: string; priority: number; effectiveFrom: string; effectiveTo?: string | null; shiftId?: string | null; shiftPatternId?: string | null; conditions: ApplicabilityCondition[] }
export type UploadRow = RosterBatch['rows'][number]
export type ShiftResolution = { employeeId: string; rosterDate: string; dayType: string; shiftId?: string | null; shiftCode?: string | null; shiftName?: string | null; assignmentSource?: string | null; underlyingCalendarDayType?: string | null; isCalendarOverride?: boolean; isExplicitRoster?: boolean }
export type RosterAssignmentRequest = { employeeId: string; fromDate: string; toDate: string; shiftId?: string | null; dayType: string; reason?: string | null }
export type ApplicabilityRule = { id: string; ruleName: string; priority: number; effectiveFrom: string; effectiveTo?: string | null; shiftId?: string | null; shiftPatternId?: string | null; isActive: boolean; conditions: Record<string, string | null> }
export type RosterGridRow = { employeeId: string; employeeCode: string; employeeName: string; rosterDate: string; dayType: string; effectiveShiftId?: string | null; effectiveShiftCode?: string | null; effectiveShiftName?: string | null; assignmentSource: string; hasExplicitRoster: boolean; isCalendarOverride: boolean; underlyingCalendarDayType: string; canRemoveOverride: boolean }
export type AttendanceDay = { date: string; dayOfWeek: string; dayType: string; attendanceStatus: string; shiftId?: string | null; shiftCode?: string | null; shiftName?: string | null; scheduledStartUtc?: string | null; scheduledEndUtc?: string | null; firstPunchAtUtc?: string | null; lastPunchAtUtc?: string | null; workedMinutes?: number | null; expectedWorkMinutes?: number | null; assignmentSource: string; isOverride: boolean; calendarSource: string; isLateIn: boolean; isEarlyOut: boolean; isGraceApplied: boolean; isSinglePunch: boolean; hasMissingInPunch: boolean; hasMissingOutPunch: boolean; hasInvalidPunchSequence: boolean; leaveConflict: boolean; requiresMarkOutApproval: boolean; punchCount: number; sessionCount: number; isProcessed: boolean; processingMessage?: string | null }
export type AttendancePunch = { id: string; employeeId: string; punchAtUtc: string; businessDate: string; direction: string; source: string; externalPunchId?: string | null; deviceId?: string | null; capturedAtUtc: string }
export type AttendanceDayDetail = { day: AttendanceDay; punches: AttendancePunch[]; sessions: { inAtUtc: string; outAtUtc: string; workedMinutes: number }[] }
export type ManagerAttendanceRow = { day: AttendanceDay; employeeId: string; employeeCode: string; employeeName: string; department?: string | null }
export type AttendanceSummary = { present: number; absent: number; onLeave: number; holiday: number; weeklyOff: number; incomplete: number; notProcessed: number; late: number; earlyOut: number; leaveConflict: number }
export type ManagerAttendanceResult = { rows: { items: ManagerAttendanceRow[]; page: number; pageSize: number; totalCount: number; totalPages: number; hasPreviousPage: boolean; hasNextPage: boolean }; summary: AttendanceSummary }
export type AttendanceWorkflowEvent = { eventType: string; actorUserId: string; occurredAtUtc: string; comments?: string | null }
export type RegularizationRequest = { businessDate: string; requestType: string; proposedInAtUtc?: string | null; proposedOutAtUtc?: string | null; reason: string }
export type Regularization = { id: string; employeeId: string; businessDate: string; requestType: string; proposedInAtUtc?: string | null; proposedOutAtUtc?: string | null; reason: string; status: string; submittedAtUtc: string; reviewedAtUtc?: string | null; reviewerComments?: string | null; events: AttendanceWorkflowEvent[] }
export type OnDutyRequest = { startDate: string; endDate: string; reason: string; purpose?: string | null; location?: string | null }
export type OnDuty = { id: string; employeeId: string; startDate: string; endDate: string; reason: string; purpose?: string | null; location?: string | null; status: string; submittedAtUtc: string; reviewedAtUtc?: string | null; reviewerComments?: string | null; events: AttendanceWorkflowEvent[] }
export type AttendanceDailyReportRow = { employeeId: string; employeeCode?: string | null; employeeName: string; businessDate: string; status: string; inTimeUtc?: string | null; outTimeUtc?: string | null; actualWorkMinutes?: number | null; expectedWorkMinutes?: number | null; isLateIn: boolean; isEarlyOut: boolean; shiftCode?: string | null; department?: string | null; workLocation?: string | null }
export type AttendanceMonthlyReportRow = { periodId: string; year: number; month: number; periodStatus: string; employeeCode?: string | null; employeeName: string; workingDays: number; presentDays: number; absentDays: number; onLeaveDays: number; onDutyDays: number; incompleteDays: number; notProcessedDays: number; expectedWorkMinutes: number; actualWorkMinutes: number; exceptionCount: number; sourceDataVersion: number }
export type AttendanceExceptionReportRow = { key: string; periodId: string; employeeId: string; businessDate: string; exceptionType: string; isBlocking: boolean; sourceId?: string | null; message: string }
export type AttendanceReportPage<T> = PagedResult<T>
export type AttendanceDailyReportFilters = { fromDate?: string; toDate?: string; employeeId?: string; departmentId?: string; workLocationId?: string; status?: string; page?: number; pageSize?: number }
export type AttendanceMonthlyReportFilters = { periodId?: string; year?: number; month?: number; employeeId?: string; page?: number; pageSize?: number }
export type AttendanceExceptionReportFilters = { periodId?: string; employeeId?: string; exceptionType?: string; isBlocking?: boolean; fromDate?: string; toDate?: string; page?: number; pageSize?: number }
export type AttendanceOperationalException = { id: string; employeeId: string; employeeCode?: string | null; employeeName: string; businessDate: string; shiftCode?: string | null; exceptionType: string; attendanceStatus: string; scheduledStartUtc?: string | null; scheduledEndUtc?: string | null; firstPunchAtUtc?: string | null; lastPunchAtUtc?: string | null; workedMinutes?: number | null; expectedWorkMinutes?: number | null; lateMinutes: number; earlyDepartureMinutes: number; isBlocking: boolean; isResolved: boolean; ageDays: number; attendanceVersion: number; relatedRequestId?: string | null; message: string }
export type AttendanceOperationsDashboard = { fromDate: string; toDate: string; employees: number; processedDays: number; presentDays: number; absentDays: number; leaveDays: number; onDutyDays: number; weeklyOffDays: number; holidayDays: number; exceptionDays: number; lateDays: number; earlyDepartureDays: number; pendingRegularizations: number; pendingOnDuty: number; openPeriods: number; finalizedPeriods: number; activeAbsentExceptions: number; missedPunchExceptions: number; pendingCorrections: number; missingInPunchExceptions: number; missingOutPunchExceptions: number }
export type AttendanceExceptionResolution = { attendanceDayId: string; exceptionType: 'LateArrival' | 'EarlyDeparture'; action: 'Acknowledge' | 'Waive'; reason: string; expectedAttendanceVersion: number }
export type AttendanceBulkCorrectionItem = { employeeId: string; businessDate: string; correctionType: string; proposedInAtUtc?: string | null; proposedOutAtUtc?: string | null; reason: string; expectedAttendanceVersion: number }
export type AttendanceBulkCorrectionResult = { employeeId: string; businessDate: string; success: boolean; failureCode?: string | null; message: string; requestId?: string | null; currentVersion?: number | null }
export type AttendanceOperationsHistoryItem = { id: string; employeeId: string; attendanceDayId?: string | null; businessDate?: string | null; action: string; actorUserId: string; occurredAtUtc: string; reason?: string | null; oldValue?: string | null; newValue?: string | null; referenceId?: string | null; attendanceVersion?: number | null; oldAttendanceVersion?: number | null; newAttendanceVersion?: number | null }
export type AttendancePeriod = { id: string; year: number; month: number; startDate: string; endDate: string; status: string; dataVersion: number; concurrencyVersion: number; processedAtUtc?: string | null; lastProcessedByUserId?: string | null }
export type AttendancePeriodOverview = { periodId: string; employeesProcessed: number; employeesWithExceptions: number; totalExceptions: number; blockingExceptions: number; processedAtUtc?: string | null; status: string; dataVersion: number }
export type AttendanceClosePreview = { periodId: string; status: string; canClose: boolean; dataVersion: number; summariesCurrent: boolean; employeesProcessed: number; blockingExceptionCount: number; pendingRegularizationCount: number; pendingOnDutyCount: number; notProcessedCount: number; incompleteCount: number; blockers: string[] }
export type AttendancePeriodEvent = { id: string; periodId: string; eventType: string; actorUserId?: string | null; occurredAtUtc: string; dataVersion: number; details?: string | null }
export type EmployeeMonthlyAttendanceSummary = { id: string; attendancePeriodId: string; employeeId: string; employeeCode?: string | null; employeeName: string; calendarDays: number; employmentDays: number; workingDays: number; presentDays: number; absentDays: number; onLeaveDays: number; onDutyDays: number; holidayDays: number; weeklyOffDays: number; incompleteDays: number; notProcessedDays: number; regularizedDays: number; approvedOnDutyDays: number; exceptionCount: number; processedAtUtc: string; presentDayQuantity: number; paidLeaveDays: number; unpaidLeaveDays: number; payableDays: number; lopDays: number; version: number }
export function listAttendancePeriods(params: { page?: number; pageSize?: number; year?: number; month?: number; status?: string } = {}): Promise<PagedResult<AttendancePeriod>> { return request(() => api.get<ApiResponse<PagedResult<AttendancePeriod>>>('/api/attendance/periods', { params: cleanParams(params) })) }
export function createAttendancePeriod(year: number, month: number): Promise<AttendancePeriod> { return request(() => api.post<ApiResponse<AttendancePeriod>>('/api/attendance/periods', { year, month })) }
export function processAttendancePeriod(id: string): Promise<AttendancePeriodOverview> { return request(() => api.post<ApiResponse<AttendancePeriodOverview>>(`/api/attendance/periods/${id}/process`)) }
export function getAttendanceClosePreview(id: string): Promise<AttendanceClosePreview> { return request(() => api.get<ApiResponse<AttendanceClosePreview>>(`/api/attendance/periods/${id}/close-preview`)) }
export function closeAttendancePeriod(id: string, comment?: string): Promise<AttendancePeriod> { return request(() => api.post<ApiResponse<AttendancePeriod>>(`/api/attendance/periods/${id}/close`, { comment: comment || null })) }
export function reopenAttendancePeriod(id: string, reason: string): Promise<AttendancePeriod> { return request(() => api.post<ApiResponse<AttendancePeriod>>(`/api/attendance/periods/${id}/reopen`, { reason })) }
export function listMyAttendanceExceptions(params: { fromDate?: string; toDate?: string; exceptionType?: string; page?: number; pageSize?: number } = {}): Promise<PagedResult<AttendanceOperationalException>> { return request(() => api.get<ApiResponse<PagedResult<AttendanceOperationalException>>>('/api/attendance/me/exceptions', { params: cleanParams(params) })) }
export function listAttendanceOperationalExceptions(params: { fromDate?: string; toDate?: string; employeeId?: string; exceptionType?: string; attendanceStatus?: string; search?: string; page?: number; pageSize?: number } = {}): Promise<PagedResult<AttendanceOperationalException>> { return request(() => api.get<ApiResponse<PagedResult<AttendanceOperationalException>>>('/api/attendance/operations/exceptions', { params: cleanParams(params) })) }
export function getAttendanceOperationsDashboard(fromDate: string, toDate: string): Promise<AttendanceOperationsDashboard> { return request(() => api.get<ApiResponse<AttendanceOperationsDashboard>>('/api/attendance/operations/dashboard', { params: { fromDate, toDate } })) }
export function resolveAttendanceException(value: AttendanceExceptionResolution): Promise<unknown> { return request(() => api.post<ApiResponse<unknown>>('/api/attendance/operations/exceptions/resolve', value)) }
export function submitManualAttendance(value: { employeeId: string; businessDate: string; correctionType: string; proposedInAtUtc?: string | null; proposedOutAtUtc?: string | null; reason: string; comments?: string | null; expectedAttendanceVersion: number }): Promise<Regularization> { return request(() => api.post<ApiResponse<Regularization>>('/api/attendance/operations/manual', value)) }
export function applyAttendanceBulkAction(items: { requestId: string; isOnDuty: boolean; approve: boolean; expectedVersion: number; comments?: string | null }[]): Promise<{ items: { requestId: string; isOnDuty: boolean; success: boolean; failureCode?: string | null; message: string; currentVersion?: number | null }[]; succeeded: number; failed: number }> { return request(() => api.post<ApiResponse<{ items: { requestId: string; isOnDuty: boolean; success: boolean; failureCode?: string | null; message: string; currentVersion?: number | null }[]; succeeded: number; failed: number }>>('/api/attendance/operations/bulk', items)) }
export function submitBulkAttendanceCorrections(items: AttendanceBulkCorrectionItem[]): Promise<{ items: AttendanceBulkCorrectionResult[]; succeeded: number; failed: number }> { return request(() => api.post<ApiResponse<{ items: AttendanceBulkCorrectionResult[]; succeeded: number; failed: number }>>('/api/attendance/operations/bulk-corrections', items)) }
export function getAttendanceOperationsHistory(employeeId: string, params: { fromDate?: string; toDate?: string; page?: number; pageSize?: number } = {}): Promise<PagedResult<AttendanceOperationsHistoryItem>> { return request(() => api.get<ApiResponse<PagedResult<AttendanceOperationsHistoryItem>>>(`/api/attendance/operations/employees/${employeeId}/history`, { params: cleanParams(params) })) }
export function downloadAttendanceOperationsExceptions(params: { fromDate?: string; toDate?: string; employeeId?: string; exceptionType?: string; search?: string } = {}): Promise<Blob> { return api.get<Blob>('/api/attendance/operations/exceptions/export', { params: cleanParams(params), responseType: 'blob' }).then(response => response.data) }
export function listAttendanceSummaries(id: string, params: { page?: number; pageSize?: number; employeeId?: string; hasExceptions?: boolean; hasLop?: boolean } = {}): Promise<PagedResult<EmployeeMonthlyAttendanceSummary>> { return request(() => api.get<ApiResponse<PagedResult<EmployeeMonthlyAttendanceSummary>>>(`/api/attendance/periods/${id}/summaries`, { params: cleanParams(params) })) }
export function listAttendancePeriodEvents(id: string): Promise<AttendancePeriodEvent[]> { return request(() => api.get<ApiResponse<AttendancePeriodEvent[]>>(`/api/attendance/periods/${id}/events`)) }
export function getMyMonthlyAttendanceSummary(params: { page?: number; pageSize?: number; hasLop?: boolean } = {}): Promise<PagedResult<EmployeeMonthlyAttendanceSummary>> { return request(() => api.get<ApiResponse<PagedResult<EmployeeMonthlyAttendanceSummary>>>('/api/attendance/my/monthly-summary', { params: cleanParams(params) })) }
function applicabilityFields(value: ApplicabilityRequest): Record<string, string | number | null> {
  const fields: Record<string, string | number | null> = { ruleName: value.ruleName?.trim() ?? null, shiftId: value.shiftId ?? null, shiftPatternId: value.shiftPatternId ?? null, priority: value.priority, effectiveFrom: value.effectiveFrom, effectiveTo: value.effectiveTo ?? null }
  const key: Record<string, string> = { Employee: 'employeeId', Department: 'departmentId', WorkLocation: 'workLocationId', EmployeeType: 'employeeTypeId', Grade: 'gradeId', Designation: 'designationId', CostCenter: 'costCenterId', HoldingCompany: 'holdingCompanyId', LOB: 'lobId', Organization: 'organisationId', SubDepartment: 'subDepartmentId', Section: 'sectionId', SubSection: 'subSectionId', Function: 'functionId', SubFunction: 'subFunctionId', Country: 'countryLocationId' }
  for (const condition of value.conditions) { const field = key[condition.dimension]; if (field) fields[field] = condition.valueId }
  return fields
}
export function listShifts(): Promise<Shift[]> { return request(() => api.get<ApiResponse<Shift[]>>('/api/attendance/shifts')) }
export function createShift(value: ShiftRequest): Promise<Shift> { return request(() => api.post<ApiResponse<Shift>>('/api/attendance/shifts', value)) }
export function updateShift(id: string, value: ShiftRequest): Promise<Shift> { return request(() => api.put<ApiResponse<Shift>>(`/api/attendance/shifts/${id}`, value)) }
export function listPatterns(): Promise<Pattern[]> { return request(() => api.get<ApiResponse<Pattern[]>>('/api/attendance/patterns')) }
export function createPattern(value: PatternRequest): Promise<Pattern> { return request(() => api.post<ApiResponse<Pattern>>('/api/attendance/patterns', value)) }
export function addApplicability(value: ApplicabilityRequest): Promise<ApplicabilityRequest> {
  return request(() => api.post<ApiResponse<ApplicabilityRequest>>('/api/attendance/applicability', applicabilityFields(value)))
}
export function listApplicability(): Promise<{ items: ApplicabilityRule[]; page: number; pageSize: number; totalCount: number }> { return request(() => api.get<ApiResponse<{ items: ApplicabilityRule[]; page: number; pageSize: number; totalCount: number }>>('/api/attendance/shift-applicability')) }
export function getApplicability(id: string): Promise<ApplicabilityRule> { return request(() => api.get<ApiResponse<ApplicabilityRule>>(`/api/attendance/shift-applicability/${id}`)) }
export function updateApplicability(id: string, value: ApplicabilityRequest): Promise<ApplicabilityRule> { return request(() => api.put<ApiResponse<ApplicabilityRule>>(`/api/attendance/shift-applicability/${id}`, applicabilityFields(value))) }
export function deleteApplicability(id: string): Promise<boolean> { return request(() => api.delete<ApiResponse<boolean>>(`/api/attendance/shift-applicability/${id}`)) }
export function downloadRosterTemplate(): Promise<Blob> { return api.get<Blob>('/api/attendance/roster/template', { responseType: 'blob' }).then(response => response.data) }
export function validateRoster(file: File): Promise<RosterBatch> { const form = new FormData(); form.append('file', file); return request(() => api.post<ApiResponse<RosterBatch>>('/api/attendance/roster/upload/validate', form, { headers: { 'Content-Type': 'multipart/form-data' } })) }
export function commitRoster(id: string): Promise<RosterBatch> { return request(() => api.post<ApiResponse<RosterBatch>>(`/api/attendance/roster/upload/${id}/commit`)) }
export function resolveRoster(employeeId: string, date: string): Promise<ShiftResolution> { return request(() => api.get<ApiResponse<ShiftResolution>>(`/api/attendance/employees/${employeeId}/roster/${date}`)) }
export function assignRoster(value: RosterAssignmentRequest): Promise<ShiftResolution[]> { return request(() => api.post<ApiResponse<ShiftResolution[]>>('/api/attendance/roster/assign', value)) }
export function removeRoster(employeeId: string, date: string): Promise<boolean> { return request(() => api.delete<ApiResponse<boolean>>(`/api/attendance/roster/${employeeId}/${date}`)) }
export function listRoster(params: { page?: number; pageSize?: number; fromDate?: string; toDate?: string; employeeId?: string; search?: string; shiftId?: string; dayType?: string; assignmentSource?: string } = {}): Promise<{ items: RosterGridRow[]; page: number; pageSize: number; totalCount: number }> { return request(() => api.get<ApiResponse<{ items: RosterGridRow[]; page: number; pageSize: number; totalCount: number }>>('/api/attendance/roster', { params })) }
export function getMyAttendanceCalendar(year: number, month: number): Promise<AttendanceDay[]> { return request(() => api.get<ApiResponse<AttendanceDay[]>>('/api/attendance/me/calendar', { params: { year, month } })) }
export function getMyAttendanceDay(date: string): Promise<AttendanceDayDetail> { return request(() => api.get<ApiResponse<AttendanceDayDetail>>(`/api/attendance/me/days/${date}`)) }
export function getManagerAttendance(params: { fromDate: string; toDate: string; page?: number; pageSize?: number; employeeId?: string; status?: string; dayType?: string; shiftId?: string; variance?: string }): Promise<ManagerAttendanceResult> { return request(() => api.get<ApiResponse<ManagerAttendanceResult>>('/api/attendance/manager/team', { params })) }
export function getManagerAttendanceDay(employeeId: string, date: string): Promise<AttendanceDayDetail> { return request(() => api.get<ApiResponse<AttendanceDayDetail>>(`/api/attendance/manager/team/${employeeId}/${date}`)) }
export function submitRegularization(value: RegularizationRequest): Promise<Regularization> { return request(() => api.post<ApiResponse<Regularization>>('/api/attendance/me/regularizations', value)) }
export function listMyRegularizations(params: { page?: number; pageSize?: number } = {}): Promise<{ items: Regularization[]; page: number; pageSize: number; totalCount: number }> { return request(() => api.get<ApiResponse<{ items: Regularization[]; page: number; pageSize: number; totalCount: number }>>('/api/attendance/me/regularizations', { params })) }
export function getMyRegularization(id: string): Promise<Regularization> { return request(() => api.get<ApiResponse<Regularization>>(`/api/attendance/me/regularizations/${id}`)) }
export function cancelRegularization(id: string): Promise<Regularization> { return request(() => api.post<ApiResponse<Regularization>>(`/api/attendance/me/regularizations/${id}/cancel`)) }
export function submitOnDuty(value: OnDutyRequest): Promise<OnDuty> { return request(() => api.post<ApiResponse<OnDuty>>('/api/attendance/me/on-duty', value)) }
export function listMyOnDuty(params: { page?: number; pageSize?: number } = {}): Promise<{ items: OnDuty[]; page: number; pageSize: number; totalCount: number }> { return request(() => api.get<ApiResponse<{ items: OnDuty[]; page: number; pageSize: number; totalCount: number }>>('/api/attendance/me/on-duty', { params })) }
export function getMyOnDuty(id: string): Promise<OnDuty> { return request(() => api.get<ApiResponse<OnDuty>>(`/api/attendance/me/on-duty/${id}`)) }
export function cancelOnDuty(id: string): Promise<OnDuty> { return request(() => api.post<ApiResponse<OnDuty>>(`/api/attendance/me/on-duty/${id}/cancel`)) }
export function listManagerRegularizations(params: { page?: number; pageSize?: number; fromDate?: string; toDate?: string } = {}): Promise<{ items: Regularization[]; page: number; pageSize: number; totalCount: number }> { return request(() => api.get<ApiResponse<{ items: Regularization[]; page: number; pageSize: number; totalCount: number }>>('/api/attendance/manager/regularizations', { params })) }
export function approveRegularization(id: string): Promise<Regularization> { return request(() => api.post<ApiResponse<Regularization>>(`/api/attendance/manager/regularizations/${id}/approve`)) }
export function rejectRegularization(id: string, comments: string): Promise<Regularization> { return request(() => api.post<ApiResponse<Regularization>>(`/api/attendance/manager/regularizations/${id}/reject`, { comments })) }
export function listManagerOnDuty(params: { page?: number; pageSize?: number } = {}): Promise<{ items: OnDuty[]; page: number; pageSize: number; totalCount: number }> { return request(() => api.get<ApiResponse<{ items: OnDuty[]; page: number; pageSize: number; totalCount: number }>>('/api/attendance/manager/on-duty', { params })) }
export function approveOnDuty(id: string): Promise<OnDuty> { return request(() => api.post<ApiResponse<OnDuty>>(`/api/attendance/manager/on-duty/${id}/approve`)) }
export function rejectOnDuty(id: string, comments: string): Promise<OnDuty> { return request(() => api.post<ApiResponse<OnDuty>>(`/api/attendance/manager/on-duty/${id}/reject`, { comments })) }
export function getDailyAttendanceReport(params: AttendanceDailyReportFilters): Promise<AttendanceReportPage<AttendanceDailyReportRow>> { return request(() => api.get<ApiResponse<AttendanceReportPage<AttendanceDailyReportRow>>>('/api/attendance/reports/daily', { params: cleanParams(params) })) }
export function getMonthlyAttendanceReport(params: AttendanceMonthlyReportFilters): Promise<AttendanceReportPage<AttendanceMonthlyReportRow>> { return request(() => api.get<ApiResponse<AttendanceReportPage<AttendanceMonthlyReportRow>>>('/api/attendance/reports/monthly', { params: cleanParams(params) })) }
export function getAttendanceExceptionReport(params: AttendanceExceptionReportFilters): Promise<AttendanceReportPage<AttendanceExceptionReportRow>> { return request(() => api.get<ApiResponse<AttendanceReportPage<AttendanceExceptionReportRow>>>('/api/attendance/reports/exceptions', { params: cleanParams(params) })) }
export async function exportAttendanceReport(kind: 'daily' | 'monthly' | 'exceptions', params: AttendanceDailyReportFilters | AttendanceMonthlyReportFilters | AttendanceExceptionReportFilters): Promise<{ blob: Blob; filename?: string }> {
  const response = await api.get<Blob>(`/api/attendance/reports/${kind}/export`, { params: cleanParams(params) as Record<string, string | number | boolean>, responseType: 'blob' })
  const header = response.headers['content-disposition'] as string | undefined
  const match = header?.match(/filename="?([^";]+)"?/i)
  return { blob: response.data, filename: match?.[1] }
}
