import { api, request } from './client.ts'
import type { ApiResponse } from './types.ts'

export type Shift = { id: string; shiftCode: string; shiftName: string; description?: string | null; shiftType: string; isDefault: boolean; startTime: string; endTime: string; plannedDurationMinutes: number; breakDurationMinutes: number; minimumWorkMinutes: number; fullDayWorkMinutes: number; halfDayWorkMinutes?: number | null; mandatoryStartTime?: string | null; mandatoryEndTime?: string | null; stretchedStartTime?: string | null; stretchedEndTime?: string | null; graceInMinutes: number; graceOutMinutes: number; lateThresholdMinutes: number; earlyOutThresholdMinutes: number; isNightShift: boolean; crossesMidnight: boolean; captureMode: string; allowedAttendanceSources: number; primaryAttendanceSource?: number | null; useDefaultAttendanceMethodology: boolean; allowEarlyMarkIn: boolean; maximumEarlyMarkInMinutes: number; postShiftMarkOutMode: string; maximumPostShiftMinutes: number; isMarkOutMandatory: boolean; allowPresentOnSinglePunch: boolean; requireExpectedWorkMinutes: boolean; showLateInIndicator: boolean; showEarlyOutIndicator: boolean; isActive: boolean; effectiveFrom: string; effectiveTo?: string | null; concurrencyToken: string; breaks: { id: string; name: string; startTime: string; endTime: string; description?: string | null; sequence: number; isPaid: boolean }[] }
export type Pattern = { id: string; code: string; name: string; cycleLengthDays: number; isActive: boolean; effectiveFrom: string; effectiveTo?: string | null; days: { sequenceDay: number; shiftId?: string | null; dayType: string }[] }
export type ShiftRequest = Omit<Shift, 'id' | 'concurrencyToken'> & { concurrencyToken?: string }
export type PatternRequest = Omit<Pattern, 'id' | 'days'> & { days: Pattern['days'] }
export type RosterBatch = { id: string; fileName: string; status: string; totalRows: number; validRows: number; invalidRows: number; committedRows: number; rows: { rowNumber: number; employeeCode: string; rosterDate: string; shiftCode?: string | null; dayType: string; isValid: boolean; action: 'New' | 'Update' | 'Unchanged' | 'Error'; currentShiftCode?: string | null; currentDayType?: string | null; errorMessage?: string | null; underlyingCalendarDayType?: string; isCurrentCalendarOverride?: boolean; willOverrideCalendar?: boolean }[] }
export type ApplicabilityCondition = { dimension: string; valueId: string; valueLabel: string }
export type ApplicabilityRequest = { ruleName?: string; priority: number; effectiveFrom: string; effectiveTo?: string | null; shiftId?: string | null; shiftPatternId?: string | null; conditions: ApplicabilityCondition[] }
export type UploadRow = RosterBatch['rows'][number]
export type ShiftResolution = { employeeId: string; rosterDate: string; dayType: string; shiftId?: string | null; shiftCode?: string | null; shiftName?: string | null; assignmentSource?: string | null; underlyingCalendarDayType?: string | null; isCalendarOverride?: boolean; isExplicitRoster?: boolean }
export type RosterAssignmentRequest = { employeeId: string; fromDate: string; toDate: string; shiftId?: string | null; dayType: string; reason?: string | null }
export type ApplicabilityRule = { id: string; ruleName: string; priority: number; effectiveFrom: string; effectiveTo?: string | null; shiftId?: string | null; shiftPatternId?: string | null; isActive: boolean; conditions: Record<string, string | null> }
export type RosterGridRow = { employeeId: string; employeeCode: string; employeeName: string; rosterDate: string; dayType: string; effectiveShiftId?: string | null; effectiveShiftCode?: string | null; effectiveShiftName?: string | null; assignmentSource: string; hasExplicitRoster: boolean; isCalendarOverride: boolean; underlyingCalendarDayType: string; canRemoveOverride: boolean }
function applicabilityFields(value: ApplicabilityRequest): Record<string, string | number | null> {
  const fields: Record<string, string | number | null> = { ruleName: value.ruleName?.trim() ?? null, shiftId: value.shiftId ?? null, shiftPatternId: value.shiftPatternId ?? null, priority: value.priority, effectiveFrom: value.effectiveFrom, effectiveTo: value.effectiveTo ?? null }
  const key: Record<string, string> = { Employee: 'employeeId', Department: 'departmentId', WorkLocation: 'workLocationId', EmployeeType: 'employeeTypeId', Grade: 'gradeId', Designation: 'designationId', CostCenter: 'costCenterId', HoldingCompany: 'holdingCompanyId', LOB: 'lobId', Organization: 'organisationId', SubDepartment: 'subDepartmentId', Section: 'sectionId', SubSection: 'subSectionId', Function: 'functionId', SubFunction: 'subFunctionId', Country: 'countryLocationId' }
  for (const condition of value.conditions) { const field = key[condition.dimension]; if (field) fields[field] = condition.valueId }
  return fields
}
export function listShifts(): Promise<Shift[]> { return request(() => api.get<ApiResponse<Shift[]>>('/api/attendance/shifts')) }
export function createShift(value: ShiftRequest): Promise<Shift> { return request(() => api.post<ApiResponse<Shift>>('/api/attendance/shifts', value)) }
export function updateShift(id: string, value: ShiftRequest): Promise<Shift> { return request(() => api.put<ApiResponse<Shift>>(`/api/attendance/shifts/${id}`, value)) }
export function listPatterns(): Promise<Pattern[]> { return request(() => api.get<ApiResponse<Pattern[]>>('/api/attendance/patterns')) }
export function createPattern(value: PatternRequest): Promise<Pattern> { return request(() => api.post<ApiResponse<Pattern>>('/api/attendance/patterns', value)) }
export function addApplicability(value: ApplicabilityRequest): Promise<ApplicabilityRequest> {
  return request(() => api.post<ApiResponse<ApplicabilityRequest>>('/api/attendance/applicability', applicabilityFields(value)))
}
export function listApplicability(): Promise<{ items: ApplicabilityRule[]; page: number; pageSize: number; totalCount: number }> { return request(() => api.get<ApiResponse<{ items: ApplicabilityRule[]; page: number; pageSize: number; totalCount: number }>>('/api/attendance/shift-applicability')) }
export function getApplicability(id: string): Promise<ApplicabilityRule> { return request(() => api.get<ApiResponse<ApplicabilityRule>>(`/api/attendance/shift-applicability/${id}`)) }
export function updateApplicability(id: string, value: ApplicabilityRequest): Promise<ApplicabilityRule> { return request(() => api.put<ApiResponse<ApplicabilityRule>>(`/api/attendance/shift-applicability/${id}`, applicabilityFields(value))) }
export function deleteApplicability(id: string): Promise<boolean> { return request(() => api.delete<ApiResponse<boolean>>(`/api/attendance/shift-applicability/${id}`)) }
export function downloadRosterTemplate(): Promise<Blob> { return api.get<Blob>('/api/attendance/roster/template', { responseType: 'blob' }).then(response => response.data) }
export function validateRoster(file: File): Promise<RosterBatch> { const form = new FormData(); form.append('file', file); return request(() => api.post<ApiResponse<RosterBatch>>('/api/attendance/roster/upload/validate', form, { headers: { 'Content-Type': 'multipart/form-data' } })) }
export function commitRoster(id: string): Promise<RosterBatch> { return request(() => api.post<ApiResponse<RosterBatch>>(`/api/attendance/roster/upload/${id}/commit`)) }
export function resolveRoster(employeeId: string, date: string): Promise<ShiftResolution> { return request(() => api.get<ApiResponse<ShiftResolution>>(`/api/attendance/employees/${employeeId}/roster/${date}`)) }
export function assignRoster(value: RosterAssignmentRequest): Promise<ShiftResolution[]> { return request(() => api.post<ApiResponse<ShiftResolution[]>>('/api/attendance/roster/assign', value)) }
export function removeRoster(employeeId: string, date: string): Promise<boolean> { return request(() => api.delete<ApiResponse<boolean>>(`/api/attendance/roster/${employeeId}/${date}`)) }
export function listRoster(params: { page?: number; pageSize?: number; fromDate?: string; toDate?: string; employeeId?: string; search?: string; shiftId?: string; dayType?: string; assignmentSource?: string } = {}): Promise<{ items: RosterGridRow[]; page: number; pageSize: number; totalCount: number }> { return request(() => api.get<ApiResponse<{ items: RosterGridRow[]; page: number; pageSize: number; totalCount: number }>>('/api/attendance/roster', { params })) }
