import { AxiosError } from 'axios'
import type { ApiResponse, ValidationError } from './types.ts'

/**
 * A failed request, normalized.
 *
 * Callers should never have to unpack an `AxiosError` — or guess whether a message lives in
 * `response.data.message`, in `error.message`, or nowhere at all. Everything that can fail a request
 * (a 4xx envelope, a 500 with an HTML body, a dropped connection, a request the user navigated away
 * from) arrives here as one shape.
 */
export class ApiError extends Error {
  /** HTTP status, or `undefined` when the request never reached the server. */
  readonly status?: number

  /** Field-level failures keyed by the API's camelCase field name, ready to render beside an input. */
  readonly fieldErrors: Readonly<Record<string, string>>

  /** True when the request was aborted by us (navigation, unmount, a superseded search). */
  readonly isCanceled: boolean

  /** True when the request never got a response — offline, DNS, refused connection, CORS block. */
  readonly isNetworkError: boolean

  constructor(
    message: string,
    options: {
      status?: number
      fieldErrors?: Record<string, string>
      isCanceled?: boolean
      isNetworkError?: boolean
      cause?: unknown
    } = {},
  ) {
    super(message, { cause: options.cause })
    this.name = 'ApiError'
    this.status = options.status
    this.fieldErrors = options.fieldErrors ?? {}
    this.isCanceled = options.isCanceled ?? false
    this.isNetworkError = options.isNetworkError ?? false
  }

  /** 401 — no session, or one the server no longer accepts. */
  get isUnauthorized(): boolean {
    return this.status === 401
  }

  /** 403 — signed in, but the permission the endpoint requires is not granted. */
  get isForbidden(): boolean {
    return this.status === 403
  }

  /** 409 — the write conflicts with existing data (duplicate code, or a row still in use). */
  get isConflict(): boolean {
    return this.status === 409
  }
}

/**
 * True when the failure carries at least one field-level message.
 *
 * Forms use this to decide whether to show the summary banner: when every message is already rendered
 * under the input it belongs to, the banner would only repeat them a second time further from the field
 * the user has to fix.
 */
export function hasFieldErrors(error: ApiError): boolean {
  return Object.keys(error.fieldErrors).length > 0
}

/** Reads the field errors out of the standard envelope, ignoring anything malformed. */
function toFieldErrors(errors: ValidationError[] | undefined): Record<string, string> {
  const map: Record<string, string> = {}
  for (const error of errors ?? []) {
    // First message per field wins: the form shows one line under an input, and the first failure
    // is the one closest to what the user typed.
    if (error?.field && !(error.field in map)) {
      map[error.field] = error.message
    }
  }
  return map
}

/**
 * Turns anything thrown by axios (or by us) into an {@link ApiError}.
 *
 * The status-specific fallbacks matter because not every failure carries our envelope: a 429 from the
 * rate limiter is generated by middleware, and a 500 may be an HTML error page. A blank "Request
 * failed with status code 429" is not something to show a person.
 */
export function toApiError(error: unknown): ApiError {
  if (error instanceof ApiError) {
    return error
  }

  if (error instanceof AxiosError) {
    if (error.code === AxiosError.ERR_CANCELED) {
      return new ApiError('The request was canceled.', { isCanceled: true, cause: error })
    }

    const response = error.response
    if (!response) {
      return new ApiError(
        'The server could not be reached. Check that the API is running and try again.',
        { isNetworkError: true, cause: error },
      )
    }

    const envelope = isEnvelope(response.data) ? response.data : undefined

    return new ApiError(envelope?.message?.trim() || defaultMessageFor(response.status), {
      status: response.status,
      fieldErrors: toFieldErrors(envelope?.errors),
      cause: error,
    })
  }

  if (error instanceof Error) {
    return new ApiError(error.message, { cause: error })
  }

  return new ApiError('Something went wrong.', { cause: error })
}

function isEnvelope(data: unknown): data is ApiResponse<unknown> {
  return typeof data === 'object' && data !== null && 'success' in data
}

function defaultMessageFor(status: number): string {
  switch (status) {
    case 400:
      return 'The request could not be processed. Please check the values and try again.'
    case 401:
      return 'Your session has ended. Please sign in again.'
    case 403:
      return 'You do not have permission to do that.'
    case 404:
      return 'That record could not be found.'
    case 409:
      return 'That change conflicts with existing data.'
    case 429:
      return 'Too many attempts. Please wait a moment and try again.'
    default:
      return status >= 500
        ? 'The server ran into a problem. Please try again.'
        : 'The request failed.'
  }
}
