import { api, cleanParams, request } from './client.ts'
import type { ApiResponse, PagedResult } from './types.ts'
import type { QueryParams } from './client.ts'

export interface PayrollAnalyticsOverview { payrollRunId: string; runNumber: string; status: string; employeeCount: number; grossTotal: number; deductionTotal: number; netPayTotal: number; employerContributionTotal: number; taxTotal: number; bankAdviceTotal: number; accountingDebitTotal: number; accountingCreditTotal: number; openFindings: number; criticalFindings: number; anomalyCount: number }
export interface PayrollVarianceRow { employeeId: string; employeeCode: string; employeeName: string; baseGross?: number | null; currentGross: number; grossDelta: number; grossVariancePercent?: number | null; baseDeduction?: number | null; currentDeduction: number; deductionDelta: number; deductionVariancePercent?: number | null; baseNet?: number | null; currentNet: number; netDelta: number; netVariancePercent?: number | null; classification: string; flags: string[] }
export interface PayrollReconciliation { id: string; payrollRunId: string; type: string; version: number; status: string; totalChecks: number; passedChecks: number; warningChecks: number; failedChecks: number; criticalChecks: number; generatedAtUtc: string; findings: PayrollFinding[] }
export interface PayrollFinding { id: string; controlCode: string; scope: string; severity: string; action: string; metric: string; employeeId?: string | null; expectedValue?: number | null; actualValue?: number | null; difference?: number | null; variancePercent?: number | null; message: string; status: string; generatedAtUtc: string; resolutionNote?: string | null; resolutionReference?: string | null }
export function getPayrollAnalyticsOverview(runId: string, signal?: AbortSignal): Promise<PayrollAnalyticsOverview> { return request<PayrollAnalyticsOverview>(() => api.get<ApiResponse<PayrollAnalyticsOverview>>(`/api/payroll/analytics/runs/${runId}/overview`, { signal })) }
export function getPayrollVariance(runId: string, params: QueryParams = {}, signal?: AbortSignal): Promise<PagedResult<PayrollVarianceRow>> { return request<PagedResult<PayrollVarianceRow>>(() => api.get<ApiResponse<PagedResult<PayrollVarianceRow>>>(`/api/payroll/analytics/runs/${runId}/variance`, { params: cleanParams(params), signal })) }
export function generatePayrollReconciliation(runId: string, type: 'pre' | 'post'): Promise<PayrollReconciliation> { return request<PayrollReconciliation>(() => api.post<ApiResponse<PayrollReconciliation>>(`/api/payroll/reconciliation/runs/${runId}/${type}`)) }
