import { api, cleanParams, request, type QueryParams } from './client.ts'
import type { ApiResponse, PagedResult } from './types.ts'

export type ReimbursementCategoryType = 'Travel' | 'Meal' | 'Mobile' | 'Internet' | 'Medical' | 'Fuel' | 'LocalConveyance' | 'Relocation' | 'Education' | 'Other'
export type ReimbursementTaxTreatment = 'NonTaxable' | 'Taxable' | 'PartiallyTaxable' | 'InformationalOnly'
export type ReimbursementSettlementMethod = 'Payroll' | 'Manual' | 'FinalSettlement'
export type ReimbursementClaimStatus = 'Draft' | 'Submitted' | 'UnderReview' | 'Approved' | 'PartiallyApproved' | 'Rejected' | 'ReadyForSettlement' | 'Settled' | 'Cancelled'
export interface ReimbursementPolicyVersion { id: string; categoryId: string; effectiveFrom: string; effectiveTo?: string | null; minClaimAmount?: number | null; maxClaimAmount?: number | null; perTransactionLimit?: number | null; monthlyLimit?: number | null; yearlyLimit?: number | null; requiresReceipt: boolean; taxTreatment: ReimbursementTaxTreatment; settlementMethod: ReimbursementSettlementMethod; status: string }
export interface ReimbursementCategory { id: string; code: string; name: string; categoryType: ReimbursementCategoryType; isActive: boolean; currencyCode: string; requiresReceipt: boolean; allowsMultipleLines: boolean; taxTreatment: ReimbursementTaxTreatment; defaultSettlementMethod: ReimbursementSettlementMethod; versions: ReimbursementPolicyVersion[] }
export interface ReimbursementAttachment { id: string; claimLineId?: string | null; fileName: string; contentType: string; storageReference: string; fileSize: number; uploadedAtUtc: string }
export interface ReimbursementSettlement { id: string; claimLineId?: string | null; settlementType: string; amount: number; taxableAmount: number; nonTaxableAmount: number; settlementDate: string; payrollRunId?: string | null; payrollResultId?: string | null; finalSettlementId?: string | null; reference?: string | null }
export interface ReimbursementHistory { id: string; eventType: string; previousStatus?: ReimbursementClaimStatus | null; newStatus?: ReimbursementClaimStatus | null; claimedAmount?: number | null; approvedAmount?: number | null; reason?: string | null; actorUserId?: string | null; occurredAtUtc: string }
export interface ReimbursementClaimLine { id: string; categoryId: string; categoryCode: string; policyVersionId?: string | null; expenseDate: string; description: string; merchantName?: string | null; referenceNumber?: string | null; claimedAmount: number; eligibleAmount: number; approvedAmount: number; taxableAmount: number; nonTaxableAmount: number; receiptRequired: boolean; receiptStatus: string; status: string; approvalComment?: string | null }
export interface ReimbursementClaim { id: string; employeeId: string; claimNumber: string; claimDate: string; currencyCode: string; totalClaimedAmount: number; totalEligibleAmount: number; totalApprovedAmount: number; taxableAmount: number; nonTaxableAmount: number; settledAmount: number; settlementMethod: ReimbursementSettlementMethod; status: ReimbursementClaimStatus; lines: ReimbursementClaimLine[]; attachments?: ReimbursementAttachment[]; settlements?: ReimbursementSettlement[]; history?: ReimbursementHistory[] }
export interface ReimbursementRegisterRow { id: string; claimNumber: string; employeeId: string; employeeCode: string; employeeName: string; claimDate: string; claimedAmount: number; eligibleAmount: number; approvedAmount: number; taxableAmount: number; nonTaxableAmount: number; settledAmount: number; outstandingAmount: number; status: ReimbursementClaimStatus; settlementMethod: ReimbursementSettlementMethod }
export interface ReimbursementCategoryRequest { code: string; name: string; categoryType: ReimbursementCategoryType; isActive: boolean; currencyCode: string; requiresReceipt: boolean; allowsMultipleLines: boolean; taxTreatment: ReimbursementTaxTreatment; defaultSettlementMethod: ReimbursementSettlementMethod; requiresApproval: boolean; settlementPriority: number }
export interface ReimbursementClaimRequest { employeeId?: string; claimDate: string; currencyCode: string; settlementMethod?: ReimbursementSettlementMethod; lines: { reimbursementCategoryId: string; expenseDate: string; description: string; claimedAmount: number; merchantName?: string; referenceNumber?: string }[] }
export interface ReimbursementPolicyVersionRequest { effectiveFrom: string; effectiveTo?: string | null; minClaimAmount?: number | null; maxClaimAmount?: number | null; perTransactionLimit?: number | null; monthlyLimit?: number | null; yearlyLimit?: number | null; requiresReceipt: boolean; receiptRequiredAbove?: number | null; taxTreatment: ReimbursementTaxTreatment; settlementMethod: ReimbursementSettlementMethod; status: string; eligibilityJson?: string | null }
export interface ReimbursementApprovalRequest { lines: { claimLineId: string; approvedAmount: number; comment?: string | null; taxableAmount?: number | null }[]; comment?: string | null }
export interface ReimbursementSettlementRequest { amount?: number | null; settlementDate?: string | null; reference?: string | null }
export interface ReimbursementAttachmentRequest { claimLineId?: string; fileName: string; contentType: string; storageReference: string; fileSize: number }
export function listReimbursementCategories(signal?: AbortSignal): Promise<ReimbursementCategory[]> { return request(() => api.get<ApiResponse<ReimbursementCategory[]>>('/api/payroll/reimbursement-categories', { signal })) }
export function listMyReimbursementCategories(signal?: AbortSignal): Promise<ReimbursementCategory[]> { return request(() => api.get<ApiResponse<ReimbursementCategory[]>>('/api/me/reimbursement-categories', { signal })) }
export function createReimbursementCategory(body: ReimbursementCategoryRequest): Promise<ReimbursementCategory> { return request(() => api.post<ApiResponse<ReimbursementCategory>>('/api/payroll/reimbursement-categories', body)) }
export function updateReimbursementCategory(id: string, body: ReimbursementCategoryRequest): Promise<ReimbursementCategory> { return request(() => api.put<ApiResponse<ReimbursementCategory>>(`/api/payroll/reimbursement-categories/${id}`, body)) }
export function createReimbursementPolicyVersion(id: string, body: ReimbursementPolicyVersionRequest): Promise<ReimbursementCategory> { return request(() => api.post<ApiResponse<ReimbursementCategory>>(`/api/payroll/reimbursement-categories/${id}/versions`, body)) }
export function listReimbursements(params: QueryParams = {}, signal?: AbortSignal): Promise<PagedResult<ReimbursementClaim>> { return request(() => api.get<ApiResponse<PagedResult<ReimbursementClaim>>>('/api/payroll/reimbursements', { params: cleanParams(params), signal })) }
export function getReimbursement(id: string): Promise<ReimbursementClaim> { return request(() => api.get<ApiResponse<ReimbursementClaim>>(`/api/payroll/reimbursements/${id}`)) }
export function getReimbursementHistory(id: string): Promise<ReimbursementHistory[]> { return request(() => api.get<ApiResponse<ReimbursementHistory[]>>(`/api/payroll/reimbursements/${id}/history`)) }
export function approveReimbursement(id: string, body: ReimbursementApprovalRequest): Promise<ReimbursementClaim> { return request(() => api.post<ApiResponse<ReimbursementClaim>>(`/api/payroll/reimbursements/${id}/approve`, body)) }
export function rejectReimbursement(id: string, reason: string): Promise<ReimbursementClaim> { return request(() => api.post<ApiResponse<ReimbursementClaim>>(`/api/payroll/reimbursements/${id}/reject`, reason)) }
export function settleReimbursementManually(id: string, body: ReimbursementSettlementRequest): Promise<ReimbursementClaim> { return request(() => api.post<ApiResponse<ReimbursementClaim>>(`/api/payroll/reimbursements/${id}/settle-manually`, body)) }
export function cancelReimbursement(id: string, reason: string): Promise<ReimbursementClaim> { return request(() => api.post<ApiResponse<ReimbursementClaim>>(`/api/payroll/reimbursements/${id}/cancel`, reason)) }
export function listReimbursementRegister(params: QueryParams = {}, signal?: AbortSignal): Promise<PagedResult<ReimbursementRegisterRow>> { return request(() => api.get<ApiResponse<PagedResult<ReimbursementRegisterRow>>>('/api/payroll/reimbursements/register', { params: cleanParams(params), signal })) }
export function listMyReimbursements(params: QueryParams = {}, signal?: AbortSignal): Promise<PagedResult<ReimbursementClaim>> { return request(() => api.get<ApiResponse<PagedResult<ReimbursementClaim>>>('/api/me/reimbursements', { params: cleanParams(params), signal })) }
export function createMyReimbursement(body: ReimbursementClaimRequest): Promise<ReimbursementClaim> { return request(() => api.post<ApiResponse<ReimbursementClaim>>('/api/me/reimbursements', body)) }
export function getMyReimbursement(id: string): Promise<ReimbursementClaim> { return request(() => api.get<ApiResponse<ReimbursementClaim>>(`/api/me/reimbursements/${id}`)) }
export function getMyReimbursementHistory(id: string): Promise<ReimbursementHistory[]> { return request(() => api.get<ApiResponse<ReimbursementHistory[]>>(`/api/me/reimbursements/${id}/history`)) }
export function updateMyReimbursement(id: string, body: ReimbursementClaimRequest): Promise<ReimbursementClaim> { return request(() => api.put<ApiResponse<ReimbursementClaim>>(`/api/me/reimbursements/${id}`, body)) }
export function submitMyReimbursement(id: string): Promise<ReimbursementClaim> { return request(() => api.post<ApiResponse<ReimbursementClaim>>(`/api/me/reimbursements/${id}/submit`)) }
export function addMyReimbursementAttachment(id: string, body: ReimbursementAttachmentRequest): Promise<unknown> { return request(() => api.post<ApiResponse<unknown>>(`/api/me/reimbursements/${id}/attachments`, body)) }
