import { api, request } from './client.ts'
import type { ApiResponse } from './types.ts'

export type SeparationStatus = 'Draft' | 'Submitted' | 'ManagerReview' | 'HrReview' | 'Approved' | 'Rejected' | 'Withdrawn' | 'NoticePeriod' | 'ReadyForExit' | 'Exited' | 'Cancelled'
export interface SeparationReason { id: string; code: string; name: string; description?: string | null; category: string; employeeInitiatedAllowed: boolean; employerInitiatedAllowed: boolean; isActive: boolean; effectiveFrom: string; effectiveTo?: string | null; displayOrder: number }
export interface SeparationCase { id: string; employeeId: string; separationNumber: string; separationType: string; reasonId: string; reasonName: string; initiatedBy: string; requestDate: string; proposedLastWorkingDate: string; approvedLastWorkingDate?: string | null; noticeStartDate?: string | null; noticeEndDate?: string | null; expectedNoticeEndDate?: string | null; noticePeriodDays?: number | null; noticeServedDays?: number | null; noticeShortfallDays?: number | null; waivedNoticeDays: number; noticeExtensionDays: number; noticeDisposition: string; status: SeparationStatus; createdAtUtc: string }
export interface SeparationNotice { separationId: string; requiredNoticeDays?: number | null; noticeStartDate?: string | null; expectedNoticeEndDate?: string | null; approvedLastWorkingDate?: string | null; servedNoticeDays?: number | null; waivedNoticeDays: number; shortfallDays?: number | null; extensionDays: number; noticeStatus: string; lastRevisionReason?: string | null; concurrencyVersion: number }
export interface SeparationClearanceTask { id: string; code: string; name: string; category: string; ownerType: string; status: string; isMandatory: boolean; dueDate?: string | null; isOverdue: boolean; comment?: string | null; blockingReason?: string | null; requiresAssetReturn: boolean }
export interface SeparationClearance { id: string; employeeSeparationId: string; employeeId: string; status: string; startedAtUtc?: string | null; completedAtUtc?: string | null; readyForExit: boolean; mandatoryTotal: number; mandatoryResolved: number; tasks: SeparationClearanceTask[] }
export interface ClearanceInboxItem { taskId: string; clearanceId: string; separationId: string; employeeId: string; employeeCode?: string | null; employeeName: string; approvedLastWorkingDate?: string | null; taskName: string; category: string; status: string; dueDate?: string | null; isOverdue: boolean; assetRequired: boolean; assetId?: string | null; assetStatus?: string | null; assetReference?: string | null; assetName?: string | null }
export interface ClearanceDashboardItem { employeeId: string; employeeCode?: string | null; employeeName: string; separationId: string; approvedLastWorkingDate?: string | null; clearanceId: string; clearanceStatus: string; mandatoryTaskCount: number; mandatoryCompletedCount: number; pendingCount: number; blockedCount: number; pendingAssetCount: number; overdueCount: number; readyForExit: boolean }
export interface ClearancePage<T> { items: T[]; page: number; pageSize: number; totalCount: number }
export interface SeparationEvent { id: string; eventType: string; fromStatus?: SeparationStatus | null; toStatus: SeparationStatus; actorUserId?: string | null; occurredAtUtc: string; reason?: string | null; comment?: string | null }

export function listSeparationReasons(signal?: AbortSignal): Promise<SeparationReason[]> { return request<SeparationReason[]>(() => api.get<ApiResponse<SeparationReason[]>>('/api/separation/reasons', { signal })) }
export function getMySeparation(signal?: AbortSignal): Promise<SeparationCase> { return request<SeparationCase>(() => api.get<ApiResponse<SeparationCase>>('/api/separation/me/current', { signal })) }
export function getMySeparationHistory(signal?: AbortSignal): Promise<SeparationCase[]> { return request<SeparationCase[]>(() => api.get<ApiResponse<SeparationCase[]>>('/api/separation/me/history', { signal })) }
export function getSeparationHistory(id: string, signal?: AbortSignal): Promise<SeparationEvent[]> { return request<SeparationEvent[]>(() => api.get<ApiResponse<SeparationEvent[]>>(`/api/separation/${id}/history`, { signal })) }
export function createMySeparation(body: { reasonId: string; requestDate: string; proposedLastWorkingDate: string; remarks?: string }): Promise<SeparationCase> { return request<SeparationCase>(() => api.post<ApiResponse<SeparationCase>>('/api/separation/me', body)) }
export function submitSeparation(id: string): Promise<SeparationCase> { return request<SeparationCase>(() => api.post<ApiResponse<SeparationCase>>(`/api/separation/${id}/submit`)) }
export function withdrawSeparation(id: string): Promise<SeparationCase> { return request<SeparationCase>(() => api.post<ApiResponse<SeparationCase>>(`/api/separation/${id}/withdraw`)) }
export function getManagerSeparationInbox(signal?: AbortSignal): Promise<SeparationCase[]> { return request<SeparationCase[]>(() => api.get<ApiResponse<SeparationCase[]>>('/api/separation/inbox/manager', { signal })) }
export function getHrSeparationInbox(signal?: AbortSignal): Promise<SeparationCase[]> { return request<SeparationCase[]>(() => api.get<ApiResponse<SeparationCase[]>>('/api/separation/inbox/hr', { signal })) }
export function managerApproveSeparation(id: string): Promise<SeparationCase> { return request<SeparationCase>(() => api.post<ApiResponse<SeparationCase>>(`/api/separation/${id}/manager-approve`)) }
export function managerRejectSeparation(id: string, comments: string): Promise<SeparationCase> { return request<SeparationCase>(() => api.post<ApiResponse<SeparationCase>>(`/api/separation/${id}/manager-reject`, { comments })) }
export function hrApproveSeparation(id: string): Promise<SeparationCase> { return request<SeparationCase>(() => api.post<ApiResponse<SeparationCase>>(`/api/separation/${id}/hr-approve`)) }
export function hrRejectSeparation(id: string, comments: string): Promise<SeparationCase> { return request<SeparationCase>(() => api.post<ApiResponse<SeparationCase>>(`/api/separation/${id}/hr-reject`, { comments })) }
export function reviseSeparationLwd(id: string, newLastWorkingDate: string, reason: string): Promise<SeparationCase> { return request<SeparationCase>(() => api.post<ApiResponse<SeparationCase>>(`/api/separation/${id}/revise-lwd`, { newLastWorkingDate, reason })) }
export function getSeparationNotice(id: string, signal?: AbortSignal): Promise<SeparationNotice> { return request<SeparationNotice>(() => api.get<ApiResponse<SeparationNotice>>(`/api/separation/${id}/notice`, { signal })) }
export function applyNoticeWaiver(id: string, waiverDays: number, reason: string): Promise<SeparationNotice> { return request<SeparationNotice>(() => api.post<ApiResponse<SeparationNotice>>(`/api/separation/${id}/notice/waive`, { waiverDays, reason })) }
export function reviseApprovedLwd(id: string, newLastWorkingDate: string, reason: string): Promise<SeparationNotice> { return request<SeparationNotice>(() => api.post<ApiResponse<SeparationNotice>>(`/api/separation/${id}/revise-approved-lwd`, { newLastWorkingDate, reason })) }
export function getSeparationClearance(id: string, signal?: AbortSignal): Promise<SeparationClearance> { return request<SeparationClearance>(() => api.get<ApiResponse<SeparationClearance>>(`/api/separation/clearance/for/${id}`, { signal })) }
function clearanceQuery(query: Record<string, string | number | boolean | undefined>) { const params = new URLSearchParams(); Object.entries(query).forEach(([key, value]) => value !== undefined && params.set(key, String(value))); return params.toString() }
export function getManagerClearanceInbox(query: Record<string, string | number | boolean | undefined>, signal?: AbortSignal): Promise<ClearancePage<ClearanceInboxItem>> { return request<ClearancePage<ClearanceInboxItem>>(() => api.get<ApiResponse<ClearancePage<ClearanceInboxItem>>>(`/api/separation/clearance/inbox/manager?${clearanceQuery(query)}`, { signal })) }
export function getFunctionalClearanceInbox(query: Record<string, string | number | boolean | undefined>, signal?: AbortSignal): Promise<ClearancePage<ClearanceInboxItem>> { return request<ClearancePage<ClearanceInboxItem>>(() => api.get<ApiResponse<ClearancePage<ClearanceInboxItem>>>(`/api/separation/clearance/inbox?${clearanceQuery(query)}`, { signal })) }
export function getHrClearanceDashboard(query: Record<string, string | number | boolean | undefined>, signal?: AbortSignal): Promise<ClearancePage<ClearanceDashboardItem>> { return request<ClearancePage<ClearanceDashboardItem>>(() => api.get<ApiResponse<ClearancePage<ClearanceDashboardItem>>>(`/api/separation/clearance/hr-dashboard?${clearanceQuery(query)}`, { signal })) }
export function clearClearanceTask(id: string, comment?: string): Promise<SeparationClearance> { return request<SeparationClearance>(() => api.post<ApiResponse<SeparationClearance>>(`/api/separation/clearance/tasks/${id}/clear`, { comment })) }
export function blockClearanceTask(id: string, reason: string): Promise<SeparationClearance> { return request<SeparationClearance>(() => api.post<ApiResponse<SeparationClearance>>(`/api/separation/clearance/tasks/${id}/block`, { reason })) }
export function updateClearanceAssetReturn(taskId: string, assetId: string, body: { assetReference: string; assetType: string; assetName: string; serialNumber?: string | null; expectedReturnDate?: string | null; returnStatus: string; condition: string; recoveryRequired: boolean; recoveryReference?: string | null; comment?: string | null }): Promise<SeparationClearanceTask> { return request<SeparationClearanceTask>(() => api.post<ApiResponse<SeparationClearanceTask>>(`/api/separation/clearance/tasks/${taskId}/assets/${assetId}`, body)) }
