import { api, request } from './client.ts'
import type { ApiResponse } from './types.ts'

export type SeparationDocumentType = 'RelievingLetter' | 'ExperienceLetter' | 'ServiceCertificate' | 'CustomSeparationDocument'
export type SeparationDocumentStatus = 'DraftGenerated' | 'PendingApproval' | 'Approved' | 'Issued' | 'Superseded' | 'Cancelled'
export interface SeparationDocumentTemplateVersion { id: string; versionNumber: number; status: string; effectiveFrom: string; effectiveTo?: string | null; subject?: string | null; bodyTemplate: string; headerTemplate?: string | null; footerTemplate?: string | null; publishedAtUtc?: string | null }
export interface SeparationDocumentTemplate { id: string; code: string; name: string; documentType: SeparationDocumentType; description?: string | null; isActive: boolean; effectiveFrom: string; effectiveTo?: string | null; requiresApproval: boolean; concurrencyVersion: number; versions: SeparationDocumentTemplateVersion[] }
export interface SeparationDocumentPreview { fileName: string; contentType: string; contentHash: string; contentBase64: string; isOfficial: boolean }
export interface SeparationDocumentReadiness { isEligible: boolean; blockers: string[]; separationId: string; employeeId: string; approvedLastWorkingDate?: string | null; settlementStatus?: string | null; clearanceComplete: boolean; readyForFinalExitClosure: boolean }
export interface SeparationGeneratedDocument { id: string; separationId: string; employeeId: string; employeeName: string; employeeCode?: string | null; documentType: SeparationDocumentType; documentNumber: string; status: SeparationDocumentStatus; issueDate: string; generatedAtUtc: string; approvedAtUtc?: string | null; fileName: string; contentHash: string; templateId: string; templateVersionId: string; supersedesDocumentId?: string | null; supersededByDocumentId?: string | null; lastReason?: string | null }
export interface SeparationDocumentPage { items: SeparationGeneratedDocument[]; page: number; pageSize: number; totalCount: number }
const query = (values: Record<string, string | number | undefined>) => new URLSearchParams(Object.entries(values).filter(([, value]) => value !== undefined).map(([key, value]) => [key, String(value)])).toString()
export function getSeparationDocumentTemplates(signal?: AbortSignal): Promise<SeparationDocumentTemplate[]> { return request(() => api.get<ApiResponse<SeparationDocumentTemplate[]>>('/api/separation/documents/templates', { signal })) }
export function createSeparationDocumentTemplate(body: { code: string; name: string; documentType: SeparationDocumentType; description?: string; effectiveFrom: string; effectiveTo?: string | null; requiresApproval: boolean }): Promise<SeparationDocumentTemplate> { return request(() => api.post<ApiResponse<SeparationDocumentTemplate>>('/api/separation/documents/templates', body)) }
export function addSeparationDocumentTemplateVersion(templateId: string, body: { effectiveFrom: string; effectiveTo?: string | null; subject?: string; bodyTemplate: string }): Promise<SeparationDocumentTemplate> { return request(() => api.post<ApiResponse<SeparationDocumentTemplate>>(`/api/separation/documents/templates/${templateId}/versions`, body)) }
export function publishSeparationDocumentTemplateVersion(templateId: string, versionId: string, expectedConcurrencyVersion: number): Promise<SeparationDocumentTemplate> { return request(() => api.post<ApiResponse<SeparationDocumentTemplate>>(`/api/separation/documents/templates/${templateId}/versions/${versionId}/publish?expectedConcurrencyVersion=${expectedConcurrencyVersion}`)) }
export function previewSeparationDocumentTemplateVersion(versionId: string): Promise<SeparationDocumentPreview> { return request(() => api.post<ApiResponse<SeparationDocumentPreview>>(`/api/separation/documents/templates/versions/${versionId}/preview`, {})) }
export function getSeparationDocumentReadiness(separationId: string, signal?: AbortSignal): Promise<SeparationDocumentReadiness> { return request(() => api.get<ApiResponse<SeparationDocumentReadiness>>(`/api/separation/documents/for/${separationId}/readiness`, { signal })) }
export function getSeparationDocuments(separationId: string, signal?: AbortSignal): Promise<SeparationGeneratedDocument[]> { return request(() => api.get<ApiResponse<SeparationGeneratedDocument[]>>(`/api/separation/documents/for/${separationId}`, { signal })) }
export function getMySeparationDocuments(separationId: string, signal?: AbortSignal): Promise<SeparationGeneratedDocument[]> { return request(() => api.get<ApiResponse<SeparationGeneratedDocument[]>>(`/api/separation/documents/mine/${separationId}`, { signal })) }
export function getSeparationDocumentDashboard(values: Record<string, string | number | undefined>, signal?: AbortSignal): Promise<SeparationDocumentPage> { return request(() => api.get<ApiResponse<SeparationDocumentPage>>(`/api/separation/documents/dashboard?${query(values)}`, { signal })) }
export function generateSeparationDocument(separationId: string, body: { documentType: SeparationDocumentType; templateVersionId?: string; issueDate?: string; expectedConcurrencyVersion?: number }): Promise<SeparationGeneratedDocument> { return request(() => api.post<ApiResponse<SeparationGeneratedDocument>>(`/api/separation/documents/for/${separationId}/generate`, body)) }
export function approveSeparationDocument(id: string, expectedConcurrencyVersion: number): Promise<SeparationGeneratedDocument> { return request(() => api.post<ApiResponse<SeparationGeneratedDocument>>(`/api/separation/documents/${id}/approve`, { expectedConcurrencyVersion })) }
export function issueSeparationDocument(id: string, expectedConcurrencyVersion: number): Promise<SeparationGeneratedDocument> { return request(() => api.post<ApiResponse<SeparationGeneratedDocument>>(`/api/separation/documents/${id}/issue?expectedConcurrencyVersion=${expectedConcurrencyVersion}`)) }
export function supersedeSeparationDocument(id: string, body: { reason: string; templateVersionId?: string; issueDate?: string; expectedConcurrencyVersion?: number }): Promise<SeparationGeneratedDocument> { return request(() => api.post<ApiResponse<SeparationGeneratedDocument>>(`/api/separation/documents/${id}/supersede`, body)) }
export async function downloadSeparationDocument(id: string, mine = false): Promise<void> { const response = await api.get<Blob>(mine ? `/api/separation/documents/mine/${id}/download` : `/api/separation/documents/${id}/download`, { responseType: 'blob' }); const url = URL.createObjectURL(response.data); const link = document.createElement('a'); link.href = url; link.download = response.headers['content-disposition']?.match(/filename="?([^";]+)"?/)?.[1] ?? 'separation-document.pdf'; link.click(); URL.revokeObjectURL(url) }
