import { api, request } from './client.ts'
import type { ApiResponse } from './types.ts'

export type SeparationStatus = 'Draft' | 'Submitted' | 'ManagerReview' | 'HrReview' | 'Approved' | 'Rejected' | 'Withdrawn' | 'NoticePeriod' | 'ReadyForExit' | 'Exited' | 'Closed' | 'Cancelled'
export interface SeparationReason { id: string; code: string; name: string; description?: string | null; category: string; employeeInitiatedAllowed: boolean; employerInitiatedAllowed: boolean; isActive: boolean; effectiveFrom: string; effectiveTo?: string | null; displayOrder: number }
export interface SeparationCase { id: string; employeeId: string; separationNumber: string; separationType: string; reasonId: string; reasonName: string; initiatedBy: string; requestDate: string; proposedLastWorkingDate: string; approvedLastWorkingDate?: string | null; noticeStartDate?: string | null; noticeEndDate?: string | null; expectedNoticeEndDate?: string | null; noticePeriodDays?: number | null; noticeServedDays?: number | null; noticeShortfallDays?: number | null; waivedNoticeDays: number; noticeExtensionDays: number; noticeDisposition: string; status: SeparationStatus; createdAtUtc: string }
export interface SeparationNotice { separationId: string; requiredNoticeDays?: number | null; noticeStartDate?: string | null; expectedNoticeEndDate?: string | null; approvedLastWorkingDate?: string | null; servedNoticeDays?: number | null; waivedNoticeDays: number; shortfallDays?: number | null; extensionDays: number; noticeStatus: string; lastRevisionReason?: string | null; concurrencyVersion: number }
export interface SeparationClearanceTask { id: string; code: string; name: string; category: string; ownerType: string; status: string; isMandatory: boolean; dueDate?: string | null; isOverdue: boolean; comment?: string | null; blockingReason?: string | null; requiresAssetReturn: boolean }
export interface SeparationClearance { id: string; employeeSeparationId: string; employeeId: string; status: string; startedAtUtc?: string | null; completedAtUtc?: string | null; readyForExit: boolean; mandatoryTotal: number; mandatoryResolved: number; tasks: SeparationClearanceTask[] }
export interface ClearanceInboxItem { taskId: string; clearanceId: string; separationId: string; employeeId: string; employeeCode?: string | null; employeeName: string; approvedLastWorkingDate?: string | null; taskName: string; category: string; status: string; dueDate?: string | null; isOverdue: boolean; assetRequired: boolean; assetId?: string | null; assetStatus?: string | null; assetReference?: string | null; assetName?: string | null }
export interface ClearanceDashboardItem { employeeId: string; employeeCode?: string | null; employeeName: string; separationId: string; approvedLastWorkingDate?: string | null; clearanceId: string; clearanceStatus: string; mandatoryTaskCount: number; mandatoryCompletedCount: number; pendingCount: number; blockedCount: number; pendingAssetCount: number; overdueCount: number; readyForExit: boolean }
export interface ClearancePage<T> { items: T[]; page: number; pageSize: number; totalCount: number }
export interface SeparationEvent { id: string; eventType: string; fromStatus?: SeparationStatus | null; toStatus: SeparationStatus; actorUserId?: string | null; occurredAtUtc: string; reason?: string | null; comment?: string | null }

export function listSeparationReasons(signal?: AbortSignal): Promise<SeparationReason[]> { return request<SeparationReason[]>(() => api.get<ApiResponse<SeparationReason[]>>('/api/separation/reasons', { signal })) }
export function getMySeparation(signal?: AbortSignal): Promise<SeparationCase> { return request<SeparationCase>(() => api.get<ApiResponse<SeparationCase>>('/api/separation/me/current', { signal })) }
export function getMySeparationHistory(signal?: AbortSignal): Promise<SeparationCase[]> { return request<SeparationCase[]>(() => api.get<ApiResponse<SeparationCase[]>>('/api/separation/me/history', { signal })) }
export function getSeparationHistory(id: string, signal?: AbortSignal): Promise<SeparationEvent[]> { return request<SeparationEvent[]>(() => api.get<ApiResponse<SeparationEvent[]>>(`/api/separation/${id}/history`, { signal })) }
export function createMySeparation(body: { reasonId: string; requestDate: string; proposedLastWorkingDate: string; remarks?: string }): Promise<SeparationCase> { return request<SeparationCase>(() => api.post<ApiResponse<SeparationCase>>('/api/separation/me', body)) }
export function submitSeparation(id: string): Promise<SeparationCase> { return request<SeparationCase>(() => api.post<ApiResponse<SeparationCase>>(`/api/separation/${id}/submit`)) }
export function withdrawSeparation(id: string): Promise<SeparationCase> { return request<SeparationCase>(() => api.post<ApiResponse<SeparationCase>>(`/api/separation/${id}/withdraw`)) }
export function getManagerSeparationInbox(signal?: AbortSignal): Promise<SeparationCase[]> { return request<SeparationCase[]>(() => api.get<ApiResponse<SeparationCase[]>>('/api/separation/inbox/manager', { signal })) }
export function getHrSeparationInbox(signal?: AbortSignal): Promise<SeparationCase[]> { return request<SeparationCase[]>(() => api.get<ApiResponse<SeparationCase[]>>('/api/separation/inbox/hr', { signal })) }
export function managerApproveSeparation(id: string): Promise<SeparationCase> { return request<SeparationCase>(() => api.post<ApiResponse<SeparationCase>>(`/api/separation/${id}/manager-approve`)) }
export function managerRejectSeparation(id: string, comments: string): Promise<SeparationCase> { return request<SeparationCase>(() => api.post<ApiResponse<SeparationCase>>(`/api/separation/${id}/manager-reject`, { comments })) }
export function hrApproveSeparation(id: string): Promise<SeparationCase> { return request<SeparationCase>(() => api.post<ApiResponse<SeparationCase>>(`/api/separation/${id}/hr-approve`)) }
export function hrRejectSeparation(id: string, comments: string): Promise<SeparationCase> { return request<SeparationCase>(() => api.post<ApiResponse<SeparationCase>>(`/api/separation/${id}/hr-reject`, { comments })) }
export function reviseSeparationLwd(id: string, newLastWorkingDate: string, reason: string): Promise<SeparationCase> { return request<SeparationCase>(() => api.post<ApiResponse<SeparationCase>>(`/api/separation/${id}/revise-lwd`, { newLastWorkingDate, reason })) }
export function getSeparationNotice(id: string, signal?: AbortSignal): Promise<SeparationNotice> { return request<SeparationNotice>(() => api.get<ApiResponse<SeparationNotice>>(`/api/separation/${id}/notice`, { signal })) }
export function applyNoticeWaiver(id: string, waiverDays: number, reason: string): Promise<SeparationNotice> { return request<SeparationNotice>(() => api.post<ApiResponse<SeparationNotice>>(`/api/separation/${id}/notice/waive`, { waiverDays, reason })) }
export function reviseApprovedLwd(id: string, newLastWorkingDate: string, reason: string): Promise<SeparationNotice> { return request<SeparationNotice>(() => api.post<ApiResponse<SeparationNotice>>(`/api/separation/${id}/revise-approved-lwd`, { newLastWorkingDate, reason })) }
export function getSeparationClearance(id: string, signal?: AbortSignal): Promise<SeparationClearance> { return request<SeparationClearance>(() => api.get<ApiResponse<SeparationClearance>>(`/api/separation/clearance/for/${id}`, { signal })) }
function clearanceQuery(query: Record<string, string | number | boolean | undefined>) { const params = new URLSearchParams(); Object.entries(query).forEach(([key, value]) => value !== undefined && params.set(key, String(value))); return params.toString() }
export function getManagerClearanceInbox(query: Record<string, string | number | boolean | undefined>, signal?: AbortSignal): Promise<ClearancePage<ClearanceInboxItem>> { return request<ClearancePage<ClearanceInboxItem>>(() => api.get<ApiResponse<ClearancePage<ClearanceInboxItem>>>(`/api/separation/clearance/inbox/manager?${clearanceQuery(query)}`, { signal })) }
export function getFunctionalClearanceInbox(query: Record<string, string | number | boolean | undefined>, signal?: AbortSignal): Promise<ClearancePage<ClearanceInboxItem>> { return request<ClearancePage<ClearanceInboxItem>>(() => api.get<ApiResponse<ClearancePage<ClearanceInboxItem>>>(`/api/separation/clearance/inbox?${clearanceQuery(query)}`, { signal })) }
export function getHrClearanceDashboard(query: Record<string, string | number | boolean | undefined>, signal?: AbortSignal): Promise<ClearancePage<ClearanceDashboardItem>> { return request<ClearancePage<ClearanceDashboardItem>>(() => api.get<ApiResponse<ClearancePage<ClearanceDashboardItem>>>(`/api/separation/clearance/hr-dashboard?${clearanceQuery(query)}`, { signal })) }
export function clearClearanceTask(id: string, comment?: string): Promise<SeparationClearance> { return request<SeparationClearance>(() => api.post<ApiResponse<SeparationClearance>>(`/api/separation/clearance/tasks/${id}/clear`, { comment })) }
export function blockClearanceTask(id: string, reason: string): Promise<SeparationClearance> { return request<SeparationClearance>(() => api.post<ApiResponse<SeparationClearance>>(`/api/separation/clearance/tasks/${id}/block`, { reason })) }
export function updateClearanceAssetReturn(taskId: string, assetId: string, body: { assetReference: string; assetType: string; assetName: string; serialNumber?: string | null; expectedReturnDate?: string | null; returnStatus: string; condition: string; recoveryRequired: boolean; recoveryReference?: string | null; comment?: string | null }): Promise<SeparationClearanceTask> { return request<SeparationClearanceTask>(() => api.post<ApiResponse<SeparationClearanceTask>>(`/api/separation/clearance/tasks/${taskId}/assets/${assetId}`, body)) }

export interface ExitInterviewQuestionOption { code: string; label: string; sequence: number }
export interface ExitInterviewQuestion { id: string; code: string; questionText: string; questionType: string; sequence: number; isRequired: boolean; isEmployeeVisible?: boolean; isHrOnly?: boolean; allowsComment: boolean; minValue?: number | null; maxValue?: number | null; options: ExitInterviewQuestionOption[] }
export interface ExitInterviewResponse { questionId: string; responseText?: string | null; numericValue?: number | null; booleanValue?: boolean | null; selectedOptionCodes: string[]; comment?: string | null }
export interface ExitInterviewEmployee { id: string; employeeSeparationId: string; status: string; assignedAtUtc: string; employeeSubmittedAtUtc?: string | null; questions: ExitInterviewQuestion[]; responses: ExitInterviewResponse[] }
export function getMyExitInterview(separationId?: string, signal?: AbortSignal): Promise<ExitInterviewEmployee> { return request<ExitInterviewEmployee>(() => api.get<ApiResponse<ExitInterviewEmployee>>(separationId ? `/api/separation/exit-interview/me/${separationId}` : '/api/separation/exit-interview/me', { signal })) }
export function saveMyExitInterview(separationId: string, responses: ExitInterviewResponse[]): Promise<ExitInterviewEmployee> { return request<ExitInterviewEmployee>(() => api.put<ApiResponse<ExitInterviewEmployee>>(`/api/separation/exit-interview/for/${separationId}/my-responses`, { responses })) }
export function submitMyExitInterview(separationId: string): Promise<ExitInterviewEmployee> { return request<ExitInterviewEmployee>(() => api.post<ApiResponse<ExitInterviewEmployee>>(`/api/separation/exit-interview/for/${separationId}/submit`)) }
export interface ExitInterviewTemplateVersion { id: string; templateId: string; versionNumber: number; effectiveFrom: string; effectiveTo?: string | null; status: string; questions: ExitInterviewQuestion[] }
export interface ExitInterviewTemplate { id: string; code: string; name: string; description?: string | null; isActive: boolean; effectiveFrom: string; effectiveTo?: string | null; versions: ExitInterviewTemplateVersion[] }
export interface ExitInterviewInboxItem { id: string; employeeSeparationId: string; employeeId: string; employeeCode?: string | null; employeeName: string; separationReason?: string | null; approvedLastWorkingDate?: string | null; status: string; assignedAtUtc: string; employeeSubmittedAtUtc?: string | null; assignedHrUserId?: string | null; hrCompletedAtUtc?: string | null }
export interface ExitInterviewHr extends ExitInterviewEmployee { employeeId: string; employeeCode?: string | null; employeeName: string; separationReason?: string | null; approvedLastWorkingDate?: string | null; assignedHrUserId?: string | null; primaryReasonCategory?: string | null; secondaryReasonCategory?: string | null; reasonComment?: string | null; rehireRecommendation: string; rehireRecommendationReason?: string | null; completedWithoutEmployeeResponse: boolean; completionReason?: string | null; confidentialNotes: string[] }
export interface ExitInterviewPage<T> { items: T[]; page: number; pageSize: number; totalCount: number }
export function getExitInterviewTemplates(signal?: AbortSignal): Promise<ExitInterviewTemplate[]> { return request<ExitInterviewTemplate[]>(() => api.get<ApiResponse<ExitInterviewTemplate[]>>('/api/separation/exit-interview/templates', { signal })) }
export function createExitInterviewTemplate(body: { code: string; name: string; description?: string; effectiveFrom: string; effectiveTo?: string | null; isEmployeeSurveyEnabled: boolean; isHrInterviewEnabled: boolean }): Promise<ExitInterviewTemplate> { return request<ExitInterviewTemplate>(() => api.post<ApiResponse<ExitInterviewTemplate>>('/api/separation/exit-interview/templates', body)) }
export function createExitInterviewVersion(templateId: string, body: { versionNumber: number; effectiveFrom: string; effectiveTo?: string | null; questions: Array<{ code: string; questionText: string; questionType: string; sequence: number; isRequired: boolean; isEmployeeVisible: boolean; isHrOnly: boolean; allowsComment: boolean; minValue?: number | null; maxValue?: number | null; options?: Array<{ code: string; label: string; sequence: number }> }> }): Promise<ExitInterviewTemplateVersion> { return request<ExitInterviewTemplateVersion>(() => api.post<ApiResponse<ExitInterviewTemplateVersion>>(`/api/separation/exit-interview/templates/${templateId}/versions`, body)) }
export function publishExitInterviewVersion(versionId: string): Promise<ExitInterviewTemplateVersion> { return request<ExitInterviewTemplateVersion>(() => api.post<ApiResponse<ExitInterviewTemplateVersion>>(`/api/separation/exit-interview/template-versions/${versionId}/publish`)) }
export function getExitInterviewInbox(query: Record<string, string | number | undefined>, signal?: AbortSignal): Promise<ExitInterviewPage<ExitInterviewInboxItem>> { const params = new URLSearchParams(Object.entries(query).filter(([, value]) => value !== undefined).map(([key, value]) => [key, String(value)])); return request<ExitInterviewPage<ExitInterviewInboxItem>>(() => api.get<ApiResponse<ExitInterviewPage<ExitInterviewInboxItem>>>(`/api/separation/exit-interview/inbox?${params}`, { signal })) }
export function getHrExitInterview(separationId: string, signal?: AbortSignal): Promise<ExitInterviewHr> { return request<ExitInterviewHr>(() => api.get<ApiResponse<ExitInterviewHr>>(`/api/separation/exit-interview/for/${separationId}`, { signal })) }
export function startHrExitInterview(separationId: string): Promise<ExitInterviewHr> { return request<ExitInterviewHr>(() => api.post<ApiResponse<ExitInterviewHr>>(`/api/separation/exit-interview/for/${separationId}/start-hr`)) }
export function addExitInterviewHrNote(separationId: string, noteText: string): Promise<ExitInterviewHr> { return request<ExitInterviewHr>(() => api.post<ApiResponse<ExitInterviewHr>>(`/api/separation/exit-interview/for/${separationId}/hr-note`, { noteText })) }
export function completeHrExitInterview(separationId: string, body: { primaryReasonCategory?: string; secondaryReasonCategory?: string; reasonComment?: string; rehireRecommendation: string; rehireRecommendationReason?: string; completedWithoutEmployeeResponse: boolean; completionReason?: string }): Promise<ExitInterviewHr> { return request<ExitInterviewHr>(() => api.post<ApiResponse<ExitInterviewHr>>(`/api/separation/exit-interview/for/${separationId}/complete`, body)) }
export function reopenHrExitInterview(separationId: string, reason: string): Promise<ExitInterviewHr> { return request<ExitInterviewHr>(() => api.post<ApiResponse<ExitInterviewHr>>(`/api/separation/exit-interview/for/${separationId}/reopen`, { reason })) }

export interface SettlementBlocker { code: string; message: string }
export interface SeparationSettlementReadiness { separationId: string; isReady: boolean; blockers: SettlementBlocker[]; approvedLastWorkingDate?: string | null; clearanceStatus?: string | null; exitInterviewStatus?: string | null; noticeShortfallDays?: number | null; pendingAssetRecoveryCount: number; existingFinalSettlementId?: string | null; settlementStatus?: string | null }
export interface SeparationSettlementStatus { separationId: string; orchestrationId?: string | null; orchestrationStatus: string; payrollFinalSettlementId?: string | null; payrollSettlementStatus?: string | null; initiatedAtUtc?: string | null; completedAtUtc?: string | null; failureCode?: string | null; failureMessage?: string | null; readyForFinalExitClosure: boolean; blockers: SettlementBlocker[] }
export interface SeparationSettlementDashboardItem { separationId: string; employeeId: string; employeeCode?: string | null; employeeName: string; approvedLastWorkingDate?: string | null; orchestrationStatus: string; payrollSettlementStatus?: string | null; isReady: boolean; blockerCount: number; initiatedAtUtc?: string | null; completedAtUtc?: string | null; readyForFinalExitClosure: boolean }
export function getSettlementReadiness(separationId: string, signal?: AbortSignal): Promise<SeparationSettlementReadiness> { return request<SeparationSettlementReadiness>(() => api.get<ApiResponse<SeparationSettlementReadiness>>(`/api/separation/${separationId}/settlement/readiness`, { signal })) }
export function getSettlementStatus(separationId: string, signal?: AbortSignal): Promise<SeparationSettlementStatus> { return request<SeparationSettlementStatus>(() => api.get<ApiResponse<SeparationSettlementStatus>>(`/api/separation/${separationId}/settlement`, { signal })) }
export function initiateSettlement(separationId: string, idempotencyKey?: string): Promise<SeparationSettlementStatus> { return request<SeparationSettlementStatus>(() => api.post<ApiResponse<SeparationSettlementStatus>>(`/api/separation/${separationId}/settlement/initiate`, { idempotencyKey })) }
export function retrySettlement(separationId: string, reason?: string): Promise<SeparationSettlementStatus> { return request<SeparationSettlementStatus>(() => api.post<ApiResponse<SeparationSettlementStatus>>(`/api/separation/${separationId}/settlement/retry`, { reason })) }
export function getSettlementDashboard(query: Record<string, string | number | undefined>, signal?: AbortSignal): Promise<{ items: SeparationSettlementDashboardItem[]; page: number; pageSize: number; totalCount: number }> { const params = new URLSearchParams(Object.entries(query).filter(([, value]) => value !== undefined).map(([key, value]) => [key, String(value)])); return request(() => api.get<ApiResponse<{ items: SeparationSettlementDashboardItem[]; page: number; pageSize: number; totalCount: number }>>(`/api/separation/settlement/dashboard?${params}`, { signal })) }
