import { useEffect, useState } from 'react'
import { ApiError } from '../../api/errors.ts'
import { getLeaveTypeAttachmentRule, saveLeaveTypeAttachmentRule, type AttachmentRequirement, type LeavePolicyAttachmentRule, type LeavePolicyVersion, type LeaveTypeSelection } from '../../api/leaveConfiguration.ts'
import { Badge } from '../../components/Badge.tsx'; import { Card } from '../../components/Card.tsx'; import { Spinner } from '../../components/Spinner.tsx'
interface Props { policyId: string; version: LeavePolicyVersion; leaveTypes: LeaveTypeSelection[]; canManage: boolean; onNotice: (message: string) => void; onChanged?: () => void }
const defaults = { attachmentRequirement: 'None' as AttachmentRequirement, thresholdQuantity: '', documentLabel: '' }
function fromRule(rule: LeavePolicyAttachmentRule | null) { return rule ? { attachmentRequirement: rule.attachmentRequirement, thresholdQuantity: rule.thresholdQuantity?.toString() ?? '', documentLabel: rule.documentLabel ?? '' } : { ...defaults } }
export function LeavePolicyAttachmentSection({ policyId, version, leaveTypes, canManage, onNotice, onChanged }: Props) {
  const [selectedTypeId, setSelectedTypeId] = useState(leaveTypes[0]?.id ?? ''); const [form, setForm] = useState({ ...defaults }); const [token, setToken] = useState(version.concurrencyToken); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<ApiError | null>(null); const editable = canManage && version.status === 'Draft'; const selected = leaveTypes.find(x => x.id === selectedTypeId)
  useEffect(() => { if (!leaveTypes.some(x => x.id === selectedTypeId)) setSelectedTypeId(leaveTypes[0]?.id ?? '') }, [leaveTypes, selectedTypeId])
  useEffect(() => { if (!selectedTypeId) return; let cancelled = false; setLoading(true); setError(null); void getLeaveTypeAttachmentRule(policyId, version.id, selectedTypeId).then(rule => { if (!cancelled) { setForm(fromRule(rule)); setToken(rule?.concurrencyToken ?? version.concurrencyToken) } }).catch(caught => { if (!cancelled && !(caught instanceof ApiError && caught.status === 404)) setError(caught instanceof ApiError ? caught : new ApiError('Unable to load Attachment Rules.')) }).finally(() => { if (!cancelled) setLoading(false) }); return () => { cancelled = true } }, [policyId, version.id, selectedTypeId, version.concurrencyToken])
  const update = (key: keyof typeof form, value: string) => setForm(current => ({ ...current, [key]: value }))
  async function save() { if (!selectedTypeId) return; setSaving(true); setError(null); try { const saved = await saveLeaveTypeAttachmentRule(policyId, version.id, selectedTypeId, { attachmentRequirement: form.attachmentRequirement, thresholdQuantity: form.attachmentRequirement === 'RequiredAboveQuantity' && form.thresholdQuantity ? Number(form.thresholdQuantity) : null, documentLabel: form.documentLabel || null, concurrencyToken: token }); setToken(saved?.concurrencyToken ?? version.concurrencyToken); onChanged?.(); onNotice('Attachment Rules saved.') } catch (caught) { setError(caught instanceof ApiError ? caught : new ApiError('Unable to save Attachment Rules.')) } finally { setSaving(false) } }
  return <Card title="10. Attachment & Declaration" subtitle="Configure supporting-evidence requirements. File upload and declaration storage are deferred.">{leaveTypes.length === 0 ? <p className="muted">Assign at least one Leave Type before configuring Attachment Rules.</p> : <><div className="eligibility-type-tabs" role="tablist" aria-label="Leave Types for Attachment Rules">{leaveTypes.map(item => <button key={item.id} type="button" role="tab" aria-selected={item.id === selectedTypeId} className={item.id === selectedTypeId ? 'button button-secondary is-selected' : 'button button-link'} onClick={() => setSelectedTypeId(item.id)}>{item.code} — {item.name}</button>)}</div>{loading ? <Spinner label="Loading Attachment Rules" /> : <>{!editable && <div className="lifecycle-notice"><Badge>{version.status}</Badge><span>{version.status === 'Published' ? 'Published Attachment Rules are immutable.' : version.status === 'Retired' ? 'Retired Attachment Rules are retained for history.' : 'You can view Attachment Rules but do not have edit permission.'}</span></div>}{error ? <div className="notice notice-error" role="alert">{error.message}{error.isConflict ? ' Reload the latest version before saving.' : ''}</div> : null}<form className="form-stack" aria-label={`${selected?.name ?? 'Leave Type'} Attachment and Declaration`} onSubmit={event => { event.preventDefault(); void save() }}><fieldset disabled={!editable} className="eligibility-fields"><legend>Attachment requirement</legend><label className="field"><span>Attachment requirement</span><select className="input" value={form.attachmentRequirement} onChange={e => update('attachmentRequirement', e.target.value)}><option value="None">No attachment required</option><option value="Optional">Attachment optional</option><option value="Required">Attachment required</option><option value="RequiredAboveQuantity">Required above Leave quantity</option></select></label>{form.attachmentRequirement === 'RequiredAboveQuantity' ? <label className="field"><span>Required above quantity</span><input className="input" type="number" min="0.001" step="0.001" required value={form.thresholdQuantity} onChange={e => update('thresholdQuantity', e.target.value)} /><small className="field-help">Supporting evidence becomes mandatory when requested Leave is above this quantity.</small></label> : null}<label className="field"><span>Document label</span><input className="input" value={form.documentLabel} onChange={e => update('documentLabel', e.target.value)} placeholder="For example, medical certificate" /></label></fieldset><div className="lifecycle-notice"><span>Declaration configuration is deferred until content and retention semantics are approved.</span></div>{editable ? <div className="form-actions"><button className="button button-primary" type="submit" disabled={saving}>{saving ? <Spinner size={14} label="Saving…" /> : 'Save Attachment Rules'}</button></div> : null}</form></>}</>}</Card>
}
