import { useEffect, useState } from 'react'
import { ApiError } from '../../api/errors.ts'
import { getLeaveTypeCancellationRule, saveLeaveTypeCancellationRule, type LeavePolicyVersion, type LeaveTypeSelection } from '../../api/leaveConfiguration.ts'
import { Badge } from '../../components/Badge.tsx'; import { Card } from '../../components/Card.tsx'; import { Spinner } from '../../components/Spinner.tsx'
interface Props { policyId: string; version: LeavePolicyVersion; leaveTypes: LeaveTypeSelection[]; canManage: boolean; onNotice: (message: string) => void; onChanged?: () => void }
const defaults = { withdrawAllowed: false, cancelAllowed: false, modifyAllowed: false }
export function LeavePolicyCancellationSection({ policyId, version, leaveTypes, canManage, onNotice, onChanged }: Props) {
  const [selectedTypeId, setSelectedTypeId] = useState(leaveTypes[0]?.id ?? ''); const [form, setForm] = useState(defaults); const [token, setToken] = useState(version.concurrencyToken); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<ApiError | null>(null); const editable = canManage && version.status === 'Draft'; const selected = leaveTypes.find(x => x.id === selectedTypeId)
  useEffect(() => { if (!leaveTypes.some(x => x.id === selectedTypeId)) setSelectedTypeId(leaveTypes[0]?.id ?? '') }, [leaveTypes, selectedTypeId])
  useEffect(() => { if (!selectedTypeId) return; let cancelled = false; setLoading(true); setError(null); void getLeaveTypeCancellationRule(policyId, version.id, selectedTypeId).then(rule => { if (!cancelled) { setForm(rule ? { withdrawAllowed: rule.withdrawAllowed, cancelAllowed: rule.cancelAllowed, modifyAllowed: rule.modifyAllowed } : { ...defaults }); setToken(rule?.concurrencyToken ?? version.concurrencyToken) } }).catch(caught => { if (!cancelled && !(caught instanceof ApiError && caught.status === 404)) setError(caught instanceof ApiError ? caught : new ApiError('Unable to load Cancellation Rules.')) }).finally(() => { if (!cancelled) setLoading(false) }); return () => { cancelled = true } }, [policyId, version.id, selectedTypeId, version.concurrencyToken])
  async function save() { if (!selectedTypeId) return; setSaving(true); setError(null); try { const saved = await saveLeaveTypeCancellationRule(policyId, version.id, selectedTypeId, { ...form, concurrencyToken: token }); setToken(saved?.concurrencyToken ?? version.concurrencyToken); onChanged?.(); onNotice('Cancellation Rules saved.') } catch (caught) { setError(caught instanceof ApiError ? caught : new ApiError('Unable to save Cancellation Rules.')) } finally { setSaving(false) } }
  return <Card title="12. Request Changes & Cancellation" subtitle="Configure policy capabilities only. Runtime withdrawal, cancellation, modification, approvals, balances, and integrations are deferred.">{leaveTypes.length === 0 ? <p className="muted">Assign at least one Leave Type before configuring Cancellation Rules.</p> : <><div className="eligibility-type-tabs" role="tablist" aria-label="Leave Types for Cancellation Rules">{leaveTypes.map(item => <button key={item.id} type="button" role="tab" aria-selected={item.id === selectedTypeId} className={item.id === selectedTypeId ? 'button button-secondary is-selected' : 'button button-link'} onClick={() => setSelectedTypeId(item.id)}>{item.code} — {item.name}</button>)}</div>{loading ? <Spinner label="Loading Cancellation Rules" /> : <>{!editable && <div className="lifecycle-notice"><Badge>{version.status}</Badge><span>Historical Cancellation Rules are read-only.</span></div>}{error ? <div className="notice notice-error" role="alert">{error.message}{error.isConflict ? ' Reload the latest version before saving.' : ''}</div> : null}<form className="form-stack" aria-label={`${selected?.name ?? 'Leave Type'} Request Changes and Cancellation`} onSubmit={event => { event.preventDefault(); void save() }}><fieldset disabled={!editable} className="eligibility-fields"><legend>Allowed policy capabilities</legend><label className="checkbox-field"><input type="checkbox" checked={form.withdrawAllowed} onChange={e => setForm(x => ({ ...x, withdrawAllowed: e.target.checked }))} /> Allow Withdraw <small className="field-help">Employee retraction capability is configured for future request workflow.</small></label><label className="checkbox-field"><input type="checkbox" checked={form.cancelAllowed} onChange={e => setForm(x => ({ ...x, cancelAllowed: e.target.checked }))} /> Allow Cancel <small className="field-help">Cancellation capability is configured separately from withdrawal.</small></label><label className="checkbox-field"><input type="checkbox" checked={form.modifyAllowed} onChange={e => setForm(x => ({ ...x, modifyAllowed: e.target.checked }))} /> Allow Modify <small className="field-help">Modification capability is configured separately from cancellation.</small></label></fieldset>{editable ? <div className="form-actions"><button className="button button-primary" type="submit" disabled={saving}>{saving ? <Spinner size={14} label="Saving…" /> : 'Save Cancellation Rules'}</button></div> : null}</form></>}</>}</Card>
}
