import { useEffect, useState } from 'react'
import { ApiError } from '../../api/errors.ts'
import { getLeavePolicyClubbing, saveLeavePolicyClubbing, type LeavePolicyClubbingRule, type LeavePolicyVersion, type LeaveTypeSelection } from '../../api/leaveConfiguration.ts'
import { Badge } from '../../components/Badge.tsx'; import { Card } from '../../components/Card.tsx'; import { Spinner } from '../../components/Spinner.tsx'
interface Props { policyId: string; version: LeavePolicyVersion; leaveTypes: LeaveTypeSelection[]; canManage: boolean; onNotice: (message: string) => void; onChanged?: () => void }
type Pair = { leaveTypeAId: string; leaveTypeBId: string; relation: 'NotAllowed' }
export function LeavePolicyClubbingSection({ policyId, version, leaveTypes, canManage, onNotice, onChanged }: Props) {
  const [pairs, setPairs] = useState<Pair[]>([]); const [token, setToken] = useState(version.concurrencyToken); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<ApiError | null>(null); const editable = canManage && version.status === 'Draft'; const names = new Map(leaveTypes.map(x => [x.id, `${x.code} — ${x.name}${x.isActive ? '' : ' (Inactive)'}`]))
  useEffect(() => { let cancelled = false; setLoading(true); setError(null); void getLeavePolicyClubbing(policyId, version.id).then(rows => { if (!cancelled) { setPairs(rows.map((x: LeavePolicyClubbingRule) => ({ leaveTypeAId: x.leaveTypeAId, leaveTypeBId: x.leaveTypeBId, relation: x.relation }))); setToken(version.concurrencyToken) } }).catch(caught => { if (!cancelled) setError(caught instanceof ApiError ? caught : new ApiError('Unable to load Clubbing Rules.')) }).finally(() => { if (!cancelled) setLoading(false) }); return () => { cancelled = true } }, [policyId, version.id, version.concurrencyToken])
  const add = () => setPairs(current => [...current, { leaveTypeAId: '', leaveTypeBId: '', relation: 'NotAllowed' }]); const remove = (index: number) => setPairs(current => current.filter((_, i) => i !== index)); const update = (index: number, key: 'leaveTypeAId' | 'leaveTypeBId', value: string) => setPairs(current => current.map((pair, i) => i === index ? { ...pair, [key]: value } : pair))
  async function save() { setSaving(true); setError(null); const normalized = pairs.map(pair => pair.leaveTypeAId < pair.leaveTypeBId ? pair : { ...pair, leaveTypeAId: pair.leaveTypeBId, leaveTypeBId: pair.leaveTypeAId }); try { const saved = await saveLeavePolicyClubbing(policyId, version.id, { rules: normalized, concurrencyToken: token }); setPairs(saved.map(x => ({ leaveTypeAId: x.leaveTypeAId, leaveTypeBId: x.leaveTypeBId, relation: x.relation }))); onChanged?.(); onNotice('Clubbing Rules saved.') } catch (caught) { setError(caught instanceof ApiError ? caught : new ApiError('Unable to save Clubbing Rules.')) } finally { setSaving(false) } }
  return <Card title="11. Leave Clubbing" subtitle="Configure symmetric Leave Type pairs. Each pair is stored once; exact request adjacency evaluation is deferred.">{loading ? <Spinner label="Loading Clubbing Rules" /> : <><div className="lifecycle-notice"><span>Each configured pair applies in both directions and represents a clubbing restriction.</span>{!editable ? <><Badge>{version.status}</Badge><span>Historical Clubbing Rules are read-only.</span></> : null}</div>{error ? <div className="notice notice-error" role="alert">{error.message}{error.isConflict ? ' Reload the latest version before saving.' : ''}</div> : null}<div className="form-stack" aria-label="Leave Clubbing rules">{pairs.length === 0 ? <p className="muted">No Clubbing Rules configured. Leave Types follow the default behavior.</p> : pairs.map((pair, index) => <div className="form-grid" key={`${index}-${pair.leaveTypeAId}-${pair.leaveTypeBId}`}><label className="field"><span>Leave Type 1</span><select className="input" value={pair.leaveTypeAId} disabled={!editable} onChange={e => update(index, 'leaveTypeAId', e.target.value)}><option value="">Select Leave Type</option>{leaveTypes.map(x => <option key={x.id} value={x.id}>{names.get(x.id)}</option>)}</select></label><span className="field-help" aria-label="symmetric pair">↔</span><label className="field"><span>Leave Type 2</span><select className="input" value={pair.leaveTypeBId} disabled={!editable} onChange={e => update(index, 'leaveTypeBId', e.target.value)}><option value="">Select Leave Type</option>{leaveTypes.filter(x => x.id !== pair.leaveTypeAId).map(x => <option key={x.id} value={x.id}>{names.get(x.id)}</option>)}</select></label>{editable ? <button className="button button-link" type="button" onClick={() => remove(index)} aria-label={`Remove Clubbing Rule ${index + 1}`}>Remove</button> : null}</div>)}{editable ? <div className="form-actions"><button className="button button-secondary" type="button" onClick={add}>Add Clubbing Rule</button><button className="button button-primary" type="button" disabled={saving} onClick={() => void save()}>{saving ? <Spinner size={14} label="Saving…" /> : 'Save Clubbing Rules'}</button></div> : null}</div></>}</Card>
}
