import { screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { Route, Routes } from 'react-router-dom'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { LeavePolicyEditorPage } from './LeavePolicyEditorPage.tsx'
import { Permissions } from '../../auth/permissions.ts'
import { makeUser, paged } from '../../test/fixtures.ts'
import { fail, installStubAdapter, ok, type StubAdapter } from '../../test/stubAdapter.ts'
import { renderAsUser } from '../../test/renderWith.tsx'

const policy = { id: 'policy-1', code: 'IND-CORP', name: 'India Corporate', description: 'Corporate leave policy', isActive: true, versionCount: 2, currentVersionNumber: 2, createdDate: '2027-01-01T00:00:00Z', modifiedDate: null, concurrencyToken: 'policy-token' }
const draft = { id: 'version-1', versionNumber: 1, effectiveFrom: '2027-01-01', effectiveTo: null, status: 'Draft' as const, priority: 10, leaveTypeCount: 0, applicabilityGroupCount: 0, createdDate: '2027-01-01T00:00:00Z', createdBy: 'admin', modifiedDate: null, concurrencyToken: 'version-token', allowedActions: { canEdit: true, canValidate: true, canPublish: true, canRetire: false, canCreateVersion: true } }
const published = { ...draft, id: 'version-2', versionNumber: 2, status: 'Published' as const, concurrencyToken: 'published-token' }

describe('LeavePolicyEditorPage', () => {
  let stub: StubAdapter
  beforeEach(() => { stub = installStubAdapter() })
  afterEach(() => stub.restore())
  function renderPage(permissions: string[] = [Permissions.leave.policyView], route = '/leave-management/policies/policy-1') { return renderAsUser(<Routes><Route path="/leave-management/policies/:policyId" element={<LeavePolicyEditorPage />} /></Routes>, { user: makeUser({ permissions }), route }) }
  function setup() { stub.on('get', '/api/leave-policies/policy-1/versions', () => ({ data: ok(paged([published, draft])) })); stub.on('get', '/api/leave-policies/policy-1/editor', call => { const requestedVersionId = typeof call.params.versionId === 'string' ? call.params.versionId : undefined; const currentVersion = requestedVersionId === 'version-1' ? draft : requestedVersionId === 'version-2' ? published : null; return { data: ok({ policy, currentVersion, leaveTypes: [], applicabilityGroups: [] }) } }) }
  async function selectVersion(versionId: string) { const initialSelector = await screen.findByRole('combobox', { name: 'Policy version' }); await waitFor(() => expect(initialSelector.querySelector(`option[value="${versionId}"]`)).not.toBeNull()); await userEvent.selectOptions(initialSelector, versionId); await waitFor(() => expect(screen.getByRole('combobox', { name: 'Policy version' })).toHaveValue(versionId)); await waitFor(() => expect(screen.queryByText('Loading Leave Policy')).not.toBeInTheDocument()); await waitFor(() => expect(screen.queryByText('No version selected. Create a Draft Version to begin.')).not.toBeInTheDocument()) }

  it('loads policy details and version selector', async () => { setup(); renderPage(); expect(await screen.findByRole('heading', { name: /IND-CORP/ })).toBeInTheDocument(); const selector = await screen.findByRole('combobox', { name: 'Policy version' }); expect(selector).toHaveValue(''); await waitFor(() => { expect(selector.querySelector('option[value="version-1"]')).toBeInTheDocument(); expect(selector.querySelector('option[value="version-2"]')).toBeInTheDocument() }); await selectVersion('version-1'); await waitFor(() => expect(stub.callsTo('get', '/api/leave-policies/policy-1/editor').some(call => call.params.versionId === 'version-1')).toBe(true)); expect(screen.getByText('You can view this Draft but do not have edit permission.')).toBeInTheDocument() })
  it('allows PolicyView users to inspect but not edit Draft settings', async () => { setup(); renderPage(); await selectVersion('version-1'); expect(screen.getByText('You can view this Draft but do not have edit permission.')).toBeInTheDocument(); expect(screen.queryByRole('button', { name: 'Save Draft' })).not.toBeInTheDocument(); expect(screen.queryByRole('button', { name: '+ Create Draft Version' })).not.toBeInTheDocument() })
  it('shows Published settings as read-only', async () => { setup(); renderPage([Permissions.leave.policyView], '/leave-management/policies/policy-1?versionId=version-2'); expect(await screen.findByText('This version is Published and cannot be edited.')).toBeInTheDocument(); expect(screen.queryByRole('button', { name: 'Save Draft' })).not.toBeInTheDocument() })
  it('shows Retired settings as read-only', async () => { const retired = { ...draft, status: 'Retired' as const }; stub.on('get', '/api/leave-policies/policy-1/versions', () => ({ data: ok(paged([retired])) })); stub.on('get', '/api/leave-policies/policy-1/editor', () => ({ data: ok({ policy, currentVersion: retired, leaveTypes: [], applicabilityGroups: [] }) })); renderPage([], '/leave-management/policies/policy-1?versionId=version-1'); expect(await screen.findByText('This version is Retired and retained for history.')).toBeInTheDocument() })
  it('creates a blank Draft and selects the server-generated version', async () => { setup(); const created = { ...draft, id: 'version-3', versionNumber: 3 }; stub.on('post', '/api/leave-policies/policy-1/versions', call => ({ data: ok({ ...created, effectiveFrom: typeof call.body === 'object' && call.body && 'effectiveFrom' in call.body ? String(call.body.effectiveFrom) : created.effectiveFrom }) })); renderPage([Permissions.leave.policyManage]); await selectVersion('version-1'); await userEvent.click(screen.getByRole('button', { name: '+ Create Draft Version' })); await waitFor(() => expect(stub.callsTo('post', '/api/leave-policies/policy-1/versions')[0]?.body).toMatchObject({ priority: 0, copyFromVersionId: null })); expect(await screen.findByText('Draft version 3 created.')).toBeInTheDocument() })
  it('edits and saves Draft dates and priority with its token', async () => { setup(); stub.on('put', '/api/leave-policies/policy-1/versions/version-1', () => ({ data: ok({ ...draft, priority: 12 }) })); renderPage([Permissions.leave.policyManage], '/leave-management/policies/policy-1?versionId=version-1'); await screen.findByLabelText(/^Priority/); await userEvent.clear(screen.getByLabelText(/Effective From/)); await userEvent.type(screen.getByLabelText(/Effective From/), '2027-02-01'); await userEvent.clear(screen.getByLabelText(/^Priority/)); await userEvent.type(screen.getByLabelText(/^Priority/), '12'); await userEvent.click(screen.getByRole('button', { name: 'Save Draft' })); await waitFor(() => expect(stub.callsTo('put', '/api/leave-policies/policy-1/versions/version-1')[0]?.body).toMatchObject({ effectiveFrom: '2027-02-01', priority: 12, concurrencyToken: 'version-token' })) })
  it('rejects an invalid effective range without submitting', async () => { setup(); renderPage([Permissions.leave.policyManage]); await selectVersion('version-1'); await userEvent.clear(screen.getByLabelText(/Effective To/)); await userEvent.type(screen.getByLabelText(/Effective To/), '2026-12-31'); await userEvent.click(screen.getByRole('button', { name: 'Save Draft' })); expect(await screen.findByText('Effective From must be on or before Effective To.')).toBeInTheDocument(); expect(stub.callsTo('put', '/api/leave-policies/policy-1/versions/version-1')).toHaveLength(0) })
  it('preserves Draft form on a 409 conflict', async () => { setup(); stub.on('put', '/api/leave-policies/policy-1/versions/version-1', () => ({ status: 409, data: fail('Configuration changed by another user. Reload before saving.') })); renderPage([Permissions.leave.policyManage]); await selectVersion('version-1'); await userEvent.click(screen.getByRole('button', { name: 'Save Draft' })); expect(await screen.findByText(/changed by another user/)).toBeInTheDocument(); expect(screen.getByDisplayValue('2027-01-01')).toBeInTheDocument() })
  it('switches versions without mutating configuration', async () => { setup(); renderPage([Permissions.leave.policyView]); await selectVersion('version-1'); await selectVersion('version-2'); expect(await screen.findByText('This version is Published and cannot be edited.')).toBeInTheDocument(); expect(stub.callsTo('put', '/api/leave-policies/policy-1/versions/version-1')).toHaveLength(0) })
})
