import { fireEvent, screen, waitFor } from '@testing-library/react'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { renderAsUser } from '../../test/renderWith.tsx'
import { ExitInterviewConfigurationPage } from './ExitInterviewConfigurationPage.tsx'
import { ExitInterviewHrDetailPage } from './ExitInterviewHrDetailPage.tsx'
import { ExitInterviewHrInboxPage } from './ExitInterviewHrInboxPage.tsx'
import { MyExitInterviewPage } from './MyExitInterviewPage.tsx'

const mocks = vi.hoisted(() => ({ mine: vi.fn(), save: vi.fn(), submit: vi.fn(), templates: vi.fn(), createTemplate: vi.fn(), createVersion: vi.fn(), publish: vi.fn(), inbox: vi.fn(), detail: vi.fn(), note: vi.fn(), complete: vi.fn(), reopen: vi.fn(), start: vi.fn() }))
vi.mock('../../api/separation.ts', () => ({ getMyExitInterview: mocks.mine, saveMyExitInterview: mocks.save, submitMyExitInterview: mocks.submit, getExitInterviewTemplates: mocks.templates, createExitInterviewTemplate: mocks.createTemplate, createExitInterviewVersion: mocks.createVersion, publishExitInterviewVersion: mocks.publish, getExitInterviewInbox: mocks.inbox, getHrExitInterview: mocks.detail, addExitInterviewHrNote: mocks.note, completeHrExitInterview: mocks.complete, reopenHrExitInterview: mocks.reopen, startHrExitInterview: mocks.start }))
vi.mock('react-router-dom', async () => { const actual = await vi.importActual<typeof import('react-router-dom')>('react-router-dom'); return { ...actual, useParams: () => ({ separationId: 's-1' }) } })

const employee = { id: 'i-1', employeeSeparationId: 's-1', status: 'EmployeeInProgress', assignedAtUtc: '2026-09-24T00:00:00Z', questions: [{ id: 'q-1', code: 'Q1', questionText: 'Why are you leaving?', questionType: 'LongText', sequence: 1, isRequired: true, allowsComment: true, options: [] }], responses: [] }
const hr = { ...employee, employeeId: 'e-1', employeeCode: 'EMP-1', employeeName: 'Nadia Farrell', separationReason: 'Resignation', approvedLastWorkingDate: '2026-10-02', rehireRecommendation: 'NotAssessed', confidentialNotes: [] }
beforeEach(() => { vi.clearAllMocks(); mocks.mine.mockResolvedValue(employee); mocks.save.mockResolvedValue(employee); mocks.submit.mockResolvedValue({ ...employee, status: 'EmployeeSubmitted' }); mocks.templates.mockResolvedValue([{ id: 't-1', code: 'EXIT', name: 'Exit', isActive: true, effectiveFrom: '2026-01-01', versions: [{ id: 'v-1', templateId: 't-1', versionNumber: 1, effectiveFrom: '2026-01-01', status: 'Draft', questions: [] }] }]); mocks.createTemplate.mockResolvedValue({ id: 't-2' }); mocks.createVersion.mockResolvedValue({ id: 'v-2' }); mocks.publish.mockResolvedValue({}); mocks.inbox.mockResolvedValue({ page: 1, pageSize: 25, totalCount: 1, items: [{ id: 'i-1', employeeSeparationId: 's-1', employeeId: 'e-1', employeeCode: 'EMP-1', employeeName: 'Nadia Farrell', separationReason: 'Resignation', approvedLastWorkingDate: '2026-10-02', status: 'EmployeeSubmitted', assignedAtUtc: '2026-09-24T00:00:00Z' }] }); mocks.detail.mockResolvedValue(hr); mocks.note.mockResolvedValue({ ...hr, confidentialNotes: ['Private observation'] }); mocks.complete.mockResolvedValue({ ...hr, status: 'Completed' }); mocks.reopen.mockResolvedValue({ ...hr, status: 'Reopened' }); mocks.start.mockResolvedValue({ ...hr, status: 'HrInProgress' }); window.confirm = vi.fn(() => true) })

describe('Phase 8E UI', () => {
  it('renders employee questionnaire and saves a draft without confidential fields', async () => { renderAsUser(<MyExitInterviewPage />); expect(await screen.findByText(/Why are you leaving/)).toBeInTheDocument(); expect(screen.queryByText(/confidential/i)).not.toBeInTheDocument(); fireEvent.change(screen.getByLabelText(/Why are you leaving/), { target: { value: 'New opportunity' } }); fireEvent.click(screen.getByRole('button', { name: 'Save draft' })); await waitFor(() => expect(mocks.save).toHaveBeenCalled()) })
  it('renders HR inbox with server-side page query and open action', async () => { renderAsUser(<ExitInterviewHrInboxPage />); expect(await screen.findByText('Nadia Farrell')).toBeInTheDocument(); expect(mocks.inbox).toHaveBeenCalledWith(expect.objectContaining({ page: 1, pageSize: 25 })); expect(screen.getByRole('link', { name: 'Open interview' })).toHaveAttribute('href', '/separation/hr-exit-interviews/s-1') })
  it('renders confidential notes and recommendation controls in HR detail', async () => { renderAsUser(<ExitInterviewHrDetailPage />); expect(await screen.findByText('Confidential — HR Only')).toBeInTheDocument(); expect(screen.getByText(/not final rehire eligibility/i)).toBeInTheDocument(); fireEvent.change(screen.getByLabelText('Confidential HR note'), { target: { value: 'Keep private' } }); fireEvent.click(screen.getByRole('button', { name: 'Save confidential note' })); await waitFor(() => expect(mocks.note).toHaveBeenCalledWith('s-1', 'Keep private')) })
  it('renders configuration question type and publishes a draft version', async () => { renderAsUser(<ExitInterviewConfigurationPage />); expect(await screen.findByText(/Version 1: Draft/)).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Publish' })); await waitFor(() => expect(mocks.publish).toHaveBeenCalledWith('v-1')) })
})
