import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { addExitInterviewHrNote, completeHrExitInterview, getHrExitInterview, reopenHrExitInterview, startHrExitInterview, type ExitInterviewHr } from '../../api/separation.ts'

export function ExitInterviewHrDetailPage() {
  const { separationId = '' } = useParams()
  const [interview, setInterview] = useState<ExitInterviewHr | null>(null)
  const [note, setNote] = useState('')
  const [recommendation, setRecommendation] = useState('NotAssessed')
  const [recommendationReason, setRecommendationReason] = useState('')
  const [completionReason, setCompletionReason] = useState('')
  const [nonParticipation, setNonParticipation] = useState(false)
  const [message, setMessage] = useState('')
  useEffect(() => { void getHrExitInterview(separationId).then(value => { setInterview(value); setRecommendation(value.rehireRecommendation); setRecommendationReason(value.rehireRecommendationReason ?? '') }).catch(value => setMessage(value instanceof Error ? value.message : 'Unable to load interview.')) }, [separationId])
  if (!interview) return <section><h1>HR exit interview</h1><p role={message ? 'alert' : undefined}>{message || 'Loading…'}</p></section>
  const refresh = (value: Promise<ExitInterviewHr>, success: string) => void value.then(next => { setInterview(next); setMessage(success) }).catch(error => setMessage(error instanceof Error ? error.message : 'Operation failed.'))
  const complete = () => { if (!window.confirm('Complete this exit interview?')) return; refresh(completeHrExitInterview(separationId, { rehireRecommendation: recommendation, rehireRecommendationReason: recommendationReason, completedWithoutEmployeeResponse: nonParticipation, completionReason }), 'Interview completed.') }
  return <section><h1>HR exit interview</h1><p><strong>{interview.employeeName}</strong> ({interview.employeeCode})</p><p>Reason: {interview.separationReason || '—'} · Approved LWD: {interview.approvedLastWorkingDate || '—'} · Status: {interview.status}</p>{message && <p role="status">{message}</p>}<h2>Employee responses</h2>{interview.questions.filter(question => !question.isHrOnly).map(question => <div key={question.id}><strong>{question.questionText}</strong><p>{JSON.stringify(interview.responses.find(response => response.questionId === question.id) ?? 'No response')}</p></div>)}<h2>Confidential — HR Only</h2><textarea aria-label="Confidential HR note" value={note} onChange={event => setNote(event.target.value)} placeholder="Add confidential observation" /><button type="button" onClick={() => { refresh(addExitInterviewHrNote(separationId, note), 'Confidential note saved.'); setNote('') }}>Save confidential note</button>{interview.confidentialNotes.map((value, index) => <p key={`${index}-${value}`}>{value}</p>)}<h2>Exit Interview Recommendation</h2><p>This is an exit interview recommendation, not final rehire eligibility.</p><select aria-label="Rehire recommendation" value={recommendation} onChange={event => setRecommendation(event.target.value)}><option>Recommended</option><option>NotRecommended</option><option>Conditional</option><option>NotAssessed</option></select><textarea aria-label="Recommendation reason" value={recommendationReason} onChange={event => setRecommendationReason(event.target.value)} placeholder="Recommendation reason" />{interview.status === 'Completed' || interview.status === 'CompletedWithoutEmployeeResponse' ? <><h2>Reopen</h2><input aria-label="Reopen reason" value={completionReason} onChange={event => setCompletionReason(event.target.value)} /><button type="button" onClick={() => refresh(reopenHrExitInterview(separationId, completionReason), 'Interview reopened.')}>Reopen</button></> : <><button type="button" onClick={() => refresh(startHrExitInterview(separationId), 'HR interview started.')}>Start HR interview</button><label><input type="checkbox" checked={nonParticipation} onChange={event => setNonParticipation(event.target.checked)} /> Complete without employee response</label>{nonParticipation && <input aria-label="Non-participation reason" value={completionReason} onChange={event => setCompletionReason(event.target.value)} placeholder="Required reason" />}<button type="button" onClick={complete}>Complete interview</button></>}</section>
}
