import { useEffect, useState } from 'react'
import { createExitInterviewTemplate, createExitInterviewVersion, getExitInterviewTemplates, publishExitInterviewVersion, type ExitInterviewTemplate } from '../../api/separation.ts'

const types = ['SingleChoice', 'MultiChoice', 'Rating', 'YesNo', 'ShortText', 'LongText', 'Number', 'Date']
export function ExitInterviewConfigurationPage() {
  const [templates, setTemplates] = useState<ExitInterviewTemplate[]>([])
  const [code, setCode] = useState('EXIT-DEFAULT'); const [name, setName] = useState('Exit interview'); const [questionText, setQuestionText] = useState('What influenced your decision to leave?'); const [questionType, setQuestionType] = useState('LongText'); const [message, setMessage] = useState('')
  const load = () => void getExitInterviewTemplates().then(setTemplates).catch(error => setMessage(error instanceof Error ? error.message : 'Unable to load templates.'))
  useEffect(load, [])
  const create = async () => { try { const template = await createExitInterviewTemplate({ code, name, effectiveFrom: new Date().toISOString().slice(0, 10), isEmployeeSurveyEnabled: true, isHrInterviewEnabled: true }); await createExitInterviewVersion(template.id, { versionNumber: 1, effectiveFrom: new Date().toISOString().slice(0, 10), questions: [{ code: 'Q1', questionText, questionType, sequence: 1, isRequired: true, isEmployeeVisible: true, isHrOnly: false, allowsComment: true, minValue: questionType === 'Rating' ? 1 : null, maxValue: questionType === 'Rating' ? 5 : null }] }); setMessage('Draft template and version created.'); load() } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to create template.') } }
  return <section><h1>Exit interview configuration</h1><p>Published versions are immutable. Create a new draft version for changes.</p><label>Code <input value={code} onChange={event => setCode(event.target.value)} /></label> <label>Name <input value={name} onChange={event => setName(event.target.value)} /></label><label>Question <input value={questionText} onChange={event => setQuestionText(event.target.value)} /></label><label>Type <select value={questionType} onChange={event => setQuestionType(event.target.value)}>{types.map(type => <option key={type}>{type}</option>)}</select></label><button type="button" onClick={() => void create()}>Create draft template/version</button>{message && <p role="status">{message}</p>}<h2>Templates</h2>{templates.map(template => <article key={template.id}><h3>{template.name} ({template.code})</h3><p>Effective {template.effectiveFrom} · {template.isActive ? 'Active' : 'Inactive'}</p>{template.versions.map(version => <p key={version.id}>Version {version.versionNumber}: {version.status} ({version.questions.length} questions) {version.status === 'Draft' && <button type="button" onClick={() => { void publishExitInterviewVersion(version.id).then(load) }}>Publish</button>}</p>)}</article>)}</section>
}
