import { useEffect, useState } from 'react'
import { addSeparationDocumentTemplateVersion, createSeparationDocumentTemplate, generateSeparationDocument, getSeparationDocumentDashboard, getSeparationDocumentTemplates, type SeparationDocumentTemplate, type SeparationDocumentType, type SeparationGeneratedDocument, approveSeparationDocument, issueSeparationDocument, downloadSeparationDocument, publishSeparationDocumentTemplateVersion, previewSeparationDocumentTemplateVersion } from '../../api/separationDocuments.ts'

const types: SeparationDocumentType[] = ['RelievingLetter', 'ExperienceLetter', 'ServiceCertificate', 'CustomSeparationDocument']
export function SeparationDocumentsPage() {
  const [templates, setTemplates] = useState<SeparationDocumentTemplate[]>([]); const [rows, setRows] = useState<SeparationGeneratedDocument[]>([]); const [message, setMessage] = useState(''); const [template, setTemplate] = useState({ code: '', name: '', documentType: 'RelievingLetter' as SeparationDocumentType, effectiveFrom: new Date().toISOString().slice(0, 10), requiresApproval: true }); const [versionBody, setVersionBody] = useState('To whom it may concern,\n\n{{Employee.FullName}} ({{Employee.EmployeeCode}}) worked as {{Employment.LastDesignation}} in {{Employment.LastDepartment}} until {{Separation.ApprovedLastWorkingDate}}.\n\n{{Organization.Name}}'); const [separationId, setSeparationId] = useState('')
  const load = () => { void Promise.all([getSeparationDocumentTemplates(), getSeparationDocumentDashboard({ page: 1, pageSize: 50 })]).then(([t, d]) => { setTemplates(t); setRows(d.items) }).catch(error => setMessage(error instanceof Error ? error.message : 'Unable to load documents.')) }
  useEffect(load, [])
  const create = () => void createSeparationDocumentTemplate(template).then(item => { setTemplates(value => [...value, item]); setMessage('Template created. Add and publish a version before generating.') }).catch(error => setMessage(error instanceof Error ? error.message : 'Template creation failed.'))
  const addVersion = (item: SeparationDocumentTemplate) => void addSeparationDocumentTemplateVersion(item.id, { effectiveFrom: template.effectiveFrom, bodyTemplate: versionBody }).then(updated => { setTemplates(value => value.map(x => x.id === updated.id ? updated : x)); setMessage('Draft version added. Publish it from the template workflow.') }).catch(error => setMessage(error instanceof Error ? error.message : 'Version creation failed.'))
  const publish = (item: SeparationDocumentTemplate, versionId: string) => void publishSeparationDocumentTemplateVersion(item.id, versionId, item.concurrencyVersion).then(updated => { setTemplates(value => value.map(x => x.id === updated.id ? updated : x)); setMessage('Published version is now read-only.') }).catch(error => setMessage(error instanceof Error ? error.message : 'Publish failed.'))
  const preview = (versionId: string) => void previewSeparationDocumentTemplateVersion(versionId).then(item => { const bytes = Uint8Array.from(atob(item.contentBase64), character => character.charCodeAt(0)); const url = URL.createObjectURL(new Blob([bytes as unknown as BlobPart], { type: item.contentType })); const link = document.createElement('a'); link.href = url; link.target = '_blank'; link.rel = 'noreferrer'; link.click(); URL.revokeObjectURL(url); setMessage('Preview generated; no official document was created.') }).catch(error => setMessage(error instanceof Error ? error.message : 'Preview failed.'))
  void publish; void preview
  const generate = () => void generateSeparationDocument(separationId, { documentType: template.documentType }).then(() => { setMessage('Document generated.'); load() }).catch(error => setMessage(error instanceof Error ? error.message : 'Generation failed.'))
  const act = (operation: Promise<unknown>) => void operation.then(() => { setMessage('Document state updated.'); load() }).catch(error => setMessage(error instanceof Error ? error.message : 'Document operation failed.'))
  return <section className="page-shell"><h1>Separation documents</h1><p>Configure safe, versioned templates and manage immutable issued documents. Document generation does not execute employment closure.</p>{message && <p role="status">{message}</p>}<div className="form-grid"><label>Template code<input value={template.code} onChange={e => setTemplate({ ...template, code: e.target.value })} /></label><label>Template name<input value={template.name} onChange={e => setTemplate({ ...template, name: e.target.value })} /></label><label>Document type<select value={template.documentType} onChange={e => setTemplate({ ...template, documentType: e.target.value as SeparationDocumentType })}>{types.map(type => <option key={type}>{type}</option>)}</select></label><label>Effective from<input type="date" value={template.effectiveFrom} onChange={e => setTemplate({ ...template, effectiveFrom: e.target.value })} /></label><label className="form-span-full">Template body<textarea rows={8} value={versionBody} onChange={e => setVersionBody(e.target.value)} /></label></div><button type="button" onClick={create}>Create template</button><h2>Templates</h2><ul>{templates.map(item => <li key={item.id}><strong>{item.code}</strong> — {item.name} ({item.documentType}) <button type="button" onClick={() => addVersion(item)}>Add draft version</button><span> {item.versions.length} version(s)</span></li>)}</ul><h2>Generate</h2><label>Separation ID<input value={separationId} onChange={e => setSeparationId(e.target.value)} /></label> <button type="button" disabled={!separationId} onClick={generate}>Generate official document</button><h2>Generated documents</h2><table><thead><tr><th>Employee</th><th>Type</th><th>Number</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td>{row.employeeName} ({row.employeeCode || '—'})</td><td>{row.documentType}</td><td>{row.documentNumber}</td><td>{row.status}</td><td>{row.status === 'PendingApproval' && <button type="button" onClick={() => act(approveSeparationDocument(row.id, 1))}>Approve</button>}{row.status === 'Approved' && <button type="button" onClick={() => act(issueSeparationDocument(row.id, 1))}>Issue</button>}{(row.status === 'Issued' || row.status === 'Approved') && <button type="button" onClick={() => void downloadSeparationDocument(row.id)}>Download</button>}</td></tr>)}</tbody></table></section>
}

export function MySeparationDocumentsPage() {
  const [rows, setRows] = useState<SeparationGeneratedDocument[]>([]); const [separationId, setSeparationId] = useState(''); const [message, setMessage] = useState(''); const load = () => separationId && void import('../../api/separationDocuments.ts').then(api => api.getMySeparationDocuments(separationId)).then(setRows).catch(error => setMessage(error instanceof Error ? error.message : 'Unable to load documents.'))
  return <section className="page-shell"><h1>My separation documents</h1><label>Separation ID<input value={separationId} onChange={e => setSeparationId(e.target.value)} /></label> <button type="button" onClick={load}>Load documents</button>{message && <p role="alert">{message}</p>}<ul>{rows.map(row => <li key={row.id}>{row.documentType} — {row.documentNumber} — {row.status} {row.status !== 'Cancelled' && <button type="button" onClick={() => void downloadSeparationDocument(row.id, true)}>Download</button>}</li>)}</ul></section>
}
