import { useEffect, useState } from 'react'
import { addSeparationDocumentTemplateVersion, createSeparationDocumentTemplate, getSeparationDocumentTemplates, previewSeparationDocumentTemplateVersion, publishSeparationDocumentTemplateVersion, type SeparationDocumentTemplate, type SeparationDocumentType } from '../../api/separationDocuments.ts'

const types: SeparationDocumentType[] = ['RelievingLetter', 'ExperienceLetter', 'ServiceCertificate', 'CustomSeparationDocument']
const fields = ['Employee.FullName', 'Employee.EmployeeCode', 'Employee.DateOfJoining', 'Employment.LastDesignation', 'Employment.LastDepartment', 'Separation.ApprovedLastWorkingDate', 'Organization.Name', 'Document.Number', 'Document.IssueDate']

export function SeparationDocumentTemplateConfigurationPage() {
  const [templates, setTemplates] = useState<SeparationDocumentTemplate[]>([])
  const [selected, setSelected] = useState<SeparationDocumentTemplate | null>(null)
  const [body, setBody] = useState('{{Employee.FullName}}\n{{Employment.LastDesignation}}\n{{Separation.ApprovedLastWorkingDate}}\n{{Organization.Name}}')
  const [form, setForm] = useState({ code: '', name: '', documentType: 'RelievingLetter' as SeparationDocumentType, effectiveFrom: new Date().toISOString().slice(0, 10), requiresApproval: true })
  const [message, setMessage] = useState('')
  const load = () => { void getSeparationDocumentTemplates().then(setTemplates).catch(error => setMessage(error instanceof Error ? error.message : 'Unable to load templates.')) }
  useEffect(load, [])
  const create = () => void createSeparationDocumentTemplate(form).then(item => { setTemplates(value => [...value, item]); setSelected(item); setMessage('Template created.') }).catch(error => setMessage(error instanceof Error ? error.message : 'Template creation failed.'))
  const addDraft = () => { if (!selected) return; void addSeparationDocumentTemplateVersion(selected.id, { effectiveFrom: form.effectiveFrom, bodyTemplate: body }).then(item => { setTemplates(value => value.map(x => x.id === item.id ? item : x)); setSelected(item); setMessage('Draft version saved.') }).catch(error => setMessage(error instanceof Error ? error.message : 'Draft save failed.')) }
  const publish = (versionId: string) => { if (!selected) return; void publishSeparationDocumentTemplateVersion(selected.id, versionId, selected.concurrencyVersion).then(item => { setTemplates(value => value.map(x => x.id === item.id ? item : x)); setSelected(item); setMessage('Published versions are read-only.') }).catch(error => setMessage(error instanceof Error ? error.message : 'Publish failed.')) }
  const preview = (versionId: string) => void previewSeparationDocumentTemplateVersion(versionId).then(item => { setMessage('NON-OFFICIAL PREVIEW generated; no number or official document was created.'); const bytes = Uint8Array.from(atob(item.contentBase64), character => character.charCodeAt(0)); const url = URL.createObjectURL(new Blob([bytes as unknown as BlobPart], { type: item.contentType })); window.open(url, '_blank', 'noopener,noreferrer'); setTimeout(() => URL.revokeObjectURL(url), 1000) }).catch(error => setMessage(error instanceof Error ? error.message : 'Preview failed.'))
  const insert = (field: string) => setBody(value => `${value}{{${field}}}`)
  return <section className="page-shell"><h1>Separation document template configuration</h1><p>Published versions cannot be edited. Preview output is always marked NON-OFFICIAL PREVIEW.</p>{message && <p role="status">{message}</p>}<div className="form-grid"><label>Code<input value={form.code} onChange={event => setForm({ ...form, code: event.target.value })} /></label><label>Name<input value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} /></label><label>Document type<select value={form.documentType} onChange={event => setForm({ ...form, documentType: event.target.value as SeparationDocumentType })}>{types.map(type => <option key={type}>{type}</option>)}</select></label><label>Effective from<input type="date" value={form.effectiveFrom} onChange={event => setForm({ ...form, effectiveFrom: event.target.value })} /></label></div><button type="button" onClick={create}>Create template</button><h2>Draft editor</h2><div>{fields.map(field => <button type="button" key={field} onClick={() => insert(field)}>{field}</button>)}</div><textarea aria-label="Template body" rows={10} value={body} onChange={event => setBody(event.target.value)} /><button type="button" disabled={!selected} onClick={addDraft}>Save draft version</button><h2>Templates</h2><ul>{templates.map(template => <li key={template.id}><button type="button" onClick={() => setSelected(template)}>{template.code} — {template.name}</button>{selected?.id === template.id && <ul>{template.versions.map(version => <li key={version.id}>v{version.versionNumber} — {version.status} <button type="button" onClick={() => preview(version.id)}>Preview</button>{version.status === 'Draft' && <button type="button" onClick={() => publish(version.id)}>Publish</button>}</li>)}</ul>}</li>)}</ul></section>
}
