import { useState, type ChangeEvent } from 'react'
import { ApiError } from '../api/errors.ts'
import { confirmMasterImport, downloadMasterTemplate, validateMasterImport, type MasterImportMode, type MasterImportPreview } from '../api/masterImport.ts'
import { Notice } from './Notice.tsx'

interface Props { kind: string; onCompleted: () => Promise<void> }

export function MasterBulkImport({ kind, onCompleted }: Props) {
  const [open, setOpen] = useState(false); const [mode, setMode] = useState<MasterImportMode>('CreateOnly'); const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<MasterImportPreview | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [result, setResult] = useState<string | null>(null)
  async function template() { setError(null); try { const blob = await downloadMasterTemplate(kind); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `${kind}-template.csv`; anchor.click(); URL.revokeObjectURL(url) } catch { setError('Unable to download the template.') } }
  function select(event: ChangeEvent<HTMLInputElement>) { setFile(event.target.files?.[0] ?? null); setPreview(null); setResult(null); setError(null) }
  async function validate() { if (!file) { setError('Select a CSV file first.'); return } setBusy(true); setError(null); setPreview(null); try { setPreview(await validateMasterImport(kind, file, mode)) } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Unable to validate this file.') } finally { setBusy(false) } }
  async function confirm() { if (!file || !preview || preview.errorRows > 0) return; setBusy(true); setError(null); try { const done = await confirmMasterImport(kind, mode, file.name, preview.inputRows); setResult(`Import completed: ${done.createdRows} created, ${done.updatedRows} updated.`); await onCompleted() } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Import failed. No changes were applied.') } finally { setBusy(false) } }
  return <><button className="button button-secondary" type="button" onClick={() => { setOpen(true); setError(null); setResult(null) }}>Bulk upload</button>{open ? <div className="import-backdrop" role="presentation"><section className="import-dialog" role="dialog" aria-modal="true" aria-labelledby="master-import-title"><header><div><h2 id="master-import-title">Bulk upload: {kind.replaceAll('-', ' ')}</h2><p>Validate every row before importing master records.</p></div><button className="master-editor-close" type="button" aria-label="Close bulk upload" onClick={() => !busy && setOpen(false)}>×</button></header>{error ? <Notice tone="error">{error}</Notice> : null}{result ? <Notice tone="success">{result}</Notice> : null}<ol className="import-steps"><li>Download template</li><li>Select and validate</li><li>Review preview</li><li>Confirm import</li></ol><p className="field-help">Accepted format: UTF-8 CSV. Maximum 5 MB and 5,000 rows. Codes are unique within this tenant. Parents are resolved by code and are never created automatically.</p><div className="import-actions"><button className="button button-secondary" type="button" onClick={() => void template()}>Download template</button><label className="button button-secondary">Select CSV<input hidden type="file" accept=".csv,text/csv" onChange={event => select(event)} /></label><select className="input select" value={mode} onChange={event => { setMode(event.target.value as MasterImportMode); setPreview(null) }}><option value="CreateOnly">Create only</option><option value="CreateOrUpdate">Create or update</option></select><button className="button button-primary" type="button" disabled={busy || !file} onClick={() => void validate()}>Validate file</button></div>{busy ? <p className="muted">Validating or importing…</p> : null}{preview ? <><div className="import-summary"><span>Total {preview.totalRows}</span><span>Valid {preview.validRows}</span><span>New {preview.newRows}</span><span>Updates {preview.updateRows}</span><span>Errors {preview.errorRows}</span></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Row</th><th>Code</th><th>Name</th><th>Parent</th><th>Action</th><th>Message</th></tr></thead><tbody>{preview.rows.map(row => <tr key={row.rowNumber}><td>{row.rowNumber}</td><td>{row.code}</td><td>{row.name}</td><td>{row.parentCode ?? '—'}</td><td>{row.action}</td><td>{row.errors.join('; ') || 'Ready'}</td></tr>)}</tbody></table></div></> : null}<footer><button className="button button-secondary" type="button" disabled={busy} onClick={() => setOpen(false)}>Close</button><button className="button button-primary" type="button" disabled={busy || !preview || preview.errorRows > 0} onClick={() => void confirm()}>Confirm import</button></footer></section></div> : null}</>
}
