import { useEffect, useState } from 'react'
import { ApiError } from '../../api/errors.ts'
import { createPattern, listPatterns, listShifts, type PatternRequest, type Shift } from '../../api/attendance.ts'
import { Card } from '../../components/Card.tsx'
import { Notice } from '../../components/Notice.tsx'
import { PageHeader } from '../../components/PageHeader.tsx'

export function ShiftPatternsPage() {
  const [shifts, setShifts] = useState<Shift[]>([])
  const [patterns, setPatterns] = useState<Awaited<ReturnType<typeof listPatterns>>>([])
  const [error, setError] = useState(''); const [notice, setNotice] = useState('')
  const [form, setForm] = useState<PatternRequest>({ code: '', name: '', cycleLengthDays: 7, isActive: true, effectiveFrom: new Date().toISOString().slice(0, 10), effectiveTo: null, days: [] })
  useEffect(() => { void Promise.all([listShifts(), listPatterns()]).then(([s, p]) => { setShifts(s); setPatterns(p); setForm(f => f.days.length ? f : { ...f, days: Array.from({ length: f.cycleLengthDays }, (_, i) => ({ sequenceDay: i + 1, dayType: 'Shift', shiftId: s[0]?.id ?? null })) }) }).catch(e => setError(e instanceof ApiError ? e.message : 'Unable to load patterns.')) }, [])
  function resize(value: number) { const n = Math.max(1, Math.min(366, value || 1)); setForm(f => ({ ...f, cycleLengthDays: n, days: Array.from({ length: n }, (_, i) => f.days.find(d => d.sequenceDay === i + 1) ?? { sequenceDay: i + 1, dayType: 'Shift', shiftId: shifts[0]?.id ?? null }) })) }
  async function save() { try { await createPattern(form); setNotice('Shift Pattern created.'); setPatterns(await listPatterns()) } catch (e) { setError(e instanceof ApiError ? e.message : 'Unable to save Shift Pattern.') } }
  return <div className="leave-admin-page"><PageHeader title="Shift Patterns" subtitle="Define reusable N-day cycles. Preview dates are calculated from the effective anchor and are not persisted." />{notice ? <Notice tone="success">{notice}</Notice> : null}{error ? <Notice tone="error">{error}</Notice> : null}<div className="form-grid"><Card title="Pattern editor"><div className="form-stack"><label className="field"><span>Pattern code</span><input className="input" value={form.code} onChange={e => setForm({ ...form, code: e.target.value })} /></label><label className="field"><span>Pattern name</span><input className="input" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><div className="form-grid"><label className="field"><span>Cycle length (days)</span><input className="input" type="number" min="1" max="366" value={form.cycleLengthDays} onChange={e => resize(Number(e.target.value))} /></label><label className="field"><span>Anchor date</span><input className="input" type="date" value={form.effectiveFrom} onChange={e => setForm({ ...form, effectiveFrom: e.target.value })} /></label></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Day</th><th>Type</th><th>Shift</th></tr></thead><tbody>{form.days.map((day, i) => <tr key={day.sequenceDay}><td>{day.sequenceDay}</td><td><select className="input" value={day.dayType} onChange={e => setForm({ ...form, days: form.days.map((d, j) => j === i ? { ...d, dayType: e.target.value, shiftId: e.target.value === 'WeeklyOff' ? null : d.shiftId } : d) })}><option value="Shift">Shift</option><option value="WeeklyOff">Weekly Off</option></select></td><td><select className="input" disabled={day.dayType === 'WeeklyOff'} value={day.shiftId ?? ''} onChange={e => setForm({ ...form, days: form.days.map((d, j) => j === i ? { ...d, shiftId: e.target.value || null } : d) })}><option value="">Select Shift</option>{shifts.map(s => <option key={s.id} value={s.id}>{s.shiftCode} - {s.shiftName}</option>)}</select></td></tr>)}</tbody></table></div><button className="button button-primary" type="button" onClick={() => { void save() }}>Create Pattern</button></div></Card><Card title="Configured patterns"><div className="table-wrap"><table className="data-table"><thead><tr><th>Code</th><th>Name</th><th>Cycle</th><th>Anchor</th></tr></thead><tbody>{patterns.map(p => <tr key={p.id}><td>{p.code}</td><td>{p.name}</td><td>{p.cycleLengthDays} days</td><td>{p.effectiveFrom}</td></tr>)}</tbody></table></div></Card></div></div>
}
