// <auto-generated />
using HRMS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable
namespace HRMS.Infrastructure.Persistence.Migrations;
[DbContext(typeof(HrmsDbContext))]
[Migration("20260904133000_LeavePolicyClubbingRules")]
partial class LeavePolicyClubbingRules
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder.HasAnnotation("ProductVersion", "10.0.11"); modelBuilder.Entity("HRMS.Domain.Entities.LeavePolicyClubbingRule", b => { b.Property<Guid>("Id"); b.Property<Guid>("TenantId"); b.Property<Guid>("LeavePolicyVersionId"); b.Property<Guid>("LowerLeavePolicyRuleId"); b.Property<Guid>("HigherLeavePolicyRuleId"); b.Property<int>("Relation"); b.Property<DateTime>("CreatedDate"); b.Property<DateTime?>("ModifiedDate"); b.HasKey("Id"); b.HasAlternateKey("TenantId", "Id"); b.HasIndex("TenantId", "LeavePolicyVersionId", "LowerLeavePolicyRuleId", "HigherLeavePolicyRuleId").IsUnique(); b.ToTable("LeavePolicyClubbingRules"); });
    }
}
