// <auto-generated />
using System;
using HRMS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HRMS.Infrastructure.Persistence.Migrations;

[DbContext(typeof(HrmsDbContext))]
[Migration("20260904111427_LeavePolicyEntitlementRules")]
partial class LeavePolicyEntitlementRules
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder.HasAnnotation("ProductVersion", "10.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);
        modelBuilder.Entity("HRMS.Domain.Entities.LeavePolicyEntitlementRule", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
            b.Property<int>("AccrualFrequency").HasColumnType("int");
            b.Property<int?>("AccrualTiming").HasColumnType("int");
            b.Property<DateTime>("CreatedDate").HasColumnType("datetime2");
            b.Property<int>("EntitlementMode").HasColumnType("int");
            b.Property<decimal?>("EntitlementQuantity").HasPrecision(9, 3).HasColumnType("decimal(9,3)");
            b.Property<int>("EntitlementSource").HasColumnType("int");
            b.Property<Guid>("LeavePolicyRuleId").HasColumnType("uniqueidentifier");
            b.Property<DateTime?>("ModifiedDate").HasColumnType("datetime2");
            b.Property<Guid>("TenantId").HasColumnType("uniqueidentifier");
            b.HasKey("Id");
            b.HasAlternateKey("TenantId", "Id");
            b.HasIndex("TenantId", "LeavePolicyRuleId").IsUnique();
            b.ToTable("LeavePolicyEntitlementRules", (string)null);
        });
    }
}
