// <auto-generated />
using HRMS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HRMS.Infrastructure.Persistence.Migrations;

[DbContext(typeof(HrmsDbContext))]
[Migration("20260904120000_LeavePolicyRequestRules")]
partial class LeavePolicyRequestRules
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder.HasAnnotation("ProductVersion", "10.0.11");
        modelBuilder.Entity("HRMS.Domain.Entities.LeavePolicyRequestRule", b =>
        {
            b.Property<Guid>("Id"); b.Property<Guid>("TenantId"); b.Property<Guid>("LeavePolicyRuleId");
            b.Property<decimal?>("MinimumRequestQuantity").HasPrecision(9, 3); b.Property<decimal?>("MaximumRequestQuantity").HasPrecision(9, 3);
            b.Property<decimal?>("MaximumConsecutiveQuantity").HasPrecision(9, 3); b.Property<int>("MinimumAdvanceNoticeDays");
            b.Property<int>("BackdatedRequestMode"); b.Property<int?>("MaximumBackdatedDays"); b.Property<int?>("MaximumRequestsPerPeriod");
            b.Property<decimal?>("MaximumQuantityPerPeriod").HasPrecision(9, 3); b.Property<int?>("RequestLimitPeriod"); b.Property<int>("PartialDayMode");
            b.Property<DateTime>("CreatedDate"); b.Property<DateTime?>("ModifiedDate"); b.HasKey("Id"); b.HasAlternateKey("TenantId", "Id");
            b.HasIndex("TenantId", "LeavePolicyRuleId").IsUnique(); b.ToTable("LeavePolicyRequestRules");
        });
    }
}
