using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HRMS.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddVariablePayPhase7QFinal : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable("VariablePayPlans", table => new { Id = table.Column<Guid>(nullable: false), TenantId = table.Column<Guid>(nullable: false), Code = table.Column<string>(maxLength: 100, nullable: false), Name = table.Column<string>(maxLength: 200, nullable: false), Description = table.Column<string>(maxLength: 1000, nullable: true), PlanType = table.Column<int>(nullable: false), CurrencyCode = table.Column<string>(maxLength: 10, nullable: false), IsActive = table.Column<bool>(nullable: false), CreatedDate = table.Column<DateTime>(nullable: false), ModifiedDate = table.Column<DateTime>(nullable: true), ConcurrencyVersion = table.Column<int>(nullable: false, defaultValue: 1) }, constraints: table => table.PrimaryKey("PK_VariablePayPlans", x => x.Id));
            migrationBuilder.CreateTable("VariablePayNumberSequences", table => new { Id = table.Column<Guid>(nullable: false), TenantId = table.Column<Guid>(nullable: false), Year = table.Column<int>(nullable: false), NextValue = table.Column<long>(nullable: false), CreatedDate = table.Column<DateTime>(nullable: false), ModifiedDate = table.Column<DateTime>(nullable: true), ConcurrencyVersion = table.Column<int>(nullable: false, defaultValue: 1) }, constraints: table => table.PrimaryKey("PK_VariablePayNumberSequences", x => x.Id));
            migrationBuilder.CreateTable("VariablePayPlanVersions", table => new { Id = table.Column<Guid>(nullable: false), TenantId = table.Column<Guid>(nullable: false), VariablePayPlanId = table.Column<Guid>(nullable: false), EffectiveFrom = table.Column<DateOnly>(nullable: false), EffectiveTo = table.Column<DateOnly>(nullable: true), Status = table.Column<int>(nullable: false), CalculationMethod = table.Column<int>(nullable: false), SalaryBasisType = table.Column<int>(nullable: false), Percentage = table.Column<decimal>(type: "decimal(18,6)", nullable: true), FixedAmount = table.Column<decimal>(type: "decimal(18,6)", nullable: true), TargetPercentage = table.Column<decimal>(type: "decimal(18,6)", nullable: true), MinimumAmount = table.Column<decimal>(type: "decimal(18,6)", nullable: true), MaximumAmount = table.Column<decimal>(type: "decimal(18,6)", nullable: true), PerformanceMultiplierMinimum = table.Column<decimal>(type: "decimal(18,6)", nullable: true), PerformanceMultiplierMaximum = table.Column<decimal>(type: "decimal(18,6)", nullable: true), ProrationMethod = table.Column<int>(nullable: false), EligibilityMethod = table.Column<int>(nullable: false), MinimumServiceMonths = table.Column<int>(nullable: true), PayoutFrequency = table.Column<int>(nullable: false), PayoutMonth = table.Column<int>(nullable: true), TaxTreatment = table.Column<int>(nullable: false), TaxablePercentage = table.Column<decimal>(type: "decimal(18,6)", nullable: true), FinalSettlementTreatment = table.Column<int>(nullable: false), RequiresApproval = table.Column<bool>(nullable: false), AllowManualOverride = table.Column<bool>(nullable: false), PerformanceRatingRequired = table.Column<bool>(nullable: false), SelectedSalaryComponentIdsJson = table.Column<string>(maxLength: 4000, nullable: true), ApplicabilityJson = table.Column<string>(maxLength: 4000, nullable: true), Notes = table.Column<string>(maxLength: 1000, nullable: true), CreatedDate = table.Column<DateTime>(nullable: false), ModifiedDate = table.Column<DateTime>(nullable: true) }, constraints: table => table.PrimaryKey("PK_VariablePayPlanVersions", x => x.Id));
            migrationBuilder.CreateTable("VariablePayAwards", table => new { Id = table.Column<Guid>(nullable: false), TenantId = table.Column<Guid>(nullable: false), EmployeeId = table.Column<Guid>(nullable: false), VariablePayPlanId = table.Column<Guid>(nullable: false), VariablePayPlanVersionId = table.Column<Guid>(nullable: false), AwardNumber = table.Column<string>(maxLength: 40, nullable: false), AwardPeriodFrom = table.Column<DateOnly>(nullable: false), AwardPeriodTo = table.Column<DateOnly>(nullable: false), EligibilityDate = table.Column<DateOnly>(nullable: false), SalaryBasisAmount = table.Column<decimal>(type: "decimal(18,6)", nullable: false), TargetAmount = table.Column<decimal>(type: "decimal(18,6)", nullable: true), PerformanceMultiplier = table.Column<decimal>(type: "decimal(18,6)", nullable: true), ProrationFactor = table.Column<decimal>(type: "decimal(18,6)", nullable: false), CalculatedAmount = table.Column<decimal>(type: "decimal(18,6)", nullable: false), ApprovedAmount = table.Column<decimal>(type: "decimal(18,6)", nullable: true), TaxableAmount = table.Column<decimal>(type: "decimal(18,6)", nullable: true), NonTaxableAmount = table.Column<decimal>(type: "decimal(18,6)", nullable: true), SettledAmount = table.Column<decimal>(type: "decimal(18,6)", nullable: false), CurrencyCode = table.Column<string>(maxLength: 10, nullable: false), PayoutDate = table.Column<DateOnly>(nullable: true), SettlementMethod = table.Column<string>(maxLength: 40, nullable: false), Status = table.Column<int>(nullable: false), Reason = table.Column<string>(maxLength: 2000, nullable: true), CreatedByUserId = table.Column<Guid>(nullable: true), SubmittedAtUtc = table.Column<DateTime>(nullable: true), SubmittedByUserId = table.Column<Guid>(nullable: true), ApprovedAtUtc = table.Column<DateTime>(nullable: true), ApprovedByUserId = table.Column<Guid>(nullable: true), RejectedAtUtc = table.Column<DateTime>(nullable: true), RejectedByUserId = table.Column<Guid>(nullable: true), CancelledAtUtc = table.Column<DateTime>(nullable: true), CancelledByUserId = table.Column<Guid>(nullable: true), CreatedDate = table.Column<DateTime>(nullable: false), ModifiedDate = table.Column<DateTime>(nullable: true), ConcurrencyVersion = table.Column<int>(nullable: false, defaultValue: 1) }, constraints: table => table.PrimaryKey("PK_VariablePayAwards", x => x.Id));
            migrationBuilder.CreateTable("VariablePaySettlements", table => new { Id = table.Column<Guid>(nullable: false), TenantId = table.Column<Guid>(nullable: false), VariablePayAwardId = table.Column<Guid>(nullable: false), EmployeeId = table.Column<Guid>(nullable: false), SettlementType = table.Column<int>(nullable: false), Amount = table.Column<decimal>(type: "decimal(18,6)", nullable: false), TaxableAmount = table.Column<decimal>(type: "decimal(18,6)", nullable: false), NonTaxableAmount = table.Column<decimal>(type: "decimal(18,6)", nullable: false), SettlementDate = table.Column<DateOnly>(nullable: false), PayrollRunId = table.Column<Guid>(nullable: true), PayrollResultId = table.Column<Guid>(nullable: true), FinalSettlementId = table.Column<Guid>(nullable: true), Reference = table.Column<string>(maxLength: 200, nullable: true), CreatedAtUtc = table.Column<DateTime>(nullable: false), CreatedByUserId = table.Column<Guid>(nullable: true), CreatedDate = table.Column<DateTime>(nullable: false), ModifiedDate = table.Column<DateTime>(nullable: true) }, constraints: table => table.PrimaryKey("PK_VariablePaySettlements", x => x.Id));
            migrationBuilder.CreateTable("VariablePayAwardHistories", table => new { Id = table.Column<Guid>(nullable: false), TenantId = table.Column<Guid>(nullable: false), VariablePayAwardId = table.Column<Guid>(nullable: false), EventType = table.Column<int>(nullable: false), OccurredAtUtc = table.Column<DateTime>(nullable: false), ActorUserId = table.Column<Guid>(nullable: true), PreviousStatus = table.Column<int>(nullable: true), NewStatus = table.Column<int>(nullable: true), OriginalAmount = table.Column<decimal>(type: "decimal(18,6)", nullable: true), NewAmount = table.Column<decimal>(type: "decimal(18,6)", nullable: true), VariablePayPlanVersionId = table.Column<Guid>(nullable: true), Reason = table.Column<string>(maxLength: 1000, nullable: true), SourceType = table.Column<string>(maxLength: 100, nullable: true), SourceId = table.Column<Guid>(nullable: true), CreatedDate = table.Column<DateTime>(nullable: false), ModifiedDate = table.Column<DateTime>(nullable: true) }, constraints: table => table.PrimaryKey("PK_VariablePayAwardHistories", x => x.Id));
            migrationBuilder.CreateIndex("IX_VariablePayPlans_TenantId_Code", "VariablePayPlans", new[] { "TenantId", "Code" }, unique: true);
            migrationBuilder.CreateIndex("IX_VariablePayNumberSequences_TenantId_Year", "VariablePayNumberSequences", new[] { "TenantId", "Year" }, unique: true);
            migrationBuilder.CreateIndex("IX_VariablePayAwards_TenantId_AwardNumber", "VariablePayAwards", new[] { "TenantId", "AwardNumber" }, unique: true);
            migrationBuilder.CreateIndex("IX_VPA_Award_Unique", "VariablePayAwards", new[] { "TenantId", "EmployeeId", "VariablePayPlanVersionId", "AwardPeriodFrom", "AwardPeriodTo" }, unique: true);
            migrationBuilder.CreateIndex("IX_VariablePaySettlements_Source", "VariablePaySettlements", new[] { "TenantId", "VariablePayAwardId", "SettlementType", "PayrollRunId", "FinalSettlementId" }, unique: true);
            migrationBuilder.CreateIndex("IX_VariablePayAwardHistories_Award", "VariablePayAwardHistories", new[] { "TenantId", "VariablePayAwardId", "OccurredAtUtc" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable("VariablePayAwardHistories"); migrationBuilder.DropTable("VariablePaySettlements"); migrationBuilder.DropTable("VariablePayAwards"); migrationBuilder.DropTable("VariablePayPlanVersions"); migrationBuilder.DropTable("VariablePayNumberSequences"); migrationBuilder.DropTable("VariablePayPlans");
        }
    }
}
