// <auto-generated />
using HRMS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HRMS.Infrastructure.Persistence.Migrations;

[DbContext(typeof(HrmsDbContext))]
[Migration("20260904150000_LeavePolicyFoundationHardening")]
partial class LeavePolicyFoundationHardening
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder.HasAnnotation("ProductVersion", "10.0.11");
        modelBuilder.Entity("HRMS.Domain.Entities.LeavePolicyRule", b =>
        {
            b.Property<Guid>("Id");
            b.Property<Guid>("TenantId");
            b.Property<Guid>("LeavePolicyVersionId");
            b.HasKey("Id");
            b.HasAlternateKey("TenantId", "Id");
            b.HasAlternateKey("TenantId", "LeavePolicyVersionId", "Id");
            b.ToTable("LeavePolicyRules");
        });
        modelBuilder.Entity("HRMS.Domain.Entities.LeavePolicyClubbingRule", b =>
        {
            b.Property<Guid>("Id");
            b.Property<Guid>("TenantId");
            b.Property<Guid>("LeavePolicyVersionId");
            b.Property<Guid>("LowerLeavePolicyRuleId");
            b.Property<Guid>("HigherLeavePolicyRuleId");
            b.Property<string>("NormalizedPairKey").HasComputedColumnSql("CASE WHEN CONVERT(varchar(36), [LowerLeavePolicyRuleId]) < CONVERT(varchar(36), [HigherLeavePolicyRuleId]) THEN CONVERT(varchar(36), [LowerLeavePolicyRuleId]) + ':' + CONVERT(varchar(36), [HigherLeavePolicyRuleId]) ELSE CONVERT(varchar(36), [HigherLeavePolicyRuleId]) + ':' + CONVERT(varchar(36), [LowerLeavePolicyRuleId]) END", true).HasMaxLength(73);
            b.Property<int>("Relation");
            b.Property<DateTime>("CreatedDate");
            b.Property<DateTime?>("ModifiedDate");
            b.HasKey("Id");
            b.HasAlternateKey("TenantId", "Id");
            b.HasIndex("TenantId", "LeavePolicyVersionId", "NormalizedPairKey").IsUnique().HasFilter(null);
            b.ToTable("LeavePolicyClubbingRules", t => t.HasCheckConstraint("CK_LeavePolicyClubbingRules_DifferentParticipants", "[LowerLeavePolicyRuleId] <> [HigherLeavePolicyRuleId]"));
        });
    }
}
