// <auto-generated />
using HRMS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable
namespace HRMS.Infrastructure.Persistence.Migrations;
[DbContext(typeof(HrmsDbContext))]
[Migration("20260904123000_LeavePolicyCalendarRules")]
partial class LeavePolicyCalendarRules
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder.HasAnnotation("ProductVersion", "10.0.11");
        modelBuilder.Entity("HRMS.Domain.Entities.LeavePolicyCalendarRule", b =>
        {
            b.Property<Guid>("Id"); b.Property<Guid>("TenantId"); b.Property<Guid>("LeavePolicyRuleId"); b.Property<int>("HolidayTreatment"); b.Property<int>("WeekOffTreatment"); b.Property<int>("SandwichMode"); b.Property<bool>("ApplyToPrefix"); b.Property<bool>("ApplyToSuffix"); b.Property<bool>("ApplyToBetween"); b.Property<DateTime>("CreatedDate"); b.Property<DateTime?>("ModifiedDate"); b.HasKey("Id"); b.HasAlternateKey("TenantId", "Id"); b.HasIndex("TenantId", "LeavePolicyRuleId").IsUnique(); b.ToTable("LeavePolicyCalendarRules");
        });
    }
}
