// <auto-generated />
using HRMS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable
namespace HRMS.Infrastructure.Persistence.Migrations;
[DbContext(typeof(HrmsDbContext))]
[Migration("20260904140000_LeavePolicyCancellationRules")]
partial class LeavePolicyCancellationRules
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder.HasAnnotation("ProductVersion", "10.0.11"); modelBuilder.Entity("HRMS.Domain.Entities.LeavePolicyCancellationRule", b => { b.Property<Guid>("Id"); b.Property<Guid>("TenantId"); b.Property<Guid>("LeavePolicyRuleId"); b.Property<bool>("WithdrawAllowed"); b.Property<bool>("CancelAllowed"); b.Property<bool>("ModifyAllowed"); b.Property<DateTime>("CreatedDate"); b.Property<DateTime?>("ModifiedDate"); b.HasKey("Id"); b.HasAlternateKey("TenantId", "Id"); b.HasIndex("TenantId", "LeavePolicyRuleId").IsUnique(); b.ToTable("LeavePolicyCancellationRules"); });
    }
}
