// <auto-generated />
using HRMS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable
namespace HRMS.Infrastructure.Persistence.Migrations;
[DbContext(typeof(HrmsDbContext))]
[Migration("20260904130000_LeavePolicyAttachmentRules")]
partial class LeavePolicyAttachmentRules
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder.HasAnnotation("ProductVersion", "10.0.11"); modelBuilder.Entity("HRMS.Domain.Entities.LeavePolicyAttachmentRule", b => { b.Property<Guid>("Id"); b.Property<Guid>("TenantId"); b.Property<Guid>("LeavePolicyRuleId"); b.Property<int>("AttachmentRequirement"); b.Property<decimal?>("ThresholdQuantity").HasPrecision(9, 3); b.Property<string>("DocumentLabel").HasMaxLength(200); b.Property<DateTime>("CreatedDate"); b.Property<DateTime?>("ModifiedDate"); b.HasKey("Id"); b.HasAlternateKey("TenantId", "Id"); b.HasIndex("TenantId", "LeavePolicyRuleId").IsUnique(); b.ToTable("LeavePolicyAttachmentRules"); });
    }
}
