using HRMS.Application.Common;
using HRMS.Domain.Enums;

namespace HRMS.Application.DTOs.Attendance;

public sealed class ShiftQuery : PagedQuery { public bool? IsActive { get; set; } }
public sealed class ShiftRequest
{
    public string ShiftCode { get; set; } = string.Empty; public string ShiftName { get; set; } = string.Empty; public string? Description { get; set; } public ShiftType ShiftType { get; set; } = ShiftType.Fixed; public bool IsDefault { get; set; }
    public TimeOnly StartTime { get; set; } public TimeOnly EndTime { get; set; } public int BreakDurationMinutes { get; set; } public TimeOnly? MandatoryStartTime { get; set; } public TimeOnly? MandatoryEndTime { get; set; } public TimeOnly? StretchedStartTime { get; set; } public TimeOnly? StretchedEndTime { get; set; }
    public int MinimumWorkMinutes { get; set; } public int FullDayWorkMinutes { get; set; } public int? HalfDayWorkMinutes { get; set; }
    public int GraceInMinutes { get; set; } public int GraceOutMinutes { get; set; } public int LateThresholdMinutes { get; set; } public int EarlyOutThresholdMinutes { get; set; }
    public bool IsNightShift { get; set; } public bool CrossesMidnight { get; set; } public AttendanceCaptureMode CaptureMode { get; set; } public AttendanceSource AllowedAttendanceSources { get; set; } = AttendanceSource.Biometric; public AttendanceSource? PrimaryAttendanceSource { get; set; } public bool UseDefaultAttendanceMethodology { get; set; } = true; public ShiftType? DeprecatedShiftType { get; set; }
    public bool AllowEarlyMarkIn { get; set; } public int MaximumEarlyMarkInMinutes { get; set; } public PostShiftMarkOutMode PostShiftMarkOutMode { get; set; } public int MaximumPostShiftMinutes { get; set; } public bool IsMarkOutMandatory { get; set; } = true; public bool AllowPresentOnSinglePunch { get; set; } public bool RequireExpectedWorkMinutes { get; set; } = true; public bool ShowLateInIndicator { get; set; } = true; public bool ShowEarlyOutIndicator { get; set; } = true; public List<ShiftBreakRequest> Breaks { get; set; } = [];
    public bool IsActive { get; set; } = true; public DateOnly EffectiveFrom { get; set; } public DateOnly? EffectiveTo { get; set; } public string? ConcurrencyToken { get; set; }
}
public sealed class ShiftBreakRequest { public string Name { get; set; } = string.Empty; public TimeOnly StartTime { get; set; } public TimeOnly EndTime { get; set; } public string? Description { get; set; } public int Sequence { get; set; } public bool IsPaid { get; set; } }
public sealed record ShiftBreakDto(Guid Id, string Name, TimeOnly StartTime, TimeOnly EndTime, string? Description, int Sequence, bool IsPaid);
public sealed record ShiftDto(Guid Id, string ShiftCode, string ShiftName, string? Description, ShiftType ShiftType, bool IsDefault, TimeOnly StartTime, TimeOnly EndTime, int PlannedDurationMinutes, int BreakDurationMinutes, TimeOnly? MandatoryStartTime, TimeOnly? MandatoryEndTime, TimeOnly? StretchedStartTime, TimeOnly? StretchedEndTime, int MinimumWorkMinutes, int FullDayWorkMinutes, int? HalfDayWorkMinutes, int GraceInMinutes, int GraceOutMinutes, int LateThresholdMinutes, int EarlyOutThresholdMinutes, bool IsNightShift, bool CrossesMidnight, AttendanceCaptureMode CaptureMode, AttendanceSource AllowedAttendanceSources, AttendanceSource? PrimaryAttendanceSource, bool UseDefaultAttendanceMethodology, bool AllowEarlyMarkIn, int MaximumEarlyMarkInMinutes, PostShiftMarkOutMode PostShiftMarkOutMode, int MaximumPostShiftMinutes, bool IsMarkOutMandatory, bool AllowPresentOnSinglePunch, bool RequireExpectedWorkMinutes, bool ShowLateInIndicator, bool ShowEarlyOutIndicator, bool IsActive, DateOnly EffectiveFrom, DateOnly? EffectiveTo, DateTime CreatedDate, DateTime? ModifiedDate, string ConcurrencyToken, IReadOnlyList<ShiftBreakDto> Breaks);
public sealed class ShiftPatternRequest { public string Code { get; set; } = string.Empty; public string Name { get; set; } = string.Empty; public int CycleLengthDays { get; set; } public bool IsActive { get; set; } = true; public DateOnly EffectiveFrom { get; set; } public DateOnly? EffectiveTo { get; set; } public List<ShiftPatternDayRequest> Days { get; set; } = []; }
public sealed class ShiftPatternDayRequest { public int SequenceDay { get; set; } public Guid? ShiftId { get; set; } public ShiftPatternDayType DayType { get; set; } = ShiftPatternDayType.Shift; }
public sealed record ShiftPatternDto(Guid Id, string Code, string Name, int CycleLengthDays, bool IsActive, DateOnly EffectiveFrom, DateOnly? EffectiveTo, IReadOnlyList<ShiftPatternDayDto> Days);
public sealed record ShiftPatternDayDto(int SequenceDay, Guid? ShiftId, ShiftPatternDayType DayType);
public sealed class ShiftApplicabilityRequest
{
    public string RuleName { get; set; } = string.Empty; public Guid? ShiftId { get; set; } public Guid? ShiftPatternId { get; set; } public Guid? EmployeeId { get; set; } public int Priority { get; set; } public DateOnly EffectiveFrom { get; set; } public DateOnly? EffectiveTo { get; set; }
    public HRMS.Domain.Enums.Gender? Gender { get; set; } public Guid? HoldingCompanyId { get; set; } public Guid? LobId { get; set; } public Guid? OrganisationId { get; set; } public Guid? DepartmentId { get; set; } public Guid? SubDepartmentId { get; set; } public Guid? SectionId { get; set; } public Guid? SubSectionId { get; set; } public Guid? FunctionId { get; set; } public Guid? SubFunctionId { get; set; } public Guid? GradeId { get; set; } public Guid? DesignationId { get; set; } public Guid? EmployeeTypeId { get; set; } public Guid? CountryLocationId { get; set; } public Guid? WorkLocationId { get; set; } public Guid? CostCenterId { get; set; }
}
public sealed class ShiftApplicabilityQuery : PagedQuery { public bool? IsActive { get; set; } }
public sealed record ShiftApplicabilityDto(Guid Id, string RuleName, int Priority, DateOnly EffectiveFrom, DateOnly? EffectiveTo, Guid? ShiftId, Guid? ShiftPatternId, bool IsActive, IReadOnlyDictionary<string, Guid?> Conditions);
public sealed class RosterQuery : PagedQuery { public DateOnly? FromDate { get; set; } public DateOnly? ToDate { get; set; } public Guid? EmployeeId { get; set; } public Guid? ShiftId { get; set; } public RosterDayType? DayType { get; set; } public RosterAssignmentSource? AssignmentSource { get; set; } }
public sealed record RosterGridRowDto(Guid EmployeeId, string EmployeeCode, string EmployeeName, DateOnly RosterDate, RosterDayType DayType, Guid? EffectiveShiftId, string? EffectiveShiftCode, string? EffectiveShiftName, RosterAssignmentSource AssignmentSource, bool HasExplicitRoster, bool IsCalendarOverride, RosterCalendarDayType UnderlyingCalendarDayType, bool CanRemoveOverride);
public sealed record ShiftResolutionDto(Guid EmployeeId, DateOnly Date, Guid? ShiftId, Guid? ShiftPatternId, ShiftPatternDayType? PatternDayType, RosterAssignmentSource Source, bool IsCalendarOverride, string Message);
public sealed class RosterAssignmentRequest { public List<Guid> EmployeeIds { get; set; } = []; public DateOnly FromDate { get; set; } public DateOnly ToDate { get; set; } public Guid? ShiftId { get; set; } public RosterDayType DayType { get; set; } = RosterDayType.Shift; public string? Reason { get; set; } }
public sealed record RosterDayDto(Guid Id, Guid EmployeeId, DateOnly RosterDate, Guid? ShiftId, Guid? ShiftPatternId, RosterDayType DayType, RosterAssignmentSource AssignmentSource, bool IsOverride, bool IsCalendarOverride, string? Comment);
public sealed record RosterUploadRowDto(int RowNumber, string EmployeeCode, DateOnly RosterDate, string? ShiftCode, RosterDayType DayType, bool IsValid, RosterUploadAction Action, string? CurrentShiftCode, RosterDayType? CurrentDayType, string? ErrorMessage, RosterCalendarDayType UnderlyingCalendarDayType, bool IsCurrentCalendarOverride, bool WillOverrideCalendar);
public sealed record RosterUploadBatchDto(Guid Id, string FileName, RosterUploadStatus Status, int TotalRows, int ValidRows, int InvalidRows, int CommittedRows, IReadOnlyList<RosterUploadRowDto> Rows);
