using HRMS.Application.Abstractions;
using HRMS.Application.Common;
using HRMS.Application.DTOs.Attendance;
using HRMS.Domain.Entities;
using HRMS.Domain.Enums;
using Microsoft.EntityFrameworkCore;

namespace HRMS.Application.Services;

public sealed class AttendanceFoundationService(IHrmsDbContext db, ITenantContext tenant, IEffectiveEmploymentResolver employmentResolver) : IAttendanceFoundationService
{
    private const int MaxUploadRows = 100_000;
    private bool TryTenant(out Guid id) { id = tenant.TenantId ?? Guid.Empty; return id != Guid.Empty; }

    public async Task<Result<IReadOnlyList<ShiftDto>>> GetShiftsAsync(ShiftQuery query, CancellationToken ct = default)
    {
        if (!TryTenant(out var tid)) return Result<IReadOnlyList<ShiftDto>>.Unauthorized("No authenticated tenant.");
        var rows = await db.Shifts.AsNoTracking().Where(x => x.TenantId == tid && (!query.IsActive.HasValue || x.IsActive == query.IsActive)).OrderBy(x => x.ShiftCode).ToListAsync(ct);
        return Result<IReadOnlyList<ShiftDto>>.Success(rows.Select(ToDto).ToList());
    }

    public async Task<Result<ShiftDto>> CreateShiftAsync(ShiftRequest r, CancellationToken ct = default) => await SaveShiftAsync(null, r, ct);
    public async Task<Result<ShiftDto>> UpdateShiftAsync(Guid id, ShiftRequest r, CancellationToken ct = default) => await SaveShiftAsync(id, r, ct);
    private async Task<Result<ShiftDto>> SaveShiftAsync(Guid? id, ShiftRequest r, CancellationToken ct)
    {
        if (!TryTenant(out var tid)) return Result<ShiftDto>.Unauthorized("No authenticated tenant.");
        var error = ValidateShift(r); if (error is not null) return Result<ShiftDto>.Invalid(error.Value.field, error.Value.message);
        if (await db.Shifts.AnyAsync(x => x.TenantId == tid && x.ShiftCode == r.ShiftCode.Trim() && x.Id != id, ct)) return Result<ShiftDto>.Conflict("Shift code already exists in this tenant.");
        Shift item;
        if (id is Guid existing) { item = await db.Shifts.FirstOrDefaultAsync(x => x.TenantId == tid && x.Id == existing, ct) ?? null!; if (item is null) return Result<ShiftDto>.NotFound("Shift was not found."); if (!TokenMatches(item, r.ConcurrencyToken)) return Result<ShiftDto>.Conflict("Shift changed by another user. Reload before saving."); }
        else { item = new Shift { Id = Guid.NewGuid(), TenantId = tid }; db.Shifts.Add(item); }
        item.ShiftCode = r.ShiftCode.Trim(); item.ShiftName = r.ShiftName.Trim(); item.Description = r.Description?.Trim(); item.StartTime = r.StartTime; item.EndTime = r.EndTime; item.BreakDurationMinutes = r.BreakDurationMinutes; item.MinimumWorkMinutes = r.MinimumWorkMinutes; item.FullDayWorkMinutes = r.FullDayWorkMinutes; item.HalfDayWorkMinutes = r.HalfDayWorkMinutes; item.GraceInMinutes = r.GraceInMinutes; item.GraceOutMinutes = r.GraceOutMinutes; item.LateThresholdMinutes = r.LateThresholdMinutes; item.EarlyOutThresholdMinutes = r.EarlyOutThresholdMinutes; item.IsNightShift = r.IsNightShift || r.CrossesMidnight; item.CrossesMidnight = r.CrossesMidnight || r.EndTime <= r.StartTime; item.CaptureMode = r.CaptureMode; item.IsActive = r.IsActive; item.EffectiveFrom = r.EffectiveFrom; item.EffectiveTo = r.EffectiveTo;
        await db.SaveChangesAsync(ct); return Result<ShiftDto>.Success(ToDto(item), id is null ? "Shift created." : "Shift updated.");
    }

    public async Task<Result<IReadOnlyList<ShiftPatternDto>>> GetPatternsAsync(CancellationToken ct = default)
    { if (!TryTenant(out var tid)) return Result<IReadOnlyList<ShiftPatternDto>>.Unauthorized("No authenticated tenant."); var rows = await db.ShiftPatterns.AsNoTracking().Include(x => x.Days).Where(x => x.TenantId == tid).OrderBy(x => x.Code).ToListAsync(ct); return Result<IReadOnlyList<ShiftPatternDto>>.Success(rows.Select(ToDto).ToList()); }

    public async Task<Result<ShiftPatternDto>> CreatePatternAsync(ShiftPatternRequest r, CancellationToken ct = default)
    {
        if (!TryTenant(out var tid)) return Result<ShiftPatternDto>.Unauthorized("No authenticated tenant.");
        if (string.IsNullOrWhiteSpace(r.Code) || string.IsNullOrWhiteSpace(r.Name)) return Result<ShiftPatternDto>.Invalid("code", "Code and name are required.");
        if (r.CycleLengthDays < 1 || r.CycleLengthDays > 366 || r.Days.Count != r.CycleLengthDays || r.Days.Select(x => x.SequenceDay).Distinct().Count() != r.CycleLengthDays) return Result<ShiftPatternDto>.Invalid("days", "A pattern must contain one row for every sequence day in its N-day cycle.");
        if (await db.ShiftPatterns.AnyAsync(x => x.TenantId == tid && x.Code == r.Code.Trim(), ct)) return Result<ShiftPatternDto>.Conflict("Pattern code already exists in this tenant.");
        var shiftIds = r.Days.Where(x => x.ShiftId.HasValue).Select(x => x.ShiftId!.Value).Distinct().ToList(); if (await db.Shifts.CountAsync(x => x.TenantId == tid && shiftIds.Contains(x.Id) && x.IsActive, ct) != shiftIds.Count) return Result<ShiftPatternDto>.Invalid("days", "Every selected Shift must be active and belong to this tenant.");
        var p = new ShiftPattern { Id = Guid.NewGuid(), TenantId = tid, Code = r.Code.Trim(), Name = r.Name.Trim(), CycleLengthDays = r.CycleLengthDays, IsActive = r.IsActive, EffectiveFrom = r.EffectiveFrom, EffectiveTo = r.EffectiveTo, Days = r.Days.OrderBy(x => x.SequenceDay).Select(x => new ShiftPatternDay { Id = Guid.NewGuid(), TenantId = tid, SequenceDay = x.SequenceDay, ShiftId = x.ShiftId, DayType = x.DayType }).ToList() }; db.ShiftPatterns.Add(p); await db.SaveChangesAsync(ct); return Result<ShiftPatternDto>.Success(ToDto(p), "Shift pattern created.");
    }

    public async Task<Result<ShiftApplicabilityRequest>> AddApplicabilityAsync(ShiftApplicabilityRequest r, CancellationToken ct = default)
    { if (!TryTenant(out var tid)) return Result<ShiftApplicabilityRequest>.Unauthorized("No authenticated tenant."); if ((r.ShiftId is null) == (r.ShiftPatternId is null)) return Result<ShiftApplicabilityRequest>.Invalid("shiftId", "Specify exactly one Shift or Shift Pattern."); if (r.EffectiveTo < r.EffectiveFrom) return Result<ShiftApplicabilityRequest>.Invalid("effectiveTo", "EffectiveTo cannot be before EffectiveFrom."); if (r.ShiftId is Guid sid && !await db.Shifts.AnyAsync(x => x.TenantId == tid && x.Id == sid && x.IsActive, ct)) return Result<ShiftApplicabilityRequest>.Invalid("shiftId", "Shift was not found in this tenant."); if (r.ShiftPatternId is Guid pid && !await db.ShiftPatterns.AnyAsync(x => x.TenantId == tid && x.Id == pid && x.IsActive, ct)) return Result<ShiftApplicabilityRequest>.Invalid("shiftPatternId", "Shift Pattern was not found in this tenant."); var item = new ShiftApplicabilityRule { Id = Guid.NewGuid(), TenantId = tid, ShiftId = r.ShiftId, ShiftPatternId = r.ShiftPatternId, Priority = r.Priority, EffectiveFrom = r.EffectiveFrom, EffectiveTo = r.EffectiveTo, Gender = r.Gender, HoldingCompanyId = r.HoldingCompanyId, LobId = r.LobId, OrganisationId = r.OrganisationId, DepartmentId = r.DepartmentId, SubDepartmentId = r.SubDepartmentId, SectionId = r.SectionId, SubSectionId = r.SubSectionId, FunctionId = r.FunctionId, SubFunctionId = r.SubFunctionId, GradeId = r.GradeId, DesignationId = r.DesignationId, EmployeeTypeId = r.EmployeeTypeId, CountryLocationId = r.CountryLocationId, WorkLocationId = r.WorkLocationId, CostCenterId = r.CostCenterId }; db.ShiftApplicabilityRules.Add(item); await db.SaveChangesAsync(ct); return Result<ShiftApplicabilityRequest>.Success(r, "Applicability rule created."); }

    public async Task<Result<ShiftResolutionDto>> ResolveAsync(Guid employeeId, DateOnly date, CancellationToken ct = default)
    {
        if (!TryTenant(out var tid)) return Result<ShiftResolutionDto>.Unauthorized("No authenticated tenant.");
        var employment = await employmentResolver.ResolveAsync(tid, employeeId, date, ct); if (employment.Status != EffectiveEmploymentResolutionStatus.Resolved || employment.Employment is null) return Result<ShiftResolutionDto>.NotFound(employment.Message);
        var manual = await db.EmployeeRosterDays.AsNoTracking().FirstOrDefaultAsync(x => x.TenantId == tid && x.EmployeeId == employeeId && x.RosterDate == date, ct);
        if (manual is not null) return Result<ShiftResolutionDto>.Success(new(employeeId, date, manual.ShiftId, manual.ShiftPatternId, null, manual.AssignmentSource, manual.IsCalendarOverride, "Explicit roster assignment overrides automatic applicability."));
        var h = employment.Employment; var rules = await db.ShiftApplicabilityRules.AsNoTracking().Where(x => x.TenantId == tid && x.EffectiveFrom <= date && (x.EffectiveTo == null || date <= x.EffectiveTo)).ToListAsync(ct); var matches = rules.Where(x => Matches(x, h)).Select(x => new { Rule = x, Specificity = Specificity(x) }).ToList(); if (matches.Count == 0) return Result<ShiftResolutionDto>.Success(new(employeeId, date, null, null, null, RosterAssignmentSource.Auto, false, "No applicable Shift or Pattern rule was found.")); var best = matches.Where(x => x.Rule.Priority == matches.Max(y => y.Rule.Priority)).ToList(); var specific = best.Where(x => x.Specificity == best.Max(y => y.Specificity)).ToList(); if (specific.Count != 1) return Result<ShiftResolutionDto>.Conflict("Multiple Shift applicability rules have the same best priority and specificity."); var rule = specific[0].Rule; if (rule.ShiftId is Guid shift) return Result<ShiftResolutionDto>.Success(new(employeeId, date, shift, null, null, RosterAssignmentSource.Auto, false, "Automatic Shift applicability resolved.")); var pattern = await db.ShiftPatterns.AsNoTracking().Include(x => x.Days).SingleAsync(x => x.TenantId == tid && x.Id == rule.ShiftPatternId, ct); var offset = (date.DayNumber - pattern.EffectiveFrom.DayNumber) % pattern.CycleLengthDays; if (offset < 0) offset += pattern.CycleLengthDays; var day = pattern.Days.Single(x => x.SequenceDay == offset + 1); return Result<ShiftResolutionDto>.Success(new(employeeId, date, day.ShiftId, pattern.Id, day.DayType, RosterAssignmentSource.Auto, false, "Automatic Shift Pattern applicability resolved."));
    }

    public async Task<Result<IReadOnlyList<RosterDayDto>>> AssignRosterAsync(RosterAssignmentRequest r, CancellationToken ct = default)
    {
        if (!TryTenant(out var tid)) return Result<IReadOnlyList<RosterDayDto>>.Unauthorized("No authenticated tenant.");
        if (r.FromDate > r.ToDate || r.EmployeeIds.Count == 0) return Result<IReadOnlyList<RosterDayDto>>.Invalid("dateRange", "A valid employee list and date range are required.");
        var days = r.ToDate.DayNumber - r.FromDate.DayNumber + 1;
        if ((long)days * r.EmployeeIds.Count > MaxUploadRows) return Result<IReadOnlyList<RosterDayDto>>.Invalid("dateRange", $"The request exceeds the safe limit of {MaxUploadRows:N0} roster rows.");
        if (r.DayType == RosterDayType.Shift && r.ShiftId is null) return Result<IReadOnlyList<RosterDayDto>>.Invalid("shiftId", "Shift is required for a working roster day.");
        if (r.ShiftId is Guid sid && !await db.Shifts.AnyAsync(x => x.TenantId == tid && x.Id == sid && x.IsActive, ct)) return Result<IReadOnlyList<RosterDayDto>>.Invalid("shiftId", "Shift was not found in this tenant.");
        var result = new List<EmployeeRosterDay>();
        foreach (var employeeId in r.EmployeeIds.Distinct())
        {
            if (!await db.Employees.AnyAsync(x => x.TenantId == tid && x.Id == employeeId, ct)) return Result<IReadOnlyList<RosterDayDto>>.Invalid("employeeIds", "One or more employees were not found in this tenant.");
            for (var d = r.FromDate; d <= r.ToDate; d = d.AddDays(1))
            {
                var item = await db.EmployeeRosterDays.FirstOrDefaultAsync(x => x.TenantId == tid && x.EmployeeId == employeeId && x.RosterDate == d, ct);
                var previousShift = item?.ShiftId; var previousDayType = item?.DayType ?? RosterDayType.NonWorking;
                if (item is null) { item = new EmployeeRosterDay { Id = Guid.NewGuid(), TenantId = tid, EmployeeId = employeeId, RosterDate = d }; db.EmployeeRosterDays.Add(item); }
                db.EmployeeRosterChangeHistories.Add(new EmployeeRosterChangeHistory { Id = Guid.NewGuid(), TenantId = tid, EmployeeId = employeeId, RosterDate = d, PreviousShiftId = previousShift, NewShiftId = r.ShiftId, PreviousDayType = previousDayType, NewDayType = r.DayType, Source = RosterAssignmentSource.Manual, Reason = r.Reason });
                item.OriginalShiftId ??= item.ShiftId; item.ShiftId = r.ShiftId; item.DayType = r.DayType; item.AssignmentSource = RosterAssignmentSource.Manual; item.IsOverride = true; item.IsCalendarOverride = true; item.Comment = r.Reason; result.Add(item);
            }
        }
        await db.SaveChangesAsync(ct); return Result<IReadOnlyList<RosterDayDto>>.Success(result.Select(ToDto).ToList(), "Roster assigned.");
    }

    public async Task<Result<RosterUploadBatchDto>> ValidateRosterUploadAsync(string fileName, Stream csv, CancellationToken ct = default)
    { if (!TryTenant(out var tid)) return Result<RosterUploadBatchDto>.Unauthorized("No authenticated tenant."); var batch = new RosterUploadBatch { Id = Guid.NewGuid(), TenantId = tid, FileName = Path.GetFileName(fileName), Status = RosterUploadStatus.Validating }; db.RosterUploadBatches.Add(batch); using var reader = new StreamReader(csv); var header = await reader.ReadLineAsync(ct); if (header is null || !header.Split(',').Select(x => x.Trim()).SequenceEqual(new[] { "EmployeeCode", "Date", "ShiftCode", "DayType" }, StringComparer.OrdinalIgnoreCase)) return Result<RosterUploadBatchDto>.Invalid("file", "CSV headers must be EmployeeCode,Date,ShiftCode,DayType."); var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase); string? line; var rowNo = 1; while ((line = await reader.ReadLineAsync(ct)) is not null) { if (++rowNo > MaxUploadRows + 1) return Result<RosterUploadBatchDto>.Invalid("file", $"The file exceeds the safe limit of {MaxUploadRows:N0} rows."); if (string.IsNullOrWhiteSpace(line)) continue; var c = line.Split(','); var row = new RosterUploadRow { Id = Guid.NewGuid(), TenantId = tid, RosterUploadBatchId = batch.Id, RowNumber = rowNo, EmployeeCode = c.ElementAtOrDefault(0)?.Trim() ?? string.Empty, ShiftCode = c.ElementAtOrDefault(2)?.Trim(), DayType = ParseDayType(c.ElementAtOrDefault(3)), IsValid = true }; batch.Rows.Add(row); batch.TotalRows++; if (!DateOnly.TryParse(c.ElementAtOrDefault(1), out var date)) { row.IsValid = false; row.ErrorMessage = "Date is invalid."; } else row.RosterDate = date; if (row.DayType == RosterDayType.NonWorking && !string.IsNullOrWhiteSpace(row.ShiftCode)) { row.IsValid = false; row.ErrorMessage = "ShiftCode must be empty for NonWorking."; } if (!Enum.TryParse<RosterDayType>(c.ElementAtOrDefault(3), true, out _)) { row.IsValid = false; row.ErrorMessage = "DayType is invalid."; } var employee = await db.Employees.AsNoTracking().FirstOrDefaultAsync(x => x.TenantId == tid && x.EmployeeCode == row.EmployeeCode, ct); if (employee is null) { row.IsValid = false; row.ErrorMessage = "EmployeeCode was not found in this tenant."; } Shift? shift = null; if (!string.IsNullOrWhiteSpace(row.ShiftCode)) shift = await db.Shifts.AsNoTracking().FirstOrDefaultAsync(x => x.TenantId == tid && x.ShiftCode == row.ShiftCode && x.IsActive, ct); if (row.DayType == RosterDayType.Shift && shift is null) { row.IsValid = false; row.ErrorMessage = "ShiftCode was not found or is inactive."; } var key = $"{row.EmployeeCode}|{row.RosterDate:yyyy-MM-dd}"; if (!seen.Add(key)) { row.IsValid = false; row.ErrorMessage = "Duplicate employee/date row."; } if (row.IsValid) batch.ValidRows++; else batch.InvalidRows++; } batch.Status = batch.InvalidRows == 0 ? RosterUploadStatus.Validated : RosterUploadStatus.Failed; await db.SaveChangesAsync(ct); return Result<RosterUploadBatchDto>.Success(ToDto(batch), batch.Status == RosterUploadStatus.Validated ? "Roster upload validated." : "Roster upload contains validation errors."); }

    public async Task<Result<RosterUploadBatchDto>> CommitRosterUploadAsync(Guid batchId, CancellationToken ct = default)
    { if (!TryTenant(out var tid)) return Result<RosterUploadBatchDto>.Unauthorized("No authenticated tenant."); var batch = await db.RosterUploadBatches.Include(x => x.Rows).FirstOrDefaultAsync(x => x.TenantId == tid && x.Id == batchId, ct); if (batch is null) return Result<RosterUploadBatchDto>.NotFound("Roster upload batch was not found."); if (batch.Status != RosterUploadStatus.Validated) return Result<RosterUploadBatchDto>.Conflict("Only a validated roster upload can be committed."); foreach (var row in batch.Rows) { var employee = await db.Employees.AsNoTracking().SingleAsync(x => x.TenantId == tid && x.EmployeeCode == row.EmployeeCode, ct); var shift = string.IsNullOrWhiteSpace(row.ShiftCode) ? null : await db.Shifts.AsNoTracking().SingleAsync(x => x.TenantId == tid && x.ShiftCode == row.ShiftCode, ct); var item = await db.EmployeeRosterDays.FirstOrDefaultAsync(x => x.TenantId == tid && x.EmployeeId == employee.Id && x.RosterDate == row.RosterDate, ct); if (item is null) { item = new EmployeeRosterDay { Id = Guid.NewGuid(), TenantId = tid, EmployeeId = employee.Id, RosterDate = row.RosterDate }; db.EmployeeRosterDays.Add(item); } else { db.EmployeeRosterChangeHistories.Add(new EmployeeRosterChangeHistory { Id = Guid.NewGuid(), TenantId = tid, EmployeeId = employee.Id, RosterDate = row.RosterDate, PreviousShiftId = item.ShiftId, NewShiftId = shift?.Id, PreviousDayType = item.DayType, NewDayType = row.DayType, Source = RosterAssignmentSource.Upload, UploadBatchId = batch.Id }); } item.ShiftId = shift?.Id; item.DayType = row.DayType; item.AssignmentSource = RosterAssignmentSource.Upload; item.IsOverride = true; item.IsCalendarOverride = row.DayType == RosterDayType.Shift; batch.CommittedRows++; } batch.Status = RosterUploadStatus.Committed; await db.SaveChangesAsync(ct); return Result<RosterUploadBatchDto>.Success(ToDto(batch), "Roster upload committed."); }

    private static (string field, string message)? ValidateShift(ShiftRequest r) { if (string.IsNullOrWhiteSpace(r.ShiftCode)) return ("shiftCode", "Shift code is required."); if (string.IsNullOrWhiteSpace(r.ShiftName)) return ("shiftName", "Shift name is required."); if (r.EffectiveTo < r.EffectiveFrom) return ("effectiveTo", "EffectiveTo cannot be before EffectiveFrom."); if (r.BreakDurationMinutes < 0 || r.MinimumWorkMinutes < 0 || r.FullDayWorkMinutes < 0 || r.GraceInMinutes < 0 || r.GraceOutMinutes < 0) return ("minutes", "Minute values cannot be negative."); return null; }
    private static bool TokenMatches(Shift x, string? token) => !string.IsNullOrWhiteSpace(token) && token == (x.ModifiedDate ?? x.CreatedDate).ToString("O");
    private static ShiftDto ToDto(Shift x) => new(x.Id, x.ShiftCode, x.ShiftName, x.Description, x.StartTime, x.EndTime, x.BreakDurationMinutes, x.MinimumWorkMinutes, x.FullDayWorkMinutes, x.HalfDayWorkMinutes, x.GraceInMinutes, x.GraceOutMinutes, x.LateThresholdMinutes, x.EarlyOutThresholdMinutes, x.IsNightShift, x.CrossesMidnight, x.CaptureMode, x.IsActive, x.EffectiveFrom, x.EffectiveTo, x.CreatedDate, x.ModifiedDate, (x.ModifiedDate ?? x.CreatedDate).ToString("O"));
    private static ShiftPatternDto ToDto(ShiftPattern x) => new(x.Id, x.Code, x.Name, x.CycleLengthDays, x.IsActive, x.EffectiveFrom, x.EffectiveTo, x.Days.OrderBy(d => d.SequenceDay).Select(d => new ShiftPatternDayDto(d.SequenceDay, d.ShiftId, d.DayType)).ToList());
    private static RosterDayDto ToDto(EmployeeRosterDay x) => new(x.Id, x.EmployeeId, x.RosterDate, x.ShiftId, x.ShiftPatternId, x.DayType, x.AssignmentSource, x.IsOverride, x.IsCalendarOverride, x.Comment);
    private static RosterUploadBatchDto ToDto(RosterUploadBatch x) => new(x.Id, x.FileName, x.Status, x.TotalRows, x.ValidRows, x.InvalidRows, x.CommittedRows, x.Rows.OrderBy(r => r.RowNumber).Select(r => new RosterUploadRowDto(r.RowNumber, r.EmployeeCode, r.RosterDate, r.ShiftCode, r.DayType, r.IsValid, r.ErrorMessage)).ToList());
    private static RosterDayType ParseDayType(string? value) => Enum.TryParse<RosterDayType>(value, true, out var result) ? result : RosterDayType.NonWorking;
    private static bool Matches(ShiftApplicabilityRule s, EffectiveEmploymentSnapshot h) => (!s.Gender.HasValue || s.Gender == h.Gender) && (!s.HoldingCompanyId.HasValue || s.HoldingCompanyId == h.HoldingCompanyId) && (!s.LobId.HasValue || s.LobId == h.LobId) && (!s.OrganisationId.HasValue || s.OrganisationId == h.OrganisationId) && (!s.DepartmentId.HasValue || s.DepartmentId == h.DepartmentId) && (!s.SubDepartmentId.HasValue || s.SubDepartmentId == h.SubDepartmentId) && (!s.SectionId.HasValue || s.SectionId == h.SectionId) && (!s.SubSectionId.HasValue || s.SubSectionId == h.SubSectionId) && (!s.FunctionId.HasValue || s.FunctionId == h.FunctionId) && (!s.SubFunctionId.HasValue || s.SubFunctionId == h.SubFunctionId) && (!s.GradeId.HasValue || s.GradeId == h.GradeId) && (!s.DesignationId.HasValue || s.DesignationId == h.DesignationId) && (!s.EmployeeTypeId.HasValue || s.EmployeeTypeId == h.EmployeeTypeId) && (!s.CountryLocationId.HasValue || s.CountryLocationId == h.CountryLocationId) && (!s.WorkLocationId.HasValue || s.WorkLocationId == h.WorkLocationId) && (!s.CostCenterId.HasValue || s.CostCenterId == h.CostCenterId);
    private static int Specificity(ShiftApplicabilityRule s) => (s.Gender.HasValue ? 1 : 0) + new Guid?[] { s.HoldingCompanyId, s.LobId, s.OrganisationId, s.DepartmentId, s.SubDepartmentId, s.SectionId, s.SubSectionId, s.FunctionId, s.SubFunctionId, s.GradeId, s.DesignationId, s.EmployeeTypeId, s.CountryLocationId, s.WorkLocationId, s.CostCenterId }.Count(x => x.HasValue);
}
