using System.Text.Json;
using HRMS.Application.Abstractions;
using HRMS.Application.Common;
using HRMS.Application.DTOs.Separation;
using HRMS.Domain.Entities.Separation;
using HRMS.Domain.Enums;
using Microsoft.EntityFrameworkCore;

namespace HRMS.Application.Services;

public sealed class ExitInterviewService(IHrmsDbContext db, ITenantContext tenant, IEmployeeIdentityResolver identity, TimeProvider clock, IExitInterviewFailureInjector? failureInjector = null) : IExitInterviewService
{
    public async Task<Result<ExitInterviewTemplateDto>> CreateTemplateAsync(ExitInterviewTemplateRequest request, CancellationToken ct = default)
    {
        if (tenant.TenantId is not Guid tenantId || tenant.UserId is not Guid actor) return Result<ExitInterviewTemplateDto>.Unauthorized("No authenticated tenant and user.");
        if (string.IsNullOrWhiteSpace(request.Code) || string.IsNullOrWhiteSpace(request.Name)) return Result<ExitInterviewTemplateDto>.Invalid("template", "Code and name are required.");
        if (request.EffectiveTo < request.EffectiveFrom) return Result<ExitInterviewTemplateDto>.Invalid("effectiveTo", "Effective To cannot precede Effective From.");
        var code = request.Code.Trim().ToUpperInvariant();
        if (await db.SeparationExitInterviewTemplates.AnyAsync(x => x.TenantId == tenantId && x.Code == code, ct)) return Result<ExitInterviewTemplateDto>.Conflict("An exit interview template with this code already exists.");
        var entity = new SeparationExitInterviewTemplate { Id = Guid.NewGuid(), TenantId = tenantId, Code = code, Name = request.Name.Trim(), Description = request.Description?.Trim(), EffectiveFrom = request.EffectiveFrom, EffectiveTo = request.EffectiveTo, AppliesToSeparationType = request.AppliesToSeparationType, AppliesToReasonId = request.AppliesToReasonId, IsEmployeeSurveyEnabled = request.IsEmployeeSurveyEnabled, IsHrInterviewEnabled = request.IsHrInterviewEnabled, CreatedByUserId = actor };
        db.SeparationExitInterviewTemplates.Add(entity); await db.SaveChangesAsync(ct); return Result<ExitInterviewTemplateDto>.Success(ToTemplate(entity));
    }

    public async Task<Result<IReadOnlyList<ExitInterviewTemplateDto>>> GetTemplatesAsync(CancellationToken ct = default)
    {
        if (tenant.TenantId is not Guid tenantId) return Result<IReadOnlyList<ExitInterviewTemplateDto>>.Unauthorized("No authenticated tenant.");
        var rows = await db.SeparationExitInterviewTemplates.AsNoTracking().Include(x => x.Versions).ThenInclude(x => x.Questions).ThenInclude(x => x.Options).Where(x => x.TenantId == tenantId).OrderBy(x => x.Code).ToListAsync(ct);
        return Result<IReadOnlyList<ExitInterviewTemplateDto>>.Success(rows.Select(ToTemplate).ToList());
    }

    public async Task<Result<ExitInterviewTemplateVersionDto>> CreateVersionAsync(Guid templateId, ExitInterviewVersionRequest request, CancellationToken ct = default)
    {
        if (tenant.TenantId is not Guid tenantId || tenant.UserId is not Guid actor) return Result<ExitInterviewTemplateVersionDto>.Unauthorized("No authenticated tenant and user.");
        if (request.Questions.Count == 0) return Result<ExitInterviewTemplateVersionDto>.Invalid("questions", "At least one question is required.");
        var template = await db.SeparationExitInterviewTemplates.FirstOrDefaultAsync(x => x.TenantId == tenantId && x.Id == templateId, ct); if (template is null) return Result<ExitInterviewTemplateVersionDto>.NotFound("Template not found.");
        if (await db.SeparationExitInterviewTemplateVersions.AnyAsync(x => x.TenantId == tenantId && x.TemplateId == templateId && x.VersionNumber == request.VersionNumber, ct)) return Result<ExitInterviewTemplateVersionDto>.Conflict("Version number already exists.");
        var version = new SeparationExitInterviewTemplateVersion { Id = Guid.NewGuid(), TenantId = tenantId, TemplateId = templateId, VersionNumber = request.VersionNumber, EffectiveFrom = request.EffectiveFrom, EffectiveTo = request.EffectiveTo, CreatedByUserId = actor };
        foreach (var q in request.Questions)
        {
            if (string.IsNullOrWhiteSpace(q.Code) || string.IsNullOrWhiteSpace(q.QuestionText)) return Result<ExitInterviewTemplateVersionDto>.Invalid("questions", "Every question needs a code and text.");
            if (q.IsHrOnly && q.IsEmployeeVisible) return Result<ExitInterviewTemplateVersionDto>.Invalid("questions", "HR-only questions cannot be employee visible.");
            var question = new SeparationExitInterviewQuestion { Id = Guid.NewGuid(), TenantId = tenantId, TemplateVersionId = version.Id, Code = q.Code.Trim().ToUpperInvariant(), QuestionText = q.QuestionText.Trim(), QuestionType = q.QuestionType, Sequence = q.Sequence, IsRequired = q.IsRequired, IsEmployeeVisible = q.IsEmployeeVisible, IsHrOnly = q.IsHrOnly, AllowsComment = q.AllowsComment, MinValue = q.MinValue, MaxValue = q.MaxValue };
            foreach (var option in q.Options ?? []) question.Options.Add(new SeparationExitInterviewQuestionOption { Id = Guid.NewGuid(), TenantId = tenantId, QuestionId = question.Id, Code = option.Code.Trim().ToUpperInvariant(), Label = option.Label.Trim(), Sequence = option.Sequence });
            version.Questions.Add(question);
        }
        db.SeparationExitInterviewTemplateVersions.Add(version); await db.SaveChangesAsync(ct); return Result<ExitInterviewTemplateVersionDto>.Success(ToVersion(version));
    }

    public async Task<Result<ExitInterviewTemplateVersionDto>> PublishVersionAsync(Guid versionId, CancellationToken ct = default)
    {
        if (tenant.TenantId is not Guid tenantId) return Result<ExitInterviewTemplateVersionDto>.Unauthorized("No authenticated tenant.");
        var version = await db.SeparationExitInterviewTemplateVersions.Include(x => x.Questions).ThenInclude(x => x.Options).FirstOrDefaultAsync(x => x.TenantId == tenantId && x.Id == versionId, ct); if (version is null) return Result<ExitInterviewTemplateVersionDto>.NotFound("Template version not found.");
        if (version.Status == SeparationExitInterviewTemplateVersionStatus.Published) return Result<ExitInterviewTemplateVersionDto>.Success(ToVersion(version), "Template version is already published.");
        if (version.EffectiveTo < version.EffectiveFrom) return Result<ExitInterviewTemplateVersionDto>.Invalid("effectiveTo", "Effective To cannot precede Effective From.");
        var overlap = await db.SeparationExitInterviewTemplateVersions.AnyAsync(x => x.TenantId == tenantId && x.TemplateId == version.TemplateId && x.Id != version.Id && x.Status == SeparationExitInterviewTemplateVersionStatus.Published && x.EffectiveFrom <= (version.EffectiveTo ?? DateOnly.MaxValue) && (x.EffectiveTo ?? DateOnly.MaxValue) >= version.EffectiveFrom, ct);
        if (overlap) return Result<ExitInterviewTemplateVersionDto>.Conflict("Published template versions may not overlap.");
        version.Status = SeparationExitInterviewTemplateVersionStatus.Published; version.PublishedAtUtc = clock.GetUtcNow().UtcDateTime; version.ConcurrencyVersion++; await db.SaveChangesAsync(ct); return Result<ExitInterviewTemplateVersionDto>.Success(ToVersion(version));
    }

    public async Task<Result<ExitInterviewHrDto>> AssignAsync(Guid separationId, ExitInterviewAssignRequest request, CancellationToken ct = default)
    {
        if (tenant.TenantId is not Guid tenantId || tenant.UserId is not Guid actor) return Result<ExitInterviewHrDto>.Unauthorized("No authenticated tenant and user.");
        if (await db.SeparationExitInterviews.AnyAsync(x => x.TenantId == tenantId && x.EmployeeSeparationId == separationId && x.Status != SeparationExitInterviewStatus.Cancelled, ct)) return Result<ExitInterviewHrDto>.Conflict("An active exit interview already exists for this separation.");
        var separation = await db.EmployeeSeparations.FirstOrDefaultAsync(x => x.TenantId == tenantId && x.Id == separationId, ct); if (separation is null) return Result<ExitInterviewHrDto>.NotFound("Separation case not found.");
        var businessDate = DateOnly.FromDateTime(clock.GetUtcNow().UtcDateTime);
        var query = db.SeparationExitInterviewTemplateVersions.Include(x => x.Questions).ThenInclude(x => x.Options).Include(x => x.Template).Where(x => x.TenantId == tenantId && x.Status == SeparationExitInterviewTemplateVersionStatus.Published && x.EffectiveFrom <= businessDate && (x.EffectiveTo == null || x.EffectiveTo >= businessDate) && x.Template!.IsActive && x.Template.EffectiveFrom <= businessDate && (x.Template.EffectiveTo == null || x.Template.EffectiveTo >= businessDate) && (x.Template.AppliesToSeparationType == null || x.Template.AppliesToSeparationType == separation.SeparationType) && (x.Template.AppliesToReasonId == null || x.Template.AppliesToReasonId == separation.ReasonId));
        var versions = request.TemplateVersionId is Guid selected ? await query.Where(x => x.Id == selected).ToListAsync(ct) : await query.OrderByDescending(x => x.Template!.AppliesToReasonId != null).ThenByDescending(x => x.EffectiveFrom).ToListAsync(ct);
        if (versions.Count == 0) return Result<ExitInterviewHrDto>.Conflict("No effective published exit interview version is configured.");
        if (request.TemplateVersionId is null && versions.Count > 1 && versions[0].EffectiveFrom == versions[1].EffectiveFrom && versions[0].Template!.AppliesToReasonId == versions[1].Template!.AppliesToReasonId) return Result<ExitInterviewHrDto>.Conflict("Effective exit interview configuration is ambiguous.");
        var interview = new SeparationExitInterview { Id = Guid.NewGuid(), TenantId = tenantId, EmployeeSeparationId = separationId, EmployeeId = separation.EmployeeId, TemplateVersionId = versions[0].Id, AssignedAtUtc = clock.GetUtcNow().UtcDateTime, AssignedHrUserId = request.AssignedHrUserId };
        db.SeparationExitInterviewEvents.Add(Event(interview, SeparationExitInterviewEventType.InterviewAssigned, null, interview.Status, actor, null)); db.SeparationExitInterviews.Add(interview); await db.SaveChangesAsync(ct); return Result<ExitInterviewHrDto>.Success(await ToHrAsync(interview, ct));
    }

    public async Task<Result<ExitInterviewEmployeeDto>> GetMineAsync(Guid? separationId = null, CancellationToken ct = default)
    {
        var who = await identity.ResolveCurrentAsync(ct); if (!who.Succeeded || who.Value is null) return Result<ExitInterviewEmployeeDto>.Unauthorized("No employee identity is linked to the current account.");
        var interview = await LoadInterviewAsync(who.Value.TenantId, separationId, who.Value.EmployeeId, ct); return interview is null ? Result<ExitInterviewEmployeeDto>.NotFound("No assigned exit interview was found.") : Result<ExitInterviewEmployeeDto>.Success(ToEmployee(interview));
    }

    public async Task<Result<ExitInterviewEmployeeDto>> SaveDraftAsync(Guid separationId, ExitInterviewDraftRequest request, CancellationToken ct = default) => await SaveEmployeeAsync(separationId, request, false, ct);
    public async Task<Result<ExitInterviewEmployeeDto>> SubmitAsync(Guid separationId, CancellationToken ct = default) => await SaveEmployeeAsync(separationId, new ExitInterviewDraftRequest([]), true, ct);

    private async Task<Result<ExitInterviewEmployeeDto>> SaveEmployeeAsync(Guid separationId, ExitInterviewDraftRequest request, bool submit, CancellationToken ct)
    {
        var who = await identity.ResolveCurrentAsync(ct); if (!who.Succeeded || who.Value is null) return Result<ExitInterviewEmployeeDto>.Unauthorized("No employee identity is linked to the current account.");
        var interview = await LoadInterviewAsync(who.Value.TenantId, separationId, who.Value.EmployeeId, ct); if (interview is null) return Result<ExitInterviewEmployeeDto>.NotFound("No assigned exit interview was found."); if (submit && interview.Status == SeparationExitInterviewStatus.EmployeeSubmitted) return Result<ExitInterviewEmployeeDto>.Success(ToEmployee(interview), "Employee submission already accepted.");
        if (interview.Status is SeparationExitInterviewStatus.EmployeeSubmitted or SeparationExitInterviewStatus.Completed or SeparationExitInterviewStatus.CompletedWithoutEmployeeResponse && !submit) return Result<ExitInterviewEmployeeDto>.Conflict("Submitted responses are read-only until the interview is reopened.");
        var questions = await db.SeparationExitInterviewQuestions.Include(x => x.Options).Where(x => x.TenantId == who.Value.TenantId && x.TemplateVersionId == interview.TemplateVersionId && x.IsActive && x.IsEmployeeVisible && !x.IsHrOnly).ToListAsync(ct);
        foreach (var response in request.Responses) { var q = questions.FirstOrDefault(x => x.Id == response.QuestionId); if (q is null) return Result<ExitInterviewEmployeeDto>.Invalid("responses", "A response references an unavailable question."); if (!Validate(q, response)) return Result<ExitInterviewEmployeeDto>.Invalid("responses", $"Response for {q.Code} is invalid for its question type."); UpsertResponse(interview, q, response, who.Value.UserId); }
        if (submit) { foreach (var q in questions.Where(x => x.IsRequired)) { var current = interview.Responses.FirstOrDefault(x => x.QuestionId == q.Id); if (current is null || Empty(current)) return Result<ExitInterviewEmployeeDto>.Invalid("responses", $"Required question {q.Code} must be answered."); } interview.Status = SeparationExitInterviewStatus.EmployeeSubmitted; interview.EmployeeSubmittedAtUtc = clock.GetUtcNow().UtcDateTime; db.SeparationExitInterviewEvents.Add(Event(interview, SeparationExitInterviewEventType.EmployeeSubmitted, SeparationExitInterviewStatus.EmployeeInProgress, interview.Status, who.Value.UserId, null)); } else { interview.Status = SeparationExitInterviewStatus.EmployeeInProgress; db.SeparationExitInterviewEvents.Add(Event(interview, SeparationExitInterviewEventType.EmployeeDraftSaved, interview.Status, interview.Status, who.Value.UserId, null)); }
        interview.ConcurrencyVersion++; try { if (submit) failureInjector?.BeforeEmployeeSubmissionCommit(); await db.SaveChangesAsync(ct); } catch (DbUpdateConcurrencyException) { return Result<ExitInterviewEmployeeDto>.Conflict("The exit interview was changed concurrently."); } catch (DbUpdateException) { return Result<ExitInterviewEmployeeDto>.Unavailable("Employee submission was rolled back; retry after review."); } catch (InvalidOperationException) { return Result<ExitInterviewEmployeeDto>.Unavailable("Employee submission was rolled back; retry after review."); } return Result<ExitInterviewEmployeeDto>.Success(ToEmployee(interview));
    }

    public async Task<Result<PagedResult<ExitInterviewInboxItemDto>>> GetInboxAsync(ExitInterviewInboxQuery query, CancellationToken ct = default)
    { if (tenant.TenantId is not Guid tenantId) return Result<PagedResult<ExitInterviewInboxItemDto>>.Unauthorized("No authenticated tenant."); var page = Math.Max(1, query.Page); var pageSize = Math.Clamp(query.PageSize, 1, 100); var q = db.SeparationExitInterviews.AsNoTracking().Include(x => x.EmployeeSeparation).ThenInclude(x => x!.Employee).Include(x => x.EmployeeSeparation).ThenInclude(x => x!.Reason).Where(x => x.TenantId == tenantId && x.Status != SeparationExitInterviewStatus.Cancelled); if (!string.IsNullOrWhiteSpace(query.Status) && Enum.TryParse<SeparationExitInterviewStatus>(query.Status, true, out var status)) q = q.Where(x => x.Status == status); if (query.AssignedHrUserId is Guid assigned) q = q.Where(x => x.AssignedHrUserId == assigned); if (query.LwdFrom is DateOnly from) q = q.Where(x => x.EmployeeSeparation!.ApprovedLastWorkingDate >= from); if (query.LwdTo is DateOnly to) q = q.Where(x => x.EmployeeSeparation!.ApprovedLastWorkingDate <= to); if (!string.IsNullOrWhiteSpace(query.EmployeeSearch)) { var search = query.EmployeeSearch.Trim(); q = q.Where(x => x.EmployeeSeparation!.Employee!.EmployeeCode!.Contains(search) || (x.EmployeeSeparation.Employee.FirstName + " " + x.EmployeeSeparation.Employee.LastName).Contains(search)); } var total = await q.CountAsync(ct); var items = await q.OrderByDescending(x => x.AssignedAtUtc).Skip((page - 1) * pageSize).Take(pageSize).Select(x => new ExitInterviewInboxItemDto(x.Id, x.EmployeeSeparationId, x.EmployeeId, x.EmployeeSeparation!.Employee!.EmployeeCode, x.EmployeeSeparation.Employee.FirstName + " " + x.EmployeeSeparation.Employee.LastName, x.EmployeeSeparation.Reason!.Name, x.EmployeeSeparation.ApprovedLastWorkingDate, x.Status, x.AssignedAtUtc, x.EmployeeSubmittedAtUtc, x.AssignedHrUserId, x.HrCompletedAtUtc)).ToListAsync(ct); return Result<PagedResult<ExitInterviewInboxItemDto>>.Success(new PagedResult<ExitInterviewInboxItemDto>(items, page, pageSize, total)); }
    public async Task<Result<ExitInterviewHrDto>> GetHrAsync(Guid separationId, CancellationToken ct = default) => await HrLoad(separationId, ct);
    public async Task<Result<ExitInterviewHrDto>> StartHrAsync(Guid separationId, CancellationToken ct = default) { var r = await HrLoad(separationId, ct); if (!r.Succeeded || r.Value is null) return r; var e = await Find(separationId, ct); if (e is null) return Result<ExitInterviewHrDto>.NotFound("Interview not found."); if (e.Status is not SeparationExitInterviewStatus.EmployeeSubmitted and not SeparationExitInterviewStatus.EmployeeInProgress and not SeparationExitInterviewStatus.Reopened) return Result<ExitInterviewHrDto>.Conflict("Interview cannot be started in its current state."); var old = e.Status; e.Status = SeparationExitInterviewStatus.HrInProgress; e.HrStartedAtUtc = clock.GetUtcNow().UtcDateTime; e.ConcurrencyVersion++; db.SeparationExitInterviewEvents.Add(Event(e, SeparationExitInterviewEventType.HrInterviewStarted, old, e.Status, tenant.UserId, null)); await db.SaveChangesAsync(ct); return Result<ExitInterviewHrDto>.Success(await ToHrAsync(e, ct)); }
    public async Task<Result<ExitInterviewHrDto>> AddHrNoteAsync(Guid separationId, ExitInterviewNoteRequest request, CancellationToken ct = default) { if (string.IsNullOrWhiteSpace(request.NoteText)) return Result<ExitInterviewHrDto>.Invalid("noteText", "A note is required."); var e = await Find(separationId, ct); if (e is null || tenant.TenantId is not Guid tid || tenant.UserId is not Guid uid) return Result<ExitInterviewHrDto>.Unauthorized("No authenticated tenant and user."); db.SeparationExitInterviewHrNotes.Add(new SeparationExitInterviewHrNote { Id = Guid.NewGuid(), TenantId = tid, ExitInterviewId = e.Id, NoteText = request.NoteText.Trim(), CreatedByUserId = uid }); db.SeparationExitInterviewEvents.Add(Event(e, SeparationExitInterviewEventType.HrNoteAdded, e.Status, e.Status, uid, null)); await db.SaveChangesAsync(ct); return Result<ExitInterviewHrDto>.Success(await ToHrAsync(e, ct)); }
    public async Task<Result<ExitInterviewHrDto>> CompleteAsync(Guid separationId, ExitInterviewCompletionRequest request, CancellationToken ct = default) { var e = await Find(separationId, ct); if (e is null || tenant.TenantId is not Guid tid || tenant.UserId is not Guid uid) return Result<ExitInterviewHrDto>.Unauthorized("No authenticated tenant and user."); if (!request.CompletedWithoutEmployeeResponse && e.Status is not SeparationExitInterviewStatus.EmployeeSubmitted and not SeparationExitInterviewStatus.HrInProgress) return Result<ExitInterviewHrDto>.Conflict("Employee submission is required before completion."); if (request.CompletedWithoutEmployeeResponse && string.IsNullOrWhiteSpace(request.CompletionReason)) return Result<ExitInterviewHrDto>.Invalid("completionReason", "A reason is required when completing without employee response."); var old = e.Status; e.Status = request.CompletedWithoutEmployeeResponse ? SeparationExitInterviewStatus.CompletedWithoutEmployeeResponse : SeparationExitInterviewStatus.Completed; e.PrimaryReasonCategory = request.PrimaryReasonCategory?.Trim(); e.SecondaryReasonCategory = request.SecondaryReasonCategory?.Trim(); e.ReasonComment = request.ReasonComment?.Trim(); e.RehireRecommendation = request.RehireRecommendation; e.RehireRecommendationReason = request.RehireRecommendationReason?.Trim(); e.CompletedWithoutEmployeeResponse = request.CompletedWithoutEmployeeResponse; e.CompletionReason = request.CompletionReason?.Trim(); e.HrCompletedAtUtc = clock.GetUtcNow().UtcDateTime; e.FinalizedAtUtc = e.HrCompletedAtUtc; e.ConcurrencyVersion++; db.SeparationExitInterviewEvents.Add(Event(e, request.CompletedWithoutEmployeeResponse ? SeparationExitInterviewEventType.InterviewCompletedWithoutEmployee : SeparationExitInterviewEventType.InterviewCompleted, old, e.Status, uid, request.CompletionReason)); try { failureInjector?.BeforeHrCompletionCommit(); await db.SaveChangesAsync(ct); } catch (DbUpdateConcurrencyException) { return Result<ExitInterviewHrDto>.Conflict("The exit interview was changed concurrently."); } catch (DbUpdateException) { return Result<ExitInterviewHrDto>.Unavailable("HR completion was rolled back; retry after review."); } catch (InvalidOperationException) { return Result<ExitInterviewHrDto>.Unavailable("HR completion was rolled back; retry after review."); } return Result<ExitInterviewHrDto>.Success(await ToHrAsync(e, ct)); }
    public async Task<Result<ExitInterviewHrDto>> ReopenAsync(Guid separationId, ExitInterviewReopenRequest request, CancellationToken ct = default) { if (string.IsNullOrWhiteSpace(request.Reason)) return Result<ExitInterviewHrDto>.Invalid("reason", "A reason is required."); var e = await Find(separationId, ct); if (e is null || tenant.UserId is not Guid uid) return Result<ExitInterviewHrDto>.Unauthorized("No authenticated user."); if (e.Status is not SeparationExitInterviewStatus.Completed and not SeparationExitInterviewStatus.CompletedWithoutEmployeeResponse) return Result<ExitInterviewHrDto>.Conflict("Only a completed interview can be reopened."); var old = e.Status; e.Status = SeparationExitInterviewStatus.Reopened; e.ReopenedAtUtc = clock.GetUtcNow().UtcDateTime; e.ConcurrencyVersion++; db.SeparationExitInterviewEvents.Add(Event(e, SeparationExitInterviewEventType.InterviewReopened, old, e.Status, uid, request.Reason.Trim())); try { failureInjector?.BeforeReopenCommit(); await db.SaveChangesAsync(ct); } catch (DbUpdateConcurrencyException) { return Result<ExitInterviewHrDto>.Conflict("The exit interview was changed concurrently."); } catch (DbUpdateException) { return Result<ExitInterviewHrDto>.Unavailable("Interview reopen was rolled back; retry after review."); } catch (InvalidOperationException) { return Result<ExitInterviewHrDto>.Unavailable("Interview reopen was rolled back; retry after review."); } return Result<ExitInterviewHrDto>.Success(await ToHrAsync(e, ct)); }
    public async Task<Result<ExitInterviewAnalyticsDto>> GetAnalyticsAsync(CancellationToken ct = default)
    { if (tenant.TenantId is not Guid tenantId) return Result<ExitInterviewAnalyticsDto>.Unauthorized("No authenticated tenant."); var interviews = db.SeparationExitInterviews.AsNoTracking().Where(x => x.TenantId == tenantId); var assigned = await interviews.CountAsync(ct); var submitted = await interviews.CountAsync(x => x.EmployeeSubmittedAtUtc != null, ct); var completed = await interviews.CountAsync(x => x.Status == SeparationExitInterviewStatus.Completed || x.Status == SeparationExitInterviewStatus.CompletedWithoutEmployeeResponse, ct); var ratings = await db.SeparationExitInterviewResponses.AsNoTracking().Where(x => x.TenantId == tenantId && x.NumericValue != null).Select(x => x.NumericValue!.Value).ToListAsync(ct); var reasons = await interviews.Where(x => x.PrimaryReasonCategory != null).GroupBy(x => x.PrimaryReasonCategory!).Select(x => new { Key = x.Key, Count = x.Count() }).ToDictionaryAsync(x => x.Key, x => x.Count, ct); var recommendations = await interviews.GroupBy(x => x.RehireRecommendation).Select(x => new { Key = x.Key.ToString(), Count = x.Count() }).ToDictionaryAsync(x => x.Key, x => x.Count, ct); return Result<ExitInterviewAnalyticsDto>.Success(new ExitInterviewAnalyticsDto(assigned, submitted, completed, ratings.Count == 0 ? null : ratings.Average(), reasons, recommendations)); }

    private async Task<SeparationExitInterview?> Find(Guid separationId, CancellationToken ct) => tenant.TenantId is Guid tid ? await db.SeparationExitInterviews.Include(x => x.Responses).Include(x => x.HrNotes).Include(x => x.EmployeeSeparation).ThenInclude(x => x!.Employee).Include(x => x.EmployeeSeparation).ThenInclude(x => x!.Reason).FirstOrDefaultAsync(x => x.TenantId == tid && x.EmployeeSeparationId == separationId, ct) : null;
    private async Task<SeparationExitInterview?> LoadInterviewAsync(Guid tenantId, Guid? separationId, Guid employeeId, CancellationToken ct) { var q = db.SeparationExitInterviews.Include(x => x.Responses).Where(x => x.TenantId == tenantId && x.EmployeeId == employeeId && x.Status != SeparationExitInterviewStatus.Cancelled); if (separationId is Guid sid) q = q.Where(x => x.EmployeeSeparationId == sid); return await q.OrderByDescending(x => x.AssignedAtUtc).FirstOrDefaultAsync(ct); }
    private async Task<Result<ExitInterviewHrDto>> HrLoad(Guid separationId, CancellationToken ct) { var e = await Find(separationId, ct); return e is null ? Result<ExitInterviewHrDto>.NotFound("Interview not found.") : Result<ExitInterviewHrDto>.Success(await ToHrAsync(e, ct)); }
    private async Task<ExitInterviewHrDto> ToHrAsync(SeparationExitInterview e, CancellationToken ct) { var questions = await db.SeparationExitInterviewQuestions.AsNoTracking().Include(x => x.Options).Where(x => x.TenantId == e.TenantId && x.TemplateVersionId == e.TemplateVersionId).OrderBy(x => x.Sequence).ToListAsync(ct); return new ExitInterviewHrDto(e.Id, e.EmployeeSeparationId, e.EmployeeId, e.EmployeeSeparation?.Employee?.EmployeeCode, $"{e.EmployeeSeparation?.Employee?.FirstName} {e.EmployeeSeparation?.Employee?.LastName}".Trim(), e.EmployeeSeparation?.Reason?.Name, e.EmployeeSeparation?.ApprovedLastWorkingDate, e.AssignedHrUserId, e.Status, e.AssignedAtUtc, e.EmployeeSubmittedAtUtc, e.PrimaryReasonCategory, e.SecondaryReasonCategory, e.ReasonComment, e.RehireRecommendation, e.RehireRecommendationReason, e.CompletedWithoutEmployeeResponse, e.CompletionReason, questions.Select(ToQuestion).ToList(), e.Responses.Select(ToResponse).ToList(), e.HrNotes.OrderBy(x => x.CreatedDate).Select(x => x.NoteText).ToList()); }
    private ExitInterviewEmployeeDto ToEmployee(SeparationExitInterview e) => new(e.Id, e.EmployeeSeparationId, e.Status, e.AssignedAtUtc, e.EmployeeSubmittedAtUtc, db.SeparationExitInterviewQuestions.AsNoTracking().Where(x => x.TenantId == e.TenantId && x.TemplateVersionId == e.TemplateVersionId && x.IsActive && x.IsEmployeeVisible && !x.IsHrOnly).Include(x => x.Options).OrderBy(x => x.Sequence).AsEnumerable().Select(ToQuestion).ToList(), e.Responses.Select(ToResponse).ToList());
    private static ExitInterviewQuestionDto ToQuestion(SeparationExitInterviewQuestion x) => new(x.Id, x.Code, x.QuestionText, x.QuestionType, x.Sequence, x.IsRequired, x.AllowsComment, x.MinValue, x.MaxValue, x.Options.OrderBy(o => o.Sequence).Select(o => new ExitInterviewQuestionOptionDto(o.Code, o.Label, o.Sequence)).ToList());
    private static ExitInterviewResponseDto ToResponse(SeparationExitInterviewResponse x) => new(x.QuestionId, x.ResponseText, x.NumericValue, x.BooleanValue, string.IsNullOrWhiteSpace(x.SelectedOptionCodes) ? [] : JsonSerializer.Deserialize<List<string>>(x.SelectedOptionCodes) ?? [], x.Comment);
    private static ExitInterviewTemplateDto ToTemplate(SeparationExitInterviewTemplate x) => new(x.Id, x.Code, x.Name, x.Description, x.IsActive, x.EffectiveFrom, x.EffectiveTo, x.Versions.OrderByDescending(v => v.VersionNumber).Select(ToVersion).ToList());
    private static ExitInterviewTemplateVersionDto ToVersion(SeparationExitInterviewTemplateVersion x) => new(x.Id, x.TemplateId, x.VersionNumber, x.EffectiveFrom, x.EffectiveTo, x.Status, x.Questions.OrderBy(q => q.Sequence).Select(ToQuestion).ToList());
    private static SeparationExitInterviewEvent Event(SeparationExitInterview e, SeparationExitInterviewEventType type, SeparationExitInterviewStatus? from, SeparationExitInterviewStatus? to, Guid? actor, string? reason) => new() { Id = Guid.NewGuid(), TenantId = e.TenantId, ExitInterviewId = e.Id, EventType = type, FromStatus = from, ToStatus = to, ActorUserId = actor, OccurredAtUtc = DateTime.UtcNow, Reason = reason };
    private static bool Empty(SeparationExitInterviewResponse x) => string.IsNullOrWhiteSpace(x.ResponseText) && x.NumericValue is null && x.BooleanValue is null && string.IsNullOrWhiteSpace(x.SelectedOptionCodes);
    private static bool Validate(SeparationExitInterviewQuestion q, ExitInterviewResponseRequest r) => q.QuestionType switch { SeparationExitInterviewQuestionType.ShortText or SeparationExitInterviewQuestionType.LongText => !string.IsNullOrWhiteSpace(r.ResponseText), SeparationExitInterviewQuestionType.Rating or SeparationExitInterviewQuestionType.Number => r.NumericValue is not null && (!q.MinValue.HasValue || r.NumericValue >= q.MinValue) && (!q.MaxValue.HasValue || r.NumericValue <= q.MaxValue), SeparationExitInterviewQuestionType.YesNo => r.BooleanValue.HasValue, SeparationExitInterviewQuestionType.SingleChoice => r.SelectedOptionCodes?.Count == 1, SeparationExitInterviewQuestionType.MultiChoice => r.SelectedOptionCodes?.Count > 0, SeparationExitInterviewQuestionType.Date => !string.IsNullOrWhiteSpace(r.ResponseText), _ => true };
    private static void UpsertResponse(SeparationExitInterview e, SeparationExitInterviewQuestion q, ExitInterviewResponseRequest r, Guid actor) { var existing = e.Responses.FirstOrDefault(x => x.QuestionId == q.Id); if (existing is null) { existing = new SeparationExitInterviewResponse { Id = Guid.NewGuid(), TenantId = e.TenantId, ExitInterviewId = e.Id, QuestionId = q.Id }; e.Responses.Add(existing); } else { e.ResponseRevisions.Add(new SeparationExitInterviewResponseRevision { Id = Guid.NewGuid(), TenantId = e.TenantId, ExitInterviewId = e.Id, QuestionId = q.Id, ResponseId = existing.Id, ResponseText = existing.ResponseText, NumericValue = existing.NumericValue, BooleanValue = existing.BooleanValue, SelectedOptionCodes = existing.SelectedOptionCodes, Comment = existing.Comment, ActorUserId = actor, RecordedAtUtc = DateTime.UtcNow }); } existing.ResponseText = r.ResponseText?.Trim(); existing.NumericValue = r.NumericValue; existing.BooleanValue = r.BooleanValue; existing.SelectedOptionCodes = r.SelectedOptionCodes is null ? null : JsonSerializer.Serialize(r.SelectedOptionCodes); existing.Comment = r.Comment?.Trim(); existing.SubmittedByEmployee = true; existing.ConcurrencyVersion++; }
}
