using HRMS.Application.Abstractions;
using HRMS.Application.Common;
using HRMS.Application.DTOs.Payroll;
using HRMS.Domain.Entities;
using HRMS.Domain.Enums;
using Microsoft.EntityFrameworkCore;

namespace HRMS.Application.Services;

public sealed class PayrollRetroSettlementService(IHrmsDbContext db, ITenantContext tenant, TimeProvider clock, IPayrollApprovalGuard? approvalGuard = null) : IPayrollRetroSettlementService
{
    public async Task<Result<PayrollRetroCaseDto>> CreateRetroCaseAsync(PayrollRetroCaseRequest request, CancellationToken ct = default)
    {
        if (tenant.TenantId is not Guid tenantId) return Result<PayrollRetroCaseDto>.Unauthorized("No authenticated tenant.");
        if (request.EffectiveTo < request.EffectiveFrom) return Result<PayrollRetroCaseDto>.Invalid("effectiveTo", "Effective To cannot be earlier than Effective From.");
        if (!await db.Employees.AnyAsync(x => x.TenantId == tenantId && x.Id == request.EmployeeId, ct)) return Result<PayrollRetroCaseDto>.NotFound("Employee not found.");
        var item = new PayrollRetroCase { Id = Guid.NewGuid(), TenantId = tenantId, EmployeeId = request.EmployeeId, TriggerType = request.TriggerType, TriggerSourceId = request.TriggerSourceId, EffectiveFrom = request.EffectiveFrom, EffectiveTo = request.EffectiveTo, DetectedAtUtc = clock.GetUtcNow().UtcDateTime, DetectedByUserId = tenant.UserId, Notes = request.Notes };
        db.PayrollRetroCases.Add(item); AddHistory(item, PayrollRetroHistoryChangeType.Created, "Retro case created."); await db.SaveChangesAsync(ct); db.ClearChangeTracker(); return Result<PayrollRetroCaseDto>.Success(ToDto(item));
    }

    public async Task<Result<PayrollRetroCaseDto>> EvaluateRetroAsync(Guid id, CancellationToken ct = default)
    {
        var item = await db.PayrollRetroCases.FirstOrDefaultAsync(x => x.TenantId == tenant.TenantId && x.Id == id, ct); if (item is null) return Result<PayrollRetroCaseDto>.NotFound("Retro case not found.");
        if (item.Status is not PayrollRetroStatus.Detected and not PayrollRetroStatus.Evaluated) return Result<PayrollRetroCaseDto>.Conflict("Retro case cannot be evaluated in its current state.");
        var results = await db.PayrollResults.AsNoTracking().Where(x => x.TenantId == item.TenantId && x.EmployeeId == item.EmployeeId && x.IsCurrent && x.PeriodEndDate >= item.EffectiveFrom && (item.EffectiveTo == null || x.PeriodStartDate <= item.EffectiveTo)).Include(x => x.Components).ToListAsync(ct);
        db.PayrollRetroResults.RemoveRange(db.PayrollRetroResults.Where(x => x.TenantId == item.TenantId && x.PayrollRetroCaseId == item.Id));
        foreach (var original in results)
        {
            var retro = new PayrollRetroResult { Id = Guid.NewGuid(), TenantId = item.TenantId, PayrollRetroCaseId = item.Id, EmployeeId = item.EmployeeId, OriginalPayrollRunId = original.PayrollRunId, OriginalPayrollResultId = original.Id, PeriodStartDate = original.PeriodStartDate, PeriodEndDate = original.PeriodEndDate, OriginalGross = original.GrossEarnings, CorrectedGross = original.GrossEarnings, GrossDifference = 0, OriginalDeductions = original.TotalDeductions, CorrectedDeductions = original.TotalDeductions, DeductionDifference = 0, OriginalNet = original.NetPay, CorrectedNet = original.NetPay, NetDifference = 0, CurrencyCode = original.CurrencyCode, CalculatedAtUtc = clock.GetUtcNow().UtcDateTime, CalculationVersion = original.CalculationVersion };
            foreach (var component in original.Components.OrderBy(x => x.CalculationSequence)) retro.Components.Add(new PayrollRetroComponent { Id = Guid.NewGuid(), TenantId = item.TenantId, SalaryComponentId = component.SalaryComponentId, ComponentCode = component.ComponentCode, ComponentName = component.ComponentName, OriginalAmount = component.CalculatedAmount, CorrectedAmount = component.CalculatedAmount, DifferenceAmount = 0, IsEarning = component.IsEarning, IsDeduction = component.IsDeduction, Sequence = component.CalculationSequence });
            db.PayrollRetroResults.Add(retro);
        }
        item.Status = results.Count == 0 || !await db.PayrollRetroResults.AnyAsync(x => x.TenantId == item.TenantId && x.PayrollRetroCaseId == item.Id && x.NetDifference != 0, ct) ? PayrollRetroStatus.NoImpact : PayrollRetroStatus.Evaluated; AddHistory(item, item.Status == PayrollRetroStatus.NoImpact ? PayrollRetroHistoryChangeType.NoImpact : PayrollRetroHistoryChangeType.Evaluated, "Retro evaluation completed without mutating historical payroll results."); await db.SaveChangesAsync(ct); return Result<PayrollRetroCaseDto>.Success(await LoadRetroDtoAsync(item.Id, ct));
    }

    public async Task<Result<PayrollRetroCaseDto>> ApproveRetroAsync(Guid id, CancellationToken ct = default)
    {
        var item = await db.PayrollRetroCases.FirstOrDefaultAsync(x => x.TenantId == tenant.TenantId && x.Id == id, ct);
        if (item is null) return Result<PayrollRetroCaseDto>.NotFound("Retro case not found.");
        var guard = await (approvalGuard ?? new PayrollApprovalGuard(db, tenant)).ValidateAsync(item.DetectedByUserId, "approve", ct: ct);
        if (!guard.Succeeded) return Result<PayrollRetroCaseDto>.Failure(guard.Status, guard.Message, guard.Errors);
        return await TransitionRetroAsync(id, PayrollRetroStatus.Approved, PayrollRetroStatus.Evaluated, PayrollRetroHistoryChangeType.Approved, "Retro case approved.", ct);
    }

    public async Task<Result<PayrollRetroCaseDto>> ApplyRetroAsync(Guid id, Guid targetPayrollRunId, CancellationToken ct = default)
    {
        var item = await db.PayrollRetroCases.FirstOrDefaultAsync(x => x.TenantId == tenant.TenantId && x.Id == id, ct); if (item is null) return Result<PayrollRetroCaseDto>.NotFound("Retro case not found."); if (item.Status != PayrollRetroStatus.Approved) return Result<PayrollRetroCaseDto>.Conflict("Only approved retro cases can be applied."); if (!await db.PayrollRuns.AnyAsync(x => x.TenantId == item.TenantId && x.Id == targetPayrollRunId && (x.Status == PayrollRunStatus.Prepared || x.Status == PayrollRunStatus.Draft), ct)) return Result<PayrollRetroCaseDto>.Conflict("Target payroll run is not eligible for adjustments.");
        var guard = await (approvalGuard ?? new PayrollApprovalGuard(db, tenant)).ValidateAsync(item.DetectedByUserId, "apply", ct: ct); if (!guard.Succeeded) return Result<PayrollRetroCaseDto>.Failure(guard.Status, guard.Message, guard.Errors);
        var results = await db.PayrollRetroResults.Where(x => x.TenantId == item.TenantId && x.PayrollRetroCaseId == id).Include(x => x.Components).ToListAsync(ct); foreach (var result in results) foreach (var component in result.Components.Where(x => x.DifferenceAmount != 0)) db.PayrollAdjustments.Add(new PayrollAdjustment { Id = Guid.NewGuid(), TenantId = item.TenantId, EmployeeId = item.EmployeeId, SourceType = nameof(PayrollRetroResult), SourceId = result.Id, AdjustmentType = component.IsDeduction ? PayrollAdjustmentType.ArrearDeduction : PayrollAdjustmentType.ArrearEarning, ComponentCode = component.ComponentCode, Description = $"Retro adjustment for {result.PeriodStartDate:yyyy-MM-dd}", Amount = component.DifferenceAmount, CurrencyCode = result.CurrencyCode, TargetPayrollRunId = targetPayrollRunId });
        item.Status = PayrollRetroStatus.Applied; AddHistory(item, PayrollRetroHistoryChangeType.Applied, "Retro adjustments attached to target payroll run."); await db.SaveChangesAsync(ct); return Result<PayrollRetroCaseDto>.Success(await LoadRetroDtoAsync(id, ct));
    }

    public async Task<Result<FinalSettlementDto>> CreateSettlementAsync(FinalSettlementRequest request, CancellationToken ct = default)
    {
        if (tenant.TenantId is not Guid tenantId) return Result<FinalSettlementDto>.Unauthorized("No authenticated tenant."); if (request.LastWorkingDate > request.SeparationDate || request.SettlementDate < request.SeparationDate) return Result<FinalSettlementDto>.Invalid("dates", "Settlement dates are invalid."); if (await db.FinalSettlementCases.AnyAsync(x => x.TenantId == tenantId && x.EmployeeId == request.EmployeeId && x.SeparationDate == request.SeparationDate && x.Status != FinalSettlementStatus.Cancelled, ct)) return Result<FinalSettlementDto>.Conflict("An active final settlement already exists for this separation.");
        var employee = await db.Employees.AsNoTracking().FirstOrDefaultAsync(x => x.TenantId == tenantId && x.Id == request.EmployeeId, ct); if (employee is null) return Result<FinalSettlementDto>.NotFound("Employee not found."); var item = new FinalSettlementCase { Id = Guid.NewGuid(), TenantId = tenantId, EmployeeId = request.EmployeeId, CreatedByUserId = tenant.UserId, SeparationDate = request.SeparationDate, LastWorkingDate = request.LastWorkingDate, SettlementDate = request.SettlementDate, CurrencyCode = request.CurrencyCode, EmployeeCodeSnapshot = employee.EmployeeCode ?? string.Empty, EmployeeNameSnapshot = string.Join(' ', new[] { employee.FirstName, employee.LastName }.Where(x => !string.IsNullOrWhiteSpace(x))), DateOfJoiningSnapshot = employee.DateOfJoining }; db.FinalSettlementCases.Add(item); AddHistory(item, FinalSettlementHistoryChangeType.Created, "Final settlement case created."); await db.SaveChangesAsync(ct); db.ClearChangeTracker(); return Result<FinalSettlementDto>.Success(ToDto(item));
    }

    public async Task<Result<FinalSettlementDto>> AddSettlementLineAsync(Guid id, FinalSettlementLineRequest request, CancellationToken ct = default)
    { var item = await db.FinalSettlementCases.AsNoTracking().FirstOrDefaultAsync(x => x.TenantId == tenant.TenantId && x.Id == id, ct); if (item is null) return Result<FinalSettlementDto>.NotFound("Final settlement not found."); if (item.Status is not FinalSettlementStatus.Draft and not FinalSettlementStatus.Calculated) return Result<FinalSettlementDto>.Conflict("Finalized settlement lines are immutable."); var sequence = await db.FinalSettlementLines.CountAsync(x => x.TenantId == item.TenantId && x.FinalSettlementCaseId == item.Id, ct) + 1; db.FinalSettlementLines.Add(new FinalSettlementLine { Id = Guid.NewGuid(), TenantId = item.TenantId, FinalSettlementCaseId = item.Id, LineType = request.LineType, ComponentCode = request.ComponentCode, Description = request.Description, Amount = request.Amount, IsEarning = request.IsEarning, IsDeduction = request.IsDeduction, SourceType = request.SourceType, SourceId = request.SourceId, Sequence = sequence }); await db.SaveChangesAsync(ct); return Result<FinalSettlementDto>.Success(await LoadSettlementDtoAsync(id, ct)); }

    public async Task<Result<FinalSettlementDto>> CalculateSettlementAsync(Guid id, CancellationToken ct = default)
    { var item = await db.FinalSettlementCases.FirstOrDefaultAsync(x => x.TenantId == tenant.TenantId && x.Id == id, ct); if (item is null) return Result<FinalSettlementDto>.NotFound("Final settlement not found."); if (item.Status is not FinalSettlementStatus.Draft and not FinalSettlementStatus.Calculated) return Result<FinalSettlementDto>.Conflict("Settlement cannot be calculated in its current state."); var lines = await db.FinalSettlementLines.AsNoTracking().Where(x => x.TenantId == item.TenantId && x.FinalSettlementCaseId == item.Id).ToListAsync(ct); item.GrossPayable = PayrollRounding(lines.Where(x => x.IsEarning).Sum(x => x.Amount)); item.TotalDeductions = PayrollRounding(lines.Where(x => x.IsDeduction).Sum(x => x.Amount)); item.NetSettlement = PayrollRounding(item.GrossPayable - item.TotalDeductions); item.Status = FinalSettlementStatus.Calculated; AddHistory(item, FinalSettlementHistoryChangeType.Calculated, "Final settlement calculated from explicit settlement lines."); await db.SaveChangesAsync(ct); return Result<FinalSettlementDto>.Success(await LoadSettlementDtoAsync(id, ct)); }

    public Task<Result<FinalSettlementDto>> ApproveSettlementAsync(Guid id, CancellationToken ct = default) => TransitionSettlementAsync(id, FinalSettlementStatus.Approved, FinalSettlementStatus.Calculated, FinalSettlementHistoryChangeType.Approved, "Final settlement approved.", "approve", ct);
    public Task<Result<FinalSettlementDto>> FinalizeSettlementAsync(Guid id, CancellationToken ct = default) => TransitionSettlementAsync(id, FinalSettlementStatus.Finalized, FinalSettlementStatus.Approved, FinalSettlementHistoryChangeType.Finalized, "Final settlement finalized.", "finalize", ct);

    private async Task<Result<PayrollRetroCaseDto>> TransitionRetroAsync(Guid id, PayrollRetroStatus next, PayrollRetroStatus required, PayrollRetroHistoryChangeType change, string message, CancellationToken ct) { var item = await db.PayrollRetroCases.FirstOrDefaultAsync(x => x.TenantId == tenant.TenantId && x.Id == id, ct); if (item is null) return Result<PayrollRetroCaseDto>.NotFound("Retro case not found."); if (item.Status != required) return Result<PayrollRetroCaseDto>.Conflict($"Retro case must be {required}."); item.Status = next; AddHistory(item, change, message); await db.SaveChangesAsync(ct); return Result<PayrollRetroCaseDto>.Success(await LoadRetroDtoAsync(id, ct)); }
    private async Task<Result<FinalSettlementDto>> TransitionSettlementAsync(Guid id, FinalSettlementStatus next, FinalSettlementStatus required, FinalSettlementHistoryChangeType change, string message, string action, CancellationToken ct) { var item = await db.FinalSettlementCases.Include(x => x.Lines).FirstOrDefaultAsync(x => x.TenantId == tenant.TenantId && x.Id == id, ct); if (item is null) return Result<FinalSettlementDto>.NotFound("Final settlement not found."); if (item.Status != required) return Result<FinalSettlementDto>.Conflict($"Final settlement must be {required}."); if (next == FinalSettlementStatus.Finalized && item.NetSettlement < 0) return Result<FinalSettlementDto>.Conflict("Negative final settlement cannot be finalized."); var maker = next == FinalSettlementStatus.Approved ? item.CreatedByUserId : item.ApprovedByUserId; var guard = await (approvalGuard ?? new PayrollApprovalGuard(db, tenant)).ValidateAsync(maker, action, ct: ct); if (!guard.Succeeded) return Result<FinalSettlementDto>.Failure(guard.Status, guard.Message, guard.Errors); item.Status = next; item.ConcurrencyVersion++; if (next == FinalSettlementStatus.Approved) { item.ApprovedAtUtc = clock.GetUtcNow().UtcDateTime; item.ApprovedByUserId = tenant.UserId; } else { item.FinalizedAtUtc = clock.GetUtcNow().UtcDateTime; item.FinalizedByUserId = tenant.UserId; } AddHistory(item, change, message); await db.SaveChangesAsync(ct); return Result<FinalSettlementDto>.Success(ToDto(item)); }
    private void AddHistory(PayrollRetroCase item, PayrollRetroHistoryChangeType change, string message) => db.PayrollRetroHistories.Add(new PayrollRetroHistory { Id = Guid.NewGuid(), TenantId = item.TenantId, PayrollRetroCaseId = item.Id, ChangeType = change, ChangedAtUtc = clock.GetUtcNow().UtcDateTime, ActorUserId = tenant.UserId, Message = message });
    private void AddHistory(FinalSettlementCase item, FinalSettlementHistoryChangeType change, string message) => db.FinalSettlementHistories.Add(new FinalSettlementHistory { Id = Guid.NewGuid(), TenantId = item.TenantId, FinalSettlementCaseId = item.Id, ChangeType = change, ChangedAtUtc = clock.GetUtcNow().UtcDateTime, ActorUserId = tenant.UserId, Message = message });
    private async Task<PayrollRetroCaseDto> LoadRetroDtoAsync(Guid id, CancellationToken ct) { var item = await db.PayrollRetroCases.AsNoTracking().Include(x => x.Results).ThenInclude(x => x.Components).SingleAsync(x => x.TenantId == tenant.TenantId && x.Id == id, ct); return ToDto(item); }
    private static PayrollRetroCaseDto ToDto(PayrollRetroCase x) => new(x.Id, x.EmployeeId, x.TriggerType, x.EffectiveFrom, x.EffectiveTo, x.Status, x.Results.Select(r => new PayrollRetroResultDto(r.Id, r.PayrollRetroCaseId, r.OriginalPayrollRunId, r.OriginalPayrollResultId, r.PeriodStartDate, r.PeriodEndDate, r.OriginalGross, r.CorrectedGross, r.GrossDifference, r.OriginalDeductions, r.CorrectedDeductions, r.DeductionDifference, r.OriginalNet, r.CorrectedNet, r.NetDifference, r.CurrencyCode, r.Components.OrderBy(c => c.Sequence).Select(c => new PayrollRetroComponentDto(c.Id, c.ComponentCode, c.ComponentName, c.OriginalAmount, c.CorrectedAmount, c.DifferenceAmount, c.IsEarning, c.IsDeduction, c.IsStatutory)).ToList())).ToList());
    private async Task<FinalSettlementDto> LoadSettlementDtoAsync(Guid id, CancellationToken ct) { var item = await db.FinalSettlementCases.AsNoTracking().Include(x => x.Lines).SingleAsync(x => x.TenantId == tenant.TenantId && x.Id == id, ct); return ToDto(item); }
    private static FinalSettlementDto ToDto(FinalSettlementCase x) => new(x.Id, x.EmployeeId, x.SeparationDate, x.LastWorkingDate, x.SettlementDate, x.Status, x.GrossPayable, x.TotalDeductions, x.NetSettlement, x.CurrencyCode, x.Lines.OrderBy(x => x.Sequence).Select(l => new FinalSettlementLineDto(l.Id, l.LineType, l.ComponentCode, l.Description, l.Amount, l.IsEarning, l.IsDeduction, l.SourceType, l.SourceId)).ToList());
    private static decimal PayrollRounding(decimal amount) => decimal.Round(amount, 2, MidpointRounding.AwayFromZero);
}
