using System.Globalization;
using HRMS.Application.Abstractions;
using HRMS.Application.Common;
using HRMS.Application.DTOs.Payroll;
using HRMS.Domain.Entities;
using HRMS.Domain.Enums;
using Microsoft.EntityFrameworkCore;

namespace HRMS.Application.Services;

/// <summary>Read-only management reporting over persisted payroll evidence.</summary>
public sealed class PayrollReportsService(IHrmsDbContext db, ITenantContext tenant) : IPayrollReportsService
{
    private IQueryable<PayrollResult> Results(PayrollReportQuery q) =>
        db.PayrollResults.AsNoTracking().Where(x => x.TenantId == tenant.TenantId && x.IsCurrent && x.Status == PayrollResultStatus.Calculated)
            .Where(x => !q.PayrollRunId.HasValue || x.PayrollRunId == q.PayrollRunId)
            .Where(x => !q.PayrollPeriodId.HasValue || x.PayrollRun!.PayrollPeriodId == q.PayrollPeriodId)
            .Where(x => !q.EmployeeId.HasValue || x.EmployeeId == q.EmployeeId)
            .Where(x => string.IsNullOrWhiteSpace(q.Search) || x.Employee!.EmployeeCode!.Contains(q.Search!) || (x.Employee.FirstName + " " + x.Employee.LastName).Contains(q.Search!))
            .Where(x => !q.DepartmentId.HasValue || x.PayrollRunEmployee!.DepartmentId == q.DepartmentId)
            .Where(x => !q.CostCenterId.HasValue || x.PayrollRunEmployee!.CostCenterId == q.CostCenterId);

    public async Task<Result<PagedResult<PayrollReportRegisterRowDto>>> GetRegisterAsync(PayrollReportQuery query, CancellationToken ct = default)
    {
        var source = Results(query).OrderBy(x => x.PayrollRun!.PayrollPeriod!.EndDate).ThenBy(x => x.Employee!.EmployeeCode).ThenBy(x => x.Id);
        var total = await source.CountAsync(ct);
        var rows = await source.Skip((query.Page - 1) * query.PageSize).Take(query.PageSize)
            .Select(x => new { x, EmployeeCode = x.Employee!.EmployeeCode ?? string.Empty, EmployeeName = x.Employee.FirstName + " " + x.Employee.LastName, x.PayrollRun!.RunType, PeriodEnd = x.PayrollRun.PayrollPeriod!.EndDate, DepartmentId = x.PayrollRunEmployee!.DepartmentId, CostCenterId = x.PayrollRunEmployee.CostCenterId }).ToListAsync(ct);
        var componentTotals = await ComponentTotals(rows.Select(x => x.x.Id), ct);
        var departments = await NamesAsync(true, rows.Select(x => x.DepartmentId).Where(x => x.HasValue).Select(x => x!.Value), ct);
        var centers = await NamesAsync(false, rows.Select(x => x.CostCenterId).Where(x => x.HasValue).Select(x => x!.Value), ct);
        var output = rows.Select(x => { var c = componentTotals.GetValueOrDefault(x.x.Id); return new PayrollReportRegisterRowDto(x.x.PayrollRunId, x.x.Id, x.x.EmployeeId, x.EmployeeCode, x.EmployeeName, x.PeriodEnd, x.RunType, Label(x.DepartmentId, departments), Label(x.CostCenterId, centers), c.Earnings, x.x.GrossEarnings, x.x.TotalDeductions, c.Tax, x.x.EmployerContributions, x.x.NetPay, c.Reimbursement, c.Loan, c.Variable, c.Adjustment, x.x.Status); }).ToList();
        return Result<PagedResult<PayrollReportRegisterRowDto>>.Success(new(output, query.Page, query.PageSize, total));
    }

    public Task<Result<PagedResult<PayrollComponentReportRowDto>>> GetEarningsAsync(PayrollReportQuery q, CancellationToken ct = default) => ComponentsAsync(q, "earning", ct);
    public Task<Result<PagedResult<PayrollComponentReportRowDto>>> GetDeductionsAsync(PayrollReportQuery q, CancellationToken ct = default) => ComponentsAsync(q, "deduction", ct);
    public Task<Result<PagedResult<PayrollComponentReportRowDto>>> GetEmployerContributionsAsync(PayrollReportQuery q, CancellationToken ct = default) => ComponentsAsync(q, "employer", ct);

    private async Task<Result<PagedResult<PayrollComponentReportRowDto>>> ComponentsAsync(PayrollReportQuery q, string mode, CancellationToken ct)
    {
        var source = Results(q).SelectMany(x => x.Components).AsNoTracking();
        source = mode switch { "earning" => source.Where(x => x.IsEarning), "deduction" => source.Where(x => x.IsDeduction), _ => source.Where(x => x.IsEmployerContribution) };
        if (!string.IsNullOrWhiteSpace(q.ComponentType)) source = source.Where(x => x.ComponentType.ToString() == q.ComponentType);
        var total = await source.CountAsync(ct);
        var output = await source.OrderBy(x => x.ComponentCode).ThenBy(x => x.Id).Skip((q.Page - 1) * q.PageSize).Take(q.PageSize).Select(x => new PayrollComponentReportRowDto(x.PayrollResult!.PayrollRunId, x.PayrollResultId, x.PayrollResult.EmployeeId, x.PayrollResult.Employee!.EmployeeCode ?? string.Empty, x.PayrollResult.Employee.FirstName + " " + x.PayrollResult.Employee.LastName, x.ComponentCode, x.ComponentName, x.ComponentType, x.CalculatedAmount, x.IsEarning, x.IsDeduction, x.IsEmployerContribution)).ToListAsync(ct);
        return Result<PagedResult<PayrollComponentReportRowDto>>.Success(new(output, q.Page, q.PageSize, total));
    }

    public async Task<Result<IReadOnlyList<PayrollDimensionReportRowDto>>> GetDepartmentsAsync(PayrollReportQuery q, CancellationToken ct = default) => Result<IReadOnlyList<PayrollDimensionReportRowDto>>.Success(await DimensionsAsync(q, true, ct));
    public async Task<Result<IReadOnlyList<PayrollDimensionReportRowDto>>> GetCostCentersAsync(PayrollReportQuery q, CancellationToken ct = default) => Result<IReadOnlyList<PayrollDimensionReportRowDto>>.Success(await DimensionsAsync(q, false, ct));

    private async Task<IReadOnlyList<PayrollDimensionReportRowDto>> DimensionsAsync(PayrollReportQuery q, bool department, CancellationToken ct)
    {
        var rows = await Results(q).Select(x => new { x, DimensionId = department ? x.PayrollRunEmployee!.DepartmentId : x.PayrollRunEmployee!.CostCenterId }).ToListAsync(ct);
        var groups = rows.GroupBy(x => x.DimensionId).ToList(); var names = await NamesAsync(department, groups.Where(x => x.Key.HasValue).Select(x => x.Key!.Value), ct);
        return groups.Select(g => { var t = g.Select(x => x.x); var id = g.Key; var label = Label(id, names); return new PayrollDimensionReportRowDto(id, label, label, t.Select(x => x.EmployeeId).Distinct().Count(), t.Count(), t.Sum(x => x.GrossEarnings), t.Sum(x => x.GrossEarnings), t.Sum(x => x.TotalDeductions), t.SelectMany(x => x.Components).Where(x => x.IsTaxable && x.IsDeduction).Sum(x => x.CalculatedAmount), t.Sum(x => x.EmployerContributions), t.Sum(x => x.NetPay)); }).OrderBy(x => x.Code).ToList();
    }

    public async Task<Result<IReadOnlyList<PayrollComponentSummaryRowDto>>> GetComponentsAsync(PayrollReportQuery q, CancellationToken ct = default)
    {
        var components = await Results(q).SelectMany(x => x.Components).AsNoTracking().ToListAsync(ct);
        var groups = components.Where(x => string.IsNullOrWhiteSpace(q.ComponentType) || x.ComponentType.ToString().Equals(q.ComponentType, StringComparison.OrdinalIgnoreCase)).GroupBy(x => new { x.ComponentCode, x.ComponentName, x.ComponentType });
        return Result<IReadOnlyList<PayrollComponentSummaryRowDto>>.Success(groups.OrderBy(x => x.Key.ComponentCode).Select(x => new PayrollComponentSummaryRowDto(x.Key.ComponentCode, x.Key.ComponentName, x.Key.ComponentType, x.Select(y => y.PayrollResultId).Distinct().Count(), x.Sum(y => y.CalculatedAmount), x.Any() ? x.Average(y => y.CalculatedAmount) : 0m, x.Any() ? x.Min(y => y.CalculatedAmount) : 0m, x.Any() ? x.Max(y => y.CalculatedAmount) : 0m)).ToList());
    }

    public async Task<Result<IReadOnlyList<PayrollStatutorySummaryRowDto>>> GetStatutorySummaryAsync(PayrollReportQuery q, CancellationToken ct = default)
    {
        var ids = await Results(q).Select(x => x.Id).ToListAsync(ct); var rows = await db.PayrollStatutoryResults.AsNoTracking().Where(x => x.TenantId == tenant.TenantId && ids.Contains(x.PayrollResultId)).ToListAsync(ct);
        return Result<IReadOnlyList<PayrollStatutorySummaryRowDto>>.Success(rows.GroupBy(x => x.StatutoryType).OrderBy(x => x.Key).Select(x => new PayrollStatutorySummaryRowDto(x.Key, x.Select(y => y.EmployeeId).Distinct().Count(), x.Sum(y => y.EmployeeAmount), x.Sum(y => y.EmployerAmount), x.Sum(y => y.TotalAmount))).ToList());
    }

    public async Task<Result<PagedResult<PayrollBankPaymentReportRowDto>>> GetBankPaymentsAsync(PayrollReportQuery q, CancellationToken ct = default)
    {
        var source = db.BankAdvicePayments.AsNoTracking().Where(x => x.TenantId == tenant.TenantId && (!q.PayrollRunId.HasValue || x.Batch!.PayrollRunId == q.PayrollRunId) && (!q.EmployeeId.HasValue || x.EmployeeId == q.EmployeeId) && (string.IsNullOrWhiteSpace(q.Search) || x.EmployeeCode.Contains(q.Search!) || x.EmployeeName.Contains(q.Search!))).OrderBy(x => x.EmployeeCode).ThenBy(x => x.Id);
        var total = await source.CountAsync(ct); var rows = await source.Skip((q.Page - 1) * q.PageSize).Take(q.PageSize).Select(x => new PayrollBankPaymentReportRowDto(x.Batch!.PayrollRunId, x.Batch.BatchNumber, x.EmployeeId, x.EmployeeCode, x.EmployeeName, x.NetPay, x.PaymentReference, x.PaymentStatus, x.ValidationStatus)).ToListAsync(ct);
        return Result<PagedResult<PayrollBankPaymentReportRowDto>>.Success(new(rows, q.Page, q.PageSize, total));
    }

    public async Task<Result<IReadOnlyList<PayrollAccountingSummaryRowDto>>> GetAccountingSummaryAsync(PayrollReportQuery q, CancellationToken ct = default)
    {
        var rows = await db.PayrollJournalBatches.AsNoTracking().Where(x => x.TenantId == tenant.TenantId && (!q.PayrollRunId.HasValue || x.PayrollRunId == q.PayrollRunId) && (!q.PayrollPeriodId.HasValue || x.PayrollPeriodId == q.PayrollPeriodId)).OrderBy(x => x.JournalDate).ThenBy(x => x.JournalNumber).Select(x => new PayrollAccountingSummaryRowDto(x.PayrollRunId, x.JournalNumber, x.TotalDebit, x.TotalCredit, x.TotalDebit == x.TotalCredit, x.Status, x.LineCount)).ToListAsync(ct);
        return Result<IReadOnlyList<PayrollAccountingSummaryRowDto>>.Success(rows);
    }

    public async Task<Result<PagedResult<PayrollLoanReportRowDto>>> GetLoanRecoveriesAsync(PayrollReportQuery q, CancellationToken ct = default) => await PageAsync(db.LoanRepayments.AsNoTracking().Where(x => x.TenantId == tenant.TenantId && (!q.PayrollRunId.HasValue || x.PayrollRunId == q.PayrollRunId) && (!q.EmployeeId.HasValue || x.EmployeeLoan!.EmployeeId == q.EmployeeId)).OrderByDescending(x => x.PaymentDate).Select(x => new PayrollLoanReportRowDto(x.EmployeeLoan!.EmployeeId, x.EmployeeLoan.Employee!.EmployeeCode ?? string.Empty, x.EmployeeLoanId, x.LoanInstallmentId, x.PayrollRunId, x.Amount, x.PrincipalAmount, x.InterestAmount, x.PaymentDate, x.Reference)), q, ct);
    public async Task<Result<PagedResult<PayrollReimbursementReportRowDto>>> GetReimbursementsAsync(PayrollReportQuery q, CancellationToken ct = default) => await PageAsync(db.ReimbursementSettlements.AsNoTracking().Where(x => x.TenantId == tenant.TenantId && (!q.PayrollRunId.HasValue || x.PayrollRunId == q.PayrollRunId) && (!q.EmployeeId.HasValue || x.EmployeeId == q.EmployeeId)).OrderByDescending(x => x.SettlementDate).Select(x => new PayrollReimbursementReportRowDto(x.EmployeeId, x.Claim!.Employee!.EmployeeCode ?? string.Empty, x.ReimbursementClaimId, x.PayrollRunId, x.PayrollResultId, x.Amount, x.TaxableAmount, x.NonTaxableAmount, x.SettlementDate, x.Reference)), q, ct);
    public async Task<Result<PagedResult<PayrollVariablePayReportRowDto>>> GetVariablePayAsync(PayrollReportQuery q, CancellationToken ct = default) => await PageAsync(db.VariablePaySettlements.AsNoTracking().Where(x => x.TenantId == tenant.TenantId && (!q.PayrollRunId.HasValue || x.PayrollRunId == q.PayrollRunId) && (!q.EmployeeId.HasValue || x.EmployeeId == q.EmployeeId)).OrderByDescending(x => x.SettlementDate).Select(x => new PayrollVariablePayReportRowDto(x.EmployeeId, x.Employee!.EmployeeCode ?? string.Empty, x.VariablePayAwardId, x.VariablePayAward!.AwardNumber, x.PayrollRunId, x.Amount, x.TaxableAmount, x.NonTaxableAmount, x.SettlementDate, x.Reference)), q, ct);
    public async Task<Result<PagedResult<PayrollAdjustmentReportRowDto>>> GetAdjustmentsAsync(PayrollReportQuery q, CancellationToken ct = default) => await PageAsync(db.PayrollAdjustmentApplications.AsNoTracking().Where(x => x.TenantId == tenant.TenantId && (!q.PayrollRunId.HasValue || x.PayrollRunId == q.PayrollRunId)).OrderByDescending(x => x.AppliedDate).Select(x => new PayrollAdjustmentReportRowDto(x.PayrollAdjustmentId, x.PayrollRunId, x.PayrollResultId, x.FinalSettlementId, x.AppliedAmount, x.AppliedDate, x.Adjustment!.AdjustmentType, x.Adjustment.Status)), q, ct);
    public async Task<Result<PagedResult<PayrollFinalSettlementReportRowDto>>> GetFinalSettlementsAsync(PayrollReportQuery q, CancellationToken ct = default) { var source = db.FinalSettlementCases.AsNoTracking().Where(x => x.TenantId == tenant.TenantId && (!q.PayrollRunId.HasValue || x.PayrollRunId == q.PayrollRunId) && (!q.EmployeeId.HasValue || x.EmployeeId == q.EmployeeId)).OrderByDescending(x => x.SettlementDate).ThenBy(x => x.EmployeeCodeSnapshot); var total = await source.CountAsync(ct); var cases = await source.Skip((q.Page - 1) * q.PageSize).Take(q.PageSize).ToListAsync(ct); var ids = cases.Select(x => x.Id).ToList(); var lines = await db.FinalSettlementLines.AsNoTracking().Where(x => x.TenantId == tenant.TenantId && ids.Contains(x.FinalSettlementCaseId)).ToListAsync(ct); var output = cases.Select(x => { var l = lines.Where(y => y.FinalSettlementCaseId == x.Id); return new PayrollFinalSettlementReportRowDto(x.Id, x.EmployeeId, x.EmployeeCodeSnapshot, x.EmployeeNameSnapshot, x.SettlementDate, x.Status, x.GrossPayable, x.TotalDeductions, x.NetSettlement, SumLine(l, FinalSettlementLineType.Gratuity), SumLine(l, FinalSettlementLineType.LeaveEncashment), SumLine(l, FinalSettlementLineType.NoticePay), SumLine(l, FinalSettlementLineType.NoticeRecovery), SumLine(l, FinalSettlementLineType.Reimbursement), l.Where(y => y.ComponentCode.Contains("loan", StringComparison.OrdinalIgnoreCase)).Sum(y => y.Amount), l.Where(y => y.ComponentCode.Contains("variable", StringComparison.OrdinalIgnoreCase)).Sum(y => y.Amount), l.Where(y => y.ComponentCode.Contains("adjust", StringComparison.OrdinalIgnoreCase)).Sum(y => y.Amount)); }).ToList(); return Result<PagedResult<PayrollFinalSettlementReportRowDto>>.Success(new(output, q.Page, q.PageSize, total)); }
    public async Task<Result<PagedResult<PayrollOffCycleReportRowDto>>> GetOffCycleAsync(PayrollReportQuery q, CancellationToken ct = default) => await PageAsync(Results(q).Where(x => x.PayrollRun!.RunType == PayrollRunType.OffCycle).OrderByDescending(x => x.PayrollRun!.PayrollPeriod!.EndDate).Select(x => new PayrollOffCycleReportRowDto(x.PayrollRunId, x.PayrollRun!.RunNumber, x.EmployeeId, x.Employee!.EmployeeCode ?? string.Empty, x.Employee.FirstName + " " + x.Employee.LastName, x.GrossEarnings, x.TotalDeductions, x.NetPay, x.PayrollRun.Status)), q, ct);

    public async Task<Result<PayrollDashboardDto>> GetDashboardAsync(PayrollReportQuery q, CancellationToken ct = default)
    {
        var rows = await Results(q).ToListAsync(ct); var components = await db.PayrollResultComponents.AsNoTracking().Where(x => x.TenantId == tenant.TenantId && rows.Select(r => r.Id).Contains(x.PayrollResultId)).ToListAsync(ct); var statutory = await db.PayrollStatutoryResults.AsNoTracking().Where(x => x.TenantId == tenant.TenantId && rows.Select(r => r.Id).Contains(x.PayrollResultId)).ToListAsync(ct); var runs = rows.Select(x => x.PayrollRunId).Distinct().Count();
        return Result<PayrollDashboardDto>.Success(new(runs, rows.Select(x => x.EmployeeId).Distinct().Count(), rows.Sum(x => x.GrossEarnings), rows.Sum(x => x.TotalDeductions), rows.Sum(x => x.NetPay), rows.Sum(x => x.EmployerContributions), statutory.Sum(x => x.EmployeeAmount), components.Where(x => x.CalculationSource.Contains("reimbursement", StringComparison.OrdinalIgnoreCase)).Sum(x => x.CalculatedAmount), components.Where(x => x.CalculationSource.Contains("loan", StringComparison.OrdinalIgnoreCase)).Sum(x => x.CalculatedAmount), components.Where(x => x.CalculationSource.Contains("variable", StringComparison.OrdinalIgnoreCase)).Sum(x => x.CalculatedAmount), components.Where(x => x.CalculationSource.Contains("adjustment", StringComparison.OrdinalIgnoreCase)).Sum(x => x.CalculatedAmount), await db.FinalSettlementCases.AsNoTracking().Where(x => x.TenantId == tenant.TenantId && (!q.PayrollRunId.HasValue || x.PayrollRunId == q.PayrollRunId)).SumAsync(x => (decimal?)x.NetSettlement, ct) ?? 0m, await db.PayrollAnomalyFlags.AsNoTracking().CountAsync(x => x.TenantId == tenant.TenantId && x.Status == PayrollFindingStatus.Open, ct)));
    }

    public async Task<Result<IReadOnlyList<PayrollTrendRowDto>>> GetTrendsAsync(PayrollReportQuery q, CancellationToken ct = default)
    {
        var runs = await db.PayrollRuns.AsNoTracking().Include(x => x.PayrollPeriod).Where(x => x.TenantId == tenant.TenantId && (!q.PayrollRunId.HasValue || x.Id == q.PayrollRunId) && (!q.PayrollPeriodId.HasValue || x.PayrollPeriodId == q.PayrollPeriodId)).OrderBy(x => x.PayrollPeriod!.EndDate).ToListAsync(ct); var output = new List<PayrollTrendRowDto>();
        foreach (var run in runs) { var rows = await Results(new PayrollReportQuery { PayrollRunId = run.Id, PageSize = PagedQuery.MaxPageSize }).ToListAsync(ct); output.Add(new PayrollTrendRowDto(run.Id, run.PayrollPeriodId, run.PayrollPeriod!.EndDate, run.RunType, rows.Select(x => x.EmployeeId).Distinct().Count(), rows.Sum(x => x.GrossEarnings), rows.Sum(x => x.TotalDeductions), rows.Sum(x => x.NetPay), rows.Sum(x => x.EmployerContributions), 0m, 0m, 0m, 0m, 0m)); }
        return Result<IReadOnlyList<PayrollTrendRowDto>>.Success(output);
    }

    public async Task<Result<PayrollOutputFile>> ExportRegisterAsync(PayrollReportQuery q, CancellationToken ct = default)
    {
        var result = await GetRegisterAsync(new PayrollReportQuery { PayrollRunId = q.PayrollRunId, PayrollPeriodId = q.PayrollPeriodId, Search = q.Search, Page = 1, PageSize = PagedQuery.MaxPageSize }, ct); if (!result.Succeeded) return Result<PayrollOutputFile>.Failure(result.Status, result.Message); var csv = new CsvBuilder("PayrollRunId", "EmployeeCode", "EmployeeName", "PeriodEndDate", "RunType", "Department", "CostCenter", "EarningsTotal", "GrossTotal", "DeductionTotal", "TaxTotal", "EmployerContributionTotal", "NetPay", "ReimbursementTotal", "LoanRecoveryTotal", "VariablePayTotal", "AdjustmentTotal", "Status"); foreach (var x in result.Value!.Items) csv.AppendRow(x.PayrollRunId.ToString(), x.EmployeeCode, x.EmployeeName, x.PeriodEndDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture), x.RunType.ToString(), x.Department, x.CostCenter, x.EarningsTotal.ToString(CultureInfo.InvariantCulture), x.GrossTotal.ToString(CultureInfo.InvariantCulture), x.DeductionTotal.ToString(CultureInfo.InvariantCulture), x.TaxTotal.ToString(CultureInfo.InvariantCulture), x.EmployerContributionTotal.ToString(CultureInfo.InvariantCulture), x.NetPay.ToString(CultureInfo.InvariantCulture), x.ReimbursementTotal.ToString(CultureInfo.InvariantCulture), x.LoanRecoveryTotal.ToString(CultureInfo.InvariantCulture), x.VariablePayTotal.ToString(CultureInfo.InvariantCulture), x.AdjustmentTotal.ToString(CultureInfo.InvariantCulture), x.Status.ToString()); return Result<PayrollOutputFile>.Success(new PayrollOutputFile("payroll-register.csv", "text/csv; charset=utf-8", csv.ToUtf8Bytes()));
    }

    public async Task<Result<PayrollOutputFile>> ExportAsync(string report, PayrollReportQuery q, CancellationToken ct = default)
    {
        var key = report.Trim().ToLowerInvariant();
        if (key is "payroll-register" or "payroll-register.csv") return await ExportRegisterAsync(q, ct);
        var exportQuery = new PayrollReportQuery { PayrollRunId = q.PayrollRunId, PayrollPeriodId = q.PayrollPeriodId, EmployeeId = q.EmployeeId, DepartmentId = q.DepartmentId, CostCenterId = q.CostCenterId, Search = q.Search, ComponentType = q.ComponentType, Page = 1, PageSize = PagedQuery.MaxPageSize };
        var csv = key switch
        {
            "earnings" => await CsvComponentsAsync("Earnings", GetEarningsAsync(exportQuery, ct)),
            "deductions" => await CsvComponentsAsync("Deductions", GetDeductionsAsync(exportQuery, ct)),
            "employer-contributions" => await CsvComponentsAsync("EmployerContributions", GetEmployerContributionsAsync(exportQuery, ct)),
            "departments" => await CsvDimensionsAsync("Department", GetDepartmentsAsync(exportQuery, ct)),
            "cost-centers" => await CsvDimensionsAsync("CostCenter", GetCostCentersAsync(exportQuery, ct)),
            "components" => await CsvComponentSummaryAsync(GetComponentsAsync(exportQuery, ct)),
            "statutory-summary" => await CsvStatutoryAsync(GetStatutorySummaryAsync(exportQuery, ct)),
            "bank-payments" => await CsvBankAsync(GetBankPaymentsAsync(exportQuery, ct)),
            "accounting-summary" => await CsvAccountingAsync(GetAccountingSummaryAsync(exportQuery, ct)),
            "loan-recoveries" => await CsvLoansAsync(GetLoanRecoveriesAsync(exportQuery, ct)),
            "reimbursements" => await CsvReimbursementsAsync(GetReimbursementsAsync(exportQuery, ct)),
            "variable-pay" => await CsvVariablePayAsync(GetVariablePayAsync(exportQuery, ct)),
            "adjustments" => await CsvAdjustmentsAsync(GetAdjustmentsAsync(exportQuery, ct)),
            "final-settlements" => await CsvFinalSettlementsAsync(GetFinalSettlementsAsync(exportQuery, ct)),
            "off-cycle" => await CsvOffCycleAsync(GetOffCycleAsync(exportQuery, ct)),
            _ => Result<PayrollOutputFile>.NotFound("Unknown Payroll report export.")
        };
        return csv;
    }

    private static async Task<Result<PayrollOutputFile>> CsvComponentsAsync(string name, Task<Result<PagedResult<PayrollComponentReportRowDto>>> task) { var r = await task; if (!r.Succeeded) return Result<PayrollOutputFile>.Failure(r.Status, r.Message); var c = new CsvBuilder("PayrollRunId", "PayrollResultId", "EmployeeId", "EmployeeCode", "EmployeeName", "ComponentCode", "ComponentName", "ComponentType", "Amount", "IsEarning", "IsDeduction", "IsEmployerContribution"); foreach (var x in r.Value!.Items) c.AppendRow(x.PayrollRunId.ToString(), x.PayrollResultId.ToString(), x.EmployeeId.ToString(), x.EmployeeCode, x.EmployeeName, x.ComponentCode, x.ComponentName, x.ComponentType.ToString(), x.Amount.ToString(CultureInfo.InvariantCulture), x.IsEarning.ToString(), x.IsDeduction.ToString(), x.IsEmployerContribution.ToString()); return File(name, c); }
    private static async Task<Result<PayrollOutputFile>> CsvDimensionsAsync(string name, Task<Result<IReadOnlyList<PayrollDimensionReportRowDto>>> task) { var r = await task; if (!r.Succeeded) return Result<PayrollOutputFile>.Failure(r.Status, r.Message); var c = new CsvBuilder("DimensionId", "Code", "Name", "EmployeeCount", "ResultCount", "EarningsTotal", "GrossTotal", "DeductionTotal", "TaxTotal", "EmployerContributionTotal", "NetPayTotal"); foreach (var x in r.Value!) c.AppendRow(x.DimensionId?.ToString(), x.Code, x.Name, x.EmployeeCount.ToString(CultureInfo.InvariantCulture), x.ResultCount.ToString(CultureInfo.InvariantCulture), x.EarningsTotal.ToString(CultureInfo.InvariantCulture), x.GrossTotal.ToString(CultureInfo.InvariantCulture), x.DeductionTotal.ToString(CultureInfo.InvariantCulture), x.TaxTotal.ToString(CultureInfo.InvariantCulture), x.EmployerContributionTotal.ToString(CultureInfo.InvariantCulture), x.NetPayTotal.ToString(CultureInfo.InvariantCulture)); return File(name, c); }
    private static async Task<Result<PayrollOutputFile>> CsvComponentSummaryAsync(Task<Result<IReadOnlyList<PayrollComponentSummaryRowDto>>> task) { var r = await task; if (!r.Succeeded) return Result<PayrollOutputFile>.Failure(r.Status, r.Message); var c = new CsvBuilder("ComponentCode", "ComponentName", "ComponentType", "EmployeeCount", "TotalAmount", "AverageAmount", "MinimumAmount", "MaximumAmount"); foreach (var x in r.Value!) c.AppendRow(x.ComponentCode, x.ComponentName, x.ComponentType.ToString(), x.EmployeeCount.ToString(CultureInfo.InvariantCulture), x.TotalAmount.ToString(CultureInfo.InvariantCulture), x.AverageAmount.ToString(CultureInfo.InvariantCulture), x.MinimumAmount.ToString(CultureInfo.InvariantCulture), x.MaximumAmount.ToString(CultureInfo.InvariantCulture)); return File("Components", c); }
    private static async Task<Result<PayrollOutputFile>> CsvStatutoryAsync(Task<Result<IReadOnlyList<PayrollStatutorySummaryRowDto>>> task) { var r = await task; if (!r.Succeeded) return Result<PayrollOutputFile>.Failure(r.Status, r.Message); var c = new CsvBuilder("StatutoryType", "EmployeeCount", "EmployeeContribution", "EmployerContribution", "TotalAmount"); foreach (var x in r.Value!) c.AppendRow(x.StatutoryType.ToString(), x.EmployeeCount.ToString(CultureInfo.InvariantCulture), x.EmployeeContribution.ToString(CultureInfo.InvariantCulture), x.EmployerContribution.ToString(CultureInfo.InvariantCulture), x.TotalAmount.ToString(CultureInfo.InvariantCulture)); return File("StatutorySummary", c); }
    private static async Task<Result<PayrollOutputFile>> CsvBankAsync(Task<Result<PagedResult<PayrollBankPaymentReportRowDto>>> task) { var r = await task; if (!r.Succeeded) return Result<PayrollOutputFile>.Failure(r.Status, r.Message); var c = new CsvBuilder("PayrollRunId", "BatchNumber", "EmployeeId", "EmployeeCode", "EmployeeName", "NetPay", "PaymentReference", "PaymentStatus", "ValidationStatus"); foreach (var x in r.Value!.Items) c.AppendRow(x.PayrollRunId.ToString(), x.BatchNumber, x.EmployeeId.ToString(), x.EmployeeCode, x.EmployeeName, x.NetPay.ToString(CultureInfo.InvariantCulture), x.PaymentReference, x.PaymentStatus.ToString(), x.ValidationStatus.ToString()); return File("BankPayments", c); }
    private static async Task<Result<PayrollOutputFile>> CsvAccountingAsync(Task<Result<IReadOnlyList<PayrollAccountingSummaryRowDto>>> task) { var r = await task; if (!r.Succeeded) return Result<PayrollOutputFile>.Failure(r.Status, r.Message); var c = new CsvBuilder("PayrollRunId", "JournalNumber", "Debit", "Credit", "IsBalanced", "Status", "LineCount"); foreach (var x in r.Value!) c.AppendRow(x.PayrollRunId?.ToString(), x.JournalNumber, x.Debit.ToString(CultureInfo.InvariantCulture), x.Credit.ToString(CultureInfo.InvariantCulture), x.IsBalanced.ToString(), x.Status.ToString(), x.LineCount.ToString(CultureInfo.InvariantCulture)); return File("AccountingSummary", c); }
    private static async Task<Result<PayrollOutputFile>> CsvLoansAsync(Task<Result<PagedResult<PayrollLoanReportRowDto>>> task) { var r = await task; if (!r.Succeeded) return Result<PayrollOutputFile>.Failure(r.Status, r.Message); var c = new CsvBuilder("EmployeeId", "EmployeeCode", "EmployeeLoanId", "LoanInstallmentId", "PayrollRunId", "Amount", "PrincipalAmount", "InterestAmount", "PaymentDate", "Reference"); foreach (var x in r.Value!.Items) c.AppendRow(x.EmployeeId.ToString(), x.EmployeeCode, x.EmployeeLoanId.ToString(), x.LoanInstallmentId?.ToString(), x.PayrollRunId?.ToString(), x.Amount.ToString(CultureInfo.InvariantCulture), x.PrincipalAmount.ToString(CultureInfo.InvariantCulture), x.InterestAmount.ToString(CultureInfo.InvariantCulture), x.PaymentDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture), x.Reference); return File("LoanRecoveries", c); }
    private static async Task<Result<PayrollOutputFile>> CsvReimbursementsAsync(Task<Result<PagedResult<PayrollReimbursementReportRowDto>>> task) { var r = await task; if (!r.Succeeded) return Result<PayrollOutputFile>.Failure(r.Status, r.Message); var c = new CsvBuilder("EmployeeId", "EmployeeCode", "ClaimId", "PayrollRunId", "PayrollResultId", "Amount", "TaxableAmount", "NonTaxableAmount", "SettlementDate", "Reference"); foreach (var x in r.Value!.Items) c.AppendRow(x.EmployeeId.ToString(), x.EmployeeCode, x.ReimbursementClaimId.ToString(), x.PayrollRunId?.ToString(), x.PayrollResultId?.ToString(), x.Amount.ToString(CultureInfo.InvariantCulture), x.TaxableAmount.ToString(CultureInfo.InvariantCulture), x.NonTaxableAmount.ToString(CultureInfo.InvariantCulture), x.SettlementDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture), x.Reference); return File("Reimbursements", c); }
    private static async Task<Result<PayrollOutputFile>> CsvVariablePayAsync(Task<Result<PagedResult<PayrollVariablePayReportRowDto>>> task) { var r = await task; if (!r.Succeeded) return Result<PayrollOutputFile>.Failure(r.Status, r.Message); var c = new CsvBuilder("EmployeeId", "EmployeeCode", "AwardId", "AwardNumber", "PayrollRunId", "Amount", "TaxableAmount", "NonTaxableAmount", "SettlementDate", "Reference"); foreach (var x in r.Value!.Items) c.AppendRow(x.EmployeeId.ToString(), x.EmployeeCode, x.VariablePayAwardId.ToString(), x.AwardNumber, x.PayrollRunId?.ToString(), x.Amount.ToString(CultureInfo.InvariantCulture), x.TaxableAmount.ToString(CultureInfo.InvariantCulture), x.NonTaxableAmount.ToString(CultureInfo.InvariantCulture), x.SettlementDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture), x.Reference); return File("VariablePay", c); }
    private static async Task<Result<PayrollOutputFile>> CsvAdjustmentsAsync(Task<Result<PagedResult<PayrollAdjustmentReportRowDto>>> task) { var r = await task; if (!r.Succeeded) return Result<PayrollOutputFile>.Failure(r.Status, r.Message); var c = new CsvBuilder("AdjustmentId", "PayrollRunId", "PayrollResultId", "FinalSettlementId", "AppliedAmount", "AppliedDate", "AdjustmentType", "Status"); foreach (var x in r.Value!.Items) c.AppendRow(x.PayrollAdjustmentId.ToString(), x.PayrollRunId?.ToString(), x.PayrollResultId?.ToString(), x.FinalSettlementId?.ToString(), x.AppliedAmount.ToString(CultureInfo.InvariantCulture), x.AppliedDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture), x.AdjustmentType.ToString(), x.Status.ToString()); return File("Adjustments", c); }
    private static async Task<Result<PayrollOutputFile>> CsvFinalSettlementsAsync(Task<Result<PagedResult<PayrollFinalSettlementReportRowDto>>> task) { var r = await task; if (!r.Succeeded) return Result<PayrollOutputFile>.Failure(r.Status, r.Message); var c = new CsvBuilder("SettlementId", "EmployeeId", "EmployeeCode", "EmployeeName", "SettlementDate", "Status", "GrossPayable", "TotalDeductions", "NetSettlement", "Gratuity", "LeaveEncashment", "NoticePay", "NoticeRecovery", "Reimbursement", "LoanRecovery", "VariablePay", "Adjustments"); foreach (var x in r.Value!.Items) c.AppendRow(x.Id.ToString(), x.EmployeeId.ToString(), x.EmployeeCode, x.EmployeeName, x.SettlementDate.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture), x.Status.ToString(), x.GrossPayable.ToString(CultureInfo.InvariantCulture), x.TotalDeductions.ToString(CultureInfo.InvariantCulture), x.NetSettlement.ToString(CultureInfo.InvariantCulture), x.Gratuity.ToString(CultureInfo.InvariantCulture), x.LeaveEncashment.ToString(CultureInfo.InvariantCulture), x.NoticePay.ToString(CultureInfo.InvariantCulture), x.NoticeRecovery.ToString(CultureInfo.InvariantCulture), x.Reimbursement.ToString(CultureInfo.InvariantCulture), x.LoanRecovery.ToString(CultureInfo.InvariantCulture), x.VariablePay.ToString(CultureInfo.InvariantCulture), x.Adjustments.ToString(CultureInfo.InvariantCulture)); return File("FinalSettlements", c); }
    private static async Task<Result<PayrollOutputFile>> CsvOffCycleAsync(Task<Result<PagedResult<PayrollOffCycleReportRowDto>>> task) { var r = await task; if (!r.Succeeded) return Result<PayrollOutputFile>.Failure(r.Status, r.Message); var c = new CsvBuilder("PayrollRunId", "RunNumber", "EmployeeId", "EmployeeCode", "EmployeeName", "EarningsTotal", "DeductionTotal", "NetPay", "Status"); foreach (var x in r.Value!.Items) c.AppendRow(x.PayrollRunId.ToString(), x.RunNumber, x.EmployeeId.ToString(), x.EmployeeCode, x.EmployeeName, x.EarningsTotal.ToString(CultureInfo.InvariantCulture), x.DeductionTotal.ToString(CultureInfo.InvariantCulture), x.NetPay.ToString(CultureInfo.InvariantCulture), x.Status.ToString()); return File("OffCycle", c); }
    private static Result<PayrollOutputFile> File(string name, CsvBuilder csv) => Result<PayrollOutputFile>.Success(new PayrollOutputFile($"payroll-{name.ToLowerInvariant()}.csv", "text/csv; charset=utf-8", csv.ToUtf8Bytes()));

    private async Task<Dictionary<Guid, (decimal Earnings, decimal Tax, decimal Reimbursement, decimal Loan, decimal Variable, decimal Adjustment)>> ComponentTotals(IEnumerable<Guid> ids, CancellationToken ct) { var list = ids.ToList(); return await db.PayrollResultComponents.AsNoTracking().Where(x => x.TenantId == tenant.TenantId && list.Contains(x.PayrollResultId)).GroupBy(x => x.PayrollResultId).ToDictionaryAsync(g => g.Key, g => (g.Where(x => x.IsEarning).Sum(x => x.CalculatedAmount), g.Where(x => x.IsTaxable && x.IsDeduction).Sum(x => x.CalculatedAmount), g.Where(x => x.CalculationSource.ToLower().Contains("reimbursement")).Sum(x => x.CalculatedAmount), g.Where(x => x.CalculationSource.ToLower().Contains("loan")).Sum(x => x.CalculatedAmount), g.Where(x => x.CalculationSource.ToLower().Contains("variable")).Sum(x => x.CalculatedAmount), g.Where(x => x.CalculationSource.ToLower().Contains("adjustment")).Sum(x => x.CalculatedAmount)), ct); }
    private async Task<Dictionary<Guid, (string Code, string Name)>> NamesAsync(bool department, IEnumerable<Guid> ids, CancellationToken ct) { var list = ids.Distinct().ToList(); if (department) return await db.Departments.AsNoTracking().Where(x => x.TenantId == tenant.TenantId && list.Contains(x.Id)).ToDictionaryAsync(x => x.Id, x => (x.Code, x.Name), ct); return await db.CostCenters.AsNoTracking().Where(x => x.TenantId == tenant.TenantId && list.Contains(x.Id)).ToDictionaryAsync(x => x.Id, x => (x.Code, x.Name), ct); }
    private static string Label(Guid? id, IReadOnlyDictionary<Guid, (string Code, string Name)> names) => id.HasValue && names.TryGetValue(id.Value, out var x) ? x.Code : "UNCLASSIFIED";
    private static decimal SumLine(IEnumerable<FinalSettlementLine> lines, FinalSettlementLineType type) => lines.Where(x => x.LineType == type && x.IsEarning).Sum(x => x.Amount);
    private static async Task<Result<PagedResult<T>>> PageAsync<T>(IQueryable<T> source, PayrollReportQuery q, CancellationToken ct) { var total = await source.CountAsync(ct); var rows = await source.Skip((q.Page - 1) * q.PageSize).Take(q.PageSize).ToListAsync(ct); return Result<PagedResult<T>>.Success(new(rows, q.Page, q.PageSize, total)); }
}
