using System.Data;
using System.Text.Json;
using HRMS.Application.Abstractions;
using HRMS.Application.Common;
using HRMS.Application.DTOs.Payroll;
using HRMS.Domain.Entities;
using HRMS.Domain.Enums;
using Microsoft.EntityFrameworkCore;

namespace HRMS.Application.Services;

public sealed class ReimbursementService(IHrmsDbContext db, ITenantContext tenant, TimeProvider clock, IPayrollApprovalGuard? approvalGuard = null) : IReimbursementService
{
    public async Task<Result<IReadOnlyList<ReimbursementCategoryDto>>> GetCategoriesAsync(CancellationToken ct = default)
    {
        if (!TryTenant(out var tid, out var failure)) return Result<IReadOnlyList<ReimbursementCategoryDto>>.Failure(failure.Status, failure.Message);
        var rows = await db.ReimbursementCategories.AsNoTracking().Include(x => x.Versions).Where(x => x.TenantId == tid).OrderBy(x => x.Code).ToListAsync(ct);
        return Result<IReadOnlyList<ReimbursementCategoryDto>>.Success(rows.Select(ToDto).ToList());
    }

    public async Task<Result<ReimbursementCategoryDto>> CreateCategoryAsync(ReimbursementCategoryRequest request, CancellationToken ct = default)
    {
        if (!TryTenant(out var tid, out var failure)) return Result<ReimbursementCategoryDto>.Failure(failure.Status, failure.Message);
        var code = request.Code.Trim().ToUpperInvariant(); if (string.IsNullOrWhiteSpace(code) || string.IsNullOrWhiteSpace(request.Name)) return Result<ReimbursementCategoryDto>.Invalid("code", "Category code and name are required.");
        if (await db.ReimbursementCategories.AnyAsync(x => x.TenantId == tid && x.Code == code, ct)) return Result<ReimbursementCategoryDto>.Conflict("Reimbursement category code already exists.");
        var item = new ReimbursementCategory { Id = Guid.NewGuid(), TenantId = tid, Code = code, Name = request.Name.Trim(), Description = request.Description?.Trim(), CategoryType = request.CategoryType, IsActive = request.IsActive, CurrencyCode = request.CurrencyCode.Trim().ToUpperInvariant(), RequiresReceipt = request.RequiresReceipt, AllowsMultipleLines = request.AllowsMultipleLines, TaxTreatment = request.TaxTreatment, DefaultSettlementMethod = request.DefaultSettlementMethod, RequiresApproval = request.RequiresApproval, SettlementPriority = request.SettlementPriority };
        db.ReimbursementCategories.Add(item); await db.SaveChangesAsync(ct); return Result<ReimbursementCategoryDto>.Success(ToDto(item), "Reimbursement category created.");
    }

    public async Task<Result<ReimbursementCategoryDto>> UpdateCategoryAsync(Guid id, ReimbursementCategoryRequest request, CancellationToken ct = default)
    {
        if (!TryTenant(out var tid, out var failure)) return Result<ReimbursementCategoryDto>.Failure(failure.Status, failure.Message);
        var item = await db.ReimbursementCategories.Include(x => x.Versions).FirstOrDefaultAsync(x => x.TenantId == tid && x.Id == id, ct); if (item is null) return Result<ReimbursementCategoryDto>.NotFound("Reimbursement category not found.");
        var code = request.Code.Trim().ToUpperInvariant(); if (await db.ReimbursementCategories.AnyAsync(x => x.TenantId == tid && x.Id != id && x.Code == code, ct)) return Result<ReimbursementCategoryDto>.Conflict("Reimbursement category code already exists.");
        item.Code = code; item.Name = request.Name.Trim(); item.Description = request.Description?.Trim(); item.CategoryType = request.CategoryType; item.IsActive = request.IsActive; item.CurrencyCode = request.CurrencyCode.Trim().ToUpperInvariant(); item.RequiresReceipt = request.RequiresReceipt; item.AllowsMultipleLines = request.AllowsMultipleLines; item.TaxTreatment = request.TaxTreatment; item.DefaultSettlementMethod = request.DefaultSettlementMethod; item.RequiresApproval = request.RequiresApproval; item.SettlementPriority = request.SettlementPriority; await db.SaveChangesAsync(ct); return Result<ReimbursementCategoryDto>.Success(ToDto(item));
    }

    public async Task<Result<ReimbursementCategoryDto>> CreatePolicyVersionAsync(Guid categoryId, ReimbursementPolicyVersionRequest request, CancellationToken ct = default)
    {
        if (!TryTenant(out var tid, out var failure)) return Result<ReimbursementCategoryDto>.Failure(failure.Status, failure.Message);
        if (request.EffectiveTo < request.EffectiveFrom) return Result<ReimbursementCategoryDto>.Invalid("effectiveTo", "Effective To cannot be earlier than Effective From.");
        var category = await db.ReimbursementCategories.Include(x => x.Versions).FirstOrDefaultAsync(x => x.TenantId == tid && x.Id == categoryId && x.IsActive, ct); if (category is null) return Result<ReimbursementCategoryDto>.NotFound("Reimbursement category not found.");
        var end = request.EffectiveTo ?? DateOnly.MaxValue; if (request.Status == ReimbursementPolicyVersionStatus.Active && await db.ReimbursementPolicyVersions.AnyAsync(x => x.TenantId == tid && x.ReimbursementCategoryId == categoryId && x.Status == ReimbursementPolicyVersionStatus.Active && x.EffectiveFrom <= end && (x.EffectiveTo == null || x.EffectiveTo >= request.EffectiveFrom), ct)) return Result<ReimbursementCategoryDto>.Conflict("Reimbursement policy versions cannot overlap.");
        var version = new ReimbursementPolicyVersion { Id = Guid.NewGuid(), TenantId = tid, ReimbursementCategoryId = categoryId, EffectiveFrom = request.EffectiveFrom, EffectiveTo = request.EffectiveTo, MinClaimAmount = request.MinClaimAmount, MaxClaimAmount = request.MaxClaimAmount, PerTransactionLimit = request.PerTransactionLimit, MonthlyLimit = request.MonthlyLimit, YearlyLimit = request.YearlyLimit, RequiresReceipt = request.RequiresReceipt, ReceiptRequiredAbove = request.ReceiptRequiredAbove, TaxTreatment = request.TaxTreatment, SettlementMethod = request.SettlementMethod, Status = request.Status, EligibilityJson = request.EligibilityJson };
        db.ReimbursementPolicyVersions.Add(version); await db.SaveChangesAsync(ct); return Result<ReimbursementCategoryDto>.Success(ToDto(category));
    }

    public async Task<Result<ReimbursementClaimDto>> GetClaimAsync(Guid id, CancellationToken ct = default)
    {
        if (!TryTenant(out var tid, out var failure)) return Result<ReimbursementClaimDto>.Failure(failure.Status, failure.Message);
        var item = await ClaimQuery(tid).SingleOrDefaultAsync(x => x.Id == id, ct); return item is null ? Result<ReimbursementClaimDto>.NotFound("Reimbursement claim not found.") : Result<ReimbursementClaimDto>.Success(ToDto(item));
    }

    public async Task<Result<IReadOnlyList<ReimbursementHistoryDto>>> GetHistoryAsync(Guid id, CancellationToken ct = default)
    {
        if (!TryTenant(out var tid, out var failure)) return Result<IReadOnlyList<ReimbursementHistoryDto>>.Failure(failure.Status, failure.Message);
        if (!await db.ReimbursementClaims.AnyAsync(x => x.TenantId == tid && x.Id == id, ct)) return Result<IReadOnlyList<ReimbursementHistoryDto>>.NotFound("Reimbursement claim not found.");
        var history = await db.ReimbursementHistories.AsNoTracking().Where(x => x.TenantId == tid && x.ReimbursementClaimId == id).OrderBy(x => x.OccurredAtUtc).ToListAsync(ct);
        return Result<IReadOnlyList<ReimbursementHistoryDto>>.Success(history.Select(x => new ReimbursementHistoryDto(x.Id, x.EventType, x.PreviousStatus, x.NewStatus, x.ClaimedAmount, x.ApprovedAmount, x.Reason, x.ActorUserId, x.OccurredAtUtc)).ToList());
    }

    public async Task<Result<PagedResult<ReimbursementClaimDto>>> GetClaimsAsync(ReimbursementClaimQuery query, CancellationToken ct = default)
    {
        if (!TryTenant(out var tid, out var failure)) return Result<PagedResult<ReimbursementClaimDto>>.Failure(failure.Status, failure.Message); if (!ValidPage(query)) return Result<PagedResult<ReimbursementClaimDto>>.Invalid("page", "Page values are out of range.");
        var source = ClaimQuery(tid); if (query.EmployeeId is Guid employeeId) source = source.Where(x => x.EmployeeId == employeeId); if (query.CategoryId is Guid categoryId) source = source.Where(x => x.Lines.Any(line => line.ReimbursementCategoryId == categoryId)); if (query.Status is ReimbursementClaimStatus status) source = source.Where(x => x.Status == status); if (query.SettlementMethod is ReimbursementSettlementMethod method) source = source.Where(x => x.SettlementMethod == method); if (query.From is DateOnly from) source = source.Where(x => x.ClaimDate >= from); if (query.To is DateOnly to) source = source.Where(x => x.ClaimDate <= to); var total = await source.CountAsync(ct); var items = await source.OrderByDescending(x => x.ClaimDate).ThenByDescending(x => x.ClaimNumber).Skip((query.Page - 1) * query.PageSize).Take(query.PageSize).ToListAsync(ct); return Result<PagedResult<ReimbursementClaimDto>>.Success(new(items.Select(ToDto).ToList(), query.Page, query.PageSize, total));
    }

    public async Task<Result<ReimbursementClaimDto>> CreateClaimAsync(ReimbursementClaimRequest request, CancellationToken ct = default)
    {
        if (!TryTenant(out var tid, out var failure)) return Result<ReimbursementClaimDto>.Failure(failure.Status, failure.Message); if (request.Lines.Count == 0) return Result<ReimbursementClaimDto>.Invalid("lines", "At least one claim line is required."); if (request.Lines.Any(x => x.ClaimedAmount <= 0 || string.IsNullOrWhiteSpace(x.Description))) return Result<ReimbursementClaimDto>.Invalid("lines", "Each line requires a description and a positive amount."); if (request.ExpenseToDate < request.ExpenseFromDate) return Result<ReimbursementClaimDto>.Invalid("expenseToDate", "Expense To cannot be earlier than Expense From.");
        var employee = await db.Employees.AsNoTracking().FirstOrDefaultAsync(x => x.TenantId == tid && x.Id == request.EmployeeId, ct); if (employee is null) return Result<ReimbursementClaimDto>.NotFound("Employee not found.");
        var categories = await db.ReimbursementCategories.AsNoTracking().Where(x => x.TenantId == tid && request.Lines.Select(l => l.ReimbursementCategoryId).Contains(x.Id) && x.IsActive).ToDictionaryAsync(x => x.Id, ct); if (categories.Count != request.Lines.Select(x => x.ReimbursementCategoryId).Distinct().Count()) return Result<ReimbursementClaimDto>.Invalid("category", "Every claim category must be active and belong to the tenant."); if (request.Lines.GroupBy(x => x.ReimbursementCategoryId).Any(g => !categories[g.Key].AllowsMultipleLines && g.Count() > 1)) return Result<ReimbursementClaimDto>.Invalid("lines", "This category does not allow multiple lines."); if (categories.Values.Any(x => !string.Equals(x.CurrencyCode, request.CurrencyCode, StringComparison.OrdinalIgnoreCase))) return Result<ReimbursementClaimDto>.Invalid("currencyCode", "Claim currency must match each category currency.");
        await using var transaction = await db.BeginTransactionAsync(IsolationLevel.Serializable, ct);
        var item = new ReimbursementClaim { Id = Guid.NewGuid(), TenantId = tid, EmployeeId = request.EmployeeId, ClaimNumber = await NextClaimNumberAsync(tid, request.ClaimDate, ct), ClaimDate = request.ClaimDate, ExpenseFromDate = request.ExpenseFromDate, ExpenseToDate = request.ExpenseToDate, CurrencyCode = request.CurrencyCode.Trim().ToUpperInvariant(), SettlementMethod = request.SettlementMethod ?? categories.Values.OrderBy(x => x.SettlementPriority).Select(x => x.DefaultSettlementMethod).FirstOrDefault(), Status = ReimbursementClaimStatus.Draft };
        foreach (var line in request.Lines) item.Lines.Add(new ReimbursementClaimLine { Id = Guid.NewGuid(), TenantId = tid, ReimbursementCategoryId = line.ReimbursementCategoryId, ExpenseDate = line.ExpenseDate, Description = line.Description.Trim(), ClaimedAmount = line.ClaimedAmount, MerchantName = line.MerchantName?.Trim(), ReferenceNumber = line.ReferenceNumber?.Trim(), Status = ReimbursementClaimLineStatus.Draft, ReceiptRequired = categories[line.ReimbursementCategoryId].RequiresReceipt, ReceiptStatus = categories[line.ReimbursementCategoryId].RequiresReceipt ? ReimbursementReceiptStatus.Missing : ReimbursementReceiptStatus.NotRequired });
        ReconcileClaim(item); db.ReimbursementClaims.Add(item); AddHistory(item, ReimbursementHistoryEventType.DraftCreated, null, item.Status, "Claim created."); await db.SaveChangesAsync(ct); await transaction.CommitAsync(ct); return Result<ReimbursementClaimDto>.Success(await LoadDtoAsync(item.Id, ct));
    }

    public async Task<Result<ReimbursementClaimDto>> UpdateClaimAsync(Guid id, ReimbursementClaimRequest request, CancellationToken ct = default)
    {
        if (!TryTenant(out var tid, out var failure)) return Result<ReimbursementClaimDto>.Failure(failure.Status, failure.Message); var item = await db.ReimbursementClaims.Include(x => x.Lines).FirstOrDefaultAsync(x => x.TenantId == tid && x.Id == id, ct); if (item is null) return Result<ReimbursementClaimDto>.NotFound("Reimbursement claim not found."); if (item.Status != ReimbursementClaimStatus.Draft) return Result<ReimbursementClaimDto>.Conflict("Only draft claims can be edited."); if (request.Lines.Count == 0) return Result<ReimbursementClaimDto>.Invalid("lines", "At least one claim line is required.");
        db.ReimbursementClaimLines.RemoveRange(item.Lines); foreach (var line in request.Lines) item.Lines.Add(new ReimbursementClaimLine { Id = Guid.NewGuid(), TenantId = tid, ReimbursementClaimId = id, ReimbursementCategoryId = line.ReimbursementCategoryId, ExpenseDate = line.ExpenseDate, Description = line.Description.Trim(), ClaimedAmount = line.ClaimedAmount, MerchantName = line.MerchantName?.Trim(), ReferenceNumber = line.ReferenceNumber?.Trim(), Status = ReimbursementClaimLineStatus.Draft, ReceiptRequired = await db.ReimbursementCategories.AnyAsync(x => x.TenantId == tid && x.Id == line.ReimbursementCategoryId && x.RequiresReceipt, ct) }); item.ClaimDate = request.ClaimDate; item.CurrencyCode = request.CurrencyCode.Trim().ToUpperInvariant(); item.ExpenseFromDate = request.ExpenseFromDate; item.ExpenseToDate = request.ExpenseToDate; item.SettlementMethod = request.SettlementMethod ?? item.SettlementMethod; ReconcileClaim(item); item.ConcurrencyVersion++; AddHistory(item, ReimbursementHistoryEventType.LineUpdated, item.Status, item.Status, "Draft claim updated."); await db.SaveChangesAsync(ct); return Result<ReimbursementClaimDto>.Success(await LoadDtoAsync(id, ct));
    }

    public async Task<Result<ReimbursementClaimDto>> SubmitAsync(Guid id, CancellationToken ct = default)
    {
        if (!TryTenant(out var tid, out var failure)) return Result<ReimbursementClaimDto>.Failure(failure.Status, failure.Message); var item = await db.ReimbursementClaims.Include(x => x.Lines).FirstOrDefaultAsync(x => x.TenantId == tid && x.Id == id, ct); if (item is null) return Result<ReimbursementClaimDto>.NotFound("Reimbursement claim not found."); if (item.Status != ReimbursementClaimStatus.Draft) return Result<ReimbursementClaimDto>.Conflict("Only draft claims can be submitted."); if (!await db.Employees.AsNoTracking().AnyAsync(x => x.TenantId == tid && x.Id == item.EmployeeId && x.Status == EmployeeStatus.Active, ct)) return Result<ReimbursementClaimDto>.Conflict("Only active employees may submit reimbursement claims.");
        foreach (var line in item.Lines) { var category = await db.ReimbursementCategories.AsNoTracking().FirstAsync(x => x.TenantId == tid && x.Id == line.ReimbursementCategoryId, ct); var policy = await ResolvePolicyAsync(tid, category.Id, line.ExpenseDate, ct); if (policy is null) return Result<ReimbursementClaimDto>.Invalid("policy", $"No active reimbursement policy applies to category {category.Code} on {line.ExpenseDate:yyyy-MM-dd}."); line.PolicyVersionId = policy.Id; line.EligibleAmount = Math.Min(line.ClaimedAmount, policy.PerTransactionLimit ?? policy.MaxClaimAmount ?? line.ClaimedAmount); if (policy.MinClaimAmount is decimal min && line.ClaimedAmount < min) line.EligibleAmount = 0; line.ReceiptRequired = policy.RequiresReceipt || category.RequiresReceipt || (policy.ReceiptRequiredAbove is decimal threshold && line.ClaimedAmount > threshold); if (line.ReceiptRequired && line.ReceiptStatus is ReimbursementReceiptStatus.Missing or ReimbursementReceiptStatus.NotRequired) return Result<ReimbursementClaimDto>.Invalid("receipt", "A receipt is required for every submitted line that requires one."); line.Status = ReimbursementClaimLineStatus.Submitted; }
        ReconcileClaim(item); item.Status = ReimbursementClaimStatus.Submitted; item.SubmittedAtUtc = clock.GetUtcNow().UtcDateTime; item.SubmittedByUserId = tenant.UserId; item.ConcurrencyVersion++; AddHistory(item, ReimbursementHistoryEventType.Submitted, ReimbursementClaimStatus.Draft, item.Status, "Claim submitted."); await db.SaveChangesAsync(ct); return Result<ReimbursementClaimDto>.Success(await LoadDtoAsync(id, ct));
    }

    public async Task<Result<ReimbursementClaimDto>> ApproveAsync(Guid id, ReimbursementApprovalRequest request, CancellationToken ct = default)
    {
        if (!TryTenant(out var tid, out var failure)) return Result<ReimbursementClaimDto>.Failure(failure.Status, failure.Message); var item = await db.ReimbursementClaims.Include(x => x.Lines).ThenInclude(x => x.PolicyVersion).FirstOrDefaultAsync(x => x.TenantId == tid && x.Id == id, ct); if (item is null) return Result<ReimbursementClaimDto>.NotFound("Reimbursement claim not found."); if (item.Status is not ReimbursementClaimStatus.Submitted and not ReimbursementClaimStatus.UnderReview) return Result<ReimbursementClaimDto>.Conflict("Claim is not awaiting approval."); var guard = await (approvalGuard ?? new PayrollApprovalGuard(db, tenant)).ValidateAsync(item.SubmittedByUserId, "approve", ct: ct); if (!guard.Succeeded) return Result<ReimbursementClaimDto>.Failure(guard.Status, guard.Message, guard.Errors);
        await using var transaction = await db.BeginTransactionAsync(IsolationLevel.Serializable, ct); var decisions = request.Lines.ToDictionary(x => x.ClaimLineId); foreach (var line in item.Lines) { var approved = decisions.TryGetValue(line.Id, out var decision) ? decision.ApprovedAmount : line.EligibleAmount; if (approved < 0 || approved > line.EligibleAmount || line.EligibleAmount > line.ClaimedAmount) return Result<ReimbursementClaimDto>.Invalid("approvedAmount", "Approved amount must be between zero and eligible amount, and eligible cannot exceed claimed."); line.ApprovedAmount = approved; line.ApprovalComment = decisions.TryGetValue(line.Id, out decision) ? decision.Comment?.Trim() : request.Comment?.Trim(); line.Status = approved == 0 ? ReimbursementClaimLineStatus.Rejected : approved < line.EligibleAmount ? ReimbursementClaimLineStatus.PartiallyApproved : ReimbursementClaimLineStatus.Approved; var taxable = decisions.TryGetValue(line.Id, out decision) && decision.TaxableAmount.HasValue ? decision.TaxableAmount.Value : line.PolicyVersion?.TaxTreatment == ReimbursementTaxTreatment.Taxable ? approved : 0m; line.TaxableAmount = Math.Clamp(taxable, 0, approved); line.NonTaxableAmount = approved - line.TaxableAmount; }
        ReconcileClaim(item); var approvedTotal = item.TotalApprovedAmount; if (await LimitExceededAsync(item, ct)) return Result<ReimbursementClaimDto>.Conflict("The reimbursement policy limit would be exceeded."); item.Status = approvedTotal == 0 ? ReimbursementClaimStatus.Rejected : approvedTotal < item.TotalClaimedAmount ? ReimbursementClaimStatus.PartiallyApproved : ReimbursementClaimStatus.Approved; if (item.Status is ReimbursementClaimStatus.Approved or ReimbursementClaimStatus.PartiallyApproved) item.Status = ReimbursementClaimStatus.ReadyForSettlement; item.ApprovedAtUtc = clock.GetUtcNow().UtcDateTime; item.ApprovedByUserId = tenant.UserId; item.ConcurrencyVersion++; AddHistory(item, approvedTotal == 0 ? ReimbursementHistoryEventType.Rejected : approvedTotal < item.TotalClaimedAmount ? ReimbursementHistoryEventType.PartiallyApproved : ReimbursementHistoryEventType.Approved, ReimbursementClaimStatus.Submitted, item.Status, request.Comment); await db.SaveChangesAsync(ct); await transaction.CommitAsync(ct); return Result<ReimbursementClaimDto>.Success(await LoadDtoAsync(id, ct));
    }

    public Task<Result<ReimbursementClaimDto>> RejectAsync(Guid id, string reason, CancellationToken ct = default) => TransitionRejectAsync(id, reason, ct);
    private async Task<Result<ReimbursementClaimDto>> TransitionRejectAsync(Guid id, string reason, CancellationToken ct)
    {
        if (!TryTenant(out var tid, out var failure)) return Result<ReimbursementClaimDto>.Failure(failure.Status, failure.Message); if (string.IsNullOrWhiteSpace(reason)) return Result<ReimbursementClaimDto>.Invalid("reason", "Rejection reason is required."); var item = await db.ReimbursementClaims.FirstOrDefaultAsync(x => x.TenantId == tid && x.Id == id, ct); if (item is null) return Result<ReimbursementClaimDto>.NotFound("Reimbursement claim not found."); if (item.Status is not ReimbursementClaimStatus.Submitted and not ReimbursementClaimStatus.UnderReview) return Result<ReimbursementClaimDto>.Conflict("Claim cannot be rejected in its current state."); var previous = item.Status; item.Status = ReimbursementClaimStatus.Rejected; item.RejectionReason = reason.Trim(); item.RejectedAtUtc = clock.GetUtcNow().UtcDateTime; item.RejectedByUserId = tenant.UserId; item.ConcurrencyVersion++; AddHistory(item, ReimbursementHistoryEventType.Rejected, previous, item.Status, reason); await db.SaveChangesAsync(ct); return Result<ReimbursementClaimDto>.Success(await LoadDtoAsync(id, ct));
    }

    public async Task<Result<ReimbursementClaimDto>> SettleManuallyAsync(Guid id, ReimbursementSettlementRequest request, CancellationToken ct = default)
    {
        if (!TryTenant(out var tid, out var failure)) return Result<ReimbursementClaimDto>.Failure(failure.Status, failure.Message); var item = await db.ReimbursementClaims.Include(x => x.Lines).FirstOrDefaultAsync(x => x.TenantId == tid && x.Id == id, ct); if (item is null) return Result<ReimbursementClaimDto>.NotFound("Reimbursement claim not found."); if (item.Status != ReimbursementClaimStatus.ReadyForSettlement && item.Status != ReimbursementClaimStatus.PartiallyApproved) return Result<ReimbursementClaimDto>.Conflict("Only approved claims can be settled."); var remaining = item.TotalApprovedAmount - item.SettledAmount; var amount = request.Amount ?? remaining; if (amount <= 0 || amount > remaining) return Result<ReimbursementClaimDto>.Invalid("amount", "Settlement amount must be positive and no greater than the approved outstanding amount."); if (string.IsNullOrWhiteSpace(request.Reference)) return Result<ReimbursementClaimDto>.Invalid("reference", "A settlement reference is required.");
        await using var transaction = await db.BeginTransactionAsync(IsolationLevel.Serializable, ct); var outstanding = amount; var date = request.SettlementDate ?? DateOnly.FromDateTime(clock.GetUtcNow().UtcDateTime);
        foreach (var line in item.Lines.OrderBy(x => x.Id).Where(x => x.ApprovedAmount > 0))
        {
            var lineSettled = await db.ReimbursementSettlements.Where(x => x.TenantId == tid && x.ReimbursementClaimLineId == line.Id).SumAsync(x => x.Amount, ct); var lineRemaining = line.ApprovedAmount - lineSettled; if (lineRemaining <= 0) continue;
            var slice = Math.Min(outstanding, lineRemaining); var taxableSettled = await db.ReimbursementSettlements.Where(x => x.TenantId == tid && x.ReimbursementClaimLineId == line.Id).SumAsync(x => x.TaxableAmount, ct); var taxable = Math.Min(slice, Math.Max(0, line.TaxableAmount - taxableSettled));
            db.ReimbursementSettlements.Add(new ReimbursementSettlement { Id = Guid.NewGuid(), TenantId = tid, ReimbursementClaimId = item.Id, ReimbursementClaimLineId = line.Id, EmployeeId = item.EmployeeId, SettlementType = ReimbursementSettlementType.Manual, Amount = slice, TaxableAmount = taxable, NonTaxableAmount = slice - taxable, SettlementDate = date, Reference = request.Reference.Trim(), CreatedByUserId = tenant.UserId }); if (slice >= lineRemaining) line.Status = ReimbursementClaimLineStatus.Settled; outstanding -= slice; if (outstanding <= 0) break;
        }
        if (outstanding > 0) return Result<ReimbursementClaimDto>.Conflict("Settlement amount exceeds the approved outstanding line amounts."); item.SettledAmount += amount; if (item.SettledAmount >= item.TotalApprovedAmount) { item.SettledAmount = item.TotalApprovedAmount; item.Status = ReimbursementClaimStatus.Settled; item.SettledAtUtc = clock.GetUtcNow().UtcDateTime; item.SettledByUserId = tenant.UserId; item.SettlementReference = request.Reference.Trim(); } item.ConcurrencyVersion++; AddHistory(item, ReimbursementHistoryEventType.ManualSettlement, item.Status, item.Status, request.Reference, amount); await db.SaveChangesAsync(ct); await transaction.CommitAsync(ct); return Result<ReimbursementClaimDto>.Success(await LoadDtoAsync(id, ct));
    }

    public async Task<Result<ReimbursementClaimDto>> CancelAsync(Guid id, string reason, CancellationToken ct = default)
    {
        if (!TryTenant(out var tid, out var failure)) return Result<ReimbursementClaimDto>.Failure(failure.Status, failure.Message); if (string.IsNullOrWhiteSpace(reason)) return Result<ReimbursementClaimDto>.Invalid("reason", "Cancellation reason is required."); var item = await db.ReimbursementClaims.FirstOrDefaultAsync(x => x.TenantId == tid && x.Id == id, ct); if (item is null) return Result<ReimbursementClaimDto>.NotFound("Reimbursement claim not found."); if (item.Status is ReimbursementClaimStatus.Settled or ReimbursementClaimStatus.Cancelled) return Result<ReimbursementClaimDto>.Conflict("Settled claims cannot be cancelled."); var previous = item.Status; item.Status = ReimbursementClaimStatus.Cancelled; item.CancelledAtUtc = clock.GetUtcNow().UtcDateTime; item.CancelledByUserId = tenant.UserId; item.CancellationReason = reason.Trim(); item.ConcurrencyVersion++; AddHistory(item, ReimbursementHistoryEventType.Cancelled, previous, item.Status, reason); await db.SaveChangesAsync(ct); return Result<ReimbursementClaimDto>.Success(await LoadDtoAsync(id, ct));
    }

    public async Task<Result<ReimbursementAttachmentDto>> AddAttachmentAsync(Guid claimId, ReimbursementAttachmentRequest request, CancellationToken ct = default)
    {
        if (!TryTenant(out var tid, out var failure)) return Result<ReimbursementAttachmentDto>.Failure(failure.Status, failure.Message);
        if (string.IsNullOrWhiteSpace(request.FileName) || string.IsNullOrWhiteSpace(request.ContentType) || string.IsNullOrWhiteSpace(request.StorageReference) || request.FileSize < 0) return Result<ReimbursementAttachmentDto>.Invalid("attachment", "Attachment metadata is incomplete.");
        var claim = await db.ReimbursementClaims.Include(x => x.Lines).FirstOrDefaultAsync(x => x.TenantId == tid && x.Id == claimId, ct); if (claim is null) return Result<ReimbursementAttachmentDto>.NotFound("Reimbursement claim not found.");
        if (request.ClaimLineId is Guid lineId && claim.Lines.All(x => x.Id != lineId)) return Result<ReimbursementAttachmentDto>.NotFound("Reimbursement claim line not found.");
        var item = new ReimbursementAttachment { Id = Guid.NewGuid(), TenantId = tid, ReimbursementClaimId = claimId, ReimbursementClaimLineId = request.ClaimLineId, FileName = request.FileName.Trim(), ContentType = request.ContentType.Trim(), StorageReference = request.StorageReference.Trim(), FileSize = request.FileSize, UploadedAtUtc = clock.GetUtcNow().UtcDateTime, UploadedByUserId = tenant.UserId };
        db.ReimbursementAttachments.Add(item); if (request.ClaimLineId is Guid uploadedLineId) claim.Lines.Single(x => x.Id == uploadedLineId).ReceiptStatus = ReimbursementReceiptStatus.Uploaded; await db.SaveChangesAsync(ct); return Result<ReimbursementAttachmentDto>.Success(new(item.Id, item.ReimbursementClaimLineId, item.FileName, item.ContentType, item.StorageReference, item.FileSize, item.UploadedAtUtc));
    }

    public async Task<Result<PagedResult<ReimbursementRegisterRowDto>>> GetRegisterAsync(ReimbursementClaimQuery query, CancellationToken ct = default)
    {
        if (!TryTenant(out var tid, out var failure)) return Result<PagedResult<ReimbursementRegisterRowDto>>.Failure(failure.Status, failure.Message); if (!ValidPage(query)) return Result<PagedResult<ReimbursementRegisterRowDto>>.Invalid("page", "Page values are out of range."); var source = db.ReimbursementClaims.AsNoTracking().Where(x => x.TenantId == tid).Include(x => x.Employee).AsQueryable(); if (query.EmployeeId is Guid eid) source = source.Where(x => x.EmployeeId == eid); if (query.Status is ReimbursementClaimStatus status) source = source.Where(x => x.Status == status); if (query.CategoryId is Guid cid) source = source.Where(x => x.Lines.Any(l => l.ReimbursementCategoryId == cid)); if (query.From is DateOnly from) source = source.Where(x => x.ClaimDate >= from); if (query.To is DateOnly to) source = source.Where(x => x.ClaimDate <= to); var total = await source.CountAsync(ct); var items = await source.OrderByDescending(x => x.ClaimDate).Skip((query.Page - 1) * query.PageSize).Take(query.PageSize).Select(x => new ReimbursementRegisterRowDto(x.Id, x.ClaimNumber, x.EmployeeId, x.Employee!.EmployeeCode ?? string.Empty, x.Employee.FirstName + " " + x.Employee.LastName, x.TotalClaimedAmount, x.TotalEligibleAmount, x.TotalApprovedAmount, x.TaxableAmount, x.NonTaxableAmount, x.SettledAmount, x.TotalApprovedAmount - x.SettledAmount, x.Status, x.SettlementMethod, x.ClaimDate)).ToListAsync(ct); return Result<PagedResult<ReimbursementRegisterRowDto>>.Success(new(items, query.Page, query.PageSize, total));
    }

    public async Task<Result<IReadOnlyList<ReimbursementPayrollRecovery>>> GetPayrollRecoveriesAsync(Guid employeeId, DateOnly asOf, CancellationToken ct = default)
    {
        if (!TryTenant(out var tid, out var failure)) return Result<IReadOnlyList<ReimbursementPayrollRecovery>>.Failure(failure.Status, failure.Message); var rows = await db.ReimbursementClaimLines.AsNoTracking().Include(x => x.Claim).Include(x => x.Category).Where(x => x.TenantId == tid && x.Claim!.EmployeeId == employeeId && x.Claim.Status == ReimbursementClaimStatus.ReadyForSettlement && x.Claim.SettlementMethod == ReimbursementSettlementMethod.Payroll && x.ExpenseDate <= asOf && x.ApprovedAmount > 0).OrderBy(x => x.Claim!.ClaimDate).ThenBy(x => x.ExpenseDate).ToListAsync(ct); var lineIds = rows.Select(x => x.Id).ToList(); var settled = await db.ReimbursementSettlements.AsNoTracking().Where(x => x.TenantId == tid && x.ReimbursementClaimLineId.HasValue && lineIds.Contains(x.ReimbursementClaimLineId.Value)).GroupBy(x => x.ReimbursementClaimLineId!.Value).Select(x => new { Id = x.Key, Amount = x.Sum(y => y.Amount), Taxable = x.Sum(y => y.TaxableAmount) }).ToDictionaryAsync(x => x.Id, ct); var recoveries = rows.Select(x => { settled.TryGetValue(x.Id, out var prior); var outstanding = x.ApprovedAmount - (prior?.Amount ?? 0m); var taxable = Math.Min(outstanding, Math.Max(0m, x.TaxableAmount - (prior?.Taxable ?? 0m))); return new ReimbursementPayrollRecovery(x.Claim!.Id, x.Id, employeeId, x.Claim.ClaimNumber, x.Category!.Code, outstanding, taxable, outstanding - taxable, x.Claim.SettlementMethod); }).Where(x => x.ApprovedAmount > 0).ToList(); return Result<IReadOnlyList<ReimbursementPayrollRecovery>>.Success(recoveries);
    }

    public async Task<Result<ReimbursementSettlementDto>> RecordPayrollSettlementAsync(Guid claimId, Guid claimLineId, Guid payrollRunId, Guid payrollResultId, decimal amount, DateOnly date, CancellationToken ct = default)
    {
        if (!TryTenant(out var tid, out var failure)) return Result<ReimbursementSettlementDto>.Failure(failure.Status, failure.Message);
        if (amount <= 0) return Result<ReimbursementSettlementDto>.Invalid("amount", "Settlement amount must be positive.");
        await using var transaction = await db.BeginTransactionAsync(IsolationLevel.Serializable, ct);
        if (await db.ReimbursementSettlements.AnyAsync(x => x.TenantId == tid && x.ReimbursementClaimLineId == claimLineId && x.PayrollResultId == payrollResultId, ct)) return Result<ReimbursementSettlementDto>.Conflict("Reimbursement line is already settled for this payroll result.");
        var claim = await db.ReimbursementClaims.Include(x => x.Lines).FirstOrDefaultAsync(x => x.TenantId == tid && x.Id == claimId, ct);
        var line = claim?.Lines.SingleOrDefault(x => x.Id == claimLineId);
        if (claim is null || line is null) return Result<ReimbursementSettlementDto>.NotFound("Reimbursement claim line not found.");
        if (claim.SettlementMethod != ReimbursementSettlementMethod.Payroll) return Result<ReimbursementSettlementDto>.Conflict("This claim is not configured for Payroll settlement.");
        var priorSettlements = db.ReimbursementSettlements.Where(x => x.TenantId == tid && x.ReimbursementClaimLineId == line.Id);
        var remaining = line.ApprovedAmount - await priorSettlements.SumAsync(x => x.Amount, ct);
        if (amount > remaining) return Result<ReimbursementSettlementDto>.Conflict("Payroll settlement exceeds the approved outstanding amount.");
        var taxableSettled = await priorSettlements.SumAsync(x => x.TaxableAmount, ct);
        var taxable = Math.Min(amount, Math.Max(0, line.TaxableAmount - taxableSettled));
        var settlement = new ReimbursementSettlement { Id = Guid.NewGuid(), TenantId = tid, ReimbursementClaimId = claimId, ReimbursementClaimLineId = claimLineId, EmployeeId = claim.EmployeeId, SettlementType = ReimbursementSettlementType.Payroll, Amount = amount, TaxableAmount = taxable, NonTaxableAmount = amount - taxable, SettlementDate = date, PayrollRunId = payrollRunId, PayrollResultId = payrollResultId, CreatedByUserId = tenant.UserId };
        db.ReimbursementSettlements.Add(settlement);
        if (amount >= remaining) line.Status = ReimbursementClaimLineStatus.Settled;
        claim.SettledAmount += amount;
        if (claim.SettledAmount >= claim.TotalApprovedAmount) { claim.SettledAmount = claim.TotalApprovedAmount; claim.Status = ReimbursementClaimStatus.Settled; claim.SettledAtUtc = clock.GetUtcNow().UtcDateTime; claim.SettledByUserId = tenant.UserId; }
        claim.ConcurrencyVersion++;
        AddHistory(claim, ReimbursementHistoryEventType.PayrollSettlement, claim.Status, claim.Status, "Payroll reimbursement settlement.", amount, settlement.Id);
        await db.SaveChangesAsync(ct);
        await transaction.CommitAsync(ct);
        return Result<ReimbursementSettlementDto>.Success(ToDto(settlement));
    }

    private IQueryable<ReimbursementClaim> ClaimQuery(Guid tid) => db.ReimbursementClaims.AsNoTracking().Include(x => x.Lines).ThenInclude(x => x.Category).Include(x => x.Lines).ThenInclude(x => x.PolicyVersion).Include(x => x.Attachments).Include(x => x.Settlements).Include(x => x.History).Where(x => x.TenantId == tid);
    private async Task<ReimbursementClaimDto> LoadDtoAsync(Guid id, CancellationToken ct) => ToDto(await ClaimQuery(tenant.TenantId!.Value).SingleAsync(x => x.Id == id, ct));
    private async Task<ReimbursementPolicyVersion?> ResolvePolicyAsync(Guid tid, Guid categoryId, DateOnly date, CancellationToken ct) => await db.ReimbursementPolicyVersions.AsNoTracking().Where(x => x.TenantId == tid && x.ReimbursementCategoryId == categoryId && x.Status == ReimbursementPolicyVersionStatus.Active && x.EffectiveFrom <= date && (x.EffectiveTo == null || x.EffectiveTo >= date)).OrderByDescending(x => x.EffectiveFrom).FirstOrDefaultAsync(ct);
    private async Task<bool> LimitExceededAsync(ReimbursementClaim item, CancellationToken ct)
    {
        foreach (var line in item.Lines.Where(x => x.ApprovedAmount > 0))
        {
            var policy = line.PolicyVersionId is Guid pid ? await db.ReimbursementPolicyVersions.AsNoTracking().SingleOrDefaultAsync(x => x.TenantId == item.TenantId && x.Id == pid, ct) : null;
            if (policy is null) continue;
            var sameCategory = db.ReimbursementClaimLines.Where(x => x.TenantId == item.TenantId && x.ReimbursementCategoryId == line.ReimbursementCategoryId && x.Claim!.EmployeeId == item.EmployeeId && x.ReimbursementClaimId != item.Id && x.Claim!.Status != ReimbursementClaimStatus.Rejected && x.Claim.Status != ReimbursementClaimStatus.Cancelled);
            var monthStart = new DateOnly(line.ExpenseDate.Year, line.ExpenseDate.Month, 1); var monthEnd = monthStart.AddMonths(1).AddDays(-1);
            var approvedMonth = await sameCategory.Where(x => x.ExpenseDate >= monthStart && x.ExpenseDate <= monthEnd).SumAsync(x => x.ApprovedAmount, ct);
            var yearStart = new DateOnly(line.ExpenseDate.Year, 1, 1); var yearEnd = new DateOnly(line.ExpenseDate.Year, 12, 31);
            var approvedYear = await sameCategory.Where(x => x.ExpenseDate >= yearStart && x.ExpenseDate <= yearEnd).SumAsync(x => x.ApprovedAmount, ct);
            var currentCategory = item.Lines.Where(x => x.ReimbursementCategoryId == line.ReimbursementCategoryId).Sum(x => x.ApprovedAmount);
            if (policy.MonthlyLimit is decimal monthly && approvedMonth + currentCategory > monthly) return true;
            if (policy.YearlyLimit is decimal yearly && approvedYear + currentCategory > yearly) return true;
        }
        return false;
    }
    private async Task<string> NextClaimNumberAsync(Guid tid, DateOnly date, CancellationToken ct)
    {
        var prefix = $"CLM/{date:yyyy}/";
        var existing = await db.ReimbursementClaims.AsNoTracking().Where(x => x.TenantId == tid && x.ClaimNumber.StartsWith(prefix)).Select(x => x.ClaimNumber).ToListAsync(ct);
        var next = existing.Select(x => x[prefix.Length..]).Where(x => int.TryParse(x, System.Globalization.NumberStyles.None, System.Globalization.CultureInfo.InvariantCulture, out _)).Select(x => int.Parse(x, System.Globalization.CultureInfo.InvariantCulture)).DefaultIfEmpty(0).Max() + 1;
        return $"{prefix}{next:000000}";
    }
    private void ReconcileClaim(ReimbursementClaim item) { item.TotalClaimedAmount = Round(item.Lines.Sum(x => x.ClaimedAmount)); item.TotalEligibleAmount = Round(item.Lines.Sum(x => x.EligibleAmount)); item.TotalApprovedAmount = Round(item.Lines.Sum(x => x.ApprovedAmount)); item.TaxableAmount = Round(item.Lines.Sum(x => x.TaxableAmount)); item.NonTaxableAmount = Round(item.Lines.Sum(x => x.NonTaxableAmount)); }
    private void AddHistory(ReimbursementClaim item, ReimbursementHistoryEventType type, ReimbursementClaimStatus? previous, ReimbursementClaimStatus? next, string? reason, decimal? amount = null, Guid? sourceId = null) => db.ReimbursementHistories.Add(new ReimbursementHistory { Id = Guid.NewGuid(), TenantId = item.TenantId, ReimbursementClaimId = item.Id, EventType = type, PreviousStatus = previous, NewStatus = next, ClaimedAmount = item.TotalClaimedAmount, ApprovedAmount = amount ?? item.TotalApprovedAmount, Reason = reason, SourceType = type.ToString(), SourceId = sourceId, ActorUserId = tenant.UserId, OccurredAtUtc = clock.GetUtcNow().UtcDateTime });
    private bool TryTenant(out Guid tenantId, out Result<bool> failure) { if (tenant.TenantId is Guid tid) { tenantId = tid; failure = Result<bool>.Success(true); return true; } tenantId = default; failure = Result<bool>.Unauthorized("No authenticated tenant."); return false; }
    private static bool ValidPage(PagedQuery q) => q.Page >= 1 && q.PageSize is >= 1 and <= 500;
    private static decimal Round(decimal value) => decimal.Round(value, 2, MidpointRounding.AwayFromZero);
    private static ReimbursementCategoryDto ToDto(ReimbursementCategory x) => new(x.Id, x.Code, x.Name, x.CategoryType, x.IsActive, x.CurrencyCode, x.RequiresReceipt, x.AllowsMultipleLines, x.TaxTreatment, x.DefaultSettlementMethod, x.RequiresApproval, x.SettlementPriority, x.Versions.OrderByDescending(v => v.EffectiveFrom).Select(ToDto).ToList());
    private static ReimbursementPolicyVersionDto ToDto(ReimbursementPolicyVersion x) => new(x.Id, x.ReimbursementCategoryId, x.EffectiveFrom, x.EffectiveTo, x.MinClaimAmount, x.MaxClaimAmount, x.PerTransactionLimit, x.MonthlyLimit, x.YearlyLimit, x.RequiresReceipt, x.ReceiptRequiredAbove, x.TaxTreatment, x.SettlementMethod, x.Status);
    private static ReimbursementClaimDto ToDto(ReimbursementClaim x) => new(x.Id, x.EmployeeId, x.ClaimNumber, x.ClaimDate, x.CurrencyCode, x.TotalClaimedAmount, x.TotalEligibleAmount, x.TotalApprovedAmount, x.TaxableAmount, x.NonTaxableAmount, x.SettledAmount, x.SettlementMethod, x.Status, x.Lines.OrderBy(l => l.ExpenseDate).Select(l => new ReimbursementClaimLineDto(l.Id, l.ReimbursementCategoryId, l.Category?.Code ?? string.Empty, l.PolicyVersionId, l.ExpenseDate, l.Description, l.ClaimedAmount, l.EligibleAmount, l.ApprovedAmount, l.TaxableAmount, l.NonTaxableAmount, l.MerchantName, l.ReferenceNumber, l.ReceiptRequired, l.ReceiptStatus, l.Status, l.ApprovalComment)).ToList(), x.Attachments.Select(a => new ReimbursementAttachmentDto(a.Id, a.ReimbursementClaimLineId, a.FileName, a.ContentType, a.StorageReference, a.FileSize, a.UploadedAtUtc)).ToList(), x.Settlements.Select(ToDto).ToList(), x.History.OrderBy(h => h.OccurredAtUtc).Select(h => new ReimbursementHistoryDto(h.Id, h.EventType, h.PreviousStatus, h.NewStatus, h.ClaimedAmount, h.ApprovedAmount, h.Reason, h.ActorUserId, h.OccurredAtUtc)).ToList());
    private static ReimbursementSettlementDto ToDto(ReimbursementSettlement x) => new(x.Id, x.ReimbursementClaimLineId, x.SettlementType, x.Amount, x.TaxableAmount, x.NonTaxableAmount, x.SettlementDate, x.PayrollRunId, x.PayrollResultId, x.FinalSettlementId, x.Reference);
}
