using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Data.Common;
using HRMS.Application.Abstractions;
using HRMS.Application.Common;
using HRMS.Application.DTOs.Separation;
using HRMS.Domain.Entities;
using HRMS.Domain.Entities.Separation;
using HRMS.Domain.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;

namespace HRMS.Application.Services;

public sealed class SeparationDocumentService(
    IHrmsDbContext db,
    ITenantContext tenant,
    TimeProvider clock,
    IEmployeeIdentityResolver identity,
    ISeparationDocumentFailureInjector? failureInjector = null) : ISeparationDocumentService
{
    private static readonly Regex Token = new(@"\{\{([A-Za-z]+\.[A-Za-z]+)\}\}", RegexOptions.Compiled);
    private static readonly HashSet<string> AllowedFields = new(StringComparer.Ordinal)
    {
        "Employee.FullName", "Employee.EmployeeCode", "Employee.DateOfJoining", "Employee.Designation", "Employee.Department", "Employee.WorkLocation",
        "Separation.ApprovedLastWorkingDate", "Separation.Reason", "Separation.Type",
        "Employment.LastDesignation", "Employment.LastDepartment", "Employment.LastGrade",
        "Organization.Name", "Organization.Address", "Organization.LogoReference",
        "Document.Number", "Document.IssueDate"
    };

    public async Task<Result<IReadOnlyList<SeparationDocumentTemplateDto>>> GetTemplatesAsync(CancellationToken ct = default)
    {
        if (tenant.TenantId is not Guid id) return Result<IReadOnlyList<SeparationDocumentTemplateDto>>.Unauthorized("No authenticated tenant.");
        var rows = await db.SeparationDocumentTemplates.AsNoTracking().Include(x => x.Versions).Where(x => x.TenantId == id).OrderBy(x => x.Code).ToListAsync(ct);
        return Result<IReadOnlyList<SeparationDocumentTemplateDto>>.Success(rows.Select(ToTemplate).ToList());
    }

    public async Task<Result<SeparationDocumentTemplateDto>> CreateTemplateAsync(SeparationDocumentTemplateRequest request, CancellationToken ct = default)
    {
        if (tenant.TenantId is not Guid id) return Result<SeparationDocumentTemplateDto>.Unauthorized("No authenticated tenant.");
        if (!Enum.IsDefined(request.DocumentType) || string.IsNullOrWhiteSpace(request.Code) || string.IsNullOrWhiteSpace(request.Name)) return Result<SeparationDocumentTemplateDto>.Invalid("template", "A valid code, name, and document type are required.");
        var code = request.Code.Trim().ToUpperInvariant(); if (await db.SeparationDocumentTemplates.AnyAsync(x => x.TenantId == id && x.Code == code, ct)) return Result<SeparationDocumentTemplateDto>.Conflict("A template with this code already exists.");
        if (!ValidDates(request.EffectiveFrom, request.EffectiveTo)) return Result<SeparationDocumentTemplateDto>.Invalid("dates", "Effective To cannot be earlier than Effective From.");
        var row = new SeparationDocumentTemplate { Id = Guid.NewGuid(), TenantId = id, Code = code, Name = request.Name.Trim(), DocumentType = request.DocumentType, Description = request.Description?.Trim(), IsActive = request.IsActive, EffectiveFrom = request.EffectiveFrom, EffectiveTo = request.EffectiveTo, RequiresApproval = request.RequiresApproval, CreatedByUserId = tenant.UserId };
        db.SeparationDocumentTemplates.Add(row); AddEvent(SeparationDocumentEventType.TemplateCreated, templateId: row.Id, reason: "Template created."); await db.SaveChangesAsync(ct); return Result<SeparationDocumentTemplateDto>.Success(ToTemplate(row));
    }

    public async Task<Result<SeparationDocumentTemplateDto>> AddVersionAsync(Guid templateId, SeparationDocumentTemplateVersionRequest request, CancellationToken ct = default)
    {
        if (tenant.TenantId is not Guid id) return Result<SeparationDocumentTemplateDto>.Unauthorized("No authenticated tenant.");
        var template = await db.SeparationDocumentTemplates.Include(x => x.Versions).FirstOrDefaultAsync(x => x.TenantId == id && x.Id == templateId, ct); if (template is null) return Result<SeparationDocumentTemplateDto>.NotFound("Document template not found.");
        var validation = ValidateBody(request.BodyTemplate); if (validation is not null) return Result<SeparationDocumentTemplateDto>.Invalid("bodyTemplate", validation); if (!ValidDates(request.EffectiveFrom, request.EffectiveTo)) return Result<SeparationDocumentTemplateDto>.Invalid("dates", "Effective To cannot be earlier than Effective From.");
        var version = new SeparationDocumentTemplateVersion { Id = Guid.NewGuid(), TenantId = id, TemplateId = templateId, VersionNumber = template.Versions.Select(x => x.VersionNumber).DefaultIfEmpty(0).Max() + 1, EffectiveFrom = request.EffectiveFrom, EffectiveTo = request.EffectiveTo, Subject = request.Subject?.Trim(), BodyTemplate = request.BodyTemplate.Trim(), HeaderTemplate = request.HeaderTemplate, FooterTemplate = request.FooterTemplate, PageSettingsJson = request.PageSettingsJson, CreatedByUserId = tenant.UserId };
        template.Versions.Add(version); db.SeparationDocumentTemplateVersions.Add(version); AddEvent(SeparationDocumentEventType.TemplateVersionCreated, templateId, version.Id, reason: "Template version created."); await db.SaveChangesAsync(ct); return Result<SeparationDocumentTemplateDto>.Success(ToTemplate(template));
    }

    public async Task<Result<SeparationDocumentTemplateDto>> PublishVersionAsync(Guid templateId, Guid versionId, int expectedConcurrencyVersion, CancellationToken ct = default)
    {
        if (tenant.TenantId is not Guid id) return Result<SeparationDocumentTemplateDto>.Unauthorized("No authenticated tenant.");
        var template = await db.SeparationDocumentTemplates.Include(x => x.Versions).FirstOrDefaultAsync(x => x.TenantId == id && x.Id == templateId, ct); if (template is null) return Result<SeparationDocumentTemplateDto>.NotFound("Document template not found."); if (template.ConcurrencyVersion != expectedConcurrencyVersion) return Result<SeparationDocumentTemplateDto>.Conflict("The template changed concurrently.");
        var version = template.Versions.SingleOrDefault(x => x.Id == versionId); if (version is null) return Result<SeparationDocumentTemplateDto>.NotFound("Template version not found."); var error = ValidateBody(version.BodyTemplate); if (error is not null) return Result<SeparationDocumentTemplateDto>.Invalid("bodyTemplate", error);
        if (template.Versions.Any(x => x.Id != versionId && x.Status == SeparationDocumentTemplateVersionStatus.Published && Overlaps(x.EffectiveFrom, x.EffectiveTo, version.EffectiveFrom, version.EffectiveTo))) return Result<SeparationDocumentTemplateDto>.Conflict("Published template versions cannot overlap.");
        version.Status = SeparationDocumentTemplateVersionStatus.Published; version.PublishedByUserId = tenant.UserId; version.PublishedAtUtc = clock.GetUtcNow().UtcDateTime; version.ConcurrencyVersion++; template.ConcurrencyVersion++; AddEvent(SeparationDocumentEventType.TemplateVersionPublished, templateId, versionId, reason: "Template version published."); try { await db.SaveChangesAsync(ct); } catch (DbUpdateConcurrencyException) { return Result<SeparationDocumentTemplateDto>.Conflict("The template changed concurrently."); } catch (DbException) { return Result<SeparationDocumentTemplateDto>.Conflict("The template changed concurrently."); } catch (InvalidOperationException) { return Result<SeparationDocumentTemplateDto>.Conflict("The template changed concurrently."); } return Result<SeparationDocumentTemplateDto>.Success(ToTemplate(template));
    }

    public async Task<Result<SeparationDocumentPreviewDto>> PreviewAsync(Guid versionId, SeparationDocumentPreviewRequest request, CancellationToken ct = default)
    {
        if (tenant.TenantId is not Guid tenantId) return Result<SeparationDocumentPreviewDto>.Unauthorized("No authenticated tenant.");
        var version = await db.SeparationDocumentTemplateVersions.AsNoTracking().Include(x => x.Template).FirstOrDefaultAsync(x => x.TenantId == tenantId && x.Id == versionId, ct);
        if (version?.Template is null) return Result<SeparationDocumentPreviewDto>.NotFound("Template version not found.");
        var validation = ValidateBody(version.BodyTemplate); if (validation is not null) return Result<SeparationDocumentPreviewDto>.Invalid("bodyTemplate", validation);
        var sample = new Dictionary<string, string?> { ["Employee.FullName"] = "Sample Employee", ["Employee.EmployeeCode"] = "EMP-PREVIEW", ["Employee.DateOfJoining"] = "2020-01-01", ["Employee.Designation"] = "Sample Designation", ["Employee.Department"] = "Sample Department", ["Employee.WorkLocation"] = "Sample Location", ["Separation.ApprovedLastWorkingDate"] = "2026-12-31", ["Separation.Reason"] = "Sample reason", ["Separation.Type"] = "EmployeeInitiated", ["Employment.LastDesignation"] = "Sample Designation", ["Employment.LastDepartment"] = "Sample Department", ["Employment.LastGrade"] = "Sample Grade", ["Organization.Name"] = "Sample Organization", ["Organization.Address"] = "Sample Address", ["Organization.LogoReference"] = null, ["Document.Number"] = "PREVIEW-NOT-OFFICIAL", ["Document.IssueDate"] = DateOnly.FromDateTime(clock.GetUtcNow().UtcDateTime).ToString("yyyy-MM-dd") };
        var bytes = RenderPdf(RenderPlainText(version.BodyTemplate, sample)); return Result<SeparationDocumentPreviewDto>.Success(new($"Preview_{version.Template.Code}.pdf", "application/pdf", Convert.ToHexString(SHA256.HashData(bytes)), Convert.ToBase64String(bytes), false), "Preview only; no official document was created.");
    }

    public async Task<Result<SeparationDocumentReadinessDto>> GetReadinessAsync(Guid separationId, CancellationToken ct = default)
    {
        var result = await LoadFactsAsync(separationId, ct); if (!result.Succeeded) return Result<SeparationDocumentReadinessDto>.Failure(result.Status, result.Message, result.Errors); var facts = result.Value!; return Result<SeparationDocumentReadinessDto>.Success(await ToReadinessAsync(facts, ct));
    }

    public async Task<Result<SeparationGeneratedDocumentDto>> GenerateAsync(Guid separationId, SeparationDocumentGenerateRequest request, CancellationToken ct = default)
    {
        if (tenant.TenantId is not Guid tenantId) return Result<SeparationGeneratedDocumentDto>.Unauthorized("No authenticated tenant.");
        var factsResult = await LoadFactsAsync(separationId, ct); if (!factsResult.Succeeded) return Result<SeparationGeneratedDocumentDto>.Failure(factsResult.Status, factsResult.Message, factsResult.Errors); var facts = factsResult.Value!; var readiness = await ToReadinessAsync(facts, ct); if (!readiness.IsEligible) return Result<SeparationGeneratedDocumentDto>.Conflict("Document generation is blocked.", readiness.Blockers.Select(x => new ValidationError("eligibility", x)).ToList());
        if (request.ExpectedConcurrencyVersion > 0 && facts.Separation.ConcurrencyVersion != request.ExpectedConcurrencyVersion) return Result<SeparationGeneratedDocumentDto>.Conflict("The separation changed concurrently.");
        IDbContextTransaction transaction;
        try { transaction = await db.BeginTransactionAsync(ct); } catch (DbException) { return Result<SeparationGeneratedDocumentDto>.Conflict("Document generation changed concurrently; retry is safe."); } catch (InvalidOperationException) { return Result<SeparationGeneratedDocumentDto>.Conflict("Document generation changed concurrently; retry is safe."); }
        await using var activeTransaction = transaction;
        var existing = await db.SeparationGeneratedDocuments.Include(x => x.Employee).FirstOrDefaultAsync(x => x.TenantId == tenantId && x.EmployeeSeparationId == separationId && x.DocumentType == request.DocumentType && new[] { SeparationGeneratedDocumentStatus.DraftGenerated, SeparationGeneratedDocumentStatus.PendingApproval, SeparationGeneratedDocumentStatus.Approved, SeparationGeneratedDocumentStatus.Issued }.Contains(x.Status), ct); if (existing is not null && request.SupersedesDocumentId is null) { await transaction.CommitAsync(ct); return Result<SeparationGeneratedDocumentDto>.Success(ToDocument(existing), "The current document already exists."); }
        var template = await ResolveTemplateAsync(tenantId, facts.Separation.ApprovedLastWorkingDate!.Value, request, ct); if (template is null) return Result<SeparationGeneratedDocumentDto>.Conflict("No effective published document template is available.");
        var employment = await ResolveEmploymentAsync(tenantId, facts.Separation.Employee!.Id, facts.Separation.ApprovedLastWorkingDate.Value, ct); if (!employment.Succeeded) return Result<SeparationGeneratedDocumentDto>.Conflict(employment.Message);
        var issueDate = request.IssueDate ?? DateOnly.FromDateTime(clock.GetUtcNow().UtcDateTime); var sequence = await AllocateNumberAsync(tenantId, request.DocumentType, issueDate.Year, ct); var snapshot = Snapshot(facts, employment.Value!, template, sequence, issueDate); var plain = RenderPlainText(template.Version.BodyTemplate, snapshot); var bytes = RenderPdf(plain); var hash = Convert.ToHexString(SHA256.HashData(bytes));
        var document = new SeparationGeneratedDocument { Id = Guid.NewGuid(), TenantId = tenantId, EmployeeSeparationId = separationId, EmployeeId = facts.Separation.Employee!.Id, DocumentType = request.DocumentType, CustomDocumentCode = request.CustomDocumentCode?.Trim(), TemplateId = template.Template.Id, TemplateVersionId = template.Version.Id, DocumentNumber = sequence, CurrentDocumentKey = "CURRENT", Status = template.Template.RequiresApproval ? SeparationGeneratedDocumentStatus.PendingApproval : SeparationGeneratedDocumentStatus.Issued, IssueDate = issueDate, GeneratedAtUtc = clock.GetUtcNow().UtcDateTime, GeneratedByUserId = tenant.UserId, ApprovedAtUtc = template.Template.RequiresApproval ? null : clock.GetUtcNow().UtcDateTime, ApprovedByUserId = template.Template.RequiresApproval ? null : tenant.UserId, SupersedesDocumentId = request.SupersedesDocumentId, StorageReference = $"separation-documents/{tenantId:N}/{Guid.NewGuid():N}.pdf", ContentHash = hash, FileName = SafeFileName(request.DocumentType, facts.Separation.Employee.EmployeeCode, issueDate), SnapshotJson = JsonSerializer.Serialize(snapshot), ContentBase64 = Convert.ToBase64String(bytes), LastReason = request.SupersedesDocumentId is null ? null : "Superseded by a regenerated document" };
        SeparationGeneratedDocument? old = null;
        if (request.SupersedesDocumentId is Guid oldId)
        {
            old = await db.SeparationGeneratedDocuments.FirstOrDefaultAsync(x => x.TenantId == tenantId && x.Id == oldId, ct);
            if (old is not null)
            {
                old.CurrentDocumentKey = old.Id.ToString("N");
                try { await db.SaveChangesAsync(ct); } catch (DbUpdateConcurrencyException) { return Result<SeparationGeneratedDocumentDto>.Conflict("Document generation changed concurrently."); } catch (DbException) { return Result<SeparationGeneratedDocumentDto>.Conflict("Document generation changed concurrently."); } catch (InvalidOperationException) { return Result<SeparationGeneratedDocumentDto>.Unavailable("Document generation can be retried safely."); }
            }
        }
        db.SeparationGeneratedDocuments.Add(document); AddEvent(SeparationDocumentEventType.DocumentGenerated, generatedDocumentId: document.Id, reason: "Official document generated."); if (template.Template.RequiresApproval) AddEvent(SeparationDocumentEventType.DocumentApprovalRequested, generatedDocumentId: document.Id, reason: "Document requires maker-checker approval."); else AddEvent(SeparationDocumentEventType.DocumentIssued, generatedDocumentId: document.Id, reason: "Document issued without approval requirement."); if (old is not null) { old.Status = SeparationGeneratedDocumentStatus.Superseded; old.CurrentDocumentKey = old.Id.ToString("N"); old.SupersededByDocumentId = document.Id; old.LastReason = "Superseded by regeneration."; old.ConcurrencyVersion++; AddEvent(SeparationDocumentEventType.DocumentSuperseded, generatedDocumentId: old.Id, reason: "Superseded by regenerated document."); }
        try { failureInjector?.BeforeGenerationCommit(); failureInjector?.BeforeStorageCommit(); await db.SaveChangesAsync(ct); await transaction.CommitAsync(ct); } catch (DbUpdateConcurrencyException) { await transaction.RollbackAsync(CancellationToken.None); return Result<SeparationGeneratedDocumentDto>.Conflict("Document generation changed concurrently."); } catch (DbException) { await transaction.RollbackAsync(CancellationToken.None); return Result<SeparationGeneratedDocumentDto>.Conflict("Document generation changed concurrently."); } catch (InvalidOperationException) { await transaction.RollbackAsync(CancellationToken.None); return Result<SeparationGeneratedDocumentDto>.Unavailable("Document generation can be retried safely."); }
        return Result<SeparationGeneratedDocumentDto>.Success(ToDocument(document));
    }

    public Task<Result<SeparationGeneratedDocumentDto>> ApproveAsync(Guid id, SeparationDocumentApproveRequest request, CancellationToken ct = default) => TransitionAsync(id, request.ExpectedConcurrencyVersion, SeparationGeneratedDocumentStatus.PendingApproval, SeparationGeneratedDocumentStatus.Approved, SeparationDocumentEventType.DocumentApproved, "Document approved.", ct, true);
    public Task<Result<SeparationGeneratedDocumentDto>> IssueAsync(Guid id, int expectedConcurrencyVersion, CancellationToken ct = default) => TransitionAsync(id, expectedConcurrencyVersion, SeparationGeneratedDocumentStatus.Approved, SeparationGeneratedDocumentStatus.Issued, SeparationDocumentEventType.DocumentIssued, "Document issued.", ct, false);

    public async Task<Result<SeparationGeneratedDocumentDto>> SupersedeAsync(Guid id, SeparationDocumentSupersedeRequest request, CancellationToken ct = default)
    {
        if (string.IsNullOrWhiteSpace(request.Reason)) return Result<SeparationGeneratedDocumentDto>.Invalid("reason", "A supersession reason is required."); var current = await GetDocumentAsync(id, ct); if (!current.Succeeded) return Result<SeparationGeneratedDocumentDto>.Failure(current.Status, current.Message, current.Errors); if (request.ExpectedConcurrencyVersion > 0 && current.Value!.ConcurrencyVersion != request.ExpectedConcurrencyVersion) return Result<SeparationGeneratedDocumentDto>.Conflict("The document changed concurrently."); return await GenerateAsync(current.Value.EmployeeSeparationId, new SeparationDocumentGenerateRequest { DocumentType = current.Value.DocumentType, CustomDocumentCode = current.Value.CustomDocumentCode, TemplateVersionId = request.TemplateVersionId, IssueDate = request.IssueDate, ExpectedConcurrencyVersion = 0, SupersedesDocumentId = id }, ct);
    }

    public async Task<Result<SeparationGeneratedDocumentDto>> CancelAsync(Guid id, SeparationDocumentCancelRequest request, CancellationToken ct = default)
    {
        if (string.IsNullOrWhiteSpace(request.Reason)) return Result<SeparationGeneratedDocumentDto>.Invalid("reason", "A cancellation reason is required."); var row = await db.SeparationGeneratedDocuments.Include(x => x.Employee).FirstOrDefaultAsync(x => x.TenantId == tenant.TenantId && x.Id == id, ct); if (row is null) return Result<SeparationGeneratedDocumentDto>.NotFound("Document not found."); if (request.ExpectedConcurrencyVersion > 0 && row.ConcurrencyVersion != request.ExpectedConcurrencyVersion) return Result<SeparationGeneratedDocumentDto>.Conflict("The document changed concurrently."); if (row.Status is SeparationGeneratedDocumentStatus.Superseded or SeparationGeneratedDocumentStatus.Cancelled) return Result<SeparationGeneratedDocumentDto>.Success(ToDocument(row), "Document was already closed."); try { row.Status = SeparationGeneratedDocumentStatus.Cancelled; row.CurrentDocumentKey = row.Id.ToString("N"); row.LastReason = request.Reason.Trim(); row.ConcurrencyVersion++; AddEvent(SeparationDocumentEventType.DocumentCancelled, generatedDocumentId: id, reason: row.LastReason); await db.SaveChangesAsync(ct); return Result<SeparationGeneratedDocumentDto>.Success(ToDocument(row)); } catch (DbUpdateConcurrencyException) { return Result<SeparationGeneratedDocumentDto>.Conflict("Document cancellation changed concurrently."); }
    }

    public async Task<Result<IReadOnlyList<SeparationGeneratedDocumentDto>>> GetForSeparationAsync(Guid separationId, bool selfOnly = false, CancellationToken ct = default)
    {
        if (tenant.TenantId is not Guid id) return Result<IReadOnlyList<SeparationGeneratedDocumentDto>>.Unauthorized("No authenticated tenant."); if (selfOnly) { var subject = await identity.ResolveCurrentAsync(ct); if (!subject.Succeeded) return Result<IReadOnlyList<SeparationGeneratedDocumentDto>>.Failure(subject.Status, subject.Message, subject.Errors); var owned = await db.EmployeeSeparations.AnyAsync(x => x.TenantId == id && x.Id == separationId && x.EmployeeId == subject.Value!.EmployeeId, ct); if (!owned) return Result<IReadOnlyList<SeparationGeneratedDocumentDto>>.Forbidden("This document does not belong to the signed-in employee."); }
        var rows = await db.SeparationGeneratedDocuments.AsNoTracking().Include(x => x.Employee).Where(x => x.TenantId == id && x.EmployeeSeparationId == separationId && (!selfOnly || new[] { SeparationGeneratedDocumentStatus.Issued, SeparationGeneratedDocumentStatus.Superseded }.Contains(x.Status))).OrderByDescending(x => x.GeneratedAtUtc).ToListAsync(ct); return Result<IReadOnlyList<SeparationGeneratedDocumentDto>>.Success(rows.Select(ToDocument).ToList());
    }

    public async Task<Result<PagedResult<SeparationDocumentDashboardItemDto>>> DashboardAsync(SeparationDocumentDashboardQuery query, CancellationToken ct = default)
    {
        if (tenant.TenantId is not Guid id) return Result<PagedResult<SeparationDocumentDashboardItemDto>>.Unauthorized("No authenticated tenant."); var source = db.SeparationGeneratedDocuments.AsNoTracking().Include(x => x.Employee).Include(x => x.Separation).Where(x => x.TenantId == id); if (query.DocumentType is { } type) source = source.Where(x => x.DocumentType == type); if (query.Status is { } status) source = source.Where(x => x.Status == status); if (query.LwdFrom is { } lwdFrom) source = source.Where(x => x.Separation!.ApprovedLastWorkingDate >= lwdFrom); if (query.LwdTo is { } lwdTo) source = source.Where(x => x.Separation!.ApprovedLastWorkingDate <= lwdTo); if (query.IssueFrom is { } issueFrom) source = source.Where(x => x.IssueDate >= issueFrom); if (query.IssueTo is { } issueTo) source = source.Where(x => x.IssueDate <= issueTo); if (!string.IsNullOrWhiteSpace(query.EmployeeSearch)) source = source.Where(x => (x.Employee!.FirstName + " " + x.Employee.LastName).Contains(query.EmployeeSearch) || (x.Employee.EmployeeCode ?? "").Contains(query.EmployeeSearch)); var total = await source.CountAsync(ct); var rows = await source.OrderByDescending(x => x.GeneratedAtUtc).Skip((query.Page - 1) * query.PageSize).Take(query.PageSize).ToListAsync(ct); return Result<PagedResult<SeparationDocumentDashboardItemDto>>.Success(new(rows.Select(x => new SeparationDocumentDashboardItemDto(x.Id, x.EmployeeSeparationId, x.EmployeeId, FullName(x.Employee), x.Employee!.EmployeeCode, x.Separation!.ApprovedLastWorkingDate, x.DocumentType, x.DocumentNumber, x.Status, x.GeneratedAtUtc, x.ApprovedAtUtc, x.IssueDate, new[] { SeparationGeneratedDocumentStatus.Approved, SeparationGeneratedDocumentStatus.Issued }.Contains(x.Status), x.Status == SeparationGeneratedDocumentStatus.Superseded ? "Superseded" : null)).ToList(), query.Page, query.PageSize, total));
    }

    public async Task<Result<IReadOnlyList<SeparationDocumentEventDto>>> HistoryAsync(Guid id, CancellationToken ct = default)
    { if (tenant.TenantId is not Guid tenantId) return Result<IReadOnlyList<SeparationDocumentEventDto>>.Unauthorized("No authenticated tenant."); if (!await db.SeparationGeneratedDocuments.AnyAsync(x => x.TenantId == tenantId && x.Id == id, ct)) return Result<IReadOnlyList<SeparationDocumentEventDto>>.NotFound("Document not found."); var rows = await db.SeparationDocumentEvents.AsNoTracking().Where(x => x.TenantId == tenantId && x.GeneratedDocumentId == id).OrderByDescending(x => x.OccurredAtUtc).ToListAsync(ct); return Result<IReadOnlyList<SeparationDocumentEventDto>>.Success(rows.Select(x => new SeparationDocumentEventDto(x.Id, x.EventType, x.OccurredAtUtc, x.ActorUserId, x.Reason)).ToList()); }

    public async Task<Result<(byte[] Content, string FileName, string ContentType)>> DownloadAsync(Guid id, bool selfOnly = false, CancellationToken ct = default)
    { var row = await db.SeparationGeneratedDocuments.AsNoTracking().FirstOrDefaultAsync(x => x.TenantId == tenant.TenantId && x.Id == id, ct); if (row is null) return Result<(byte[], string, string)>.NotFound("Document not found."); if (row.Status is not SeparationGeneratedDocumentStatus.Approved and not SeparationGeneratedDocumentStatus.Issued and not SeparationGeneratedDocumentStatus.Superseded) return Result<(byte[], string, string)>.Forbidden("This document is not available for download."); if (selfOnly) { var subject = await identity.ResolveCurrentAsync(ct); if (!subject.Succeeded || subject.Value!.EmployeeId != row.EmployeeId) return Result<(byte[], string, string)>.Forbidden("This document does not belong to the signed-in employee."); if (row.Status is not SeparationGeneratedDocumentStatus.Issued and not SeparationGeneratedDocumentStatus.Superseded) return Result<(byte[], string, string)>.Forbidden("This document has not been issued."); } var content = Convert.FromBase64String(row.ContentBase64); if (!Convert.ToHexString(SHA256.HashData(content)).Equals(row.ContentHash, StringComparison.OrdinalIgnoreCase)) return Result<(byte[], string, string)>.Unavailable("Document integrity validation failed."); return Result<(byte[], string, string)>.Success((content, row.FileName, row.MimeType)); }

    private async Task<Result<SeparationGeneratedDocumentDto>> TransitionAsync(Guid id, int expected, SeparationGeneratedDocumentStatus from, SeparationGeneratedDocumentStatus to, SeparationDocumentEventType eventType, string reason, CancellationToken ct, bool approval)
    { var row = await db.SeparationGeneratedDocuments.Include(x => x.Employee).FirstOrDefaultAsync(x => x.TenantId == tenant.TenantId && x.Id == id, ct); if (row is null) return Result<SeparationGeneratedDocumentDto>.NotFound("Document not found."); if (row.Status == to) return Result<SeparationGeneratedDocumentDto>.Success(ToDocument(row), "Document was already transitioned."); if (row.Status != from) return Result<SeparationGeneratedDocumentDto>.Conflict("The document is not in the required state."); if (expected > 0 && row.ConcurrencyVersion != expected) return Result<SeparationGeneratedDocumentDto>.Conflict("The document changed concurrently."); if (approval && row.GeneratedByUserId == tenant.UserId) return Result<SeparationGeneratedDocumentDto>.Forbidden("The maker cannot approve the same document."); try { if (approval) { if (!Convert.ToHexString(SHA256.HashData(Convert.FromBase64String(row.ContentBase64))).Equals(row.ContentHash, StringComparison.OrdinalIgnoreCase)) return Result<SeparationGeneratedDocumentDto>.Conflict("Document integrity validation failed."); failureInjector?.BeforeApprovalCommit(); row.ApprovedAtUtc = clock.GetUtcNow().UtcDateTime; row.ApprovedByUserId = tenant.UserId; } row.Status = to; row.ConcurrencyVersion++; AddEvent(eventType, generatedDocumentId: id, reason: reason); await db.SaveChangesAsync(ct); return Result<SeparationGeneratedDocumentDto>.Success(ToDocument(row)); } catch (DbUpdateConcurrencyException) { return Result<SeparationGeneratedDocumentDto>.Conflict("Document transition changed concurrently."); } catch (DbException) { return Result<SeparationGeneratedDocumentDto>.Conflict("Document transition changed concurrently."); } catch (InvalidOperationException) { return Result<SeparationGeneratedDocumentDto>.Unavailable("Document transition can be retried safely."); } }

    private async Task<Result<Facts>> LoadFactsAsync(Guid separationId, CancellationToken ct)
    { if (tenant.TenantId is not Guid id) return Result<Facts>.Unauthorized("No authenticated tenant."); var separation = await db.EmployeeSeparations.AsNoTracking().Include(x => x.Employee).Include(x => x.Tenant).Include(x => x.Reason).FirstOrDefaultAsync(x => x.TenantId == id && x.Id == separationId, ct); if (separation?.Employee is null) return Result<Facts>.NotFound("Separation not found."); var orchestration = await db.SeparationSettlementOrchestrations.AsNoTracking().FirstOrDefaultAsync(x => x.TenantId == id && x.EmployeeSeparationId == separationId, ct); var settlement = orchestration?.PayrollFinalSettlementId is Guid sid ? await db.FinalSettlementCases.AsNoTracking().FirstOrDefaultAsync(x => x.TenantId == id && x.Id == sid, ct) : null; var clearance = await db.SeparationClearances.AsNoTracking().FirstOrDefaultAsync(x => x.TenantId == id && x.EmployeeSeparationId == separationId, ct); var template = await db.SeparationDocumentTemplates.AsNoTracking().Include(x => x.Versions).Where(x => x.TenantId == id && x.IsActive).ToListAsync(ct); return Result<Facts>.Success(new(id, separation, orchestration, settlement, clearance, template)); }
    private async Task<SeparationDocumentReadinessDto> ToReadinessAsync(Facts f, CancellationToken ct) { var blockers = new List<string>(); if (f.Separation.ApprovedLastWorkingDate is null) blockers.Add("ApprovedLastWorkingDateRequired"); if (f.Separation.Status is not EmployeeSeparationStatus.Approved and not EmployeeSeparationStatus.NoticePeriod and not EmployeeSeparationStatus.ReadyForExit and not EmployeeSeparationStatus.Exited) blockers.Add("SeparationNotApproved"); if (f.Settlement?.Status != FinalSettlementStatus.Finalized) blockers.Add("FinalSettlementNotFinalized"); if (f.Clearance?.Status != SeparationClearanceStatus.Completed) blockers.Add("ClearanceIncomplete"); var templates = f.Templates.Any(x => x.Versions.Any(v => v.Status == SeparationDocumentTemplateVersionStatus.Published && f.Separation.ApprovedLastWorkingDate is DateOnly d && v.EffectiveFrom <= d && (v.EffectiveTo == null || v.EffectiveTo >= d))); if (!templates) blockers.Add("DocumentTemplateUnavailable"); var ready = blockers.Count == 0; return new(ready, blockers, f.Separation.Id, f.Separation.EmployeeId, f.Separation.ApprovedLastWorkingDate, f.Settlement?.Status, f.Clearance?.Status == SeparationClearanceStatus.Completed, ready); }
    private async Task<TemplateChoice?> ResolveTemplateAsync(Guid tenantId, DateOnly date, SeparationDocumentGenerateRequest request, CancellationToken ct) { if (request.TemplateVersionId is Guid versionId) { var explicitVersion = await db.SeparationDocumentTemplateVersions.Include(x => x.Template).FirstOrDefaultAsync(x => x.TenantId == tenantId && x.Id == versionId && x.Status == SeparationDocumentTemplateVersionStatus.Published && x.Template!.DocumentType == request.DocumentType, ct); return explicitVersion is null ? null : new(explicitVersion.Template!, explicitVersion); } var rows = await db.SeparationDocumentTemplates.Include(x => x.Versions).Where(x => x.TenantId == tenantId && x.IsActive && x.DocumentType == request.DocumentType).ToListAsync(ct); var matches = rows.SelectMany(x => x.Versions.Where(v => v.Status == SeparationDocumentTemplateVersionStatus.Published && v.EffectiveFrom <= date && (v.EffectiveTo == null || v.EffectiveTo >= date)).Select(v => new TemplateChoice(x, v))).OrderByDescending(x => x.Version.EffectiveFrom).ToList(); return matches.FirstOrDefault(); }
    private async Task<string> AllocateNumberAsync(Guid tenantId, SeparationDocumentType type, int year, CancellationToken ct) { var seq = await db.SeparationDocumentNumberSequences.FirstOrDefaultAsync(x => x.TenantId == tenantId && x.DocumentType == type && x.Year == year, ct); var number = seq?.NextNumber ?? 1; if (seq is null) db.SeparationDocumentNumberSequences.Add(new SeparationDocumentNumberSequence { Id = Guid.NewGuid(), TenantId = tenantId, DocumentType = type, Year = year, NextNumber = 2 }); else { seq.NextNumber++; seq.ConcurrencyVersion++; } return $"{Prefix(type)}/{year}/{number:000000}"; }
    private async Task<Result<SeparationGeneratedDocument>> GetDocumentAsync(Guid id, CancellationToken ct) { var row = await db.SeparationGeneratedDocuments.FirstOrDefaultAsync(x => x.TenantId == tenant.TenantId && x.Id == id, ct); return row is null ? Result<SeparationGeneratedDocument>.NotFound("Document not found.") : Result<SeparationGeneratedDocument>.Success(row); }
    private async Task<Result<EmploymentFacts>> ResolveEmploymentAsync(Guid tenantId, Guid employeeId, DateOnly date, CancellationToken ct)
    { var resolved = await new EffectiveEmploymentResolver(db, tenant).ResolveAsync(tenantId, employeeId, date, ct); if (resolved.Employment is null) return Result<EmploymentFacts>.Conflict("Historical employment facts are unavailable."); var history = await db.EmployeeEmploymentHistory.AsNoTracking().Include(x => x.WorkLocation).Where(x => x.TenantId == tenantId && x.EmployeeId == employeeId && !x.IsSuperseded && x.EffectiveFrom <= date && (x.EffectiveTo == null || date <= x.EffectiveTo)).OrderByDescending(x => x.EffectiveFrom).FirstOrDefaultAsync(ct); return history is null ? Result<EmploymentFacts>.Conflict("Historical employment facts are unavailable.") : Result<EmploymentFacts>.Success(new(history.DesignationName, history.DepartmentName, history.WorkLocation?.Name, history.GradeLevel)); }
    private void AddEvent(SeparationDocumentEventType type, Guid? templateId = null, Guid? versionId = null, Guid? generatedDocumentId = null, string? reason = null) => db.SeparationDocumentEvents.Add(new SeparationDocumentEvent { Id = Guid.NewGuid(), TenantId = tenant.TenantId!.Value, TemplateId = templateId, TemplateVersionId = versionId, GeneratedDocumentId = generatedDocumentId, EventType = type, ActorUserId = tenant.UserId, OccurredAtUtc = clock.GetUtcNow().UtcDateTime, Reason = reason });
    private static string? ValidateBody(string body) { if (string.IsNullOrWhiteSpace(body)) return "Template body is required."; if (body.Contains("<script", StringComparison.OrdinalIgnoreCase) || body.Contains("javascript:", StringComparison.OrdinalIgnoreCase) || body.Contains("file:", StringComparison.OrdinalIgnoreCase) || body.Contains("http://", StringComparison.OrdinalIgnoreCase) || body.Contains("https://", StringComparison.OrdinalIgnoreCase) || body.Contains("localhost", StringComparison.OrdinalIgnoreCase) || body.Contains("127.0.0.1", StringComparison.OrdinalIgnoreCase) || body.Contains("../", StringComparison.OrdinalIgnoreCase)) return "Executable or unsafe template content is not allowed."; foreach (Match match in Regex.Matches(body, @"\{\{([^{}]+)\}\}")) if (!AllowedFields.Contains(match.Groups[1].Value)) return $"Unknown merge field '{match.Groups[1].Value}'."; return null; }
    private static string RenderPlainText(string body, object snapshot) { var json = JsonSerializer.Deserialize<Dictionary<string, string?>>(JsonSerializer.Serialize(snapshot)) ?? []; var result = Token.Replace(body, m => json.TryGetValue(m.Groups[1].Value, out var value) ? value ?? string.Empty : string.Empty); return WebUtility.HtmlDecode(Regex.Replace(result, "<[^>]+>", " ")).Replace("\r", string.Empty).Trim(); }
    private static byte[] RenderPdf(string text) { var escaped = text.Replace("\\", "\\\\").Replace("(", "\\(").Replace(")", "\\)").Replace("\n", ") Tj 0 -16 Td (" ); var content = $"BT /F1 11 Tf 50 780 Td ({escaped}) Tj ET"; var objects = new[] { "<< /Type /Catalog /Pages 2 0 R >>", "<< /Type /Pages /Kids [3 0 R] /Count 1 >>", "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>", "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>", $"<< /Length {Encoding.ASCII.GetByteCount(content)} >>\nstream\n{content}\nendstream" }; using var ms = new MemoryStream(); using var sw = new StreamWriter(ms, Encoding.ASCII, 1024, true); sw.Write("%PDF-1.4\n"); var offsets = new List<long> { 0 }; for (var i = 0; i < objects.Length; i++) { sw.Flush(); offsets.Add(ms.Position); sw.Write($"{i + 1} 0 obj\n{objects[i]}\nendobj\n"); } sw.Flush(); var start = ms.Position; sw.Write($"xref\n0 {objects.Length + 1}\n0000000000 65535 f \n"); for (var i = 1; i < offsets.Count; i++) sw.Write($"{offsets[i]:0000000000} 00000 n \n"); sw.Write($"trailer\n<< /Size {objects.Length + 1} /Root 1 0 R >>\nstartxref\n{start}\n%%EOF"); sw.Flush(); return ms.ToArray(); }
    private static object Snapshot(Facts f, EmploymentFacts e, TemplateChoice t, string number, DateOnly issueDate) => new Dictionary<string, string?> { ["Employee.FullName"] = FullName(f.Separation.Employee!), ["Employee.EmployeeCode"] = f.Separation.Employee!.EmployeeCode, ["Employee.DateOfJoining"] = f.Separation.Employee.DateOfJoining.ToString("yyyy-MM-dd"), ["Employee.Designation"] = e.DesignationName, ["Employee.Department"] = e.DepartmentName, ["Employee.WorkLocation"] = e.WorkLocationName, ["Separation.ApprovedLastWorkingDate"] = f.Separation.ApprovedLastWorkingDate?.ToString("yyyy-MM-dd"), ["Separation.Reason"] = f.Separation.Reason?.Name, ["Separation.Type"] = f.Separation.SeparationType.ToString(), ["Employment.LastDesignation"] = e.DesignationName, ["Employment.LastDepartment"] = e.DepartmentName, ["Employment.LastGrade"] = e.GradeLevel, ["Organization.Name"] = f.Separation.Tenant?.TenantName, ["Organization.Address"] = f.Separation.Tenant?.Address, ["Organization.LogoReference"] = null, ["Document.Number"] = number, ["Document.IssueDate"] = issueDate.ToString("yyyy-MM-dd") };
    private static string SafeFileName(SeparationDocumentType type, string? code, DateOnly date) => $"{Regex.Replace(type.ToString(), "[^A-Za-z0-9]", string.Empty)}_{Regex.Replace(code ?? "Employee", "[^A-Za-z0-9_-]", string.Empty)}_{date:yyyy}.pdf";
    private static string Prefix(SeparationDocumentType type) => type switch { SeparationDocumentType.RelievingLetter => "RL", SeparationDocumentType.ExperienceLetter => "EL", SeparationDocumentType.ServiceCertificate => "SC", _ => "SD" };
    private static bool ValidDates(DateOnly from, DateOnly? to) => to is null || to >= from;
    private static bool Overlaps(DateOnly a, DateOnly? at, DateOnly b, DateOnly? bt) => a <= (bt ?? DateOnly.MaxValue) && b <= (at ?? DateOnly.MaxValue);
    private static string FullName(HRMS.Domain.Entities.Employee e) => string.Join(' ', new[] { e.FirstName, e.MiddleName, e.LastName }.Where(x => !string.IsNullOrWhiteSpace(x)));
    private static SeparationDocumentTemplateDto ToTemplate(SeparationDocumentTemplate x) => new(x.Id, x.Code, x.Name, x.DocumentType, x.Description, x.IsActive, x.EffectiveFrom, x.EffectiveTo, x.RequiresApproval, x.ConcurrencyVersion, x.Versions.OrderByDescending(v => v.VersionNumber).Select(v => new SeparationDocumentTemplateVersionDto(v.Id, v.VersionNumber, v.Status, v.EffectiveFrom, v.EffectiveTo, v.Subject, v.BodyTemplate, v.HeaderTemplate, v.FooterTemplate, v.PublishedAtUtc)).ToList());
    private static SeparationGeneratedDocumentDto ToDocument(SeparationGeneratedDocument x) => new(x.Id, x.EmployeeSeparationId, x.EmployeeId, x.Employee is null ? string.Empty : FullName(x.Employee), x.Employee?.EmployeeCode, x.DocumentType, x.CustomDocumentCode, x.DocumentNumber, x.Status, x.IssueDate, x.GeneratedAtUtc, x.ApprovedAtUtc, x.FileName, x.ContentHash, x.TemplateId, x.TemplateVersionId, x.SupersedesDocumentId, x.SupersededByDocumentId, x.LastReason);
    private sealed record Facts(Guid TenantId, EmployeeSeparation Separation, SeparationSettlementOrchestration? Orchestration, FinalSettlementCase? Settlement, SeparationClearance? Clearance, IReadOnlyList<SeparationDocumentTemplate> Templates);
    private sealed record EmploymentFacts(string? DesignationName, string? DepartmentName, string? WorkLocationName, string? GradeLevel);
    private sealed record TemplateChoice(SeparationDocumentTemplate Template, SeparationDocumentTemplateVersion Version);
}
