using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using HRMS.Application.Abstractions;
using HRMS.Application.Common;
using HRMS.Application.DTOs.Payroll;
using HRMS.Domain.Entities;
using HRMS.Domain.Enums;
using Microsoft.EntityFrameworkCore;

namespace HRMS.Application.Services;

public sealed class StatutoryFilingService(IHrmsDbContext db, ITenantContext tenant, TimeProvider clock, IPayrollApprovalGuard? approvalGuard = null, IStatutoryFilingConnectorRegistry? connectorRegistry = null) : IStatutoryFilingService
{
    public async Task<Result<StatutoryFilingDefinitionDto>> CreateDefinitionAsync(StatutoryFilingDefinitionRequest request, CancellationToken ct = default)
    {
        if (tenant.TenantId is not Guid tid) return Result<StatutoryFilingDefinitionDto>.Unauthorized("No authenticated tenant.");
        var code = request.Code.Trim().ToUpperInvariant();
        if (string.IsNullOrWhiteSpace(code) || string.IsNullOrWhiteSpace(request.Name) || string.IsNullOrWhiteSpace(request.FilingType)) return Result<StatutoryFilingDefinitionDto>.Invalid("Definition code, name and filing type are required.");
        if (await db.StatutoryFilingDefinitions.AnyAsync(x => x.TenantId == tid && x.Code == code, ct)) return Result<StatutoryFilingDefinitionDto>.Conflict("Filing definition already exists.");
        if (request.ConnectionProfileId is Guid profileId && !await db.StatutoryFilingConnectionProfiles.AnyAsync(x => x.TenantId == tid && x.Id == profileId && x.IsActive, ct)) return Result<StatutoryFilingDefinitionDto>.Invalid("connectionProfileId", "The active connection profile was not found for this tenant.");
        var definition = new StatutoryFilingDefinition { Id = Guid.NewGuid(), TenantId = tid, Code = code, Name = request.Name.Trim(), FilingType = request.FilingType.Trim(), JurisdictionCode = request.JurisdictionCode?.Trim().ToUpperInvariant(), RequiresApproval = request.RequiresApproval, DestinationType = request.DestinationType, ConnectionProfileId = request.ConnectionProfileId };
        var version = new StatutoryFilingDefinitionVersion { Id = Guid.NewGuid(), TenantId = tid, DefinitionId = definition.Id, Version = 1, EffectiveFrom = DateOnly.FromDateTime(clock.GetUtcNow().UtcDateTime), OutputFormat = request.OutputFormat, SourceType = request.SourceType?.Trim() };
        db.StatutoryFilingDefinitions.Add(definition); db.StatutoryFilingDefinitionVersions.Add(version); await db.SaveChangesAsync(ct); return Result<StatutoryFilingDefinitionDto>.Success(ToDto(definition));
    }

    public async Task<Result<IReadOnlyList<StatutoryFilingDefinitionDto>>> GetDefinitionsAsync(CancellationToken ct = default)
    {
        if (tenant.TenantId is not Guid tid) return Result<IReadOnlyList<StatutoryFilingDefinitionDto>>.Unauthorized("No authenticated tenant.");
        var rows = await db.StatutoryFilingDefinitions.AsNoTracking().Where(x => x.TenantId == tid).OrderBy(x => x.Code).Select(x => new StatutoryFilingDefinitionDto(x.Id, x.Code, x.Name, x.FilingType, x.JurisdictionCode, x.RequiresApproval, x.DestinationType, x.IsActive, x.ConnectionProfileId)).ToListAsync(ct);
        return Result<IReadOnlyList<StatutoryFilingDefinitionDto>>.Success(rows);
    }

    public async Task<Result<IReadOnlyList<StatutoryFilingConnectionProfileDto>>> GetConnectionProfilesAsync(CancellationToken ct = default)
    {
        if (tenant.TenantId is not Guid tid) return Result<IReadOnlyList<StatutoryFilingConnectionProfileDto>>.Unauthorized("No authenticated tenant.");
        var rows = await db.StatutoryFilingConnectionProfiles.AsNoTracking().Where(x => x.TenantId == tid).OrderBy(x => x.Name).Select(x => ToProfileDto(x)).ToListAsync(ct);
        return Result<IReadOnlyList<StatutoryFilingConnectionProfileDto>>.Success(rows);
    }

    public async Task<Result<StatutoryFilingConnectionProfileDto>> CreateConnectionProfileAsync(StatutoryFilingConnectionProfileRequest request, CancellationToken ct = default)
    {
        if (tenant.TenantId is not Guid tid) return Result<StatutoryFilingConnectionProfileDto>.Unauthorized("No authenticated tenant.");
        if (string.IsNullOrWhiteSpace(request.Name)) return Result<StatutoryFilingConnectionProfileDto>.Invalid("name", "Connection profile name is required.");
        if (await db.StatutoryFilingConnectionProfiles.AnyAsync(x => x.TenantId == tid && x.Name == request.Name.Trim(), ct)) return Result<StatutoryFilingConnectionProfileDto>.Conflict("Connection profile already exists.");
        var profile = new StatutoryFilingConnectionProfile { Id = Guid.NewGuid(), TenantId = tid, Name = request.Name.Trim(), ConnectorType = request.ConnectorType, Endpoint = request.Endpoint?.Trim(), NonSecretConfigurationJson = request.NonSecretConfigurationJson?.Trim(), SecretReference = request.SecretReference?.Trim(), EffectiveFrom = request.EffectiveFrom, EffectiveTo = request.EffectiveTo, IsActive = request.IsActive };
        var validation = await ResolveConnector(profile).ValidateConfigurationAsync(profile, ct); profile.LastValidationStatus = validation.Succeeded ? "Valid" : "Invalid"; profile.LastValidatedAtUtc = clock.GetUtcNow().UtcDateTime; db.StatutoryFilingConnectionProfiles.Add(profile); await db.SaveChangesAsync(ct); return Result<StatutoryFilingConnectionProfileDto>.Success(ToProfileDto(profile));
    }

    public async Task<Result<StatutoryFilingConnectionProfileDto>> UpdateConnectionProfileAsync(Guid id, StatutoryFilingConnectionProfileRequest request, CancellationToken ct = default)
    {
        var profile = await db.StatutoryFilingConnectionProfiles.FirstOrDefaultAsync(x => x.TenantId == tenant.TenantId && x.Id == id, ct); if (profile is null) return Result<StatutoryFilingConnectionProfileDto>.NotFound("Connection profile not found."); if (string.IsNullOrWhiteSpace(request.Name)) return Result<StatutoryFilingConnectionProfileDto>.Invalid("name", "Connection profile name is required."); profile.Name = request.Name.Trim(); profile.ConnectorType = request.ConnectorType; profile.Endpoint = request.Endpoint?.Trim(); profile.NonSecretConfigurationJson = request.NonSecretConfigurationJson?.Trim(); profile.SecretReference = request.SecretReference?.Trim(); profile.EffectiveFrom = request.EffectiveFrom; profile.EffectiveTo = request.EffectiveTo; profile.IsActive = request.IsActive; profile.ConcurrencyVersion++; var validation = await ResolveConnector(profile).ValidateConfigurationAsync(profile, ct); profile.LastValidationStatus = validation.Succeeded ? "Valid" : "Invalid"; profile.LastValidatedAtUtc = clock.GetUtcNow().UtcDateTime; await db.SaveChangesAsync(ct); return Result<StatutoryFilingConnectionProfileDto>.Success(ToProfileDto(profile));
    }

    public async Task<Result<StatutoryFilingConnectionProfileDto>> ValidateConnectionProfileAsync(Guid id, CancellationToken ct = default)
    {
        var profile = await db.StatutoryFilingConnectionProfiles.FirstOrDefaultAsync(x => x.TenantId == tenant.TenantId && x.Id == id, ct); if (profile is null) return Result<StatutoryFilingConnectionProfileDto>.NotFound("Connection profile not found."); var validation = await ResolveConnector(profile).ValidateConfigurationAsync(profile, ct); profile.LastValidationStatus = validation.Succeeded ? "Valid" : "Invalid"; profile.LastValidatedAtUtc = clock.GetUtcNow().UtcDateTime; await db.SaveChangesAsync(ct); return validation.Succeeded ? Result<StatutoryFilingConnectionProfileDto>.Success(ToProfileDto(profile)) : Result<StatutoryFilingConnectionProfileDto>.Invalid("configuration", validation.Message ?? "Connector configuration is invalid.");
    }

    public async Task<Result<StatutoryFilingRunDto>> CreateRunAsync(StatutoryFilingRunRequest request, CancellationToken ct = default)
    {
        if (tenant.TenantId is not Guid tid) return Result<StatutoryFilingRunDto>.Unauthorized("No authenticated tenant.");
        var definition = await db.StatutoryFilingDefinitions.FirstOrDefaultAsync(x => x.TenantId == tid && x.Id == request.DefinitionId && x.IsActive, ct);
        var version = await db.StatutoryFilingDefinitionVersions.Where(x => x.TenantId == tid && x.DefinitionId == request.DefinitionId && x.EffectiveFrom <= DateOnly.FromDateTime(clock.GetUtcNow().UtcDateTime) && (x.EffectiveTo == null || x.EffectiveTo >= DateOnly.FromDateTime(clock.GetUtcNow().UtcDateTime))).OrderByDescending(x => x.Version).FirstOrDefaultAsync(ct);
        if (definition is null || version is null) return Result<StatutoryFilingRunDto>.NotFound("Active filing definition/version not found.");
        if (await db.StatutoryFilingRuns.AnyAsync(x => x.TenantId == tid && x.DefinitionId == request.DefinitionId && x.FilingPeriod == request.FilingPeriod.Trim() && x.Status != StatutoryFilingRunStatus.Cancelled, ct)) return Result<StatutoryFilingRunDto>.Conflict("An active filing run already exists for this period.");
        var run = new StatutoryFilingRun { Id = Guid.NewGuid(), TenantId = tid, DefinitionId = definition.Id, DefinitionVersionId = version.Id, FilingPeriod = request.FilingPeriod.Trim(), Status = StatutoryFilingRunStatus.Draft };
        db.StatutoryFilingRuns.Add(run); AddHistory(run, StatutoryFilingHistoryEvent.RunCreated, null, run.Status, "Filing run created."); await db.SaveChangesAsync(ct); return Result<StatutoryFilingRunDto>.Success(ToDto(run, null, null));
    }

    public async Task<Result<IReadOnlyList<StatutoryFilingRunDto>>> GetRunsAsync(CancellationToken ct = default)
    {
        if (tenant.TenantId is not Guid tid) return Result<IReadOnlyList<StatutoryFilingRunDto>>.Unauthorized("No authenticated tenant.");
        var runs = await db.StatutoryFilingRuns.AsNoTracking().Where(x => x.TenantId == tid).OrderByDescending(x => x.CreatedDate).Select(x => new StatutoryFilingRunDto(x.Id, x.DefinitionId, x.FilingPeriod, x.Status, x.RowCount, x.ValidationErrorCount, x.ValidationWarningCount, null, null, null, null)).ToListAsync(ct);
        return Result<IReadOnlyList<StatutoryFilingRunDto>>.Success(runs);
    }

    public async Task<Result<StatutoryFilingRunDto>> GenerateAsync(Guid runId, CancellationToken ct = default)
    {
        var run = await LoadRun(runId, ct); if (run is null) return Result<StatutoryFilingRunDto>.NotFound("Filing run not found.");
        if (run.Status is not StatutoryFilingRunStatus.Draft and not StatutoryFilingRunStatus.Generated and not StatutoryFilingRunStatus.Validated and not StatutoryFilingRunStatus.Rejected and not StatutoryFilingRunStatus.Failed) return Result<StatutoryFilingRunDto>.Conflict("Run cannot be generated in its current state.");
        var period = ParsePeriod(run.FilingPeriod); if (period is null) return Result<StatutoryFilingRunDto>.Invalid("filingPeriod", "Filing period must use yyyy-MM format.");
        var returnRows = await db.PayrollStatutoryReturnEmployees.AsNoTracking().Where(x => x.TenantId == run.TenantId && x.ReturnBatch!.Status != PayrollStatutoryReturnStatus.Draft && x.ReturnBatch.Status != PayrollStatutoryReturnStatus.Cancelled && x.ReturnBatch.CompliancePeriod!.PeriodEnd.Year == period.Value.Year && x.ReturnBatch.CompliancePeriod.PeriodEnd.Month == period.Value.Month).OrderBy(x => x.Sequence).ToListAsync(ct);
        if (returnRows.Count == 0) return Result<StatutoryFilingRunDto>.Conflict("No finalized statutory source rows match the filing period.");
        var oldItems = await db.StatutoryFilingRunItems.Where(x => x.TenantId == run.TenantId && x.RunId == run.Id).ToListAsync(ct); db.StatutoryFilingRunItems.RemoveRange(oldItems);
        var sequence = 1; foreach (var row in returnRows) db.StatutoryFilingRunItems.Add(new StatutoryFilingRunItem { Id = Guid.NewGuid(), TenantId = run.TenantId, RunId = run.Id, EmployeeId = row.EmployeeId, PayrollStatutoryReturnEmployeeId = row.Id, SourceReference = row.Id.ToString("N"), SourceSnapshotJson = $"{{\"employeeCode\":\"{Escape(row.EmployeeCodeSnapshot)}\",\"amount\":{row.PayableAmount.ToString(CultureInfo.InvariantCulture)}}}", Amount = row.PayableAmount, Sequence = sequence++ });
        var csv = new StringBuilder("Sequence,EmployeeCode,EmployeeName,PayableAmount\r\n"); foreach (var row in returnRows) csv.Append(row.Sequence.ToString(CultureInfo.InvariantCulture)).Append(',').Append(Csv(row.EmployeeCodeSnapshot)).Append(',').Append(Csv(row.EmployeeNameSnapshot)).Append(',').Append(row.PayableAmount.ToString("0.00", CultureInfo.InvariantCulture)).Append("\r\n");
        var content = csv.ToString(); var hash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(content))).ToLowerInvariant(); var resubmission = run.Status is StatutoryFilingRunStatus.Rejected or StatutoryFilingRunStatus.Failed; var previousPackage = resubmission ? await db.StatutoryFilingPackages.Where(x => x.TenantId == run.TenantId && x.RunId == run.Id).OrderByDescending(x => x.Version).FirstOrDefaultAsync(ct) : null; var previousSubmission = resubmission ? await db.StatutoryFilingSubmissions.Where(x => x.TenantId == run.TenantId && x.RunId == run.Id).OrderByDescending(x => x.CreatedDate).FirstOrDefaultAsync(ct) : null; var package = resubmission ? null : await db.StatutoryFilingPackages.FirstOrDefaultAsync(x => x.TenantId == run.TenantId && x.RunId == run.Id && x.PackageHash == hash, ct); if (package is null) { var version = (await db.StatutoryFilingPackages.Where(x => x.TenantId == run.TenantId && x.RunId == run.Id).Select(x => (int?)x.Version).MaxAsync(ct) ?? 0) + 1; package = new StatutoryFilingPackage { Id = Guid.NewGuid(), TenantId = run.TenantId, RunId = run.Id, Version = version, PreviousPackageId = previousPackage?.Id, ResubmissionOfSubmissionId = previousSubmission?.Id, FileName = $"{run.FilingPeriod}-statutory-filing-v{version}.csv", ContentType = "text/csv; charset=utf-8", PackageHash = hash, RowCount = returnRows.Count, ByteCount = Encoding.UTF8.GetByteCount(content), Content = content }; db.StatutoryFilingPackages.Add(package); }
        run.RowCount = returnRows.Count; run.Status = StatutoryFilingRunStatus.Generated; run.GeneratedAtUtc = clock.GetUtcNow().UtcDateTime; run.GeneratedByUserId = tenant.UserId; AddHistory(run, StatutoryFilingHistoryEvent.Generated, StatutoryFilingRunStatus.Draft, run.Status, "Package generated from persisted statutory register data."); AddHistory(run, StatutoryFilingHistoryEvent.PackageCreated, run.Status, run.Status, $"Package SHA-256 {hash}."); try { await db.SaveChangesAsync(ct); } catch (DbUpdateConcurrencyException) { db.ClearChangeTracker(); var current = await LoadRun(runId, ct); return current is null ? Result<StatutoryFilingRunDto>.NotFound("Filing run not found.") : await GetRunResult(current, ct); } catch (DbUpdateException) { db.ClearChangeTracker(); var current = await LoadRun(runId, ct); return current is null ? Result<StatutoryFilingRunDto>.NotFound("Filing run not found.") : await GetRunResult(current, ct); } return await GetRunResult(run, ct);
    }

    public async Task<Result<StatutoryFilingRunDto>> ValidateAsync(Guid runId, CancellationToken ct = default)
    {
        var run = await LoadRun(runId, ct); if (run is null) return Result<StatutoryFilingRunDto>.NotFound("Filing run not found.");
        if (run.Status is not StatutoryFilingRunStatus.Generated and not StatutoryFilingRunStatus.Validated) return Result<StatutoryFilingRunDto>.Conflict("Run must be generated before validation.");
        var issues = await db.StatutoryFilingValidationIssues.Where(x => x.TenantId == run.TenantId && x.RunId == run.Id).ToListAsync(ct); db.StatutoryFilingValidationIssues.RemoveRange(issues);
        var items = await db.StatutoryFilingRunItems.Where(x => x.TenantId == run.TenantId && x.RunId == run.Id).ToListAsync(ct); foreach (var item in items.Where(x => string.IsNullOrWhiteSpace(x.SourceReference))) db.StatutoryFilingValidationIssues.Add(new StatutoryFilingValidationIssue { Id = Guid.NewGuid(), TenantId = run.TenantId, RunId = run.Id, RunItemId = item.Id, Severity = StatutoryFilingIssueSeverity.Error, Code = "MissingSource", Message = "Source reference is required." });
        run.ValidationErrorCount = await db.StatutoryFilingValidationIssues.CountAsync(x => x.TenantId == run.TenantId && x.RunId == run.Id && x.Severity == StatutoryFilingIssueSeverity.Error, ct); run.ValidationWarningCount = await db.StatutoryFilingValidationIssues.CountAsync(x => x.TenantId == run.TenantId && x.RunId == run.Id && x.Severity == StatutoryFilingIssueSeverity.Warning, ct); if (run.ValidationErrorCount > 0) return Result<StatutoryFilingRunDto>.Conflict("Filing run contains blocking validation errors.");
        var previous = run.Status; run.Status = StatutoryFilingRunStatus.Validated; AddHistory(run, StatutoryFilingHistoryEvent.Validated, previous, run.Status, "Filing run validated."); await db.SaveChangesAsync(ct); return await GetRunResult(run, ct);
    }

    public Task<Result<StatutoryFilingRunDto>> SubmitForApprovalAsync(Guid runId, CancellationToken ct = default) => TransitionAsync(runId, StatutoryFilingRunStatus.SubmittedForApproval, StatutoryFilingRunStatus.Validated, StatutoryFilingHistoryEvent.SubmittedForApproval, ct);

    public async Task<Result<StatutoryFilingRunDto>> ApproveAsync(Guid runId, CancellationToken ct = default)
    {
        var run = await LoadRun(runId, ct); if (run is null) return Result<StatutoryFilingRunDto>.NotFound("Filing run not found."); var guard = await (approvalGuard ?? new PayrollApprovalGuard(db, tenant)).ValidateAsync(run.GeneratedByUserId, "approve", ct: ct); if (!guard.Succeeded) return Result<StatutoryFilingRunDto>.Failure(guard.Status, guard.Message, guard.Errors); return await TransitionAsync(runId, StatutoryFilingRunStatus.Approved, StatutoryFilingRunStatus.SubmittedForApproval, StatutoryFilingHistoryEvent.Approved, ct);
    }

    public async Task<Result<StatutoryFilingRunDto>> SubmitAsync(Guid runId, CancellationToken ct = default)
    {
        var run = await LoadRun(runId, ct); if (run is null) return Result<StatutoryFilingRunDto>.NotFound("Filing run not found."); if (run.Status is StatutoryFilingRunStatus.Submitted or StatutoryFilingRunStatus.Acknowledged) return await GetRunResult(run, ct); if (run.Status != StatutoryFilingRunStatus.Approved) return Result<StatutoryFilingRunDto>.Conflict("Only approved runs can be submitted.");
        var package = await db.StatutoryFilingPackages.Where(x => x.TenantId == run.TenantId && x.RunId == run.Id).OrderByDescending(x => x.Version).FirstOrDefaultAsync(ct); if (package is null) return Result<StatutoryFilingRunDto>.Conflict("Generate a package before submitting.");
        var existing = await db.StatutoryFilingSubmissions.FirstOrDefaultAsync(x => x.TenantId == run.TenantId && x.PackageId == package.Id, ct); if (existing is not null) return await GetRunResult(run, ct);
        var definition = await db.StatutoryFilingDefinitions.FirstAsync(x => x.TenantId == run.TenantId && x.Id == run.DefinitionId, ct); var profile = definition.ConnectionProfileId is Guid profileId ? await db.StatutoryFilingConnectionProfiles.FirstOrDefaultAsync(x => x.TenantId == run.TenantId && x.Id == profileId && x.IsActive, ct) : null; var connector = ResolveConnector(profile, definition.DestinationType); var validation = await connector.ValidateConfigurationAsync(profile, ct); if (!validation.Succeeded) return Result<StatutoryFilingRunDto>.Invalid("connector", validation.Message ?? "Connector configuration is invalid."); var connectorResult = await connector.SubmitAsync(package, profile, ct); if (!connectorResult.Succeeded) return Result<StatutoryFilingRunDto>.Failure(connectorResult.Status, connectorResult.Message, connectorResult.Errors); var response = connectorResult.Value!; var submission = new StatutoryFilingSubmission { Id = Guid.NewGuid(), TenantId = run.TenantId, RunId = run.Id, PackageId = package.Id, ResubmissionOfSubmissionId = package.ResubmissionOfSubmissionId, Outcome = response.Outcome, ExternalReference = response.ExternalReference, ResponseCode = response.ResponseCode, SubmittedAtUtc = clock.GetUtcNow().UtcDateTime, SafeResponseSummary = response.SafeResponseSummary }; db.StatutoryFilingSubmissions.Add(submission); db.StatutoryFilingSubmissionAttempts.Add(new StatutoryFilingSubmissionAttempt { Id = Guid.NewGuid(), TenantId = run.TenantId, SubmissionId = submission.Id, AttemptNumber = 1, Outcome = submission.Outcome, ExternalReference = response.ExternalReference, ResponseCode = response.ResponseCode, AttemptedAtUtc = submission.SubmittedAtUtc.Value, SafeResponseSummary = response.SafeResponseSummary }); package.IsSubmitted = true; var previous = run.Status; run.Status = response.Outcome == StatutoryFilingSubmissionOutcome.Rejected ? StatutoryFilingRunStatus.Rejected : response.Outcome == StatutoryFilingSubmissionOutcome.Failed ? StatutoryFilingRunStatus.Failed : response.Outcome is StatutoryFilingSubmissionOutcome.Accepted or StatutoryFilingSubmissionOutcome.Acknowledged ? StatutoryFilingRunStatus.Submitted : StatutoryFilingRunStatus.Submitted; AddHistory(run, response.Outcome == StatutoryFilingSubmissionOutcome.Rejected ? StatutoryFilingHistoryEvent.Rejected : StatutoryFilingHistoryEvent.Submitted, previous, run.Status, response.SafeResponseSummary); try { await db.SaveChangesAsync(ct); } catch (DbUpdateConcurrencyException) { db.ClearChangeTracker(); var current = await LoadRun(runId, ct); return current is null ? Result<StatutoryFilingRunDto>.NotFound("Filing run not found.") : await GetRunResult(current, ct); } catch (DbUpdateException) { db.ClearChangeTracker(); var current = await LoadRun(runId, ct); return current is null ? Result<StatutoryFilingRunDto>.NotFound("Filing run not found.") : await GetRunResult(current, ct); } return await GetRunResult(run, ct);
    }

    public Task<Result<StatutoryFilingRunDto>> RejectAsync(Guid runId, string reason, CancellationToken ct = default) => TransitionAsync(runId, StatutoryFilingRunStatus.Rejected, StatutoryFilingRunStatus.Submitted, StatutoryFilingHistoryEvent.Rejected, ct, reason);

    public async Task<Result<StatutoryFilingRunDto>> AcknowledgeAsync(Guid runId, StatutoryFilingAcknowledgementRequest request, CancellationToken ct = default)
    {
        var run = await LoadRun(runId, ct); if (run is null) return Result<StatutoryFilingRunDto>.NotFound("Filing run not found."); if (string.IsNullOrWhiteSpace(request.ReferenceNumber)) return Result<StatutoryFilingRunDto>.Invalid("referenceNumber", "Acknowledgement reference is required."); var submission = await db.StatutoryFilingSubmissions.FirstOrDefaultAsync(x => x.TenantId == run.TenantId && x.RunId == run.Id, ct); if (submission is null) return Result<StatutoryFilingRunDto>.Conflict("Submit the package before recording acknowledgement."); if (!await db.StatutoryFilingAcknowledgements.AnyAsync(x => x.TenantId == run.TenantId && x.SubmissionId == submission.Id && x.ReferenceNumber == request.ReferenceNumber.Trim(), ct)) db.StatutoryFilingAcknowledgements.Add(new StatutoryFilingAcknowledgement { Id = Guid.NewGuid(), TenantId = run.TenantId, SubmissionId = submission.Id, ReferenceNumber = request.ReferenceNumber.Trim(), Notes = request.Notes?.Trim(), AcknowledgedAtUtc = clock.GetUtcNow().UtcDateTime }); submission.Outcome = StatutoryFilingSubmissionOutcome.Acknowledged; submission.AcknowledgedAtUtc = clock.GetUtcNow().UtcDateTime; var previous = run.Status; run.Status = StatutoryFilingRunStatus.Acknowledged; AddHistory(run, StatutoryFilingHistoryEvent.Acknowledged, previous, run.Status, "Acknowledgement recorded manually."); await db.SaveChangesAsync(ct); return await GetRunResult(run, ct);
    }

    public Task<Result<StatutoryFilingRunDto>> CancelAsync(Guid runId, CancellationToken ct = default) => TransitionAsync(runId, StatutoryFilingRunStatus.Cancelled, StatutoryFilingRunStatus.Draft, StatutoryFilingHistoryEvent.Cancelled, ct);

    public async Task<Result<StatutoryFilingPackageDto>> GetPackageAsync(Guid runId, CancellationToken ct = default) { var run = await LoadRun(runId, ct); var package = run is null ? null : await db.StatutoryFilingPackages.AsNoTracking().Where(x => x.TenantId == run.TenantId && x.RunId == runId).OrderByDescending(x => x.Version).FirstOrDefaultAsync(ct); return package is null ? Result<StatutoryFilingPackageDto>.NotFound("Package not found.") : Result<StatutoryFilingPackageDto>.Success(new(package.Id, package.Version, package.FileName, package.ContentType, package.PackageHash, package.RowCount, package.ByteCount)); }
    public async Task<Result<PayrollOutputFile>> DownloadAsync(Guid runId, CancellationToken ct = default) { var run = await LoadRun(runId, ct); var package = run is null ? null : await db.StatutoryFilingPackages.AsNoTracking().Where(x => x.TenantId == run.TenantId && x.RunId == runId).OrderByDescending(x => x.Version).FirstOrDefaultAsync(ct); return package is null ? Result<PayrollOutputFile>.NotFound("Package not found.") : Result<PayrollOutputFile>.Success(new(package.FileName, package.ContentType, Encoding.UTF8.GetBytes(package.Content))); }
    public async Task<Result<IReadOnlyList<StatutoryFilingIssueDto>>> GetIssuesAsync(Guid runId, CancellationToken ct = default) { if (tenant.TenantId is not Guid tid) return Result<IReadOnlyList<StatutoryFilingIssueDto>>.Unauthorized("No authenticated tenant."); var rows = await db.StatutoryFilingValidationIssues.AsNoTracking().Where(x => x.TenantId == tid && x.RunId == runId).OrderBy(x => x.Id).Select(x => new StatutoryFilingIssueDto(x.Id, x.Severity, x.Code, x.Message)).ToListAsync(ct); return Result<IReadOnlyList<StatutoryFilingIssueDto>>.Success(rows); }

    private async Task<Result<StatutoryFilingRunDto>> TransitionAsync(Guid id, StatutoryFilingRunStatus next, StatutoryFilingRunStatus required, StatutoryFilingHistoryEvent change, CancellationToken ct, string? message = null) { var run = await LoadRun(id, ct); if (run is null) return Result<StatutoryFilingRunDto>.NotFound("Filing run not found."); if (run.Status != required) return Result<StatutoryFilingRunDto>.Conflict($"Run must be {required}."); var previous = run.Status; run.Status = next; run.ConcurrencyVersion++; AddHistory(run, change, previous, next, message ?? $"Run transitioned to {next}."); try { await db.SaveChangesAsync(ct); } catch (DbUpdateConcurrencyException) { return Result<StatutoryFilingRunDto>.Conflict("Filing run was changed by another operation."); } return await GetRunResult(run, ct); }
    private async Task<StatutoryFilingRun?> LoadRun(Guid id, CancellationToken ct) => await db.StatutoryFilingRuns.FirstOrDefaultAsync(x => x.TenantId == tenant.TenantId && x.Id == id, ct);
    private async Task<Result<StatutoryFilingRunDto>> GetRunResult(StatutoryFilingRun run, CancellationToken ct) { var package = await db.StatutoryFilingPackages.AsNoTracking().Where(x => x.TenantId == run.TenantId && x.RunId == run.Id).OrderByDescending(x => x.Version).FirstOrDefaultAsync(ct); var submission = await db.StatutoryFilingSubmissions.AsNoTracking().Where(x => x.TenantId == run.TenantId && x.RunId == run.Id).OrderByDescending(x => x.CreatedDate).FirstOrDefaultAsync(ct); return Result<StatutoryFilingRunDto>.Success(ToDto(run, package, submission)); }
    private void AddHistory(StatutoryFilingRun run, StatutoryFilingHistoryEvent e, StatutoryFilingRunStatus? previous, StatutoryFilingRunStatus? next, string message) => db.StatutoryFilingHistories.Add(new StatutoryFilingHistory { Id = Guid.NewGuid(), TenantId = run.TenantId, RunId = run.Id, Event = e, PreviousStatus = previous, NewStatus = next, ActorUserId = tenant.UserId, OccurredAtUtc = clock.GetUtcNow().UtcDateTime, Message = message });
    private IStatutoryFilingConnector ResolveConnector(StatutoryFilingConnectionProfile? profile, StatutoryFilingDestinationType destination = StatutoryFilingDestinationType.ManualDownload) => (connectorRegistry ?? new StatutoryFilingConnectorRegistry(new IStatutoryFilingConnector[] { new ManualDownloadStatutoryFilingConnector(), new TestStatutoryFilingConnector() })).Resolve(profile?.ConnectorType ?? (destination == StatutoryFilingDestinationType.ManualDownload ? StatutoryFilingConnectorType.ManualDownload : StatutoryFilingConnectorType.Test));
    private IStatutoryFilingConnector ResolveConnector(StatutoryFilingConnectionProfile profile) => ResolveConnector(profile, StatutoryFilingDestinationType.ManualDownload);
    private static StatutoryFilingDefinitionDto ToDto(StatutoryFilingDefinition x) => new(x.Id, x.Code, x.Name, x.FilingType, x.JurisdictionCode, x.RequiresApproval, x.DestinationType, x.IsActive, x.ConnectionProfileId);
    private static StatutoryFilingConnectionProfileDto ToProfileDto(StatutoryFilingConnectionProfile x) => new(x.Id, x.Name, x.ConnectorType, x.Endpoint, x.IsActive, x.EffectiveFrom, x.EffectiveTo, x.LastValidationStatus, x.LastValidatedAtUtc, !string.IsNullOrWhiteSpace(x.SecretReference));
    private static StatutoryFilingRunDto ToDto(StatutoryFilingRun x, StatutoryFilingPackage? p, StatutoryFilingSubmission? s) => new(x.Id, x.DefinitionId, x.FilingPeriod, x.Status, x.RowCount, x.ValidationErrorCount, x.ValidationWarningCount, p?.Id, p?.PackageHash, s?.Id, s?.ExternalReference);
    private static string Escape(string value) => value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
    private static (int Year, int Month)? ParsePeriod(string value) => DateTime.TryParseExact(value, "yyyy-MM", CultureInfo.InvariantCulture, DateTimeStyles.None, out var parsed) ? (parsed.Year, parsed.Month) : null;
    private static string Csv(string? value) { var text = value ?? string.Empty; return text.Contains(',', StringComparison.Ordinal) || text.Contains('"', StringComparison.Ordinal) || text.Contains('\n') || text.Contains('\r') ? $"\"{text.Replace("\"", "\"\"", StringComparison.Ordinal)}\"" : text; }
}
