namespace HRMS.Application.DTOs.Employees;

public record EmployeeSupervisorDto(
    Guid Id,
    Guid EmployeeId,
    string? L1ManagerCode,
    string? L1ManagerName,
    Guid? L1ManagerId,
    string? L2ManagerCode,
    string? L2ManagerName,
    Guid? L2ManagerId,
    string? L3ManagerCode,
    string? L3ManagerName,
    Guid? L3ManagerId,
    string? L4ManagerCode,
    string? L4ManagerName,
    Guid? L4ManagerId,
    string? L5ManagerCode,
    string? L5ManagerName,
    Guid? L5ManagerId,
    string? TimeManagerCode,
    string? TimeManagerName,
    Guid? TimeManagerId,
    string? EroCode,
    string? EroName,
    Guid? EroId,
    string? ChroManagerCode,
    string? ChroManagerName,
    Guid? ChroManagerId,
    DateTime CreatedDate,
    DateTime? ModifiedDate,
    string? L1ResolutionStatus = null,
    string? L1ResolutionMessage = null);
